In [1]:
# NOTE: This does NOT have points close to real ones removed!

import pandas as pd
import numpy as np
%matplotlib inline
import matplotlib.pyplot as plt
import sklearn

crime = pd.read_csv('E:/Vancouver Crime Final/Synthetic Data/both_bne_500k_combined.csv')

crime

type             datetime  year  month  \
0       Break and Enter Residential/Other  2003-01-01 00:00:00  2003      1   
1              Break and Enter Commercial  2003-01-01 00:00:00  2003      1   
2       Break and Enter Residential/Other  2003-01-01 00:00:00  2003      1   
3       Break and Enter Residential/Other  2003-01-01 00:00:00  2003      1   
4       Break and Enter Residential/Other  2003-01-01 01:01:00  2003      1   
...                                   ...                  ...   ...    ...   
604243                               NONE  2016-10-29 16:05:00  2016     10   
604244                               NONE  2007-10-02 23:40:00  2007     10   
604245                               NONE  2006-10-03 09:29:00  2006     10   
604246                               NONE  2005-02-02 05:29:00  2005      2   
604247                               NONE  2013-11-26 22:01:00  2013     11   

        day  hour  minute  Hour_Minute           hundred_block          utm_x  \
0         1     0       0     0.000000          9XX W 15TH AVE  490791.120000   
1         1     0       0     0.000000        64XX VICTORIA DR  495220.950000   
2         1     0       1     0.016667         34XX W 42ND AVE  486837.110000   
3         1     0      20     0.333333          19XX PARKER ST  495279.460000   
4         1     1      46     1.766667            45XX MAIN ST  492627.840000   
...     ...   ...     ...          ...                     ...            ...   
604243   29    16       5    16.083333        40XX BOUNDARY RD  498263.140760   
604244    2    23      40    23.666667         37XX W 31ST AVE  486377.345932   
604245    3     9      29     9.483333           42XX YUKON ST  491831.626717   
604246    2     5      29     5.483333         19XX W 39TH AVE  489136.700000   
604247   26    22       1    22.016667  E 35TH AVE / KNIGHT ST  494415.830000   

        ...  signal_200  trees_25  trees_100  rain_mm  snow_cm  \
0       ...           2         0         32     21.6      0.0   
1       ...           2         5         40     21.6      0.0   
2       ...           3         6         38     21.6      0.0   
3       ...           1         8         88     21.6      0.0   
4       ...           2         8         83     21.6      0.0   
...     ...         ...       ...        ...      ...      ...   
604243  ...           0         4         27      6.4      0.0   
604244  ...           2         9         45      5.2      0.0   
604245  ...           0         8         67      0.0      0.0   
604246  ...           0         8         69      0.0      0.0   
604247  ...           3         2         31      0.0      0.0   

        total_precip_mm  temp_c  humidity  pressure  hours_of_light  
0                  21.6     5.8      81.0    101.70            9.53  
1                  21.6     5.8      81.0    101.70            9.53  
2                  21.6     5.8      81.0    101.70            9.53  
3                  21.6     5.8      81.0    101.70            9.53  
4                  21.6     6.2      78.0    101.73            9.53  
...                 ...     ...       ...       ...             ...  
604243              6.4    11.0      89.0    101.34           11.08  
604244              5.2     9.5      87.0    100.86           12.66  
604245              0.0    11.9      84.0    102.09           12.58  
604246              0.0     8.2      90.0    102.93           10.63  
604247              0.0     5.8      84.0    102.00            9.87  

[604248 rows x 30 columns]

In [2]:
# Set Break and ENters to 1 and everything else to 0

crime = crime.replace(['NONE'], 0)

crime = crime.replace(['Break and Enter Residential/Other', 'Break and Enter Commercial'], 1)
crime.head()

type             datetime  year  month  day  hour  minute  Hour_Minute  \
0     1  2003-01-01 00:00:00  2003      1    1     0       0     0.000000   
1     1  2003-01-01 00:00:00  2003      1    1     0       0     0.000000   
2     1  2003-01-01 00:00:00  2003      1    1     0       1     0.016667   
3     1  2003-01-01 00:00:00  2003      1    1     0      20     0.333333   
4     1  2003-01-01 01:01:00  2003      1    1     1      46     1.766667   

      hundred_block      utm_x  ...  signal_200  trees_25  trees_100  rain_mm  \
0    9XX W 15TH AVE  490791.12  ...           2         0         32     21.6   
1  64XX VICTORIA DR  495220.95  ...           2         5         40     21.6   
2   34XX W 42ND AVE  486837.11  ...           3         6         38     21.6   
3    19XX PARKER ST  495279.46  ...           1         8         88     21.6   
4      45XX MAIN ST  492627.84  ...           2         8         83     21.6   

   snow_cm  total_precip_mm  temp_c  humidity  pressure  hours_of_light  
0      0.0             21.6     5.8      81.0    101.70            9.53  
1      0.0             21.6     5.8      81.0    101.70            9.53  
2      0.0             21.6     5.8      81.0    101.70            9.53  
3      0.0             21.6     5.8      81.0    101.70            9.53  
4      0.0             21.6     6.2      78.0    101.73            9.53  

[5 rows x 30 columns]

In [3]:
crime

type             datetime  year  month  day  hour  minute  \
0          1  2003-01-01 00:00:00  2003      1    1     0       0   
1          1  2003-01-01 00:00:00  2003      1    1     0       0   
2          1  2003-01-01 00:00:00  2003      1    1     0       1   
3          1  2003-01-01 00:00:00  2003      1    1     0      20   
4          1  2003-01-01 01:01:00  2003      1    1     1      46   
...      ...                  ...   ...    ...  ...   ...     ...   
604243     0  2016-10-29 16:05:00  2016     10   29    16       5   
604244     0  2007-10-02 23:40:00  2007     10    2    23      40   
604245     0  2006-10-03 09:29:00  2006     10    3     9      29   
604246     0  2005-02-02 05:29:00  2005      2    2     5      29   
604247     0  2013-11-26 22:01:00  2013     11   26    22       1   

        Hour_Minute           hundred_block          utm_x  ...  signal_200  \
0          0.000000          9XX W 15TH AVE  490791.120000  ...           2   
1          0.000000        64XX VICTORIA DR  495220.950000  ...           2   
2          0.016667         34XX W 42ND AVE  486837.110000  ...           3   
3          0.333333          19XX PARKER ST  495279.460000  ...           1   
4          1.766667            45XX MAIN ST  492627.840000  ...           2   
...             ...                     ...            ...  ...         ...   
604243    16.083333        40XX BOUNDARY RD  498263.140760  ...           0   
604244    23.666667         37XX W 31ST AVE  486377.345932  ...           2   
604245     9.483333           42XX YUKON ST  491831.626717  ...           0   
604246     5.483333         19XX W 39TH AVE  489136.700000  ...           0   
604247    22.016667  E 35TH AVE / KNIGHT ST  494415.830000  ...           3   

        trees_25  trees_100  rain_mm  snow_cm  total_precip_mm  temp_c  \
0              0         32     21.6      0.0             21.6     5.8   
1              5         40     21.6      0.0             21.6     5.8   
2              6         38     21.6      0.0             21.6     5.8   
3              8         88     21.6      0.0             21.6     5.8   
4              8         83     21.6      0.0             21.6     6.2   
...          ...        ...      ...      ...              ...     ...   
604243         4         27      6.4      0.0              6.4    11.0   
604244         9         45      5.2      0.0              5.2     9.5   
604245         8         67      0.0      0.0              0.0    11.9   
604246         8         69      0.0      0.0              0.0     8.2   
604247         2         31      0.0      0.0              0.0     5.8   

        humidity  pressure  hours_of_light  
0           81.0    101.70            9.53  
1           81.0    101.70            9.53  
2           81.0    101.70            9.53  
3           81.0    101.70            9.53  
4           78.0    101.73            9.53  
...          ...       ...             ...  
604243      89.0    101.34           11.08  
604244      87.0    100.86           12.66  
604245      84.0    102.09           12.58  
604246      90.0    102.93           10.63  
604247      84.0    102.00            9.87  

[604248 rows x 30 columns]

In [4]:
### Begin Processing the Data


# Import Pre-processing module
from sklearn import preprocessing

# Create Label Encoder
le = preprocessing.LabelEncoder()

# Convert the string columns to numeric
# .astype(str) to ensude they are read as strings and not as mixed types
crime['datetime'] = le.fit_transform(crime['datetime'].astype(str))
crime['hundred_block'] = le.fit_transform(crime['hundred_block'].astype(str))


# Display the results
crime

type  datetime  year  month  day  hour  minute  Hour_Minute  \
0          1         0  2003      1    1     0       0     0.000000   
1          1         0  2003      1    1     0       0     0.000000   
2          1         0  2003      1    1     0       1     0.016667   
3          1         0  2003      1    1     0      20     0.333333   
4          1         5  2003      1    1     1      46     1.766667   
...      ...       ...   ...    ...  ...   ...     ...          ...   
604243     0    460352  2016     10   29    16       5    16.083333   
604244     0    162251  2007     10    2    23      40    23.666667   
604245     0    128500  2006     10    3     9      29     9.483333   
604246     0     72018  2005      2    2     5      29     5.483333   
604247     0    364049  2013     11   26    22       1    22.016667   

        hundred_block          utm_x  ...  signal_200  trees_25  trees_100  \
0               14804  490791.120000  ...           2         0         32   
1               11850  495220.950000  ...           2         5         40   
2                7276  486837.110000  ...           3         6         38   
3                2686  495279.460000  ...           1         8         88   
4                9186  492627.840000  ...           2         8         83   
...               ...            ...  ...         ...       ...        ...   
604243           8571  498263.140760  ...           0         4         27   
604244           7850  486377.345932  ...           2         9         45   
604245           8893  491831.626717  ...           0         8         67   
604246           2739  489136.700000  ...           0         8         69   
604247          17132  494415.830000  ...           3         2         31   

        rain_mm  snow_cm  total_precip_mm  temp_c  humidity  pressure  \
0          21.6      0.0             21.6     5.8      81.0    101.70   
1          21.6      0.0             21.6     5.8      81.0    101.70   
2          21.6      0.0             21.6     5.8      81.0    101.70   
3          21.6      0.0             21.6     5.8      81.0    101.70   
4          21.6      0.0             21.6     6.2      78.0    101.73   
...         ...      ...              ...     ...       ...       ...   
604243      6.4      0.0              6.4    11.0      89.0    101.34   
604244      5.2      0.0              5.2     9.5      87.0    100.86   
604245      0.0      0.0              0.0    11.9      84.0    102.09   
604246      0.0      0.0              0.0     8.2      90.0    102.93   
604247      0.0      0.0              0.0     5.8      84.0    102.00   

        hours_of_light  
0                 9.53  
1                 9.53  
2                 9.53  
3                 9.53  
4                 9.53  
...                ...  
604243           11.08  
604244           12.66  
604245           12.58  
604246           10.63  
604247            9.87  

[604248 rows x 30 columns]

In [5]:
# Scale the Data

columns = [col for col in crime if col not in ['type']]


# Properly scale the reduced set of features
features = crime[columns]

from sklearn.preprocessing import MinMaxScaler
scaler = preprocessing.MinMaxScaler()

print(scaler.fit(features))

MinMaxScaler(copy=True, feature_range=(0, 1))


In [6]:
# Properly scale the features

columns = [col for col in crime if col not in ['type']]

# Properly scale the reduced set of features
features = crime[columns]


scaler = MinMaxScaler().fit(features.values) # scaler = MinMaxScaler().fit(features.values)
features = scaler.transform(features.values) # features = scaler.transform(features.values)
crime[columns] = features
crime

type  datetime    year     month       day      hour    minute  \
0          1  0.000000  0.0000  0.000000  0.000000  0.000000  0.000000   
1          1  0.000000  0.0000  0.000000  0.000000  0.000000  0.000000   
2          1  0.000000  0.0000  0.000000  0.000000  0.000000  0.016949   
3          1  0.000000  0.0000  0.000000  0.000000  0.000000  0.338983   
4          1  0.000009  0.0000  0.000000  0.000000  0.043478  0.779661   
...      ...       ...     ...       ...       ...       ...       ...   
604243     0  0.833073  0.8125  0.818182  0.933333  0.695652  0.084746   
604244     0  0.293616  0.2500  0.818182  0.033333  1.000000  0.677966   
604245     0  0.232539  0.1875  0.818182  0.066667  0.391304  0.491525   
604246     0  0.130327  0.1250  0.090909  0.033333  0.217391  0.491525   
604247     0  0.658799  0.6250  0.909091  0.833333  0.956522  0.016949   

        Hour_Minute  hundred_block     utm_x  ...  signal_200  trees_25  \
0          0.000000       0.673368  0.485327  ...    0.133333  0.000000   
1          0.000000       0.539004  0.788720  ...    0.133333  0.151515   
2          0.000695       0.330953  0.214522  ...    0.200000  0.181818   
3          0.013899       0.122174  0.792727  ...    0.066667  0.242424   
4          0.073662       0.417830  0.611121  ...    0.133333  0.242424   
...             ...            ...       ...  ...         ...       ...   
604243     0.670605       0.389857  0.997076  ...    0.000000  0.121212   
604244     0.986796       0.357062  0.183033  ...    0.133333  0.272727   
604245     0.395413       0.404503  0.556590  ...    0.000000  0.242424   
604246     0.228631       0.124585  0.372018  ...    0.000000  0.242424   
604247     0.917999       0.779259  0.733578  ...    0.200000  0.060606   

        trees_100   rain_mm  snow_cm  total_precip_mm    temp_c  humidity  \
0        0.244275  0.235808      0.0         0.235808  0.408421  0.781609   
1        0.305344  0.235808      0.0         0.235808  0.408421  0.781609   
2        0.290076  0.235808      0.0         0.235808  0.408421  0.781609   
3        0.671756  0.235808      0.0         0.235808  0.408421  0.781609   
4        0.633588  0.235808      0.0         0.235808  0.416842  0.747126   
...           ...       ...      ...              ...       ...       ...   
604243   0.206107  0.069869      0.0         0.069869  0.517895  0.873563   
604244   0.343511  0.056769      0.0         0.056769  0.486316  0.850575   
604245   0.511450  0.000000      0.0         0.000000  0.536842  0.816092   
604246   0.526718  0.000000      0.0         0.000000  0.458947  0.885057   
604247   0.236641  0.000000      0.0         0.000000  0.408421  0.816092   

        pressure  hours_of_light  
0       0.612081        0.010909  
1       0.612081        0.010909  
2       0.612081        0.010909  
3       0.612081        0.010909  
4       0.616107        0.010909  
...          ...             ...  
604243  0.563758        0.198788  
604244  0.499329        0.390303  
604245  0.664430        0.380606  
604246  0.777181        0.144242  
604247  0.652349        0.052121  

[604248 rows x 30 columns]

In [7]:
# split training data into training and testing
from sklearn.model_selection import train_test_split

# Select columns to that are data
cols = [col for col in crime if col not in ['type']]

X = crime[cols]

# Select target data
y = crime['type']

X_train, X_test, y_train, y_test = train_test_split(X, y, random_state=100, test_size=0.3)
print(X_train.shape)

(422973, 29)


In [8]:
# Trying Random Forest Classifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.feature_selection import SelectFromModel

model_tree = RandomForestClassifier(random_state=100, n_estimators=50)
model_tree.fit(X_train, y_train)
print(model_tree.feature_importances_)
sel_model_tree = SelectFromModel(estimator=model_tree, prefit=True, threshold='mean')  
      # since we already fit the data, we specify prefit option here
      # Features whose importance is greater or equal to the threshold are kept while the others are discarded.
X_train_sfm_tree = sel_model_tree.transform(X_train)
print(sel_model_tree.get_support())

feature_importances = pd.DataFrame(model_tree.feature_importances_,
                                   index = X_train.columns,
                                    columns=['importance']).sort_values('importance', 
                                                                        ascending=False)
feature_importances

[0.03359069 0.01619423 0.01338508 0.0212882  0.01924984 0.31520915
 0.04123774 0.10201058 0.03706868 0.04035171 0.03955978 0.03739028
 0.01076743 0.01479191 0.02025143 0.02939922 0.00210492 0.00271557
 0.00968723 0.01435153 0.02149537 0.02949163 0.01245378 0.00135285
 0.01265339 0.02601832 0.02312021 0.02708999 0.02571928]
[False False False False False  True  True  True  True  True  True  True
 False False False False False False False False False False False False
 False False False False False]


importance
minute             0.315209
hundred_block      0.102011
Hour_Minute        0.041238
utm_y              0.040352
latitude           0.039560
longitude          0.037390
utm_x              0.037069
datetime           0.033591
trees_100          0.029492
light_pole_100     0.029399
pressure           0.027090
temp_c             0.026018
hours_of_light     0.025719
humidity           0.023120
trees_25           0.021495
day                0.021288
light_pole_50      0.020251
hour               0.019250
year               0.016194
light_pole_25      0.014792
signal_200         0.014352
month              0.013385
total_precip_mm    0.012653
rain_mm            0.012454
light_pole_12_5    0.010767
signal_100         0.009687
signal_50          0.002716
signal_25          0.002105
snow_cm            0.001353

In [9]:
# Simple Neural Network

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import sklearn
from sklearn.neural_network import MLPClassifier
from sklearn.neural_network import MLPRegressor

# import needed modules
from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_squared_error
from math import sqrt
from sklearn.metrics import r2_score

In [10]:
# Try using the MLP Classifier
mlp = MLPClassifier(hidden_layer_sizes=(29, 29, 29), activation='relu', solver='adam', max_iter=300)
mlp.fit(X_train, y_train)

predict_train = mlp.predict(X_train)
predict_test = mlp.predict(X_test)

In [11]:
from sklearn.metrics import classification_report, confusion_matrix
print(confusion_matrix(y_train, predict_train))
print(classification_report(y_train, predict_train))

[[341868   8118]
 [ 31466  41521]]
              precision    recall  f1-score   support

           0       0.92      0.98      0.95    349986
           1       0.84      0.57      0.68     72987

    accuracy                           0.91    422973
   macro avg       0.88      0.77      0.81    422973
weighted avg       0.90      0.91      0.90    422973



In [12]:
print(confusion_matrix(y_test, predict_test))
print(classification_report(y_test, predict_test))

[[146498   3627]
 [ 13464  17686]]
              precision    recall  f1-score   support

           0       0.92      0.98      0.94    150125
           1       0.83      0.57      0.67     31150

    accuracy                           0.91    181275
   macro avg       0.87      0.77      0.81    181275
weighted avg       0.90      0.91      0.90    181275



In [13]:
# Try using the MLP Classifier
mlp = MLPClassifier(hidden_layer_sizes=(29, 29, 29, 29, 29), activation='relu', solver='adam', max_iter=200)
mlp.fit(X_train, y_train)

predict_train = mlp.predict(X_train)
predict_test = mlp.predict(X_test)

In [14]:
print(confusion_matrix(y_train, predict_train))
print(classification_report(y_train, predict_train))

[[341867   8119]
 [ 30251  42736]]
              precision    recall  f1-score   support

           0       0.92      0.98      0.95    349986
           1       0.84      0.59      0.69     72987

    accuracy                           0.91    422973
   macro avg       0.88      0.78      0.82    422973
weighted avg       0.91      0.91      0.90    422973



In [15]:
print(confusion_matrix(y_test, predict_test))
print(classification_report(y_test, predict_test))

[[146507   3618]
 [ 12977  18173]]
              precision    recall  f1-score   support

           0       0.92      0.98      0.95    150125
           1       0.83      0.58      0.69     31150

    accuracy                           0.91    181275
   macro avg       0.88      0.78      0.82    181275
weighted avg       0.90      0.91      0.90    181275



In [ ]:
############################# END HERE ###################################

In [16]:
feature_importances

importance
minute             0.315209
hundred_block      0.102011
Hour_Minute        0.041238
utm_y              0.040352
latitude           0.039560
longitude          0.037390
utm_x              0.037069
datetime           0.033591
trees_100          0.029492
light_pole_100     0.029399
pressure           0.027090
temp_c             0.026018
hours_of_light     0.025719
humidity           0.023120
trees_25           0.021495
day                0.021288
light_pole_50      0.020251
hour               0.019250
year               0.016194
light_pole_25      0.014792
signal_200         0.014352
month              0.013385
total_precip_mm    0.012653
rain_mm            0.012454
light_pole_12_5    0.010767
signal_100         0.009687
signal_50          0.002716
signal_25          0.002105
snow_cm            0.001353

In [17]:
# Cut down features

# split training data into training and testing
from sklearn.model_selection import train_test_split

# Select columns to that are data
cols = [col for col in crime if col not in ['type', 'Hour_Minute', 'latitude', 'longitude', 
                                            'datetime', 'snow_cm', 'rain_mm']]

X = crime[cols]

# Select target data
y = crime['type']

X_train, X_test, y_train, y_test = train_test_split(X, y, random_state=100, test_size=0.3)
print(X_train.shape)

(422973, 23)


In [18]:
# Trying Random Forest Classifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.feature_selection import SelectFromModel

model_tree = RandomForestClassifier(random_state=100, n_estimators=50)
model_tree.fit(X_train, y_train)
print(model_tree.feature_importances_)
sel_model_tree = SelectFromModel(estimator=model_tree, prefit=True, threshold='mean')  
      # since we already fit the data, we specify prefit option here
      # Features whose importance is greater or equal to the threshold are kept while the others are discarded.
X_train_sfm_tree = sel_model_tree.transform(X_train)
print(sel_model_tree.get_support())

feature_importances = pd.DataFrame(model_tree.feature_importances_,
                                   index = X_train.columns,
                                    columns=['importance']).sort_values('importance', 
                                                                        ascending=False)
feature_importances

[0.02739788 0.01733951 0.02772423 0.03098652 0.33130388 0.11171287
 0.05263587 0.05726343 0.01256844 0.01793752 0.02560873 0.03747251
 0.00247797 0.00333381 0.00935339 0.01943506 0.02603086 0.03805456
 0.01887145 0.03378807 0.03010165 0.03504814 0.03355366]
[False False False False  True  True  True  True False False False False
 False False False False False False False False False False False]


importance
minute             0.331304
hundred_block      0.111713
utm_y              0.057263
utm_x              0.052636
trees_100          0.038055
light_pole_100     0.037473
pressure           0.035048
temp_c             0.033788
hours_of_light     0.033554
hour               0.030987
humidity           0.030102
day                0.027724
year               0.027398
trees_25           0.026031
light_pole_50      0.025609
signal_200         0.019435
total_precip_mm    0.018871
light_pole_25      0.017938
month              0.017340
light_pole_12_5    0.012568
signal_100         0.009353
signal_50          0.003334
signal_25          0.002478

In [19]:
# Try using the MLP Classifier
mlp = MLPClassifier(hidden_layer_sizes=(23, 23, 23), activation='relu', solver='adam', max_iter=300)
mlp.fit(X_train, y_train)

predict_train = mlp.predict(X_train)
predict_test = mlp.predict(X_test)

In [20]:
print(confusion_matrix(y_train, predict_train))
print(classification_report(y_train, predict_train))

[[341295   8691]
 [ 30131  42856]]
              precision    recall  f1-score   support

           0       0.92      0.98      0.95    349986
           1       0.83      0.59      0.69     72987

    accuracy                           0.91    422973
   macro avg       0.88      0.78      0.82    422973
weighted avg       0.90      0.91      0.90    422973



In [21]:
print(confusion_matrix(y_test, predict_test))
print(classification_report(y_test, predict_test))

[[146329   3796]
 [ 12875  18275]]
              precision    recall  f1-score   support

           0       0.92      0.97      0.95    150125
           1       0.83      0.59      0.69     31150

    accuracy                           0.91    181275
   macro avg       0.87      0.78      0.82    181275
weighted avg       0.90      0.91      0.90    181275



In [22]:
# Try using the MLP Classifier
mlp = MLPClassifier(hidden_layer_sizes=(23, 23, 23, 23, 23, 23, 23), activation='relu', solver='adam', max_iter=300)
mlp.fit(X_train, y_train)

predict_train = mlp.predict(X_train)
predict_test = mlp.predict(X_test)

In [23]:
print(confusion_matrix(y_train, predict_train))
print(classification_report(y_train, predict_train))

[[341712   8274]
 [ 30654  42333]]
              precision    recall  f1-score   support

           0       0.92      0.98      0.95    349986
           1       0.84      0.58      0.69     72987

    accuracy                           0.91    422973
   macro avg       0.88      0.78      0.82    422973
weighted avg       0.90      0.91      0.90    422973



In [24]:
print(confusion_matrix(y_test, predict_test))
print(classification_report(y_test, predict_test))

[[146515   3610]
 [ 13100  18050]]
              precision    recall  f1-score   support

           0       0.92      0.98      0.95    150125
           1       0.83      0.58      0.68     31150

    accuracy                           0.91    181275
   macro avg       0.88      0.78      0.81    181275
weighted avg       0.90      0.91      0.90    181275

