In [7]:
# NOTE: This does NOT have points close to real ones removed!

import pandas as pd
import numpy as np
%matplotlib inline
import matplotlib.pyplot as plt
import sklearn

crime = pd.read_csv('E:/Vancouver Crime Final/Synthetic Data/both_bne_100k_notwithin_1week_100m.csv')

crime.head(20)

type             datetime  year  month  day  \
0   Break and Enter Residential/Other  2003-01-01 00:00:00  2003      1    1   
1          Break and Enter Commercial  2003-01-01 00:00:00  2003      1    1   
2   Break and Enter Residential/Other  2003-01-01 00:00:00  2003      1    1   
3   Break and Enter Residential/Other  2003-01-01 00:00:00  2003      1    1   
4   Break and Enter Residential/Other  2003-01-01 01:01:00  2003      1    1   
5   Break and Enter Residential/Other  2003-01-01 04:04:00  2003      1    1   
6   Break and Enter Residential/Other  2003-01-01 04:04:00  2003      1    1   
7          Break and Enter Commercial  2003-01-01 06:06:00  2003      1    1   
8          Break and Enter Commercial  2003-01-01 07:07:00  2003      1    1   
9          Break and Enter Commercial  2003-01-01 07:07:00  2003      1    1   
10  Break and Enter Residential/Other  2003-01-01 07:07:00  2003      1    1   
11  Break and Enter Residential/Other  2003-01-01 11:11:00  2003      1    1   
12         Break and Enter Commercial  2003-01-01 11:11:00  2003      1    1   
13  Break and Enter Residential/Other  2003-01-01 11:11:00  2003      1    1   
14         Break and Enter Commercial  2003-01-01 12:12:00  2003      1    1   
15         Break and Enter Commercial  2003-01-01 12:12:00  2003      1    1   
16  Break and Enter Residential/Other  2003-01-01 12:12:00  2003      1    1   
17         Break and Enter Commercial  2003-01-01 12:12:00  2003      1    1   
18  Break and Enter Residential/Other  2003-01-01 15:15:00  2003      1    1   
19  Break and Enter Residential/Other  2003-01-01 16:16:00  2003      1    1   

    hour  minute  Hour_Minute      hundred_block      utm_x  ...  signal_200  \
0      0       0     0.000000     9XX W 15TH AVE  490791.12  ...           2   
1      0       0     0.000000   64XX VICTORIA DR  495220.95  ...           2   
2      0       1     0.016667    34XX W 42ND AVE  486837.11  ...           3   
3      0      20     0.333333     19XX PARKER ST  495279.46  ...           1   
4      1      46     1.766667       45XX MAIN ST  492627.84  ...           2   
5      4       0     4.000000   25XX GRAVELEY ST  496100.23  ...           0   
6      4      30     4.500000  15XX SE MARINE DR  494572.37  ...           1   
7      6       0     6.000000   5XX W GEORGIA ST  491507.39  ...          10   
8      7      13     7.216667    18XX W 57TH AVE  489132.03  ...           0   
9      7      13     7.216667     45XX FRASER ST  493431.80  ...           2   
10     7      25     7.416667      7XX SEMLIN DR  495363.36  ...           1   
11    11       0    11.000000    22XX TRIUMPH ST  495716.74  ...           4   
12    11       0    11.000000     35XX FRASER ST  493447.88  ...           1   
13    11      45    11.750000    38XX HEATHER ST  491248.44  ...           1   
14    12       0    12.000000      5XX BEATTY ST  492024.04  ...          10   
15    12       0    12.000000   7XX PACIFIC BLVD  492005.87  ...           2   
16    12       0    12.000000       41XX VINE ST  488613.83  ...           0   
17    12      49    12.816667    28XX BENTALL ST  497676.19  ...           3   
18    15      30    15.500000  30XX E KENT N AVE  496782.22  ...           1   
19    16      30    16.500000    28XX E 22ND AVE  496722.62  ...           1   

    trees_25  trees_100  rain_mm  snow_cm  total_precip_mm  temp_c  humidity  \
0          0         32     21.6      0.0             21.6     5.8      81.0   
1          5         40     21.6      0.0             21.6     5.8      81.0   
2          6         38     21.6      0.0             21.6     5.8      81.0   
3          8         88     21.6      0.0             21.6     5.8      81.0   
4          8         83     21.6      0.0             21.6     6.2      78.0   
5          7         73     21.6      0.0             21.6     5.5      88.0   
6          0         41     21.6      0.0             21.6     5.5      88.0   
7          2         27     21.

In [8]:
# Set Break and ENters to 1 and everything else to 0

crime = crime.replace(['NONE'], 0)

crime = crime.replace(['Break and Enter Residential/Other', 'Break and Enter Commercial'], 1)
crime.head()

type             datetime  year  month  day  hour  minute  Hour_Minute  \
0     1  2003-01-01 00:00:00  2003      1    1     0       0     0.000000   
1     1  2003-01-01 00:00:00  2003      1    1     0       0     0.000000   
2     1  2003-01-01 00:00:00  2003      1    1     0       1     0.016667   
3     1  2003-01-01 00:00:00  2003      1    1     0      20     0.333333   
4     1  2003-01-01 01:01:00  2003      1    1     1      46     1.766667   

      hundred_block      utm_x  ...  signal_200  trees_25  trees_100  rain_mm  \
0    9XX W 15TH AVE  490791.12  ...           2         0         32     21.6   
1  64XX VICTORIA DR  495220.95  ...           2         5         40     21.6   
2   34XX W 42ND AVE  486837.11  ...           3         6         38     21.6   
3    19XX PARKER ST  495279.46  ...           1         8         88     21.6   
4      45XX MAIN ST  492627.84  ...           2         8         83     21.6   

   snow_cm  total_precip_mm  temp_c  humidity  pressure  hours_of_light  
0      0.0             21.6     5.8      81.0    101.70            9.53  
1      0.0             21.6     5.8      81.0    101.70            9.53  
2      0.0             21.6     5.8      81.0    101.70            9.53  
3      0.0             21.6     5.8      81.0    101.70            9.53  
4      0.0             21.6     6.2      78.0    101.73            9.53  

[5 rows x 30 columns]

In [9]:
crime

type             datetime  year  month  day  hour  minute  \
0          1  2003-01-01 00:00:00  2003      1    1     0       0   
1          1  2003-01-01 00:00:00  2003      1    1     0       0   
2          1  2003-01-01 00:00:00  2003      1    1     0       1   
3          1  2003-01-01 00:00:00  2003      1    1     0      20   
4          1  2003-01-01 01:01:00  2003      1    1     1      46   
...      ...                  ...   ...    ...  ...   ...     ...   
204570     0  2013-05-01 21:53:00  2013      5    1    21      53   
204571     0  2013-04-16 05:33:00  2013      4   16     5      33   
204572     0  2005-10-16 01:58:00  2005     10   16     1      58   
204573     0  2011-06-10 01:03:00  2011      6   10     1       3   
204574     0  2019-05-23 00:19:00  2019      5   23     0      19   

        Hour_Minute     hundred_block          utm_x  ...  signal_200  \
0          0.000000    9XX W 15TH AVE  490791.120000  ...           2   
1          0.000000  64XX VICTORIA DR  495220.950000  ...           2   
2          0.016667   34XX W 42ND AVE  486837.110000  ...           3   
3          0.333333    19XX PARKER ST  495279.460000  ...           1   
4          1.766667      45XX MAIN ST  492627.840000  ...           2   
...             ...               ...            ...  ...         ...   
204570    21.883333     35XX TOLBOOTH  497860.233100  ...           1   
204571     5.550000   25XX NANAIMO ST  495880.968016  ...           1   
204572     1.966667    12XX VERNON DR  494281.898055  ...           1   
204573     1.050000  55XX COLUMBIA ST  491945.209888  ...           0   
204574     0.316667    13XX CAMBIE ST  491644.720000  ...           1   

        trees_25  trees_100  rain_mm  snow_cm  total_precip_mm  temp_c  \
0              0         32     21.6      0.0             21.6     5.8   
1              5         40     21.6      0.0             21.6     5.8   
2              6         38     21.6      0.0             21.6     5.8   
3              8         88     21.6      0.0             21.6     5.8   
4              8         83     21.6      0.0             21.6     6.2   
...          ...        ...      ...      ...              ...     ...   
204570         1         29      0.0      0.0              0.0    11.0   
204571        10         41      0.0      0.0              0.0     4.0   
204572         0         12     20.2      0.0             20.2    11.5   
204573         8         72      0.0      0.0              0.0    13.5   
204574         0          3      0.0      0.0              0.0    14.4   

        humidity  pressure  hours_of_light  
0           81.0    101.70            9.53  
1           81.0    101.70            9.53  
2           81.0    101.70            9.53  
3           81.0    101.70            9.53  
4           78.0    101.73            9.53  
...          ...       ...             ...  
204570      45.0    103.50           15.86  
204571      73.0    102.52           14.94  
204572      95.0    101.61           11.81  
204573      83.0    101.86           17.58  
204574      77.0    101.61           17.00  

[204575 rows x 30 columns]

In [10]:
### Begin Processing the Data


# Import Pre-processing module
from sklearn import preprocessing

# Create Label Encoder
le = preprocessing.LabelEncoder()

# Convert the string columns to numeric
# .astype(str) to ensude they are read as strings and not as mixed types
crime['datetime'] = le.fit_transform(crime['datetime'].astype(str))
crime['hundred_block'] = le.fit_transform(crime['hundred_block'].astype(str))


# Display the results
crime

type  datetime  year  month  day  hour  minute  Hour_Minute  \
0          1         0  2003      1    1     0       0     0.000000   
1          1         0  2003      1    1     0       0     0.000000   
2          1         0  2003      1    1     0       1     0.016667   
3          1         0  2003      1    1     0      20     0.333333   
4          1         2  2003      1    1     1      46     1.766667   
...      ...       ...   ...    ...  ...   ...     ...          ...   
204570     0    107864  2013      5    1    21      53    21.883333   
204571     0    107430  2013      4   16     5      33     5.550000   
204572     0     31269  2005     10   16     1      58     1.966667   
204573     0     89506  2011      6   10     1       3     1.050000   
204574     0    166873  2019      5   23     0      19     0.316667   

        hundred_block          utm_x  ...  signal_200  trees_25  trees_100  \
0               14731  490791.120000  ...           2         0         32   
1               11790  495220.950000  ...           2         5         40   
2                7233  486837.110000  ...           3         6         38   
3                2664  495279.460000  ...           1         8         88   
4                9138  492627.840000  ...           2         8         83   
...               ...            ...  ...         ...       ...        ...   
204570           7428  497860.233100  ...           1         1         29   
204571           4659  495880.968016  ...           1        10         41   
204572            793  494281.898055  ...           1         0         12   
204573          10420  491945.209888  ...           0         8         72   
204574            945  491644.720000  ...           1         0          3   

        rain_mm  snow_cm  total_precip_mm  temp_c  humidity  pressure  \
0          21.6      0.0             21.6     5.8      81.0    101.70   
1          21.6      0.0             21.6     5.8      81.0    101.70   
2          21.6      0.0             21.6     5.8      81.0    101.70   
3          21.6      0.0             21.6     5.8      81.0    101.70   
4          21.6      0.0             21.6     6.2      78.0    101.73   
...         ...      ...              ...     ...       ...       ...   
204570      0.0      0.0              0.0    11.0      45.0    103.50   
204571      0.0      0.0              0.0     4.0      73.0    102.52   
204572     20.2      0.0             20.2    11.5      95.0    101.61   
204573      0.0      0.0              0.0    13.5      83.0    101.86   
204574      0.0      0.0              0.0    14.4      77.0    101.61   

        hours_of_light  
0                 9.53  
1                 9.53  
2                 9.53  
3                 9.53  
4                 9.53  
...                ...  
204570           15.86  
204571           14.94  
204572           11.81  
204573           17.58  
204574           17.00  

[204575 rows x 30 columns]

In [11]:
# Scale the Data

columns = [col for col in crime if col not in ['type']]


# Properly scale the reduced set of features
features = crime[columns]

from sklearn.preprocessing import MinMaxScaler
scaler = preprocessing.MinMaxScaler()

print(scaler.fit(features))

MinMaxScaler(copy=True, feature_range=(0, 1))


In [12]:
# Properly scale the features

columns = [col for col in crime if col not in ['type']]

# Properly scale the reduced set of features
features = crime[columns]


scaler = MinMaxScaler().fit(features.values) # scaler = MinMaxScaler().fit(features.values)
features = scaler.transform(features.values) # features = scaler.transform(features.values)
crime[columns] = features
crime

type  datetime   year     month       day      hour    minute  \
0          1  0.000000  0.000  0.000000  0.000000  0.000000  0.000000   
1          1  0.000000  0.000  0.000000  0.000000  0.000000  0.000000   
2          1  0.000000  0.000  0.000000  0.000000  0.000000  0.016949   
3          1  0.000000  0.000  0.000000  0.000000  0.000000  0.338983   
4          1  0.000012  0.000  0.000000  0.000000  0.043478  0.779661   
...      ...       ...    ...       ...       ...       ...       ...   
204570     0  0.636204  0.625  0.363636  0.000000  0.913043  0.898305   
204571     0  0.633645  0.625  0.272727  0.500000  0.217391  0.559322   
204572     0  0.184431  0.125  0.818182  0.500000  0.043478  0.983051   
204573     0  0.527925  0.500  0.454545  0.300000  0.043478  0.050847   
204574     0  0.984252  1.000  0.363636  0.733333  0.000000  0.322034   

        Hour_Minute  hundred_block     utm_x  ...  signal_200  trees_25  \
0          0.000000       0.674898  0.485335  ...    0.142857   0.00000   
1          0.000000       0.540157  0.788733  ...    0.142857   0.15625   
2          0.000695       0.331379  0.214525  ...    0.214286   0.18750   
3          0.013899       0.122051  0.792740  ...    0.071429   0.25000   
4          0.073662       0.418656  0.611131  ...    0.142857   0.25000   
...             ...            ...       ...  ...         ...       ...   
204570     0.912439       0.340312  0.969497  ...    0.071429   0.03125   
204571     0.231411       0.213451  0.833938  ...    0.071429   0.31250   
204572     0.082001       0.036331  0.724418  ...    0.071429   0.00000   
204573     0.043780       0.477390  0.564378  ...    0.000000   0.25000   
204574     0.013204       0.043295  0.543798  ...    0.071429   0.00000   

        trees_100   rain_mm  snow_cm  total_precip_mm    temp_c  humidity  \
0        0.244275  0.235808      0.0         0.235808  0.408421  0.781609   
1        0.305344  0.235808      0.0         0.235808  0.408421  0.781609   
2        0.290076  0.235808      0.0         0.235808  0.408421  0.781609   
3        0.671756  0.235808      0.0         0.235808  0.408421  0.781609   
4        0.633588  0.235808      0.0         0.235808  0.416842  0.747126   
...           ...       ...      ...              ...       ...       ...   
204570   0.221374  0.000000      0.0         0.000000  0.517895  0.367816   
204571   0.312977  0.000000      0.0         0.000000  0.370526  0.689655   
204572   0.091603  0.220524      0.0         0.220524  0.528421  0.942529   
204573   0.549618  0.000000      0.0         0.000000  0.570526  0.804598   
204574   0.022901  0.000000      0.0         0.000000  0.589474  0.735632   

        pressure  hours_of_light  
0       0.609459        0.010909  
1       0.609459        0.010909  
2       0.609459        0.010909  
3       0.609459        0.010909  
4       0.613514        0.010909  
...          ...             ...  
204570  0.852703        0.778182  
204571  0.720270        0.666667  
204572  0.597297        0.287273  
204573  0.631081        0.986667  
204574  0.597297        0.916364  

[204575 rows x 30 columns]

In [13]:
# split training data into training and testing
from sklearn.model_selection import train_test_split

# Select columns to that are data
cols = [col for col in crime if col not in ['type']]

X = crime[cols]

# Select target data
y = crime['type']

X_train, X_test, y_train, y_test = train_test_split(X, y, random_state=100, test_size=0.3)
print(X_train.shape)

(143202, 29)


In [14]:
# Trying Random Forest Classifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.feature_selection import SelectFromModel

model_tree = RandomForestClassifier(random_state=100, n_estimators=50)
model_tree.fit(X_train, y_train)
print(model_tree.feature_importances_)
sel_model_tree = SelectFromModel(estimator=model_tree, prefit=True, threshold='mean')  
      # since we already fit the data, we specify prefit option here
      # Features whose importance is greater or equal to the threshold are kept while the others are discarded.
X_train_sfm_tree = sel_model_tree.transform(X_train)
print(sel_model_tree.get_support())

feature_importances = pd.DataFrame(model_tree.feature_importances_,
                                   index = X_train.columns,
                                    columns=['importance']).sort_values('importance', 
                                                                        ascending=False)
feature_importances

[0.03490129 0.01965601 0.01333065 0.02119106 0.01902308 0.2407082
 0.0372564  0.17109237 0.03652026 0.04634953 0.04137386 0.03628394
 0.01000177 0.01477903 0.01937537 0.03383527 0.00197586 0.00237521
 0.00928657 0.01982228 0.0193742  0.02888895 0.01182225 0.00107127
 0.01183066 0.02500875 0.02251335 0.02538143 0.02497111]
[ True False False False False  True  True  True  True  True  True  True
 False False False False False False False False False False False False
 False False False False False]


importance
minute             0.240708
hundred_block      0.171092
utm_y              0.046350
latitude           0.041374
Hour_Minute        0.037256
utm_x              0.036520
longitude          0.036284
datetime           0.034901
light_pole_100     0.033835
trees_100          0.028889
pressure           0.025381
temp_c             0.025009
hours_of_light     0.024971
humidity           0.022513
day                0.021191
signal_200         0.019822
year               0.019656
light_pole_50      0.019375
trees_25           0.019374
hour               0.019023
light_pole_25      0.014779
month              0.013331
total_precip_mm    0.011831
rain_mm            0.011822
light_pole_12_5    0.010002
signal_100         0.009287
signal_50          0.002375
signal_25          0.001976
snow_cm            0.001071

In [15]:
# Simple Neural Network

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import sklearn
from sklearn.neural_network import MLPClassifier
from sklearn.neural_network import MLPRegressor

# import needed modules
from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_squared_error
from math import sqrt
from sklearn.metrics import r2_score

In [16]:
# Try using the MLP Classifier
mlp = MLPClassifier(hidden_layer_sizes=(29, 29, 29), activation='relu', solver='adam', max_iter=300)
mlp.fit(X_train, y_train)

predict_train = mlp.predict(X_train)
predict_test = mlp.predict(X_test)

In [17]:
from sklearn.metrics import classification_report, confusion_matrix
print(confusion_matrix(y_train, predict_train))
print(classification_report(y_train, predict_train))

[[59749 10637]
 [15726 57090]]
              precision    recall  f1-score   support

           0       0.79      0.85      0.82     70386
           1       0.84      0.78      0.81     72816

    accuracy                           0.82    143202
   macro avg       0.82      0.82      0.82    143202
weighted avg       0.82      0.82      0.82    143202



In [18]:
print(confusion_matrix(y_test, predict_test))
print(classification_report(y_test, predict_test))

[[25503  4549]
 [ 6903 24418]]
              precision    recall  f1-score   support

           0       0.79      0.85      0.82     30052
           1       0.84      0.78      0.81     31321

    accuracy                           0.81     61373
   macro avg       0.81      0.81      0.81     61373
weighted avg       0.82      0.81      0.81     61373



In [19]:
# Try using the MLP Classifier
mlp = MLPClassifier(hidden_layer_sizes=(29, 29, 29), activation='relu', solver='adam', max_iter=200)
mlp.fit(X_train, y_train)

predict_train = mlp.predict(X_train)
predict_test = mlp.predict(X_test)

In [20]:
print(confusion_matrix(y_train, predict_train))
print(classification_report(y_train, predict_train))

[[52967 17419]
 [12206 60610]]
              precision    recall  f1-score   support

           0       0.81      0.75      0.78     70386
           1       0.78      0.83      0.80     72816

    accuracy                           0.79    143202
   macro avg       0.79      0.79      0.79    143202
weighted avg       0.79      0.79      0.79    143202



In [21]:
print(confusion_matrix(y_test, predict_test))
print(classification_report(y_test, predict_test))

[[22629  7423]
 [ 5368 25953]]
              precision    recall  f1-score   support

           0       0.81      0.75      0.78     30052
           1       0.78      0.83      0.80     31321

    accuracy                           0.79     61373
   macro avg       0.79      0.79      0.79     61373
weighted avg       0.79      0.79      0.79     61373



In [ ]:
############################# END HERE ###################################

In [22]:
# try a different split
# split training data into training and testing
from sklearn.model_selection import train_test_split

# Select columns to that are data
cols = [col for col in crime if col not in ['type']]

X = crime[cols]

# Select target data
y = crime['type']

X_train, X_test, y_train, y_test = train_test_split(X, y, random_state=100, test_size=0.3)
print(X_train.shape)

(143202, 29)


In [26]:
# Try using the MLP Classifier
mlp = MLPClassifier(hidden_layer_sizes=(29, 29, 29), activation='relu', solver='adam', max_iter=600)
mlp.fit(X_train, y_train)

predict_train = mlp.predict(X_train)
predict_test = mlp.predict(X_test)

In [27]:
print(confusion_matrix(y_train, predict_train))
print(classification_report(y_train, predict_train))

[[61939  8447]
 [17518 55298]]
              precision    recall  f1-score   support

           0       0.78      0.88      0.83     70386
           1       0.87      0.76      0.81     72816

    accuracy                           0.82    143202
   macro avg       0.82      0.82      0.82    143202
weighted avg       0.82      0.82      0.82    143202



In [28]:
print(confusion_matrix(y_test, predict_test))
print(classification_report(y_test, predict_test))

[[26387  3665]
 [ 7673 23648]]
              precision    recall  f1-score   support

           0       0.77      0.88      0.82     30052
           1       0.87      0.76      0.81     31321

    accuracy                           0.82     61373
   macro avg       0.82      0.82      0.81     61373
weighted avg       0.82      0.82      0.81     61373



In [29]:
# try a different split
# split training data into training and testing
from sklearn.model_selection import train_test_split

# Select columns to that are data
cols = [col for col in crime if col not in ['type']]

X = crime[cols]

# Select target data
y = crime['type']

X_train, X_test, y_train, y_test = train_test_split(X, y, random_state=100, test_size=0.3)
print(X_train.shape)

(143202, 29)


In [30]:
# Try using the MLP Classifier
mlp = MLPClassifier(hidden_layer_sizes=(29, 29, 29), activation='relu', solver='adam', max_iter=600)
mlp.fit(X_train, y_train)

predict_train = mlp.predict(X_train)
predict_test = mlp.predict(X_test)

In [31]:
print(confusion_matrix(y_train, predict_train))
print(classification_report(y_train, predict_train))

[[63315  7071]
 [17703 55113]]
              precision    recall  f1-score   support

           0       0.78      0.90      0.84     70386
           1       0.89      0.76      0.82     72816

    accuracy                           0.83    143202
   macro avg       0.83      0.83      0.83    143202
weighted avg       0.83      0.83      0.83    143202



In [32]:
print(confusion_matrix(y_test, predict_test))
print(classification_report(y_test, predict_test))

[[26870  3182]
 [ 7878 23443]]
              precision    recall  f1-score   support

           0       0.77      0.89      0.83     30052
           1       0.88      0.75      0.81     31321

    accuracy                           0.82     61373
   macro avg       0.83      0.82      0.82     61373
weighted avg       0.83      0.82      0.82     61373



In [34]:
# try a different split
# split training data into training and testing
from sklearn.model_selection import train_test_split

# Select columns to that are data
cols = [col for col in crime if col not in ['type']]

X = crime[cols]

# Select target data
y = crime['type']

X_train, X_test, y_train, y_test = train_test_split(X, y, random_state=100, test_size=0.25)
print(X_train.shape)

(153431, 29)


In [ ]:
# Try using the MLP Classifier
mlp = MLPClassifier(hidden_layer_sizes=(29, 29, 29, 29), activation='relu', solver='adam', max_iter=300)
mlp.fit(X_train, y_train)

predict_train = mlp.predict(X_train)
predict_test = mlp.predict(X_test)

In [ ]:
print(confusion_matrix(y_train, predict_train))
print(classification_report(y_train, predict_train))

In [ ]:
print(confusion_matrix(y_test, predict_test))
print(classification_report(y_test, predict_test))

In [ ]:
# Use a chi squared test to test relationship between each feature and the target

from sklearn.feature_selection import SelectKBest, chi2

sel_chi2 = SelectKBest(chi2, k=4)    # select 4 features
X_train_chi2 = sel_chi2.fit_transform(X_train, y_train)
print(sel_chi2.get_support())

In [ ]:
# try f test
from sklearn.feature_selection import SelectKBest, f_classif

sel_f = SelectKBest(f_classif, k=4)
X_train_f = sel_f.fit_transform(X_train, y_train)
print(sel_f.get_support())