In [1]:
# NOTE: This does NOT have points close to real ones removed!

import pandas as pd
import numpy as np
%matplotlib inline
import matplotlib.pyplot as plt
import sklearn

crime = pd.read_csv('E:/Vancouver Crime Final/Synthetic Data/both_bne_200k_combined.csv')

crime.head(20)

type             datetime  year  month  day  \
0   Break and Enter Residential/Other  2003-01-01 00:00:00  2003      1    1   
1          Break and Enter Commercial  2003-01-01 00:00:00  2003      1    1   
2   Break and Enter Residential/Other  2003-01-01 00:00:00  2003      1    1   
3   Break and Enter Residential/Other  2003-01-01 00:00:00  2003      1    1   
4   Break and Enter Residential/Other  2003-01-01 01:01:00  2003      1    1   
5   Break and Enter Residential/Other  2003-01-01 04:04:00  2003      1    1   
6   Break and Enter Residential/Other  2003-01-01 04:04:00  2003      1    1   
7          Break and Enter Commercial  2003-01-01 06:06:00  2003      1    1   
8          Break and Enter Commercial  2003-01-01 07:07:00  2003      1    1   
9          Break and Enter Commercial  2003-01-01 07:07:00  2003      1    1   
10  Break and Enter Residential/Other  2003-01-01 07:07:00  2003      1    1   
11  Break and Enter Residential/Other  2003-01-01 11:11:00  2003      1    1   
12         Break and Enter Commercial  2003-01-01 11:11:00  2003      1    1   
13  Break and Enter Residential/Other  2003-01-01 11:11:00  2003      1    1   
14         Break and Enter Commercial  2003-01-01 12:12:00  2003      1    1   
15         Break and Enter Commercial  2003-01-01 12:12:00  2003      1    1   
16  Break and Enter Residential/Other  2003-01-01 12:12:00  2003      1    1   
17         Break and Enter Commercial  2003-01-01 12:12:00  2003      1    1   
18  Break and Enter Residential/Other  2003-01-01 15:15:00  2003      1    1   
19  Break and Enter Residential/Other  2003-01-01 16:16:00  2003      1    1   

    hour  minute  Hour_Minute      hundred_block      utm_x  ...  signal_200  \
0      0       0     0.000000     9XX W 15TH AVE  490791.12  ...           2   
1      0       0     0.000000   64XX VICTORIA DR  495220.95  ...           2   
2      0       1     0.016667    34XX W 42ND AVE  486837.11  ...           3   
3      0      20     0.333333     19XX PARKER ST  495279.46  ...           1   
4      1      46     1.766667       45XX MAIN ST  492627.84  ...           2   
5      4       0     4.000000   25XX GRAVELEY ST  496100.23  ...           0   
6      4      30     4.500000  15XX SE MARINE DR  494572.37  ...           1   
7      6       0     6.000000   5XX W GEORGIA ST  491507.39  ...          10   
8      7      13     7.216667    18XX W 57TH AVE  489132.03  ...           0   
9      7      13     7.216667     45XX FRASER ST  493431.80  ...           2   
10     7      25     7.416667      7XX SEMLIN DR  495363.36  ...           1   
11    11       0    11.000000    22XX TRIUMPH ST  495716.74  ...           4   
12    11       0    11.000000     35XX FRASER ST  493447.88  ...           1   
13    11      45    11.750000    38XX HEATHER ST  491248.44  ...           1   
14    12       0    12.000000      5XX BEATTY ST  492024.04  ...          10   
15    12       0    12.000000   7XX PACIFIC BLVD  492005.87  ...           2   
16    12       0    12.000000       41XX VINE ST  488613.83  ...           0   
17    12      49    12.816667    28XX BENTALL ST  497676.19  ...           3   
18    15      30    15.500000  30XX E KENT N AVE  496782.22  ...           1   
19    16      30    16.500000    28XX E 22ND AVE  496722.62  ...           1   

    trees_25  trees_100  rain_mm  snow_cm  total_precip_mm  temp_c  humidity  \
0          0         32     21.6      0.0             21.6     5.8      81.0   
1          5         40     21.6      0.0             21.6     5.8      81.0   
2          6         38     21.6      0.0             21.6     5.8      81.0   
3          8         88     21.6      0.0             21.6     5.8      81.0   
4          8         83     21.6      0.0             21.6     6.2      78.0   
5          7         73     21.6      0.0             21.6     5.5      88.0   
6          0         41     21.6      0.0             21.6     5.5      88.0   
7          2         27     21.

In [2]:
# Set Break and ENters to 1 and everything else to 0

crime = crime.replace(['NONE'], 0)

crime = crime.replace(['Break and Enter Residential/Other', 'Break and Enter Commercial'], 1)
crime.head()

type             datetime  year  month  day  hour  minute  Hour_Minute  \
0     1  2003-01-01 00:00:00  2003      1    1     0       0     0.000000   
1     1  2003-01-01 00:00:00  2003      1    1     0       0     0.000000   
2     1  2003-01-01 00:00:00  2003      1    1     0       1     0.016667   
3     1  2003-01-01 00:00:00  2003      1    1     0      20     0.333333   
4     1  2003-01-01 01:01:00  2003      1    1     1      46     1.766667   

      hundred_block      utm_x  ...  signal_200  trees_25  trees_100  rain_mm  \
0    9XX W 15TH AVE  490791.12  ...           2         0         32     21.6   
1  64XX VICTORIA DR  495220.95  ...           2         5         40     21.6   
2   34XX W 42ND AVE  486837.11  ...           3         6         38     21.6   
3    19XX PARKER ST  495279.46  ...           1         8         88     21.6   
4      45XX MAIN ST  492627.84  ...           2         8         83     21.6   

   snow_cm  total_precip_mm  temp_c  humidity  pressure  hours_of_light  
0      0.0             21.6     5.8      81.0    101.70            9.53  
1      0.0             21.6     5.8      81.0    101.70            9.53  
2      0.0             21.6     5.8      81.0    101.70            9.53  
3      0.0             21.6     5.8      81.0    101.70            9.53  
4      0.0             21.6     6.2      78.0    101.73            9.53  

[5 rows x 30 columns]

In [3]:
crime

type             datetime  year  month  day  hour  minute  \
0          1  2003-01-01 00:00:00  2003      1    1     0       0   
1          1  2003-01-01 00:00:00  2003      1    1     0       0   
2          1  2003-01-01 00:00:00  2003      1    1     0       1   
3          1  2003-01-01 00:00:00  2003      1    1     0      20   
4          1  2003-01-01 01:01:00  2003      1    1     1      46   
...      ...                  ...   ...    ...  ...   ...     ...   
312139     0  2010-07-31 22:02:00  2010      7   31    22       2   
312140     0  2016-05-31 23:58:00  2016      5   31    23      58   
312141     0  2017-04-05 03:48:00  2017      4    5     3      48   
312142     0  2009-02-11 13:00:00  2009      2   11    13       0   
312143     0  2018-11-19 03:18:00  2018     11   19     3      18   

        Hour_Minute             hundred_block          utm_x  ...  signal_200  \
0          0.000000            9XX W 15TH AVE  490791.120000  ...           2   
1          0.000000          64XX VICTORIA DR  495220.950000  ...           2   
2          0.016667           34XX W 42ND AVE  486837.110000  ...           3   
3          0.333333            19XX PARKER ST  495279.460000  ...           1   
4          1.766667              45XX MAIN ST  492627.840000  ...           2   
...             ...                       ...            ...  ...         ...   
312139    22.033333  SKEENA ST / LOUGHEED HWY  497927.854786  ...           1   
312140    23.966667    E 24TH AVE / SKEENA ST  497923.660000  ...           0   
312141     3.800000        25XX BLOCK PINE ST  489565.000000  ...           5   
312142    13.000000       34XX COLLINGWOOD ST  486772.913788  ...           0   
312143     3.300000             31XX CROWN ST  485880.742079  ...           2   

        trees_25  trees_100  rain_mm  snow_cm  total_precip_mm  temp_c  \
0              0         32     21.6      0.0             21.6     5.8   
1              5         40     21.6      0.0             21.6     5.8   
2              6         38     21.6      0.0             21.6     5.8   
3              8         88     21.6      0.0             21.6     5.8   
4              8         83     21.6      0.0             21.6     6.2   
...          ...        ...      ...      ...              ...     ...   
312139         0         34      0.0      0.0              0.0    16.0   
312140         8         58      0.0      0.0              0.0    16.0   
312141         2         40     13.4      0.0             13.4     8.8   
312142         6         77      1.2      0.0              1.2     5.8   
312143         7         53      0.0      0.0              0.0     0.2   

        humidity  pressure  hours_of_light  
0           81.0    101.70            9.53  
1           81.0    101.70            9.53  
2           81.0    101.70            9.53  
3           81.0    101.70            9.53  
4           78.0    101.73            9.53  
...          ...       ...             ...  
312139      77.0    101.48           16.44  
312140      77.0    101.31           17.34  
312141      90.0    101.03           14.26  
312142      77.0    102.04           11.09  
312143      98.0    102.17           10.12  

[312144 rows x 30 columns]

In [4]:
### Begin Processing the Data


# Import Pre-processing module
from sklearn import preprocessing

# Create Label Encoder
le = preprocessing.LabelEncoder()

# Convert the string columns to numeric
# .astype(str) to ensude they are read as strings and not as mixed types
crime['datetime'] = le.fit_transform(crime['datetime'].astype(str))
crime['hundred_block'] = le.fit_transform(crime['hundred_block'].astype(str))


# Display the results
crime

type  datetime  year  month  day  hour  minute  Hour_Minute  \
0          1         0  2003      1    1     0       0     0.000000   
1          1         0  2003      1    1     0       0     0.000000   
2          1         0  2003      1    1     0       1     0.016667   
3          1         0  2003      1    1     0      20     0.333333   
4          1         4  2003      1    1     1      46     1.766667   
...      ...       ...   ...    ...  ...   ...     ...          ...   
312139     0    129827  2010      7   31    22       2    22.033333   
312140     0    223146  2016      5   31    23      58    23.966667   
312141     0    236692  2017      4    5     3      48     3.800000   
312142     0    106312  2009      2   11    13       0    13.000000   
312143     0    262382  2018     11   19     3      18     3.300000   

        hundred_block          utm_x  ...  signal_200  trees_25  trees_100  \
0               14803  490791.120000  ...           2         0         32   
1               11849  495220.950000  ...           2         5         40   
2                7275  486837.110000  ...           3         6         38   
3                2685  495279.460000  ...           1         8         88   
4                9185  492627.840000  ...           2         8         83   
...               ...            ...  ...         ...       ...        ...   
312139          20324  497927.854786  ...           1         0         34   
312140          16902  497923.660000  ...           0         8         58   
312141           4563  489565.000000  ...           5         2         40   
312142           7122  486772.913788  ...           0         6         77   
312143           6425  485880.742079  ...           2         7         53   

        rain_mm  snow_cm  total_precip_mm  temp_c  humidity  pressure  \
0          21.6      0.0             21.6     5.8      81.0    101.70   
1          21.6      0.0             21.6     5.8      81.0    101.70   
2          21.6      0.0             21.6     5.8      81.0    101.70   
3          21.6      0.0             21.6     5.8      81.0    101.70   
4          21.6      0.0             21.6     6.2      78.0    101.73   
...         ...      ...              ...     ...       ...       ...   
312139      0.0      0.0              0.0    16.0      77.0    101.48   
312140      0.0      0.0              0.0    16.0      77.0    101.31   
312141     13.4      0.0             13.4     8.8      90.0    101.03   
312142      1.2      0.0              1.2     5.8      77.0    102.04   
312143      0.0      0.0              0.0     0.2      98.0    102.17   

        hours_of_light  
0                 9.53  
1                 9.53  
2                 9.53  
3                 9.53  
4                 9.53  
...                ...  
312139           16.44  
312140           17.34  
312141           14.26  
312142           11.09  
312143           10.12  

[312144 rows x 30 columns]

In [5]:
# Scale the Data

columns = [col for col in crime if col not in ['type']]


# Properly scale the reduced set of features
features = crime[columns]

from sklearn.preprocessing import MinMaxScaler
scaler = preprocessing.MinMaxScaler()

print(scaler.fit(features))

MinMaxScaler(copy=True, feature_range=(0, 1))


In [6]:
# Properly scale the features

columns = [col for col in crime if col not in ['type']]

# Properly scale the reduced set of features
features = crime[columns]


scaler = MinMaxScaler().fit(features.values) # scaler = MinMaxScaler().fit(features.values)
features = scaler.transform(features.values) # features = scaler.transform(features.values)
crime[columns] = features
crime

type  datetime    year     month       day      hour    minute  \
0          1  0.000000  0.0000  0.000000  0.000000  0.000000  0.000000   
1          1  0.000000  0.0000  0.000000  0.000000  0.000000  0.000000   
2          1  0.000000  0.0000  0.000000  0.000000  0.000000  0.016949   
3          1  0.000000  0.0000  0.000000  0.000000  0.000000  0.338983   
4          1  0.000015  0.0000  0.000000  0.000000  0.043478  0.779661   
...      ...       ...     ...       ...       ...       ...       ...   
312139     0  0.473086  0.4375  0.545455  1.000000  0.956522  0.033898   
312140     0  0.813137  0.8125  0.363636  1.000000  1.000000  0.983051   
312141     0  0.862498  0.8750  0.272727  0.133333  0.130435  0.813559   
312142     0  0.387398  0.3750  0.090909  0.333333  0.565217  0.000000   
312143     0  0.956112  0.9375  0.909091  0.600000  0.130435  0.305085   

        Hour_Minute  hundred_block     utm_x  ...  signal_200  trees_25  \
0          0.000000       0.673353  0.485335  ...    0.133333   0.00000   
1          0.000000       0.538983  0.788733  ...    0.133333   0.15625   
2          0.000695       0.330922  0.214525  ...    0.200000   0.18750   
3          0.013899       0.122134  0.792740  ...    0.066667   0.25000   
4          0.073662       0.417804  0.611131  ...    0.133333   0.25000   
...             ...            ...       ...  ...         ...       ...   
312139     0.918694       0.924491  0.974129  ...    0.066667   0.00000   
312140     0.999305       0.768832  0.973841  ...    0.000000   0.25000   
312141     0.158443       0.207560  0.401358  ...    0.333333   0.06250   
312142     0.542043       0.323963  0.210128  ...    0.000000   0.18750   
312143     0.137596       0.292258  0.149024  ...    0.133333   0.21875   

        trees_100   rain_mm  snow_cm  total_precip_mm    temp_c  humidity  \
0        0.244275  0.235808      0.0         0.235808  0.408421  0.781609   
1        0.305344  0.235808      0.0         0.235808  0.408421  0.781609   
2        0.290076  0.235808      0.0         0.235808  0.408421  0.781609   
3        0.671756  0.235808      0.0         0.235808  0.408421  0.781609   
4        0.633588  0.235808      0.0         0.235808  0.416842  0.747126   
...           ...       ...      ...              ...       ...       ...   
312139   0.259542  0.000000      0.0         0.000000  0.623158  0.735632   
312140   0.442748  0.000000      0.0         0.000000  0.623158  0.735632   
312141   0.305344  0.146288      0.0         0.146288  0.471579  0.885057   
312142   0.587786  0.013100      0.0         0.013100  0.408421  0.735632   
312143   0.404580  0.000000      0.0         0.000000  0.290526  0.977011   

        pressure  hours_of_light  
0       0.609459        0.010909  
1       0.609459        0.010909  
2       0.609459        0.010909  
3       0.609459        0.010909  
4       0.613514        0.010909  
...          ...             ...  
312139  0.579730        0.848485  
312140  0.556757        0.957576  
312141  0.518919        0.584242  
312142  0.655405        0.200000  
312143  0.672973        0.082424  

[312144 rows x 30 columns]

In [7]:
# split training data into training and testing
from sklearn.model_selection import train_test_split

# Select columns to that are data
cols = [col for col in crime if col not in ['type']]

X = crime[cols]

# Select target data
y = crime['type']

X_train, X_test, y_train, y_test = train_test_split(X, y, random_state=100, test_size=0.3)
print(X_train.shape)

(218500, 29)


In [8]:
# Trying Random Forest Classifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.feature_selection import SelectFromModel

model_tree = RandomForestClassifier(random_state=100, n_estimators=50)
model_tree.fit(X_train, y_train)
print(model_tree.feature_importances_)
sel_model_tree = SelectFromModel(estimator=model_tree, prefit=True, threshold='mean')  
      # since we already fit the data, we specify prefit option here
      # Features whose importance is greater or equal to the threshold are kept while the others are discarded.
X_train_sfm_tree = sel_model_tree.transform(X_train)
print(sel_model_tree.get_support())

feature_importances = pd.DataFrame(model_tree.feature_importances_,
                                   index = X_train.columns,
                                    columns=['importance']).sort_values('importance', 
                                                                        ascending=False)
feature_importances

[0.03280743 0.01696635 0.01300886 0.02068578 0.01910406 0.29985963
 0.03904277 0.13116993 0.03535726 0.04154573 0.03731375 0.03554767
 0.01107956 0.01443185 0.01969443 0.02993445 0.002072   0.00249689
 0.01108526 0.01575531 0.02037428 0.02815301 0.01213591 0.00123724
 0.0118907  0.02502962 0.02221348 0.02540864 0.02459814]
[False False False False False  True  True  True  True  True  True  True
 False False False False False False False False False False False False
 False False False False False]


importance
minute             0.299860
hundred_block      0.131170
utm_y              0.041546
Hour_Minute        0.039043
latitude           0.037314
longitude          0.035548
utm_x              0.035357
datetime           0.032807
light_pole_100     0.029934
trees_100          0.028153
pressure           0.025409
temp_c             0.025030
hours_of_light     0.024598
humidity           0.022213
day                0.020686
trees_25           0.020374
light_pole_50      0.019694
hour               0.019104
year               0.016966
signal_200         0.015755
light_pole_25      0.014432
month              0.013009
rain_mm            0.012136
total_precip_mm    0.011891
signal_100         0.011085
light_pole_12_5    0.011080
signal_50          0.002497
signal_25          0.002072
snow_cm            0.001237

In [9]:
# Simple Neural Network

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import sklearn
from sklearn.neural_network import MLPClassifier
from sklearn.neural_network import MLPRegressor

# import needed modules
from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_squared_error
from math import sqrt
from sklearn.metrics import r2_score

In [10]:
# Try using the MLP Classifier
mlp = MLPClassifier(hidden_layer_sizes=(29, 29, 29), activation='relu', solver='adam', max_iter=300)
mlp.fit(X_train, y_train)

predict_train = mlp.predict(X_train)
predict_test = mlp.predict(X_test)

In [11]:
from sklearn.metrics import classification_report, confusion_matrix
print(confusion_matrix(y_train, predict_train))
print(classification_report(y_train, predict_train))

[[135380  10136]
 [ 24024  48960]]
              precision    recall  f1-score   support

           0       0.85      0.93      0.89    145516
           1       0.83      0.67      0.74     72984

    accuracy                           0.84    218500
   macro avg       0.84      0.80      0.81    218500
weighted avg       0.84      0.84      0.84    218500



In [12]:
print(confusion_matrix(y_test, predict_test))
print(classification_report(y_test, predict_test))

[[58074  4417]
 [10445 20708]]
              precision    recall  f1-score   support

           0       0.85      0.93      0.89     62491
           1       0.82      0.66      0.74     31153

    accuracy                           0.84     93644
   macro avg       0.84      0.80      0.81     93644
weighted avg       0.84      0.84      0.84     93644



In [13]:
# Try using the MLP Classifier
mlp = MLPClassifier(hidden_layer_sizes=(29, 29, 29), activation='relu', solver='adam', max_iter=3000)
mlp.fit(X_train, y_train)

predict_train = mlp.predict(X_train)
predict_test = mlp.predict(X_test)

In [14]:
print(confusion_matrix(y_train, predict_train))
print(classification_report(y_train, predict_train))

[[137309   8207]
 [ 23059  49925]]
              precision    recall  f1-score   support

           0       0.86      0.94      0.90    145516
           1       0.86      0.68      0.76     72984

    accuracy                           0.86    218500
   macro avg       0.86      0.81      0.83    218500
weighted avg       0.86      0.86      0.85    218500



In [15]:
print(confusion_matrix(y_test, predict_test))
print(classification_report(y_test, predict_test))

[[58838  3653]
 [10053 21100]]
              precision    recall  f1-score   support

           0       0.85      0.94      0.90     62491
           1       0.85      0.68      0.75     31153

    accuracy                           0.85     93644
   macro avg       0.85      0.81      0.83     93644
weighted avg       0.85      0.85      0.85     93644



In [16]:
############################# END HERE ###################################

In [17]:
# Try using the MLP Classifier
mlp = MLPClassifier(hidden_layer_sizes=(29, 29, 29, 29, 29, 29, 29), activation='relu', solver='adam', max_iter=300)
mlp.fit(X_train, y_train)

predict_train = mlp.predict(X_train)
predict_test = mlp.predict(X_test)

In [18]:
print(confusion_matrix(y_train, predict_train))
print(classification_report(y_train, predict_train))

[[138448   7068]
 [ 25065  47919]]
              precision    recall  f1-score   support

           0       0.85      0.95      0.90    145516
           1       0.87      0.66      0.75     72984

    accuracy                           0.85    218500
   macro avg       0.86      0.80      0.82    218500
weighted avg       0.85      0.85      0.85    218500



In [19]:
print(confusion_matrix(y_test, predict_test))
print(classification_report(y_test, predict_test))

[[59386  3105]
 [10878 20275]]
              precision    recall  f1-score   support

           0       0.85      0.95      0.89     62491
           1       0.87      0.65      0.74     31153

    accuracy                           0.85     93644
   macro avg       0.86      0.80      0.82     93644
weighted avg       0.85      0.85      0.84     93644



In [20]:
feature_importances

importance
minute             0.299860
hundred_block      0.131170
utm_y              0.041546
Hour_Minute        0.039043
latitude           0.037314
longitude          0.035548
utm_x              0.035357
datetime           0.032807
light_pole_100     0.029934
trees_100          0.028153
pressure           0.025409
temp_c             0.025030
hours_of_light     0.024598
humidity           0.022213
day                0.020686
trees_25           0.020374
light_pole_50      0.019694
hour               0.019104
year               0.016966
signal_200         0.015755
light_pole_25      0.014432
month              0.013009
rain_mm            0.012136
total_precip_mm    0.011891
signal_100         0.011085
light_pole_12_5    0.011080
signal_50          0.002497
signal_25          0.002072
snow_cm            0.001237

In [21]:
# Cut down features

# split training data into training and testing
from sklearn.model_selection import train_test_split

# Select columns to that are data
cols = [col for col in crime if col not in ['type', 'minute', 'hour', 'latitude', 'longitude', 'datetime']]

X = crime[cols]

# Select target data
y = crime['type']

X_train, X_test, y_train, y_test = train_test_split(X, y, random_state=100, test_size=0.3)
print(X_train.shape)

(218500, 24)


In [22]:
X_train

year     month       day  Hour_Minute  hundred_block     utm_x  \
189587  0.1875  1.000000  0.366667     0.774149       0.260553  0.262273   
46082   0.3125  0.272727  0.400000     0.708826       0.081878  0.410261   
196050  0.5000  0.454545  0.900000     0.163308       0.271743  0.617510   
40658   0.2500  0.545455  0.400000     0.312717       0.063956  0.420296   
240857  0.6250  0.454545  0.466667     0.523280       0.066503  0.748807   
...        ...       ...       ...          ...            ...       ...   
65615   0.5000  1.000000  0.266667     0.458652       0.482806  0.521112   
253799  0.6250  0.636364  0.533333     0.002780       0.535162  0.544118   
210755  0.0000  0.181818  0.533333     0.804726       0.371406  0.595628   
56088   0.4375  0.000000  0.133333     0.625434       0.458470  0.711003   
300552  0.1875  0.090909  0.200000     0.699097       0.832742  0.997450   

           utm_y  light_pole_12_5  light_pole_25  light_pole_50  ...  \
189587  0.284029         0.035714       0.014925       0.025316  ...   
46082   0.496586         0.000000       0.014925       0.139241  ...   
196050  0.367856         0.000000       0.014925       0.025316  ...   
40658   0.177420         0.000000       0.029851       0.113924  ...   
240857  0.326542         0.000000       0.014925       0.113924  ...   
...          ...              ...            ...            ...  ...   
65615   0.293253         0.035714       0.044776       0.101266  ...   
253799  0.236150         0.035714       0.014925       0.037975  ...   
210755  0.352726         0.000000       0.029851       0.050633  ...   
56088   0.333695         0.000000       0.014925       0.075949  ...   
300552  0.508719         0.000000       0.104478       0.177215  ...   

        signal_200  trees_25  trees_100   rain_mm  snow_cm  total_precip_mm  \
189587    0.000000   0.28125   0.511450  0.069869      0.0         0.069869   
46082     0.066667   0.21875   0.435115  0.008734      0.0         0.008734   
196050    0.133333   0.15625   0.465649  0.000000      0.0         0.000000   
40658     0.066667   0.21875   0.305344  0.000000      0.0         0.000000   
240857    0.000000   0.21875   0.496183  0.000000      0.0         0.000000   
...            ...       ...        ...       ...      ...              ...   
65615     0.066667   0.18750   0.190840  0.000000      0.0         0.000000   
253799    0.133333   0.21875   0.297710  0.000000      0.0         0.000000   
210755    0.066667   0.15625   0.328244  0.009825      0.0         0.009825   
56088     0.000000   0.28125   0.374046  0.010917      0.0         0.010917   
300552    0.066667   0.03125   0.076336  0.013100      0.0         0.013100   

          temp_c  humidity  pressure  hours_of_light  
189587  0.429474  0.839080  0.579730        0.007273  
46082   0.538947  0.402299  0.590541        0.646061  
196050  0.631579  0.816092  0.450000        0.993939  
40658   0.671579  0.689655  0.602703        0.949091  
240857  0.669474  0.701149  0.583784        0.996364  
...          ...       ...       ...             ...  
65615   0.353684  0.816092  0.741892        0.013333  
253799  0.694737  0.873563  0.575676        0.727273  
210755  0.458947  0.678161  0.660811        0.435152  
56088   0.454737  0.873563  0.658108        0.019394  
300552  0.456842  0.758621  0.677027        0.172121  

[218500 rows x 24 columns]

In [23]:
y_train

189587    0
46082     1
196050    0
40658     1
240857    0
         ..
65615     1
253799    0
210755    0
56088     1
300552    0
Name: type, Length: 218500, dtype: int64

In [24]:
# Trying Random Forest Classifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.feature_selection import SelectFromModel

model_tree = RandomForestClassifier(random_state=100, n_estimators=50)
model_tree.fit(X_train, y_train)
print(model_tree.feature_importances_)
sel_model_tree = SelectFromModel(estimator=model_tree, prefit=True, threshold='mean')  
      # since we already fit the data, we specify prefit option here
      # Features whose importance is greater or equal to the threshold are kept while the others are discarded.
X_train_sfm_tree = sel_model_tree.transform(X_train)
print(sel_model_tree.get_support())

feature_importances = pd.DataFrame(model_tree.feature_importances_,
                                   index = X_train.columns,
                                    columns=['importance']).sort_values('importance', 
                                                                        ascending=False)
feature_importances

[0.04066442 0.02290708 0.03673466 0.07831813 0.18850818 0.07442564
 0.08151805 0.01683447 0.02445969 0.034556   0.05105562 0.00336905
 0.00394734 0.01436685 0.02527861 0.03453481 0.05293107 0.02067129
 0.00170445 0.02125305 0.04420932 0.03961705 0.04489077 0.04324441]
[False False False  True  True  True  True False False False  True False
 False False False False  True False False False  True False  True  True]


importance
hundred_block      0.188508
utm_y              0.081518
Hour_Minute        0.078318
utm_x              0.074426
trees_100          0.052931
light_pole_100     0.051056
pressure           0.044891
temp_c             0.044209
hours_of_light     0.043244
year               0.040664
humidity           0.039617
day                0.036735
light_pole_50      0.034556
trees_25           0.034535
signal_200         0.025279
light_pole_25      0.024460
month              0.022907
total_precip_mm    0.021253
rain_mm            0.020671
light_pole_12_5    0.016834
signal_100         0.014367
signal_50          0.003947
signal_25          0.003369
snow_cm            0.001704

In [25]:
# Try using the MLP Classifier
mlp = MLPClassifier(hidden_layer_sizes=(24, 24, 24), activation='relu', solver='adam', max_iter=300)
mlp.fit(X_train, y_train)

predict_train = mlp.predict(X_train)
predict_test = mlp.predict(X_test)

d:\program files (x86)\microsoft visual studio\shared\python37_64\lib\site-packages\sklearn\neural_network\multilayer_perceptron.py:566: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (300) reached and the optimization hasn't converged yet.
  % self.max_iter, ConvergenceWarning)


In [26]:
print(confusion_matrix(y_train, predict_train))
print(classification_report(y_train, predict_train))

[[126624  18892]
 [ 34257  38727]]
              precision    recall  f1-score   support

           0       0.79      0.87      0.83    145516
           1       0.67      0.53      0.59     72984

    accuracy                           0.76    218500
   macro avg       0.73      0.70      0.71    218500
weighted avg       0.75      0.76      0.75    218500



In [27]:
print(confusion_matrix(y_test, predict_test))
print(classification_report(y_test, predict_test))

[[54119  8372]
 [14924 16229]]
              precision    recall  f1-score   support

           0       0.78      0.87      0.82     62491
           1       0.66      0.52      0.58     31153

    accuracy                           0.75     93644
   macro avg       0.72      0.69      0.70     93644
weighted avg       0.74      0.75      0.74     93644

