In [1]:
# NOTE: This does NOT have points close to real ones removed!

import pandas as pd
import numpy as np
%matplotlib inline
import matplotlib.pyplot as plt
import sklearn

crime = pd.read_csv('E:/Vancouver Crime Final/Synthetic Data/both_bne_100k_from300k_combined.csv')

crime.head(20)

type             datetime  year  month  day  \
0   Break and Enter Residential/Other  2003-01-01 00:00:00  2003      1    1   
1          Break and Enter Commercial  2003-01-01 00:00:00  2003      1    1   
2   Break and Enter Residential/Other  2003-01-01 00:00:00  2003      1    1   
3   Break and Enter Residential/Other  2003-01-01 00:00:00  2003      1    1   
4   Break and Enter Residential/Other  2003-01-01 01:01:00  2003      1    1   
5   Break and Enter Residential/Other  2003-01-01 04:04:00  2003      1    1   
6   Break and Enter Residential/Other  2003-01-01 04:04:00  2003      1    1   
7          Break and Enter Commercial  2003-01-01 06:06:00  2003      1    1   
8          Break and Enter Commercial  2003-01-01 07:07:00  2003      1    1   
9          Break and Enter Commercial  2003-01-01 07:07:00  2003      1    1   
10  Break and Enter Residential/Other  2003-01-01 07:07:00  2003      1    1   
11  Break and Enter Residential/Other  2003-01-01 11:11:00  2003      1    1   
12         Break and Enter Commercial  2003-01-01 11:11:00  2003      1    1   
13  Break and Enter Residential/Other  2003-01-01 11:11:00  2003      1    1   
14         Break and Enter Commercial  2003-01-01 12:12:00  2003      1    1   
15         Break and Enter Commercial  2003-01-01 12:12:00  2003      1    1   
16  Break and Enter Residential/Other  2003-01-01 12:12:00  2003      1    1   
17         Break and Enter Commercial  2003-01-01 12:12:00  2003      1    1   
18  Break and Enter Residential/Other  2003-01-01 15:15:00  2003      1    1   
19  Break and Enter Residential/Other  2003-01-01 16:16:00  2003      1    1   

    hour  minute  Hour_Minute      hundred_block      utm_x  ...  signal_200  \
0      0       0     0.000000     9XX W 15TH AVE  490791.12  ...           2   
1      0       0     0.000000   64XX VICTORIA DR  495220.95  ...           2   
2      0       1     0.016667    34XX W 42ND AVE  486837.11  ...           3   
3      0      20     0.333333     19XX PARKER ST  495279.46  ...           1   
4      1      46     1.766667       45XX MAIN ST  492627.84  ...           2   
5      4       0     4.000000   25XX GRAVELEY ST  496100.23  ...           0   
6      4      30     4.500000  15XX SE MARINE DR  494572.37  ...           1   
7      6       0     6.000000   5XX W GEORGIA ST  491507.39  ...          10   
8      7      13     7.216667    18XX W 57TH AVE  489132.03  ...           0   
9      7      13     7.216667     45XX FRASER ST  493431.80  ...           2   
10     7      25     7.416667      7XX SEMLIN DR  495363.36  ...           1   
11    11       0    11.000000    22XX TRIUMPH ST  495716.74  ...           4   
12    11       0    11.000000     35XX FRASER ST  493447.88  ...           1   
13    11      45    11.750000    38XX HEATHER ST  491248.44  ...           1   
14    12       0    12.000000      5XX BEATTY ST  492024.04  ...          10   
15    12       0    12.000000   7XX PACIFIC BLVD  492005.87  ...           2   
16    12       0    12.000000       41XX VINE ST  488613.83  ...           0   
17    12      49    12.816667    28XX BENTALL ST  497676.19  ...           3   
18    15      30    15.500000  30XX E KENT N AVE  496782.22  ...           1   
19    16      30    16.500000    28XX E 22ND AVE  496722.62  ...           1   

    trees_25  trees_100  rain_mm  snow_cm  total_precip_mm  temp_c  humidity  \
0          0         32     21.6      0.0             21.6     5.8      81.0   
1          5         40     21.6      0.0             21.6     5.8      81.0   
2          6         38     21.6      0.0             21.6     5.8      81.0   
3          8         88     21.6      0.0             21.6     5.8      81.0   
4          8         83     21.6      0.0             21.6     6.2      78.0   
5          7         73     21.6      0.0             21.6     5.5      88.0   
6          0         41     21.6      0.0             21.6     5.5      88.0   
7          2         27     21.

In [2]:
# Set Break and ENters to 1 and everything else to 0

crime = crime.replace(['NONE'], 0)

crime = crime.replace(['Break and Enter Residential/Other', 'Break and Enter Commercial'], 1)
crime.head()

type             datetime  year  month  day  hour  minute  Hour_Minute  \
0     1  2003-01-01 00:00:00  2003      1    1     0       0     0.000000   
1     1  2003-01-01 00:00:00  2003      1    1     0       0     0.000000   
2     1  2003-01-01 00:00:00  2003      1    1     0       1     0.016667   
3     1  2003-01-01 00:00:00  2003      1    1     0      20     0.333333   
4     1  2003-01-01 01:01:00  2003      1    1     1      46     1.766667   

      hundred_block      utm_x  ...  signal_200  trees_25  trees_100  rain_mm  \
0    9XX W 15TH AVE  490791.12  ...           2         0         32     21.6   
1  64XX VICTORIA DR  495220.95  ...           2         5         40     21.6   
2   34XX W 42ND AVE  486837.11  ...           3         6         38     21.6   
3    19XX PARKER ST  495279.46  ...           1         8         88     21.6   
4      45XX MAIN ST  492627.84  ...           2         8         83     21.6   

   snow_cm  total_precip_mm  temp_c  humidity  pressure  hours_of_light  
0      0.0             21.6     5.8      81.0    101.70            9.53  
1      0.0             21.6     5.8      81.0    101.70            9.53  
2      0.0             21.6     5.8      81.0    101.70            9.53  
3      0.0             21.6     5.8      81.0    101.70            9.53  
4      0.0             21.6     6.2      78.0    101.73            9.53  

[5 rows x 30 columns]

In [3]:
crime

type             datetime  year  month  day  hour  minute  \
0          1  2003-01-01 00:00:00  2003      1    1     0       0   
1          1  2003-01-01 00:00:00  2003      1    1     0       0   
2          1  2003-01-01 00:00:00  2003      1    1     0       1   
3          1  2003-01-01 00:00:00  2003      1    1     0      20   
4          1  2003-01-01 01:01:00  2003      1    1     1      46   
...      ...                  ...   ...    ...  ...   ...     ...   
206805     0  2008-08-19 02:29:00  2008      8   19     2      29   
206806     0  2010-01-24 10:12:00  2010      1   24    10      12   
206807     0  2016-07-25 04:56:00  2016      7   25     4      56   
206808     0  2018-01-11 03:42:00  2018      1   11     3      42   
206809     0  2011-04-22 04:37:00  2011      4   22     4      37   

        Hour_Minute                 hundred_block          utm_x  ...  \
0          0.000000                9XX W 15TH AVE  490791.120000  ...   
1          0.000000              64XX VICTORIA DR  495220.950000  ...   
2          0.016667               34XX W 42ND AVE  486837.110000  ...   
3          0.333333                19XX PARKER ST  495279.460000  ...   
4          1.766667                  45XX MAIN ST  492627.840000  ...   
...             ...                           ...            ...  ...   
206805     2.483333  E 5TH AVE / PRINCE EDWARD ST  493041.100000  ...   
206806    10.200000        SLOCAN ST / TRIUMPH ST  496412.900000  ...   
206807     4.933333      HIGHBURY ST / W 10TH AVE  486335.362207  ...   
206808     3.700000      E 33RD AVE / DUMFRIES ST  494617.321156  ...   
206809     4.616667                 1X W 13TH AVE  492323.780000  ...   

        signal_200  trees_25  trees_100  rain_mm  snow_cm  total_precip_mm  \
0                2         0         32     21.6      0.0             21.6   
1                2         5         40     21.6      0.0             21.6   
2                3         6         38     21.6      0.0             21.6   
3                1         8         88     21.6      0.0             21.6   
4                2         8         83     21.6      0.0             21.6   
...            ...       ...        ...      ...      ...              ...   
206805           1         4         49      7.8      0.0              7.8   
206806           1         7         60      3.8      0.0              3.8   
206807           3         1         37      0.0      0.0              0.0   
206808           2         5         49     17.6      0.0             17.6   
206809           3         4         48      0.0      0.0              0.0   

        temp_c  humidity  pressure  hours_of_light  
0          5.8      81.0    101.70            9.53  
1          5.8      81.0    101.70            9.53  
2          5.8      81.0    101.70            9.53  
3          5.8      81.0    101.70            9.53  
4          6.2      78.0    101.73            9.53  
...        ...       ...       ...             ...  
206805    15.8      87.0    100.88           15.31  
206806     5.6      79.0    101.22           10.21  
206807    16.6      83.0    101.63           16.72  
206808     4.5      94.0    101.51            9.75  
206809     4.3      80.0    102.43           15.28  

[206810 rows x 30 columns]

In [4]:
### Begin Processing the Data


# Import Pre-processing module
from sklearn import preprocessing

# Create Label Encoder
le = preprocessing.LabelEncoder()

# Convert the string columns to numeric
# .astype(str) to ensude they are read as strings and not as mixed types
crime['datetime'] = le.fit_transform(crime['datetime'].astype(str))
crime['hundred_block'] = le.fit_transform(crime['hundred_block'].astype(str))


# Display the results
crime

type  datetime  year  month  day  hour  minute  Hour_Minute  \
0          1         0  2003      1    1     0       0     0.000000   
1          1         0  2003      1    1     0       0     0.000000   
2          1         0  2003      1    1     0       1     0.016667   
3          1         0  2003      1    1     0      20     0.333333   
4          1         1  2003      1    1     1      46     1.766667   
...      ...       ...   ...    ...  ...   ...     ...          ...   
206805     0     63566  2008      8   19     2      29     2.483333   
206806     0     77992  2010      1   24    10      12    10.200000   
206807     0    141828  2016      7   25     4      56     4.933333   
206808     0    156279  2018      1   11     3      42     3.700000   
206809     0     89912  2011      4   22     4      37     4.616667   

        hundred_block          utm_x  ...  signal_200  trees_25  trees_100  \
0               14775  490791.120000  ...           2         0         32   
1               11827  495220.950000  ...           2         5         40   
2                7262  486837.110000  ...           3         6         38   
3                2679  495279.460000  ...           1         8         88   
4                9167  492627.840000  ...           2         8         83   
...               ...            ...  ...         ...       ...        ...   
206805          17570  493041.100000  ...           1         4         49   
206806          20263  496412.900000  ...           1         7         60   
206807          18531  486335.362207  ...           3         1         37   
206808          17048  494617.321156  ...           2         5         49   
206809           2837  492323.780000  ...           3         4         48   

        rain_mm  snow_cm  total_precip_mm  temp_c  humidity  pressure  \
0          21.6      0.0             21.6     5.8      81.0    101.70   
1          21.6      0.0             21.6     5.8      81.0    101.70   
2          21.6      0.0             21.6     5.8      81.0    101.70   
3          21.6      0.0             21.6     5.8      81.0    101.70   
4          21.6      0.0             21.6     6.2      78.0    101.73   
...         ...      ...              ...     ...       ...       ...   
206805      7.8      0.0              7.8    15.8      87.0    100.88   
206806      3.8      0.0              3.8     5.6      79.0    101.22   
206807      0.0      0.0              0.0    16.6      83.0    101.63   
206808     17.6      0.0             17.6     4.5      94.0    101.51   
206809      0.0      0.0              0.0     4.3      80.0    102.43   

        hours_of_light  
0                 9.53  
1                 9.53  
2                 9.53  
3                 9.53  
4                 9.53  
...                ...  
206805           15.31  
206806           10.21  
206807           16.72  
206808            9.75  
206809           15.28  

[206810 rows x 30 columns]

In [5]:
# Scale the Data

columns = [col for col in crime if col not in ['type']]


# Properly scale the reduced set of features
features = crime[columns]

from sklearn.preprocessing import MinMaxScaler
scaler = preprocessing.MinMaxScaler()

print(scaler.fit(features))

MinMaxScaler(copy=True, feature_range=(0, 1))


In [6]:
# Properly scale the features

columns = [col for col in crime if col not in ['type']]

# Properly scale the reduced set of features
features = crime[columns]


scaler = MinMaxScaler().fit(features.values) # scaler = MinMaxScaler().fit(features.values)
features = scaler.transform(features.values) # features = scaler.transform(features.values)
crime[columns] = features
crime

type  datetime    year     month       day      hour    minute  \
0          1  0.000000  0.0000  0.000000  0.000000  0.000000  0.000000   
1          1  0.000000  0.0000  0.000000  0.000000  0.000000  0.000000   
2          1  0.000000  0.0000  0.000000  0.000000  0.000000  0.016949   
3          1  0.000000  0.0000  0.000000  0.000000  0.000000  0.338983   
4          1  0.000006  0.0000  0.000000  0.000000  0.043478  0.779661   
...      ...       ...     ...       ...       ...       ...       ...   
206805     0  0.370129  0.3125  0.636364  0.600000  0.086957  0.491525   
206806     0  0.454128  0.4375  0.000000  0.766667  0.434783  0.203390   
206807     0  0.825830  0.8125  0.545455  0.800000  0.173913  0.949153   
206808     0  0.909974  0.9375  0.000000  0.333333  0.130435  0.711864   
206809     0  0.523536  0.5000  0.272727  0.700000  0.173913  0.627119   

        Hour_Minute  hundred_block     utm_x  ...  signal_200  trees_25  \
0          0.000000       0.675120  0.485327  ...    0.133333   0.00000   
1          0.000000       0.540416  0.788720  ...    0.133333   0.15625   
2          0.000695       0.331825  0.214522  ...    0.200000   0.18750   
3          0.013899       0.122413  0.792727  ...    0.066667   0.25000   
4          0.073662       0.418871  0.611121  ...    0.133333   0.25000   
...             ...            ...       ...  ...         ...       ...   
206805     0.103544       0.802833  0.639425  ...    0.066667   0.12500   
206806     0.425295       0.925885  0.870355  ...    0.066667   0.21875   
206807     0.205698       0.846744  0.180158  ...    0.200000   0.03125   
206808     0.154274       0.778981  0.747378  ...    0.133333   0.15625   
206809     0.192495       0.129632  0.590297  ...    0.200000   0.12500   

        trees_100   rain_mm  snow_cm  total_precip_mm    temp_c  humidity  \
0        0.244275  0.235808      0.0         0.235808  0.408421  0.781609   
1        0.305344  0.235808      0.0         0.235808  0.408421  0.781609   
2        0.290076  0.235808      0.0         0.235808  0.408421  0.781609   
3        0.671756  0.235808      0.0         0.235808  0.408421  0.781609   
4        0.633588  0.235808      0.0         0.235808  0.416842  0.747126   
...           ...       ...      ...              ...       ...       ...   
206805   0.374046  0.085153      0.0         0.085153  0.618947  0.850575   
206806   0.458015  0.041485      0.0         0.041485  0.404211  0.758621   
206807   0.282443  0.000000      0.0         0.000000  0.635789  0.804598   
206808   0.374046  0.192140      0.0         0.192140  0.381053  0.931034   
206809   0.366412  0.000000      0.0         0.000000  0.376842  0.770115   

        pressure  hours_of_light  
0       0.607337        0.010909  
1       0.607337        0.010909  
2       0.607337        0.010909  
3       0.607337        0.010909  
4       0.611413        0.010909  
...          ...             ...  
206805  0.495924        0.711515  
206806  0.542120        0.093333  
206807  0.597826        0.882424  
206808  0.581522        0.037576  
206809  0.706522        0.707879  

[206810 rows x 30 columns]

In [7]:
# split training data into training and testing
from sklearn.model_selection import train_test_split

# Select columns to that are data
cols = [col for col in crime if col not in ['type']]

X = crime[cols]

# Select target data
y = crime['type']

X_train, X_test, y_train, y_test = train_test_split(X, y, random_state=100, test_size=0.3)
print(X_train.shape)

(144767, 29)


In [8]:
# Trying Random Forest Classifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.feature_selection import SelectFromModel

model_tree = RandomForestClassifier(random_state=100, n_estimators=50)
model_tree.fit(X_train, y_train)
print(model_tree.feature_importances_)
sel_model_tree = SelectFromModel(estimator=model_tree, prefit=True, threshold='mean')  
      # since we already fit the data, we specify prefit option here
      # Features whose importance is greater or equal to the threshold are kept while the others are discarded.
X_train_sfm_tree = sel_model_tree.transform(X_train)
print(sel_model_tree.get_support())

feature_importances = pd.DataFrame(model_tree.feature_importances_,
                                   index = X_train.columns,
                                    columns=['importance']).sort_values('importance', 
                                                                        ascending=False)
feature_importances

[0.03430519 0.0190266  0.01335124 0.02119461 0.0196742  0.24407758
 0.03697486 0.17640869 0.0358664  0.04115978 0.0397719  0.03620222
 0.01103939 0.01470101 0.01972682 0.0313312  0.00223378 0.00250173
 0.00856219 0.01765218 0.02006407 0.02888761 0.01214024 0.00110877
 0.01225634 0.02549988 0.02288248 0.026151   0.02524804]
[False False False False False  True  True  True  True  True  True  True
 False False False False False False False False False False False False
 False False False False False]


importance
minute             0.244078
hundred_block      0.176409
utm_y              0.041160
latitude           0.039772
Hour_Minute        0.036975
longitude          0.036202
utm_x              0.035866
datetime           0.034305
light_pole_100     0.031331
trees_100          0.028888
pressure           0.026151
temp_c             0.025500
hours_of_light     0.025248
humidity           0.022882
day                0.021195
trees_25           0.020064
light_pole_50      0.019727
hour               0.019674
year               0.019027
signal_200         0.017652
light_pole_25      0.014701
month              0.013351
total_precip_mm    0.012256
rain_mm            0.012140
light_pole_12_5    0.011039
signal_100         0.008562
signal_50          0.002502
signal_25          0.002234
snow_cm            0.001109

In [9]:
# Simple Neural Network

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import sklearn
from sklearn.neural_network import MLPClassifier
from sklearn.neural_network import MLPRegressor

# import needed modules
from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_squared_error
from math import sqrt
from sklearn.metrics import r2_score

In [10]:
# Try using the MLP Classifier
mlp = MLPClassifier(hidden_layer_sizes=(29, 29, 29), activation='relu', solver='adam', max_iter=300)
mlp.fit(X_train, y_train)

predict_train = mlp.predict(X_train)
predict_test = mlp.predict(X_test)

In [11]:
from sklearn.metrics import classification_report, confusion_matrix
print(confusion_matrix(y_train, predict_train))
print(classification_report(y_train, predict_train))

[[62643  9402]
 [17770 54952]]
              precision    recall  f1-score   support

           0       0.78      0.87      0.82     72045
           1       0.85      0.76      0.80     72722

    accuracy                           0.81    144767
   macro avg       0.82      0.81      0.81    144767
weighted avg       0.82      0.81      0.81    144767



In [12]:
print(confusion_matrix(y_test, predict_test))
print(classification_report(y_test, predict_test))

[[26625  4003]
 [ 7835 23580]]
              precision    recall  f1-score   support

           0       0.77      0.87      0.82     30628
           1       0.85      0.75      0.80     31415

    accuracy                           0.81     62043
   macro avg       0.81      0.81      0.81     62043
weighted avg       0.81      0.81      0.81     62043



In [13]:
# Try using the MLP Classifier
mlp = MLPClassifier(hidden_layer_sizes=(29, 29, 29), activation='relu', solver='adam', max_iter=3000)
mlp.fit(X_train, y_train)

predict_train = mlp.predict(X_train)
predict_test = mlp.predict(X_test)

In [14]:
print(confusion_matrix(y_train, predict_train))
print(classification_report(y_train, predict_train))

[[64401  7644]
 [18474 54248]]
              precision    recall  f1-score   support

           0       0.78      0.89      0.83     72045
           1       0.88      0.75      0.81     72722

    accuracy                           0.82    144767
   macro avg       0.83      0.82      0.82    144767
weighted avg       0.83      0.82      0.82    144767



In [15]:
print(confusion_matrix(y_test, predict_test))
print(classification_report(y_test, predict_test))

[[27332  3296]
 [ 8133 23282]]
              precision    recall  f1-score   support

           0       0.77      0.89      0.83     30628
           1       0.88      0.74      0.80     31415

    accuracy                           0.82     62043
   macro avg       0.82      0.82      0.82     62043
weighted avg       0.82      0.82      0.81     62043



In [16]:
############################# END HERE ###################################

In [17]:
# Try using the MLP Classifier
mlp = MLPClassifier(hidden_layer_sizes=(29, 29, 29, 29, 29, 29, 29), activation='relu', solver='adam', max_iter=200)
mlp.fit(X_train, y_train)

predict_train = mlp.predict(X_train)
predict_test = mlp.predict(X_test)

In [18]:
print(confusion_matrix(y_train, predict_train))
print(classification_report(y_train, predict_train))

[[64760  7285]
 [19660 53062]]
              precision    recall  f1-score   support

           0       0.77      0.90      0.83     72045
           1       0.88      0.73      0.80     72722

    accuracy                           0.81    144767
   macro avg       0.82      0.81      0.81    144767
weighted avg       0.82      0.81      0.81    144767



In [19]:
print(confusion_matrix(y_test, predict_test))
print(classification_report(y_test, predict_test))

[[27460  3168]
 [ 8588 22827]]
              precision    recall  f1-score   support

           0       0.76      0.90      0.82     30628
           1       0.88      0.73      0.80     31415

    accuracy                           0.81     62043
   macro avg       0.82      0.81      0.81     62043
weighted avg       0.82      0.81      0.81     62043



In [20]:
feature_importances

importance
minute             0.244078
hundred_block      0.176409
utm_y              0.041160
latitude           0.039772
Hour_Minute        0.036975
longitude          0.036202
utm_x              0.035866
datetime           0.034305
light_pole_100     0.031331
trees_100          0.028888
pressure           0.026151
temp_c             0.025500
hours_of_light     0.025248
humidity           0.022882
day                0.021195
trees_25           0.020064
light_pole_50      0.019727
hour               0.019674
year               0.019027
signal_200         0.017652
light_pole_25      0.014701
month              0.013351
total_precip_mm    0.012256
rain_mm            0.012140
light_pole_12_5    0.011039
signal_100         0.008562
signal_50          0.002502
signal_25          0.002234
snow_cm            0.001109

In [21]:
# Cut down features

# split training data into training and testing
from sklearn.model_selection import train_test_split

# Select columns to that are data
cols = [col for col in crime if col not in ['type', 'minute', 'hour', 'latitude', 'longitude', 'datetime']]

X = crime[cols]

# Select target data
y = crime['type']

X_train, X_test, y_train, y_test = train_test_split(X, y, random_state=100, test_size=0.3)
print(X_train.shape)

(144767, 24)


In [22]:
X_train

year     month       day  Hour_Minute  hundred_block     utm_x  \
199298  0.5000  0.545455  0.100000     0.447533       0.892986  0.527619   
131956  0.0625  0.000000  0.133333     0.379430       0.278638  0.561107   
184994  0.3125  0.000000  0.100000     0.157054       0.976971  0.519015   
59295   0.4375  0.636364  0.933333     0.539958       0.653233  0.689556   
10402   0.0625  0.000000  0.400000     0.875608       0.235093  0.882944   
...        ...       ...       ...          ...            ...       ...   
194442  0.3750  0.272727  0.000000     0.268242       0.390770  0.141916   
65615   0.5000  1.000000  0.266667     0.458652       0.484122  0.521103   
77655   0.6875  0.363636  0.333333     0.834607       0.433722  0.467887   
56088   0.4375  0.000000  0.133333     0.625434       0.459676  0.710992   
38408   0.2500  0.181818  0.766667     0.604587       0.574412  0.520844   

           utm_y  light_pole_12_5  light_pole_25  light_pole_50  ...  \
199298  0.668134         0.071429       0.134328       0.240506  ...   
131956  0.238213         0.000000       0.014925       0.063291  ...   
184994  0.570419         0.035714       0.014925       0.050633  ...   
59295   0.563038         0.000000       0.029851       0.101266  ...   
10402   0.712687         0.071429       0.089552       0.139241  ...   
...          ...              ...            ...            ...  ...   
194442  0.295748         0.000000       0.029851       0.075949  ...   
65615   0.293253         0.035714       0.044776       0.101266  ...   
77655   0.368430         0.000000       0.029851       0.037975  ...   
56088   0.333695         0.000000       0.014925       0.075949  ...   
38408   0.589036         0.035714       0.044776       0.126582  ...   

        signal_200  trees_25  trees_100   rain_mm  snow_cm  total_precip_mm  \
199298    0.733333   0.21875   0.534351  0.000000      0.0         0.000000   
131956    0.066667   0.25000   0.480916  0.000000      0.0         0.000000   
184994    0.266667   0.15625   0.458015  0.078603      0.0         0.078603   
59295     0.000000   0.21875   0.358779  0.000000      0.0         0.000000   
10402     0.200000   0.03125   0.236641  0.058952      0.0         0.058952   
...            ...       ...        ...       ...      ...              ...   
194442    0.200000   0.03125   0.160305  0.277293      0.0         0.277293   
65615     0.066667   0.18750   0.190840  0.000000      0.0         0.000000   
77655     0.066667   0.31250   0.496183  0.000000      0.0         0.000000   
56088     0.000000   0.28125   0.374046  0.010917      0.0         0.010917   
38408     0.133333   0.37500   0.312977  0.172489      0.0         0.172489   

          temp_c  humidity  pressure  hours_of_light  
199298  0.635789  0.643678  0.652174        0.980606  
131956  0.120000  0.528736  0.873641        0.018182  
184994  0.412632  0.816092  0.270380        0.015758  
59295   0.635789  0.563218  0.520380        0.641212  
10402   0.475789  0.919540  0.611413        0.043636  
...          ...       ...       ...             ...  
194442  0.364211  0.735632  0.604620        0.552727  
65615   0.353684  0.816092  0.740489        0.013333  
77655   0.566316  0.724138  0.713315        0.844848  
56088   0.454737  0.873563  0.656250        0.019394  
38408   0.501053  0.931034  0.464674        0.488485  

[144767 rows x 24 columns]

In [23]:
y_train

199298    0
131956    0
184994    0
59295     1
10402     1
         ..
194442    0
65615     1
77655     1
56088     1
38408     1
Name: type, Length: 144767, dtype: int64

In [24]:
# Trying Random Forest Classifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.feature_selection import SelectFromModel

model_tree = RandomForestClassifier(random_state=100, n_estimators=50)
model_tree.fit(X_train, y_train)
print(model_tree.feature_importances_)
sel_model_tree = SelectFromModel(estimator=model_tree, prefit=True, threshold='mean')  
      # since we already fit the data, we specify prefit option here
      # Features whose importance is greater or equal to the threshold are kept while the others are discarded.
X_train_sfm_tree = sel_model_tree.transform(X_train)
print(sel_model_tree.get_support())

feature_importances = pd.DataFrame(model_tree.feature_importances_,
                                   index = X_train.columns,
                                    columns=['importance']).sort_values('importance', 
                                                                        ascending=False)
feature_importances

[0.04158714 0.0222075  0.03615968 0.07110927 0.22536677 0.068862
 0.07597512 0.01619619 0.02377977 0.03228032 0.04736712 0.00352735
 0.00382655 0.01224162 0.02595283 0.03262224 0.05034009 0.02027254
 0.00167953 0.02050248 0.0432561  0.03872169 0.04372989 0.0424362 ]
[False False False  True  True  True  True False False False  True False
 False False False False  True False False False  True False  True  True]


importance
hundred_block      0.225367
utm_y              0.075975
Hour_Minute        0.071109
utm_x              0.068862
trees_100          0.050340
light_pole_100     0.047367
pressure           0.043730
temp_c             0.043256
hours_of_light     0.042436
year               0.041587
humidity           0.038722
day                0.036160
trees_25           0.032622
light_pole_50      0.032280
signal_200         0.025953
light_pole_25      0.023780
month              0.022207
total_precip_mm    0.020502
rain_mm            0.020273
light_pole_12_5    0.016196
signal_100         0.012242
signal_50          0.003827
signal_25          0.003527
snow_cm            0.001680

In [25]:
# Try using the MLP Classifier
mlp = MLPClassifier(hidden_layer_sizes=(24, 24, 24), activation='relu', solver='adam', max_iter=300)
mlp.fit(X_train, y_train)

predict_train = mlp.predict(X_train)
predict_test = mlp.predict(X_test)

In [26]:
print(confusion_matrix(y_train, predict_train))
print(classification_report(y_train, predict_train))

[[46575 25470]
 [13282 59440]]
              precision    recall  f1-score   support

           0       0.78      0.65      0.71     72045
           1       0.70      0.82      0.75     72722

    accuracy                           0.73    144767
   macro avg       0.74      0.73      0.73    144767
weighted avg       0.74      0.73      0.73    144767



In [27]:
print(confusion_matrix(y_test, predict_test))
print(classification_report(y_test, predict_test))

[[19704 10924]
 [ 5835 25580]]
              precision    recall  f1-score   support

           0       0.77      0.64      0.70     30628
           1       0.70      0.81      0.75     31415

    accuracy                           0.73     62043
   macro avg       0.74      0.73      0.73     62043
weighted avg       0.74      0.73      0.73     62043



In [28]:
# Try using the MLP Classifier
mlp = MLPClassifier(hidden_layer_sizes=(29, 29, 29, 29, 29, 29, 29), activation='relu', solver='adam', max_iter=300)
mlp.fit(X_train, y_train)

predict_train = mlp.predict(X_train)
predict_test = mlp.predict(X_test)

In [29]:
print(confusion_matrix(y_train, predict_train))
print(classification_report(y_train, predict_train))

[[48636 23409]
 [13135 59587]]
              precision    recall  f1-score   support

           0       0.79      0.68      0.73     72045
           1       0.72      0.82      0.77     72722

    accuracy                           0.75    144767
   macro avg       0.75      0.75      0.75    144767
weighted avg       0.75      0.75      0.75    144767



In [30]:
print(confusion_matrix(y_test, predict_test))
print(classification_report(y_test, predict_test))

[[20250 10378]
 [ 6265 25150]]
              precision    recall  f1-score   support

           0       0.76      0.66      0.71     30628
           1       0.71      0.80      0.75     31415

    accuracy                           0.73     62043
   macro avg       0.74      0.73      0.73     62043
weighted avg       0.74      0.73      0.73     62043



In [31]:
# Cut down features again

# split training data into training and testing
from sklearn.model_selection import train_test_split

# Select columns to that are data
cols = [col for col in crime if col not in ['type', 'minute', 'hour', 'latitude', 'longitude', 'datetime', 
                                            'snow_cm', 'rain_mm', 'signal_25', 'signal_50', 'signal_100', 
                                            'light_pole_12_5']]

X = crime[cols]

# Select target data
y = crime['type']

X_train, X_test, y_train, y_test = train_test_split(X, y, random_state=100, test_size=0.3)
print(X_train.shape)

(144767, 18)


In [32]:
# Trying Random Forest Classifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.feature_selection import SelectFromModel

model_tree = RandomForestClassifier(random_state=100, n_estimators=50)
model_tree.fit(X_train, y_train)
print(model_tree.feature_importances_)
sel_model_tree = SelectFromModel(estimator=model_tree, prefit=True, threshold='mean')  
      # since we already fit the data, we specify prefit option here
      # Features whose importance is greater or equal to the threshold are kept while the others are discarded.
X_train_sfm_tree = sel_model_tree.transform(X_train)
print(sel_model_tree.get_support())

feature_importances = pd.DataFrame(model_tree.feature_importances_,
                                   index = X_train.columns,
                                    columns=['importance']).sort_values('importance', 
                                                                        ascending=False)
feature_importances

[0.0412567  0.02195444 0.03675423 0.07751069 0.24394078 0.07521048
 0.08109379 0.02629659 0.03390872 0.05245774 0.02530184 0.03196316
 0.05194105 0.02464236 0.04523102 0.04000082 0.0462991  0.04423649]
[False False False  True  True  True  True False False False False False
 False False False False False False]


importance
hundred_block      0.243941
utm_y              0.081094
Hour_Minute        0.077511
utm_x              0.075210
light_pole_100     0.052458
trees_100          0.051941
pressure           0.046299
temp_c             0.045231
hours_of_light     0.044236
year               0.041257
humidity           0.040001
day                0.036754
light_pole_50      0.033909
trees_25           0.031963
light_pole_25      0.026297
signal_200         0.025302
total_precip_mm    0.024642
month              0.021954

In [33]:
# Try using the MLP Classifier
mlp = MLPClassifier(hidden_layer_sizes=(18, 18, 18), activation='relu', solver='adam', max_iter=300)
mlp.fit(X_train, y_train)

predict_train = mlp.predict(X_train)
predict_test = mlp.predict(X_test)

In [34]:
print(confusion_matrix(y_train, predict_train))
print(classification_report(y_train, predict_train))

[[43114 28931]
 [11628 61094]]
              precision    recall  f1-score   support

           0       0.79      0.60      0.68     72045
           1       0.68      0.84      0.75     72722

    accuracy                           0.72    144767
   macro avg       0.73      0.72      0.72    144767
weighted avg       0.73      0.72      0.72    144767



In [35]:
print(confusion_matrix(y_test, predict_test))
print(classification_report(y_test, predict_test))

[[18328 12300]
 [ 5060 26355]]
              precision    recall  f1-score   support

           0       0.78      0.60      0.68     30628
           1       0.68      0.84      0.75     31415

    accuracy                           0.72     62043
   macro avg       0.73      0.72      0.72     62043
weighted avg       0.73      0.72      0.72     62043



In [36]:
# Try using the MLP Classifier
mlp = MLPClassifier(hidden_layer_sizes=(18, 18, 18, 18, 18, 18, 18), activation='relu', solver='adam', max_iter=300)
mlp.fit(X_train, y_train)

predict_train = mlp.predict(X_train)
predict_test = mlp.predict(X_test)

d:\program files (x86)\microsoft visual studio\shared\python37_64\lib\site-packages\sklearn\neural_network\multilayer_perceptron.py:568: UserWarning: Training interrupted by user.
  warnings.warn("Training interrupted by user.")


In [37]:
print(confusion_matrix(y_train, predict_train))
print(classification_report(y_train, predict_train))

[[41461 30584]
 [12907 59815]]
              precision    recall  f1-score   support

           0       0.76      0.58      0.66     72045
           1       0.66      0.82      0.73     72722

    accuracy                           0.70    144767
   macro avg       0.71      0.70      0.69    144767
weighted avg       0.71      0.70      0.69    144767



In [38]:
print(confusion_matrix(y_test, predict_test))
print(classification_report(y_test, predict_test))

[[17725 12903]
 [ 5640 25775]]
              precision    recall  f1-score   support

           0       0.76      0.58      0.66     30628
           1       0.67      0.82      0.74     31415

    accuracy                           0.70     62043
   macro avg       0.71      0.70      0.70     62043
weighted avg       0.71      0.70      0.70     62043

