In [1]:
# NOTE: This does NOT have points close to real ones removed!

import pandas as pd
import numpy as np
%matplotlib inline
import matplotlib.pyplot as plt
import sklearn

crime = pd.read_csv('E:/Vancouver Crime Final/Synthetic Data/commercial_bne_500k_combined.csv')

crime.head(20)

type             datetime  year  month  day  hour  \
0   Break and Enter Commercial  2003-01-01 00:00:00  2003      1    1     0   
1   Break and Enter Commercial  2003-01-01 06:06:00  2003      1    1     6   
2   Break and Enter Commercial  2003-01-01 07:07:00  2003      1    1     7   
3   Break and Enter Commercial  2003-01-01 07:07:00  2003      1    1     7   
4   Break and Enter Commercial  2003-01-01 11:11:00  2003      1    1    11   
5   Break and Enter Commercial  2003-01-01 12:12:00  2003      1    1    12   
6   Break and Enter Commercial  2003-01-01 12:12:00  2003      1    1    12   
7   Break and Enter Commercial  2003-01-01 12:12:00  2003      1    1    12   
8   Break and Enter Commercial  2003-01-01 19:19:00  2003      1    1    19   
9   Break and Enter Commercial  2003-01-01 23:23:00  2003      1    1    23   
10  Break and Enter Commercial  2003-01-02 02:02:00  2003      1    2     2   
11  Break and Enter Commercial  2003-01-02 03:03:00  2003      1    2     3   
12  Break and Enter Commercial  2003-01-02 06:06:00  2003      1    2     6   
13  Break and Enter Commercial  2003-01-02 09:09:00  2003      1    2     9   
14  Break and Enter Commercial  2003-01-02 17:17:00  2003      1    2    17   
15  Break and Enter Commercial  2003-01-02 21:21:00  2003      1    2    21   
16  Break and Enter Commercial  2003-01-02 23:23:00  2003      1    2    23   
17  Break and Enter Commercial  2003-01-03 02:02:00  2003      1    3     2   
18  Break and Enter Commercial  2003-01-03 02:02:00  2003      1    3     2   
19  Break and Enter Commercial  2003-01-03 03:03:00  2003      1    3     3   

    minute  Hour_Minute          hundred_block      utm_x  ...  signal_200  \
0        0     0.000000       64XX VICTORIA DR  495220.95  ...           2   
1        0     6.000000       5XX W GEORGIA ST  491507.39  ...          10   
2       13     7.216667        18XX W 57TH AVE  489132.03  ...           0   
3       13     7.216667         45XX FRASER ST  493431.80  ...           2   
4        0    11.000000         35XX FRASER ST  493447.88  ...           1   
5        0    12.000000          5XX BEATTY ST  492024.04  ...          10   
6        0    12.000000       7XX PACIFIC BLVD  492005.87  ...           2   
7       49    12.816667        28XX BENTALL ST  497676.19  ...           3   
8       35    19.583333  9XX W KING EDWARD AVE  490906.22  ...           2   
9       19    23.316667      10XX E GEORGIA ST  494077.84  ...           1   
10       0     2.000000            3XX HOWE ST  491696.77  ...          10   
11       0     3.000000         28XX W 4TH AVE  487680.42  ...           4   
12      55     6.916667      10XX KINGSWAY AVE  494039.54  ...           2   
13       5     9.083333     36XX E HASTINGS ST  498193.37  ...           2   
14      30    17.500000         29XX W 4TH AVE  487535.71  ...           2   
15      41    21.683333       15XX KOOTENAY ST  498032.54  ...           2   
16      30    23.500000           21XX MAIN ST  492674.67  ...           2   
17       0     2.000000         27XX RUPERT ST  497553.23  ...           3   
18      28     2.466667         30XX SLOCAN ST  496391.40  ...           2   
19       0     3.000000     19XX COMMERCIAL DR  494925.66  ...           2   

    trees_25  trees_100  rain_mm  snow_cm  total_precip_mm  temp_c  humidity  \
0          5         40     21.6      0.0             21.6     5.8      81.0   
1          2         27     21.6      0.0             21.6     5.5      96.0   
2          8         73     21.6      0.0             21.6     5.8      95.0   
3          2         19     21.6      0.0             21.6     5.8      95.0   
4          3         51     21.6      0.0             21.6     6.0      95.0   
5          0         39     21.6      0.0             21.6     5.7      95.0   
6          0          0     21.6      0.0             21.6     5.7      95.0   
7          0         13     21.6      0.0             21.6     5.7      95.0   
8      

In [2]:
# Set Break and ENters to 1 and everything else to 0

crime = crime.replace(['NONE'], 0)

crime = crime.replace(['Break and Enter Residential/Other', 'Break and Enter Commercial'], 1)
crime.head()

type             datetime  year  month  day  hour  minute  Hour_Minute  \
0     1  2003-01-01 00:00:00  2003      1    1     0       0     0.000000   
1     1  2003-01-01 06:06:00  2003      1    1     6       0     6.000000   
2     1  2003-01-01 07:07:00  2003      1    1     7      13     7.216667   
3     1  2003-01-01 07:07:00  2003      1    1     7      13     7.216667   
4     1  2003-01-01 11:11:00  2003      1    1    11       0    11.000000   

      hundred_block      utm_x  ...  signal_200  trees_25  trees_100  rain_mm  \
0  64XX VICTORIA DR  495220.95  ...           2         5         40     21.6   
1  5XX W GEORGIA ST  491507.39  ...          10         2         27     21.6   
2   18XX W 57TH AVE  489132.03  ...           0         8         73     21.6   
3    45XX FRASER ST  493431.80  ...           2         2         19     21.6   
4    35XX FRASER ST  493447.88  ...           1         3         51     21.6   

   snow_cm  total_precip_mm  temp_c  humidity  pressure  hours_of_light  
0      0.0             21.6     5.8      81.0    101.70            9.53  
1      0.0             21.6     5.5      96.0    101.58            9.53  
2      0.0             21.6     5.8      95.0    101.50            9.53  
3      0.0             21.6     5.8      95.0    101.50            9.53  
4      0.0             21.6     6.0      95.0    101.33            9.53  

[5 rows x 30 columns]

In [3]:
crime

type             datetime  year  month  day  hour  minute  \
0          1  2003-01-01 00:00:00  2003      1    1     0       0   
1          1  2003-01-01 06:06:00  2003      1    1     6       0   
2          1  2003-01-01 07:07:00  2003      1    1     7      13   
3          1  2003-01-01 07:07:00  2003      1    1     7      13   
4          1  2003-01-01 11:11:00  2003      1    1    11       0   
...      ...                  ...   ...    ...  ...   ...     ...   
538463     0  2016-10-29 16:05:00  2016     10   29    16       5   
538464     0  2007-10-02 23:40:00  2007     10    2    23      40   
538465     0  2006-10-03 09:29:00  2006     10    3     9      29   
538466     0  2005-02-02 05:29:00  2005      2    2     5      29   
538467     0  2013-11-26 22:01:00  2013     11   26    22       1   

        Hour_Minute           hundred_block          utm_x  ...  signal_200  \
0          0.000000        64XX VICTORIA DR  495220.950000  ...           2   
1          6.000000        5XX W GEORGIA ST  491507.390000  ...          10   
2          7.216667         18XX W 57TH AVE  489132.030000  ...           0   
3          7.216667          45XX FRASER ST  493431.800000  ...           2   
4         11.000000          35XX FRASER ST  493447.880000  ...           1   
...             ...                     ...            ...  ...         ...   
538463    16.083333        40XX BOUNDARY RD  498263.140760  ...           0   
538464    23.666667         37XX W 31ST AVE  486377.345932  ...           2   
538465     9.483333           42XX YUKON ST  491831.626717  ...           0   
538466     5.483333         19XX W 39TH AVE  489136.700000  ...           0   
538467    22.016667  E 35TH AVE / KNIGHT ST  494415.830000  ...           3   

        trees_25  trees_100  rain_mm  snow_cm  total_precip_mm  temp_c  \
0              5         40     21.6      0.0             21.6     5.8   
1              2         27     21.6      0.0             21.6     5.5   
2              8         73     21.6      0.0             21.6     5.8   
3              2         19     21.6      0.0             21.6     5.8   
4              3         51     21.6      0.0             21.6     6.0   
...          ...        ...      ...      ...              ...     ...   
538463         4         27      6.4      0.0              6.4    11.0   
538464         9         45      5.2      0.0              5.2     9.5   
538465         8         67      0.0      0.0              0.0    11.9   
538466         8         69      0.0      0.0              0.0     8.2   
538467         2         31      0.0      0.0              0.0     5.8   

        humidity  pressure  hours_of_light  
0           81.0    101.70            9.53  
1           96.0    101.58            9.53  
2           95.0    101.50            9.53  
3           95.0    101.50            9.53  
4           95.0    101.33            9.53  
...          ...       ...             ...  
538463      89.0    101.34           11.08  
538464      87.0    100.86           12.66  
538465      84.0    102.09           12.58  
538466      90.0    102.93           10.63  
538467      84.0    102.00            9.87  

[538468 rows x 30 columns]

In [4]:
### Begin Processing the Data


# Import Pre-processing module
from sklearn import preprocessing

# Create Label Encoder
le = preprocessing.LabelEncoder()

# Convert the string columns to numeric
# .astype(str) to ensude they are read as strings and not as mixed types
crime['datetime'] = le.fit_transform(crime['datetime'].astype(str))
crime['hundred_block'] = le.fit_transform(crime['hundred_block'].astype(str))


# Display the results
crime

type  datetime  year  month  day  hour  minute  Hour_Minute  \
0          1         0  2003      1    1     0       0     0.000000   
1          1        21  2003      1    1     6       0     6.000000   
2          1        26  2003      1    1     7      13     7.216667   
3          1        26  2003      1    1     7      13     7.216667   
4          1        40  2003      1    1    11       0    11.000000   
...      ...       ...   ...    ...  ...   ...     ...          ...   
538463     0    428076  2016     10   29    16       5    16.083333   
538464     0    148443  2007     10    2    23      40    23.666667   
538465     0    117468  2006     10    3     9      29     9.483333   
538466     0     65578  2005      2    2     5      29     5.483333   
538467     0    336996  2013     11   26    22       1    22.016667   

        hundred_block          utm_x  ...  signal_200  trees_25  trees_100  \
0               11850  495220.950000  ...           2         5         40   
1               11411  491507.390000  ...          10         2         27   
2                2495  489132.030000  ...           0         8         73   
3                9167  493431.800000  ...           2         2         19   
4                7397  493447.880000  ...           1         3         51   
...               ...            ...  ...         ...       ...        ...   
538463           8571  498263.140760  ...           0         4         27   
538464           7850  486377.345932  ...           2         9         45   
538465           8893  491831.626717  ...           0         8         67   
538466           2739  489136.700000  ...           0         8         69   
538467          17132  494415.830000  ...           3         2         31   

        rain_mm  snow_cm  total_precip_mm  temp_c  humidity  pressure  \
0          21.6      0.0             21.6     5.8      81.0    101.70   
1          21.6      0.0             21.6     5.5      96.0    101.58   
2          21.6      0.0             21.6     5.8      95.0    101.50   
3          21.6      0.0             21.6     5.8      95.0    101.50   
4          21.6      0.0             21.6     6.0      95.0    101.33   
...         ...      ...              ...     ...       ...       ...   
538463      6.4      0.0              6.4    11.0      89.0    101.34   
538464      5.2      0.0              5.2     9.5      87.0    100.86   
538465      0.0      0.0              0.0    11.9      84.0    102.09   
538466      0.0      0.0              0.0     8.2      90.0    102.93   
538467      0.0      0.0              0.0     5.8      84.0    102.00   

        hours_of_light  
0                 9.53  
1                 9.53  
2                 9.53  
3                 9.53  
4                 9.53  
...                ...  
538463           11.08  
538464           12.66  
538465           12.58  
538466           10.63  
538467            9.87  

[538468 rows x 30 columns]

In [5]:
# Scale the Data

columns = [col for col in crime if col not in ['type']]


# Properly scale the reduced set of features
features = crime[columns]

from sklearn.preprocessing import MinMaxScaler
scaler = preprocessing.MinMaxScaler()

print(scaler.fit(features))

MinMaxScaler(copy=True, feature_range=(0, 1))


In [6]:
# Properly scale the features

columns = [col for col in crime if col not in ['type']]

# Properly scale the reduced set of features
features = crime[columns]


scaler = MinMaxScaler().fit(features.values) # scaler = MinMaxScaler().fit(features.values)
features = scaler.transform(features.values) # features = scaler.transform(features.values)
crime[columns] = features
crime

type  datetime    year     month       day      hour    minute  \
0          1  0.000000  0.0000  0.000000  0.000000  0.000000  0.000000   
1          1  0.000041  0.0000  0.000000  0.000000  0.260870  0.000000   
2          1  0.000050  0.0000  0.000000  0.000000  0.304348  0.220339   
3          1  0.000050  0.0000  0.000000  0.000000  0.304348  0.220339   
4          1  0.000078  0.0000  0.000000  0.000000  0.478261  0.000000   
...      ...       ...     ...       ...       ...       ...       ...   
538463     0  0.829595  0.8125  0.818182  0.933333  0.695652  0.084746   
538464     0  0.287677  0.2500  0.818182  0.033333  1.000000  0.677966   
538465     0  0.227649  0.1875  0.818182  0.066667  0.391304  0.491525   
538466     0  0.127088  0.1250  0.090909  0.033333  0.217391  0.491525   
538467     0  0.653085  0.6250  0.909091  0.833333  0.956522  0.016949   

        Hour_Minute  hundred_block     utm_x  ...  signal_200  trees_25  \
0          0.000000       0.539004  0.788663  ...    0.133333  0.151515   
1          0.250174       0.519036  0.534258  ...    0.666667  0.060606   
2          0.300903       0.113486  0.371528  ...    0.000000  0.242424   
3          0.300903       0.416966  0.666093  ...    0.133333  0.060606   
4          0.458652       0.336457  0.667195  ...    0.066667  0.090909   
...             ...            ...       ...  ...         ...       ...   
538463     0.670605       0.389857  0.997075  ...    0.000000  0.121212   
538464     0.986796       0.357062  0.182813  ...    0.133333  0.272727   
538465     0.395413       0.404503  0.556470  ...    0.000000  0.242424   
538466     0.228631       0.124585  0.371848  ...    0.000000  0.242424   
538467     0.917999       0.779259  0.733507  ...    0.200000  0.060606   

        trees_100   rain_mm  snow_cm  total_precip_mm    temp_c  humidity  \
0        0.305344  0.235808      0.0         0.235808  0.408421  0.781609   
1        0.206107  0.235808      0.0         0.235808  0.402105  0.954023   
2        0.557252  0.235808      0.0         0.235808  0.408421  0.942529   
3        0.145038  0.235808      0.0         0.235808  0.408421  0.942529   
4        0.389313  0.235808      0.0         0.235808  0.412632  0.942529   
...           ...       ...      ...              ...       ...       ...   
538463   0.206107  0.069869      0.0         0.069869  0.517895  0.873563   
538464   0.343511  0.056769      0.0         0.056769  0.486316  0.850575   
538465   0.511450  0.000000      0.0         0.000000  0.536842  0.816092   
538466   0.526718  0.000000      0.0         0.000000  0.458947  0.885057   
538467   0.236641  0.000000      0.0         0.000000  0.408421  0.816092   

        pressure  hours_of_light  
0       0.612081        0.010909  
1       0.595973        0.010909  
2       0.585235        0.010909  
3       0.585235        0.010909  
4       0.562416        0.010909  
...          ...             ...  
538463  0.563758        0.198788  
538464  0.499329        0.390303  
538465  0.664430        0.380606  
538466  0.777181        0.144242  
538467  0.652349        0.052121  

[538468 rows x 30 columns]

In [7]:
# split training data into training and testing
from sklearn.model_selection import train_test_split

# Select columns to that are data
cols = [col for col in crime if col not in ['type']]

X = crime[cols]

# Select target data
y = crime['type']

X_train, X_test, y_train, y_test = train_test_split(X, y, random_state=100, test_size=0.3)
print(X_train.shape)

(376927, 29)


In [8]:
# Trying Random Forest Classifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.feature_selection import SelectFromModel

model_tree = RandomForestClassifier(random_state=100, n_estimators=50)
model_tree.fit(X_train, y_train)
print(model_tree.feature_importances_)
sel_model_tree = SelectFromModel(estimator=model_tree, prefit=True, threshold='mean')  
      # since we already fit the data, we specify prefit option here
      # Features whose importance is greater or equal to the threshold are kept while the others are discarded.
X_train_sfm_tree = sel_model_tree.transform(X_train)
print(sel_model_tree.get_support())

feature_importances = pd.DataFrame(model_tree.feature_importances_,
                                   index = X_train.columns,
                                    columns=['importance']).sort_values('importance', 
                                                                        ascending=False)
feature_importances

[0.03296654 0.01776747 0.01390616 0.02156072 0.02476357 0.18199159
 0.05010255 0.0990773  0.04532272 0.0535003  0.0514353  0.04521016
 0.0158075  0.02565258 0.02766939 0.04505758 0.00323418 0.00599463
 0.02248409 0.0300901  0.02404624 0.03383839 0.012815   0.00145342
 0.01280217 0.02585213 0.02309394 0.02687841 0.02562587]
[False False False False False  True  True  True  True  True  True  True
 False False False  True False False False False False False False False
 False False False False False]


importance
minute             0.181992
hundred_block      0.099077
utm_y              0.053500
latitude           0.051435
Hour_Minute        0.050103
utm_x              0.045323
longitude          0.045210
light_pole_100     0.045058
trees_100          0.033838
datetime           0.032967
signal_200         0.030090
light_pole_50      0.027669
pressure           0.026878
temp_c             0.025852
light_pole_25      0.025653
hours_of_light     0.025626
hour               0.024764
trees_25           0.024046
humidity           0.023094
signal_100         0.022484
day                0.021561
year               0.017767
light_pole_12_5    0.015808
month              0.013906
rain_mm            0.012815
total_precip_mm    0.012802
signal_50          0.005995
signal_25          0.003234
snow_cm            0.001453

In [9]:
# Simple Neural Network

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import sklearn
from sklearn.neural_network import MLPClassifier
from sklearn.neural_network import MLPRegressor

# import needed modules
from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_squared_error
from math import sqrt
from sklearn.metrics import r2_score

In [10]:
# Try using the MLP Classifier
mlp = MLPClassifier(hidden_layer_sizes=(29, 29, 29), activation='relu', solver='adam', max_iter=300)
mlp.fit(X_train, y_train)

predict_train = mlp.predict(X_train)
predict_test = mlp.predict(X_test)

In [11]:
from sklearn.metrics import classification_report, confusion_matrix
print(confusion_matrix(y_train, predict_train))
print(classification_report(y_train, predict_train))

[[346124   4023]
 [ 13355  13425]]
              precision    recall  f1-score   support

           0       0.96      0.99      0.98    350147
           1       0.77      0.50      0.61     26780

    accuracy                           0.95    376927
   macro avg       0.87      0.74      0.79    376927
weighted avg       0.95      0.95      0.95    376927



In [12]:
print(confusion_matrix(y_test, predict_test))
print(classification_report(y_test, predict_test))

[[148215   1749]
 [  5810   5767]]
              precision    recall  f1-score   support

           0       0.96      0.99      0.98    149964
           1       0.77      0.50      0.60     11577

    accuracy                           0.95    161541
   macro avg       0.86      0.74      0.79    161541
weighted avg       0.95      0.95      0.95    161541



In [13]:
# Try using the MLP Classifier
mlp = MLPClassifier(hidden_layer_sizes=(29, 29, 29), activation='relu', solver='adam', max_iter=3000)
mlp.fit(X_train, y_train)

predict_train = mlp.predict(X_train)
predict_test = mlp.predict(X_test)

In [14]:
print(confusion_matrix(y_train, predict_train))
print(classification_report(y_train, predict_train))

[[346959   3188]
 [ 14954  11826]]
              precision    recall  f1-score   support

           0       0.96      0.99      0.97    350147
           1       0.79      0.44      0.57     26780

    accuracy                           0.95    376927
   macro avg       0.87      0.72      0.77    376927
weighted avg       0.95      0.95      0.95    376927



In [15]:
print(confusion_matrix(y_test, predict_test))
print(classification_report(y_test, predict_test))

[[148522   1442]
 [  6641   4936]]
              precision    recall  f1-score   support

           0       0.96      0.99      0.97    149964
           1       0.77      0.43      0.55     11577

    accuracy                           0.95    161541
   macro avg       0.87      0.71      0.76    161541
weighted avg       0.94      0.95      0.94    161541



In [16]:
############################# END HERE ###################################

In [17]:
# Try using the MLP Classifier
mlp = MLPClassifier(hidden_layer_sizes=(29, 29, 29, 29, 29, 29, 29), activation='relu', solver='adam', max_iter=200)
mlp.fit(X_train, y_train)

predict_train = mlp.predict(X_train)
predict_test = mlp.predict(X_test)

In [18]:
print(confusion_matrix(y_train, predict_train))
print(classification_report(y_train, predict_train))

[[346352   3795]
 [ 13333  13447]]
              precision    recall  f1-score   support

           0       0.96      0.99      0.98    350147
           1       0.78      0.50      0.61     26780

    accuracy                           0.95    376927
   macro avg       0.87      0.75      0.79    376927
weighted avg       0.95      0.95      0.95    376927



In [19]:
print(confusion_matrix(y_test, predict_test))
print(classification_report(y_test, predict_test))

[[148217   1747]
 [  5882   5695]]
              precision    recall  f1-score   support

           0       0.96      0.99      0.97    149964
           1       0.77      0.49      0.60     11577

    accuracy                           0.95    161541
   macro avg       0.86      0.74      0.79    161541
weighted avg       0.95      0.95      0.95    161541



In [20]:
feature_importances

importance
minute             0.181992
hundred_block      0.099077
utm_y              0.053500
latitude           0.051435
Hour_Minute        0.050103
utm_x              0.045323
longitude          0.045210
light_pole_100     0.045058
trees_100          0.033838
datetime           0.032967
signal_200         0.030090
light_pole_50      0.027669
pressure           0.026878
temp_c             0.025852
light_pole_25      0.025653
hours_of_light     0.025626
hour               0.024764
trees_25           0.024046
humidity           0.023094
signal_100         0.022484
day                0.021561
year               0.017767
light_pole_12_5    0.015808
month              0.013906
rain_mm            0.012815
total_precip_mm    0.012802
signal_50          0.005995
signal_25          0.003234
snow_cm            0.001453

In [21]:
# Cut down features

# split training data into training and testing
from sklearn.model_selection import train_test_split

# Select columns to that are data
cols = [col for col in crime if col not in ['type', 'minute', 'hour', 'latitude', 'longitude', 'datetime']]

X = crime[cols]

# Select target data
y = crime['type']

X_train, X_test, y_train, y_test = train_test_split(X, y, random_state=100, test_size=0.3)
print(X_train.shape)

(376927, 24)


In [22]:
X_train

year     month       day  Hour_Minute  hundred_block     utm_x  \
34570   0.8750  0.909091  0.133333     0.416956       0.097339  0.710683   
426210  0.8125  1.000000  1.000000     0.821404       0.792267  0.702932   
278535  0.6250  0.363636  0.766667     0.687978       0.114897  0.598495   
68989   0.2500  0.090909  0.266667     0.305073       0.367296  0.480679   
85625   0.8750  0.000000  0.666667     0.073662       0.196952  0.544084   
...        ...       ...       ...          ...            ...       ...   
344414  0.7500  0.636364  0.833333     0.214038       0.570571  0.654582   
212912  0.8125  0.909091  0.133333     0.742877       0.074778  0.650987   
65615   0.5000  0.272727  0.366667     0.683808       0.036434  0.724328   
210755  1.0000  0.363636  0.066667     0.207783       0.928224  0.652474   
56088   0.4375  1.000000  0.966667     0.637248       0.026655  0.518351   

           utm_y  light_pole_12_5  light_pole_25  light_pole_50  ...  \
34570   0.608583         0.035714       0.014925       0.088608  ...   
426210  0.217242         0.035714       0.014925       0.088608  ...   
278535  0.716246         0.035714       0.059701       0.265823  ...   
68989   0.440646         0.035714       0.029851       0.101266  ...   
85625   0.560891         0.035714       0.104478       0.151899  ...   
...          ...              ...            ...            ...  ...   
344414  0.117911         0.000000       0.000000       0.025316  ...   
212912  0.628067         0.035714       0.104478       0.164557  ...   
65615   0.644755         0.035714       0.014925       0.050633  ...   
210755  0.547463         0.071429       0.089552       0.151899  ...   
56088   0.773960         0.107143       0.089552       0.189873  ...   

        signal_200  trees_25  trees_100   rain_mm   snow_cm  total_precip_mm  \
34570     0.066667  0.000000   0.076336  0.000000  0.000000         0.000000   
426210    0.000000  0.212121   0.488550  0.078603  0.156716         0.144105   
278535    0.466667  0.121212   0.427481  0.000000  0.000000         0.000000   
68989     0.200000  0.121212   0.282443  0.026201  0.000000         0.026201   
85625     0.533333  0.212121   0.320611  0.017467  0.000000         0.017467   
...            ...       ...        ...       ...       ...              ...   
344414    0.066667  0.151515   0.236641  0.000000  0.000000         0.000000   
212912    0.066667  0.090909   0.137405  0.216157  0.000000         0.216157   
65615     0.066667  0.000000   0.091603  0.000000  0.000000         0.000000   
210755    0.066667  0.090909   0.381679  0.000000  0.000000         0.000000   
56088     0.466667  0.121212   0.442748  0.000000  0.000000         0.000000   

          temp_c  humidity  pressure  hours_of_light  
34570   0.370526  0.402299  0.565101        0.157576  
426210  0.298947  0.954023  0.469799        0.009697  
278535  0.635789  0.402299  0.593289        0.923636  
68989   0.349474  0.873563  0.565101        0.183030  
85625   0.387368  0.873563  0.240268        0.080000  
...          ...       ...       ...             ...  
344414  0.555789  0.839080  0.590604        0.665455  
212912  0.524211  0.942529  0.497987        0.156364  
65615   0.477895  0.597701  0.609396        0.632727  
210755  0.492632  0.747126  0.651007        0.789091  
56088   0.317895  0.413793  0.652349        0.007273  

[376927 rows x 24 columns]

In [23]:
y_train

34570     1
426210    0
278535    0
68989     0
85625     0
         ..
344414    0
212912    0
65615     0
210755    0
56088     0
Name: type, Length: 376927, dtype: int64

In [24]:
# Trying Random Forest Classifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.feature_selection import SelectFromModel

model_tree = RandomForestClassifier(random_state=100, n_estimators=50)
model_tree.fit(X_train, y_train)
print(model_tree.feature_importances_)
sel_model_tree = SelectFromModel(estimator=model_tree, prefit=True, threshold='mean')  
      # since we already fit the data, we specify prefit option here
      # Features whose importance is greater or equal to the threshold are kept while the others are discarded.
X_train_sfm_tree = sel_model_tree.transform(X_train)
print(sel_model_tree.get_support())

feature_importances = pd.DataFrame(model_tree.feature_importances_,
                                   index = X_train.columns,
                                    columns=['importance']).sort_values('importance', 
                                                                        ascending=False)
feature_importances

[0.03299753 0.02127901 0.03212064 0.07782771 0.12996875 0.07917455
 0.09341309 0.02233922 0.0349412  0.04378651 0.06274037 0.00544946
 0.00833681 0.02699518 0.0424189  0.03719362 0.05553598 0.01903678
 0.00186291 0.01938521 0.03898875 0.03496462 0.04011188 0.03913128]
[False False False  True  True  True  True False False  True  True False
 False False  True False  True False False False False False False False]


importance
hundred_block      0.129969
utm_y              0.093413
utm_x              0.079175
Hour_Minute        0.077828
light_pole_100     0.062740
trees_100          0.055536
light_pole_50      0.043787
signal_200         0.042419
pressure           0.040112
hours_of_light     0.039131
temp_c             0.038989
trees_25           0.037194
humidity           0.034965
light_pole_25      0.034941
year               0.032998
day                0.032121
signal_100         0.026995
light_pole_12_5    0.022339
month              0.021279
total_precip_mm    0.019385
rain_mm            0.019037
signal_50          0.008337
signal_25          0.005449
snow_cm            0.001863

In [25]:
# Try using the MLP Classifier
mlp = MLPClassifier(hidden_layer_sizes=(24, 24, 24), activation='relu', solver='adam', max_iter=300)
mlp.fit(X_train, y_train)

predict_train = mlp.predict(X_train)
predict_test = mlp.predict(X_test)

In [26]:
print(confusion_matrix(y_train, predict_train))
print(classification_report(y_train, predict_train))

[[347527   2620]
 [ 21305   5475]]
              precision    recall  f1-score   support

           0       0.94      0.99      0.97    350147
           1       0.68      0.20      0.31     26780

    accuracy                           0.94    376927
   macro avg       0.81      0.60      0.64    376927
weighted avg       0.92      0.94      0.92    376927



In [27]:
print(confusion_matrix(y_test, predict_test))
print(classification_report(y_test, predict_test))

[[148771   1193]
 [  9314   2263]]
              precision    recall  f1-score   support

           0       0.94      0.99      0.97    149964
           1       0.65      0.20      0.30     11577

    accuracy                           0.93    161541
   macro avg       0.80      0.59      0.63    161541
weighted avg       0.92      0.93      0.92    161541



In [28]:
# Try using the MLP Classifier
mlp = MLPClassifier(hidden_layer_sizes=(29, 29, 29, 29, 29, 29, 29), activation='relu', solver='adam', max_iter=300)
mlp.fit(X_train, y_train)

predict_train = mlp.predict(X_train)
predict_test = mlp.predict(X_test)

In [29]:
print(confusion_matrix(y_train, predict_train))
print(classification_report(y_train, predict_train))

[[344316   5831]
 [ 15934  10846]]
              precision    recall  f1-score   support

           0       0.96      0.98      0.97    350147
           1       0.65      0.41      0.50     26780

    accuracy                           0.94    376927
   macro avg       0.80      0.69      0.73    376927
weighted avg       0.93      0.94      0.94    376927



In [30]:
print(confusion_matrix(y_test, predict_test))
print(classification_report(y_test, predict_test))

[[147248   2716]
 [  7186   4391]]
              precision    recall  f1-score   support

           0       0.95      0.98      0.97    149964
           1       0.62      0.38      0.47     11577

    accuracy                           0.94    161541
   macro avg       0.79      0.68      0.72    161541
weighted avg       0.93      0.94      0.93    161541



In [31]:
# Cut down features again

# split training data into training and testing
from sklearn.model_selection import train_test_split

# Select columns to that are data
cols = [col for col in crime if col not in ['type', 'minute', 'hour', 'latitude', 'longitude', 'datetime', 
                                            'snow_cm', 'rain_mm', 'signal_25', 'signal_50', 'signal_100', 
                                            'light_pole_12_5']]

X = crime[cols]

# Select target data
y = crime['type']

X_train, X_test, y_train, y_test = train_test_split(X, y, random_state=100, test_size=0.3)
print(X_train.shape)

(376927, 18)


In [32]:
# Trying Random Forest Classifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.feature_selection import SelectFromModel

model_tree = RandomForestClassifier(random_state=100, n_estimators=50)
model_tree.fit(X_train, y_train)
print(model_tree.feature_importances_)
sel_model_tree = SelectFromModel(estimator=model_tree, prefit=True, threshold='mean')  
      # since we already fit the data, we specify prefit option here
      # Features whose importance is greater or equal to the threshold are kept while the others are discarded.
X_train_sfm_tree = sel_model_tree.transform(X_train)
print(sel_model_tree.get_support())

feature_importances = pd.DataFrame(model_tree.feature_importances_,
                                   index = X_train.columns,
                                    columns=['importance']).sort_values('importance', 
                                                                        ascending=False)
feature_importances

[0.03507749 0.02129673 0.03410902 0.08892283 0.13674565 0.0904727
 0.10293398 0.03911845 0.04401369 0.07891167 0.04712418 0.03780225
 0.0572034  0.02329866 0.04120023 0.03703483 0.04341958 0.04131468]
[False False False  True  True  True  True False False  True False False
  True False False False False False]


importance
hundred_block      0.136746
utm_y              0.102934
utm_x              0.090473
Hour_Minute        0.088923
light_pole_100     0.078912
trees_100          0.057203
signal_200         0.047124
light_pole_50      0.044014
pressure           0.043420
hours_of_light     0.041315
temp_c             0.041200
light_pole_25      0.039118
trees_25           0.037802
humidity           0.037035
year               0.035077
day                0.034109
total_precip_mm    0.023299
month              0.021297

In [33]:
# Try using the MLP Classifier
mlp = MLPClassifier(hidden_layer_sizes=(18, 18, 18), activation='relu', solver='adam', max_iter=300)
mlp.fit(X_train, y_train)

predict_train = mlp.predict(X_train)
predict_test = mlp.predict(X_test)

In [34]:
print(confusion_matrix(y_train, predict_train))
print(classification_report(y_train, predict_train))

[[347838   2309]
 [ 22603   4177]]
              precision    recall  f1-score   support

           0       0.94      0.99      0.97    350147
           1       0.64      0.16      0.25     26780

    accuracy                           0.93    376927
   macro avg       0.79      0.57      0.61    376927
weighted avg       0.92      0.93      0.91    376927



In [35]:
print(confusion_matrix(y_test, predict_test))
print(classification_report(y_test, predict_test))

[[148988    976]
 [  9779   1798]]
              precision    recall  f1-score   support

           0       0.94      0.99      0.97    149964
           1       0.65      0.16      0.25     11577

    accuracy                           0.93    161541
   macro avg       0.79      0.57      0.61    161541
weighted avg       0.92      0.93      0.91    161541



In [36]:
# Try using the MLP Classifier
mlp = MLPClassifier(hidden_layer_sizes=(18, 18, 18, 18, 18, 18, 18), activation='relu', solver='adam', max_iter=300)
mlp.fit(X_train, y_train)

predict_train = mlp.predict(X_train)
predict_test = mlp.predict(X_test)

In [37]:
print(confusion_matrix(y_train, predict_train))
print(classification_report(y_train, predict_train))

[[346565   3582]
 [ 20745   6035]]
              precision    recall  f1-score   support

           0       0.94      0.99      0.97    350147
           1       0.63      0.23      0.33     26780

    accuracy                           0.94    376927
   macro avg       0.79      0.61      0.65    376927
weighted avg       0.92      0.94      0.92    376927



In [38]:
print(confusion_matrix(y_test, predict_test))
print(classification_report(y_test, predict_test))

[[148465   1499]
 [  9076   2501]]
              precision    recall  f1-score   support

           0       0.94      0.99      0.97    149964
           1       0.63      0.22      0.32     11577

    accuracy                           0.93    161541
   macro avg       0.78      0.60      0.64    161541
weighted avg       0.92      0.93      0.92    161541

