In [1]:
# NOTE: This does NOT have points close to real ones removed!

import pandas as pd
import numpy as np
%matplotlib inline
import matplotlib.pyplot as plt
import sklearn

crime = pd.read_csv('E:/Vancouver Crime Final/Synthetic Data/residential_bne_500k_combined.csv')

crime.head(20)

type             datetime  year  month  day  \
0   Break and Enter Residential/Other  2003-01-01 00:00:00  2003      1    1   
1   Break and Enter Residential/Other  2003-01-01 00:00:00  2003      1    1   
2   Break and Enter Residential/Other  2003-01-01 00:00:00  2003      1    1   
3   Break and Enter Residential/Other  2003-01-01 01:01:00  2003      1    1   
4   Break and Enter Residential/Other  2003-01-01 04:04:00  2003      1    1   
5   Break and Enter Residential/Other  2003-01-01 04:04:00  2003      1    1   
6   Break and Enter Residential/Other  2003-01-01 07:07:00  2003      1    1   
7   Break and Enter Residential/Other  2003-01-01 11:11:00  2003      1    1   
8   Break and Enter Residential/Other  2003-01-01 11:11:00  2003      1    1   
9   Break and Enter Residential/Other  2003-01-01 12:12:00  2003      1    1   
10  Break and Enter Residential/Other  2003-01-01 15:15:00  2003      1    1   
11  Break and Enter Residential/Other  2003-01-01 16:16:00  2003      1    1   
12  Break and Enter Residential/Other  2003-01-01 17:17:00  2003      1    1   
13  Break and Enter Residential/Other  2003-01-01 17:17:00  2003      1    1   
14  Break and Enter Residential/Other  2003-01-01 17:17:00  2003      1    1   
15  Break and Enter Residential/Other  2003-01-01 17:17:00  2003      1    1   
16  Break and Enter Residential/Other  2003-01-01 18:18:00  2003      1    1   
17  Break and Enter Residential/Other  2003-01-01 19:19:00  2003      1    1   
18  Break and Enter Residential/Other  2003-01-01 19:19:00  2003      1    1   
19  Break and Enter Residential/Other  2003-01-01 20:20:00  2003      1    1   

    hour  minute  Hour_Minute      hundred_block      utm_x  ...  signal_200  \
0      0       0     0.000000     9XX W 15TH AVE  490791.12  ...           2   
1      0       1     0.016667    34XX W 42ND AVE  486837.11  ...           3   
2      0      20     0.333333     19XX PARKER ST  495279.46  ...           1   
3      1      46     1.766667       45XX MAIN ST  492627.84  ...           2   
4      4       0     4.000000   25XX GRAVELEY ST  496100.23  ...           0   
5      4      30     4.500000  15XX SE MARINE DR  494572.37  ...           1   
6      7      25     7.416667      7XX SEMLIN DR  495363.36  ...           1   
7     11       0    11.000000    22XX TRIUMPH ST  495716.74  ...           4   
8     11      45    11.750000    38XX HEATHER ST  491248.44  ...           1   
9     12       0    12.000000       41XX VINE ST  488613.83  ...           0   
10    15      30    15.500000  30XX E KENT N AVE  496782.22  ...           1   
11    16      30    16.500000    28XX E 22ND AVE  496722.62  ...           1   
12    17       0    17.000000   16XX LAKEWOOD DR  495502.64  ...           2   
13    17       0    17.000000     39XX KNIGHT ST  494454.07  ...           3   
14    17       0    17.000000    14XX W 45TH AVE  489954.83  ...           1   
15    17       2    17.033333     5XX E 49TH AVE  493244.66  ...           2   
16    18      15    18.250000     9XX E 22ND AVE  493885.71  ...           0   
17    19       0    19.000000    17XX CYPRESS ST  489246.98  ...           1   
18    19       0    19.000000    17XX E 12TH AVE  495017.16  ...           4   
19    20       0    20.000000     15XX E 4TH AVE  494675.26  ...           0   

    trees_25  trees_100  rain_mm  snow_cm  total_precip_mm  temp_c  humidity  \
0          0         32     21.6      0.0             21.6     5.8      81.0   
1          6         38     21.6      0.0             21.6     5.8      81.0   
2          8         88     21.6      0.0             21.6     5.8      81.0   
3          8         83     21.6      0.0             21.6     6.2      78.0   
4          7         73     21.6      0.0             21.6     5.5      88.0   
5          0         41     21.6      0.0             21.6     5.5      88.0   
6          1         61     21.6      0.0             21.6     5.8      95.0   
7          6         67     21.

In [2]:
# Set Break and ENters to 1 and everything else to 0

crime = crime.replace(['NONE'], 0)

crime = crime.replace(['Break and Enter Residential/Other', 'Break and Enter Commercial'], 1)
crime.head()

type             datetime  year  month  day  hour  minute  Hour_Minute  \
0     1  2003-01-01 00:00:00  2003      1    1     0       0     0.000000   
1     1  2003-01-01 00:00:00  2003      1    1     0       1     0.016667   
2     1  2003-01-01 00:00:00  2003      1    1     0      20     0.333333   
3     1  2003-01-01 01:01:00  2003      1    1     1      46     1.766667   
4     1  2003-01-01 04:04:00  2003      1    1     4       0     4.000000   

      hundred_block      utm_x  ...  signal_200  trees_25  trees_100  rain_mm  \
0    9XX W 15TH AVE  490791.12  ...           2         0         32     21.6   
1   34XX W 42ND AVE  486837.11  ...           3         6         38     21.6   
2    19XX PARKER ST  495279.46  ...           1         8         88     21.6   
3      45XX MAIN ST  492627.84  ...           2         8         83     21.6   
4  25XX GRAVELEY ST  496100.23  ...           0         7         73     21.6   

   snow_cm  total_precip_mm  temp_c  humidity  pressure  hours_of_light  
0      0.0             21.6     5.8      81.0    101.70            9.53  
1      0.0             21.6     5.8      81.0    101.70            9.53  
2      0.0             21.6     5.8      81.0    101.70            9.53  
3      0.0             21.6     6.2      78.0    101.73            9.53  
4      0.0             21.6     5.5      88.0    101.70            9.53  

[5 rows x 30 columns]

In [3]:
crime

type             datetime  year  month  day  hour  minute  \
0          1  2003-01-01 00:00:00  2003      1    1     0       0   
1          1  2003-01-01 00:00:00  2003      1    1     0       1   
2          1  2003-01-01 00:00:00  2003      1    1     0      20   
3          1  2003-01-01 01:01:00  2003      1    1     1      46   
4          1  2003-01-01 04:04:00  2003      1    1     4       0   
...      ...                  ...   ...    ...  ...   ...     ...   
565886     0  2016-10-29 16:05:00  2016     10   29    16       5   
565887     0  2007-10-02 23:40:00  2007     10    2    23      40   
565888     0  2006-10-03 09:29:00  2006     10    3     9      29   
565889     0  2005-02-02 05:29:00  2005      2    2     5      29   
565890     0  2013-11-26 22:01:00  2013     11   26    22       1   

        Hour_Minute           hundred_block          utm_x  ...  signal_200  \
0          0.000000          9XX W 15TH AVE  490791.120000  ...           2   
1          0.016667         34XX W 42ND AVE  486837.110000  ...           3   
2          0.333333          19XX PARKER ST  495279.460000  ...           1   
3          1.766667            45XX MAIN ST  492627.840000  ...           2   
4          4.000000        25XX GRAVELEY ST  496100.230000  ...           0   
...             ...                     ...            ...  ...         ...   
565886    16.083333        40XX BOUNDARY RD  498263.140760  ...           0   
565887    23.666667         37XX W 31ST AVE  486377.345932  ...           2   
565888     9.483333           42XX YUKON ST  491831.626717  ...           0   
565889     5.483333         19XX W 39TH AVE  489136.700000  ...           0   
565890    22.016667  E 35TH AVE / KNIGHT ST  494415.830000  ...           3   

        trees_25  trees_100  rain_mm  snow_cm  total_precip_mm  temp_c  \
0              0         32     21.6      0.0             21.6     5.8   
1              6         38     21.6      0.0             21.6     5.8   
2              8         88     21.6      0.0             21.6     5.8   
3              8         83     21.6      0.0             21.6     6.2   
4              7         73     21.6      0.0             21.6     5.5   
...          ...        ...      ...      ...              ...     ...   
565886         4         27      6.4      0.0              6.4    11.0   
565887         9         45      5.2      0.0              5.2     9.5   
565888         8         67      0.0      0.0              0.0    11.9   
565889         8         69      0.0      0.0              0.0     8.2   
565890         2         31      0.0      0.0              0.0     5.8   

        humidity  pressure  hours_of_light  
0           81.0    101.70            9.53  
1           81.0    101.70            9.53  
2           81.0    101.70            9.53  
3           78.0    101.73            9.53  
4           88.0    101.70            9.53  
...          ...       ...             ...  
565886      89.0    101.34           11.08  
565887      87.0    100.86           12.66  
565888      84.0    102.09           12.58  
565889      90.0    102.93           10.63  
565890      84.0    102.00            9.87  

[565891 rows x 30 columns]

In [4]:
### Begin Processing the Data


# Import Pre-processing module
from sklearn import preprocessing

# Create Label Encoder
le = preprocessing.LabelEncoder()

# Convert the string columns to numeric
# .astype(str) to ensude they are read as strings and not as mixed types
crime['datetime'] = le.fit_transform(crime['datetime'].astype(str))
crime['hundred_block'] = le.fit_transform(crime['hundred_block'].astype(str))


# Display the results
crime

type  datetime  year  month  day  hour  minute  Hour_Minute  \
0          1         0  2003      1    1     0       0     0.000000   
1          1         0  2003      1    1     0       1     0.016667   
2          1         0  2003      1    1     0      20     0.333333   
3          1         5  2003      1    1     1      46     1.766667   
4          1        18  2003      1    1     4       0     4.000000   
...      ...       ...   ...    ...  ...   ...     ...          ...   
565886     0    444215  2016     10   29    16       5    16.083333   
565887     0    156503  2007     10    2    23      40    23.666667   
565888     0    123965  2006     10    3     9      29     9.483333   
565889     0     69505  2005      2    2     5      29     5.483333   
565890     0    351997  2013     11   26    22       1    22.016667   

        hundred_block          utm_x  ...  signal_200  trees_25  trees_100  \
0               14804  490791.120000  ...           2         0         32   
1                7276  486837.110000  ...           3         6         38   
2                2686  495279.460000  ...           1         8         88   
3                9186  492627.840000  ...           2         8         83   
4                4669  496100.230000  ...           0         7         73   
...               ...            ...  ...         ...       ...        ...   
565886           8571  498263.140760  ...           0         4         27   
565887           7850  486377.345932  ...           2         9         45   
565888           8893  491831.626717  ...           0         8         67   
565889           2739  489136.700000  ...           0         8         69   
565890          17132  494415.830000  ...           3         2         31   

        rain_mm  snow_cm  total_precip_mm  temp_c  humidity  pressure  \
0          21.6      0.0             21.6     5.8      81.0    101.70   
1          21.6      0.0             21.6     5.8      81.0    101.70   
2          21.6      0.0             21.6     5.8      81.0    101.70   
3          21.6      0.0             21.6     6.2      78.0    101.73   
4          21.6      0.0             21.6     5.5      88.0    101.70   
...         ...      ...              ...     ...       ...       ...   
565886      6.4      0.0              6.4    11.0      89.0    101.34   
565887      5.2      0.0              5.2     9.5      87.0    100.86   
565888      0.0      0.0              0.0    11.9      84.0    102.09   
565889      0.0      0.0              0.0     8.2      90.0    102.93   
565890      0.0      0.0              0.0     5.8      84.0    102.00   

        hours_of_light  
0                 9.53  
1                 9.53  
2                 9.53  
3                 9.53  
4                 9.53  
...                ...  
565886           11.08  
565887           12.66  
565888           12.58  
565889           10.63  
565890            9.87  

[565891 rows x 30 columns]

In [5]:
# Scale the Data

columns = [col for col in crime if col not in ['type']]


# Properly scale the reduced set of features
features = crime[columns]

from sklearn.preprocessing import MinMaxScaler
scaler = preprocessing.MinMaxScaler()

print(scaler.fit(features))

MinMaxScaler(copy=True, feature_range=(0, 1))


In [6]:
# Properly scale the features

columns = [col for col in crime if col not in ['type']]

# Properly scale the reduced set of features
features = crime[columns]


scaler = MinMaxScaler().fit(features.values) # scaler = MinMaxScaler().fit(features.values)
features = scaler.transform(features.values) # features = scaler.transform(features.values)
crime[columns] = features
crime

type  datetime    year     month       day      hour    minute  \
0          1  0.000000  0.0000  0.000000  0.000000  0.000000  0.000000   
1          1  0.000000  0.0000  0.000000  0.000000  0.000000  0.016949   
2          1  0.000000  0.0000  0.000000  0.000000  0.000000  0.338983   
3          1  0.000009  0.0000  0.000000  0.000000  0.043478  0.779661   
4          1  0.000034  0.0000  0.000000  0.000000  0.173913  0.000000   
...      ...       ...     ...       ...       ...       ...       ...   
565886     0  0.833992  0.8125  0.818182  0.933333  0.695652  0.084746   
565887     0  0.293827  0.2500  0.818182  0.033333  1.000000  0.677966   
565888     0  0.232738  0.1875  0.818182  0.066667  0.391304  0.491525   
565889     0  0.130492  0.1250  0.090909  0.033333  0.217391  0.491525   
565890     0  0.660857  0.6250  0.909091  0.833333  0.956522  0.016949   

        Hour_Minute  hundred_block     utm_x  ...  signal_200  trees_25  \
0          0.000000       0.673368  0.485327  ...    0.133333  0.000000   
1          0.000695       0.330953  0.214522  ...    0.200000  0.181818   
2          0.013899       0.122174  0.792727  ...    0.066667  0.242424   
3          0.073662       0.417830  0.611121  ...    0.133333  0.242424   
4          0.166782       0.212372  0.848941  ...    0.000000  0.212121   
...             ...            ...       ...  ...         ...       ...   
565886     0.670605       0.389857  0.997076  ...    0.000000  0.121212   
565887     0.986796       0.357062  0.183033  ...    0.133333  0.272727   
565888     0.395413       0.404503  0.556590  ...    0.000000  0.242424   
565889     0.228631       0.124585  0.372018  ...    0.000000  0.242424   
565890     0.917999       0.779259  0.733578  ...    0.200000  0.060606   

        trees_100   rain_mm  snow_cm  total_precip_mm    temp_c  humidity  \
0        0.244275  0.235808      0.0         0.235808  0.408421  0.781609   
1        0.290076  0.235808      0.0         0.235808  0.408421  0.781609   
2        0.671756  0.235808      0.0         0.235808  0.408421  0.781609   
3        0.633588  0.235808      0.0         0.235808  0.416842  0.747126   
4        0.557252  0.235808      0.0         0.235808  0.402105  0.862069   
...           ...       ...      ...              ...       ...       ...   
565886   0.206107  0.069869      0.0         0.069869  0.517895  0.873563   
565887   0.343511  0.056769      0.0         0.056769  0.486316  0.850575   
565888   0.511450  0.000000      0.0         0.000000  0.536842  0.816092   
565889   0.526718  0.000000      0.0         0.000000  0.458947  0.885057   
565890   0.236641  0.000000      0.0         0.000000  0.408421  0.816092   

        pressure  hours_of_light  
0       0.612081        0.010909  
1       0.612081        0.010909  
2       0.612081        0.010909  
3       0.616107        0.010909  
4       0.612081        0.010909  
...          ...             ...  
565886  0.563758        0.198788  
565887  0.499329        0.390303  
565888  0.664430        0.380606  
565889  0.777181        0.144242  
565890  0.652349        0.052121  

[565891 rows x 30 columns]

In [7]:
# split training data into training and testing
from sklearn.model_selection import train_test_split

# Select columns to that are data
cols = [col for col in crime if col not in ['type']]

X = crime[cols]

# Select target data
y = crime['type']

X_train, X_test, y_train, y_test = train_test_split(X, y, random_state=100, test_size=0.3)
print(X_train.shape)

(396123, 29)


In [8]:
# Trying Random Forest Classifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.feature_selection import SelectFromModel

model_tree = RandomForestClassifier(random_state=100, n_estimators=50)
model_tree.fit(X_train, y_train)
print(model_tree.feature_importances_)
sel_model_tree = SelectFromModel(estimator=model_tree, prefit=True, threshold='mean')  
      # since we already fit the data, we specify prefit option here
      # Features whose importance is greater or equal to the threshold are kept while the others are discarded.
X_train_sfm_tree = sel_model_tree.transform(X_train)
print(sel_model_tree.get_support())

feature_importances = pd.DataFrame(model_tree.feature_importances_,
                                   index = X_train.columns,
                                    columns=['importance']).sort_values('importance', 
                                                                        ascending=False)
feature_importances

[0.03788859 0.01673471 0.01367545 0.0223965  0.02130966 0.34980986
 0.04870028 0.08070912 0.03413167 0.03425333 0.03478445 0.03455532
 0.00784299 0.01201072 0.01868273 0.02532305 0.00247426 0.00213857
 0.00543652 0.01212392 0.01968015 0.02990842 0.01304287 0.00160236
 0.01315032 0.02758984 0.02451413 0.02848608 0.02704412]
[ True False False False False  True  True  True False False  True  True
 False False False False False False False False False False False False
 False False False False False]


importance
minute             0.349810
hundred_block      0.080709
Hour_Minute        0.048700
datetime           0.037889
latitude           0.034784
longitude          0.034555
utm_y              0.034253
utm_x              0.034132
trees_100          0.029908
pressure           0.028486
temp_c             0.027590
hours_of_light     0.027044
light_pole_100     0.025323
humidity           0.024514
day                0.022396
hour               0.021310
trees_25           0.019680
light_pole_50      0.018683
year               0.016735
month              0.013675
total_precip_mm    0.013150
rain_mm            0.013043
signal_200         0.012124
light_pole_25      0.012011
light_pole_12_5    0.007843
signal_100         0.005437
signal_25          0.002474
signal_50          0.002139
snow_cm            0.001602

In [9]:
# Simple Neural Network

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import sklearn
from sklearn.neural_network import MLPClassifier
from sklearn.neural_network import MLPRegressor

# import needed modules
from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_squared_error
from math import sqrt
from sklearn.metrics import r2_score

In [10]:
# Try using the MLP Classifier
mlp = MLPClassifier(hidden_layer_sizes=(29, 29, 29), activation='relu', solver='adam', max_iter=300)
mlp.fit(X_train, y_train)

predict_train = mlp.predict(X_train)
predict_test = mlp.predict(X_test)

In [11]:
from sklearn.metrics import classification_report, confusion_matrix
print(confusion_matrix(y_train, predict_train))
print(classification_report(y_train, predict_train))

[[343471   6674]
 [ 18316  27662]]
              precision    recall  f1-score   support

           0       0.95      0.98      0.96    350145
           1       0.81      0.60      0.69     45978

    accuracy                           0.94    396123
   macro avg       0.88      0.79      0.83    396123
weighted avg       0.93      0.94      0.93    396123



In [12]:
print(confusion_matrix(y_test, predict_test))
print(classification_report(y_test, predict_test))

[[147101   2865]
 [  7927  11875]]
              precision    recall  f1-score   support

           0       0.95      0.98      0.96    149966
           1       0.81      0.60      0.69     19802

    accuracy                           0.94    169768
   macro avg       0.88      0.79      0.83    169768
weighted avg       0.93      0.94      0.93    169768



In [13]:
# Try using the MLP Classifier
mlp = MLPClassifier(hidden_layer_sizes=(29, 29, 29), activation='relu', solver='adam', max_iter=3000)
mlp.fit(X_train, y_train)

predict_train = mlp.predict(X_train)
predict_test = mlp.predict(X_test)

In [14]:
print(confusion_matrix(y_train, predict_train))
print(classification_report(y_train, predict_train))

[[343725   6420]
 [ 18506  27472]]
              precision    recall  f1-score   support

           0       0.95      0.98      0.97    350145
           1       0.81      0.60      0.69     45978

    accuracy                           0.94    396123
   macro avg       0.88      0.79      0.83    396123
weighted avg       0.93      0.94      0.93    396123



In [15]:
print(confusion_matrix(y_test, predict_test))
print(classification_report(y_test, predict_test))

[[147197   2769]
 [  8067  11735]]
              precision    recall  f1-score   support

           0       0.95      0.98      0.96    149966
           1       0.81      0.59      0.68     19802

    accuracy                           0.94    169768
   macro avg       0.88      0.79      0.82    169768
weighted avg       0.93      0.94      0.93    169768



In [16]:
############################# END HERE ###################################

In [17]:
# Try using the MLP Classifier
mlp = MLPClassifier(hidden_layer_sizes=(29, 29, 29, 29, 29, 29, 29), activation='relu', solver='adam', max_iter=200)
mlp.fit(X_train, y_train)

predict_train = mlp.predict(X_train)
predict_test = mlp.predict(X_test)

In [18]:
print(confusion_matrix(y_train, predict_train))
print(classification_report(y_train, predict_train))

[[345749   4396]
 [ 25358  20620]]
              precision    recall  f1-score   support

           0       0.93      0.99      0.96    350145
           1       0.82      0.45      0.58     45978

    accuracy                           0.92    396123
   macro avg       0.88      0.72      0.77    396123
weighted avg       0.92      0.92      0.91    396123



In [19]:
print(confusion_matrix(y_test, predict_test))
print(classification_report(y_test, predict_test))

[[148027   1939]
 [ 10892   8910]]
              precision    recall  f1-score   support

           0       0.93      0.99      0.96    149966
           1       0.82      0.45      0.58     19802

    accuracy                           0.92    169768
   macro avg       0.88      0.72      0.77    169768
weighted avg       0.92      0.92      0.91    169768



In [20]:
feature_importances

importance
minute             0.349810
hundred_block      0.080709
Hour_Minute        0.048700
datetime           0.037889
latitude           0.034784
longitude          0.034555
utm_y              0.034253
utm_x              0.034132
trees_100          0.029908
pressure           0.028486
temp_c             0.027590
hours_of_light     0.027044
light_pole_100     0.025323
humidity           0.024514
day                0.022396
hour               0.021310
trees_25           0.019680
light_pole_50      0.018683
year               0.016735
month              0.013675
total_precip_mm    0.013150
rain_mm            0.013043
signal_200         0.012124
light_pole_25      0.012011
light_pole_12_5    0.007843
signal_100         0.005437
signal_25          0.002474
signal_50          0.002139
snow_cm            0.001602

In [21]:
# Cut down features

# split training data into training and testing
from sklearn.model_selection import train_test_split

# Select columns to that are data
cols = [col for col in crime if col not in ['type', 'minute', 'hour', 'latitude', 'longitude', 'datetime']]

X = crime[cols]

# Select target data
y = crime['type']

X_train, X_test, y_train, y_test = train_test_split(X, y, random_state=100, test_size=0.3)
print(X_train.shape)

(396123, 24)


In [22]:
X_train

year     month       day  Hour_Minute  hundred_block     utm_x  \
53028   0.6875  0.909091  0.366667     0.354413       0.289788  0.248176   
146681  0.9375  0.545455  0.400000     0.138290       0.354787  0.495377   
61220   0.8750  0.636364  0.800000     0.052120       0.446987  0.642649   
368676  0.1250  0.545455  0.066667     0.187630       0.434887  0.208616   
126363  0.3125  0.909091  0.666667     0.344684       0.919991  0.713509   
...        ...       ...       ...          ...            ...       ...   
344414  0.0625  0.545455  0.233333     0.489924       0.544826  0.409325   
212912  0.0625  0.090909  0.700000     0.606671       0.497885  0.602683   
65615   1.0000  0.636364  0.100000     0.833912       0.614010  0.675237   
210755  0.9375  0.181818  0.000000     0.746352       0.492882  0.504779   
56088   0.7500  0.909091  0.533333     0.000000       0.112258  0.381998   

           utm_y  light_pole_12_5  light_pole_25  light_pole_50  ...  \
53028   0.508500         0.000000       0.029851       0.101266  ...   
146681  0.459261         0.035714       0.014925       0.050633  ...   
61220   0.462374         0.035714       0.014925       0.075949  ...   
368676  0.364744         0.035714       0.014925       0.025316  ...   
126363  0.089786         0.035714       0.044776       0.101266  ...   
...          ...              ...            ...            ...  ...   
344414  0.221643         0.000000       0.014925       0.025316  ...   
212912  0.735427         0.142857       0.104478       0.341772  ...   
65615   0.514937         0.035714       0.014925       0.101266  ...   
210755  0.277224         0.000000       0.000000       0.025316  ...   
56088   0.542510         0.035714       0.014925       0.025316  ...   

        signal_200  trees_25  trees_100   rain_mm  snow_cm  total_precip_mm  \
53028     0.000000  0.181818   0.580153  0.000000      0.0         0.000000   
146681    0.000000  0.121212   0.396947  0.000000      0.0         0.000000   
61220     0.000000  0.212121   0.435115  0.000000      0.0         0.000000   
368676    0.000000  0.181818   0.595420  0.000000      0.0         0.000000   
126363    0.133333  0.121212   0.290076  0.074236      0.0         0.074236   
...            ...       ...        ...       ...      ...              ...   
344414    0.066667  0.242424   0.175573  0.000000      0.0         0.000000   
212912    0.200000  0.090909   0.328244  0.000000      0.0         0.000000   
65615     0.133333  0.212121   0.442748  0.000000      0.0         0.000000   
210755    0.133333  0.090909   0.198473  0.021834      0.0         0.021834   
56088     0.200000  0.151515   0.366412  0.063319      0.0         0.063319   

          temp_c  humidity  pressure  hours_of_light  
53028   0.280000  0.367816  0.748993        0.118788  
146681  0.635789  0.816092  0.604027        0.947879  
61220   0.572632  0.793103  0.616107        0.669091  
368676  0.534737  0.793103  0.629530        0.983030  
126363  0.418947  0.804598  0.692617        0.071515  
...          ...       ...       ...             ...  
344414  0.658947  0.609195  0.601342        0.966061  
212912  0.507368  0.574713  0.459060        0.267879  
65615   0.703158  0.758621  0.570470        0.823030  
210755  0.471579  0.390805  0.367785        0.321212  
56088   0.404211  0.931034  0.495302        0.094545  

[396123 rows x 24 columns]

In [23]:
y_train

53028     1
146681    0
61220     1
368676    0
126363    0
         ..
344414    0
212912    0
65615     1
210755    0
56088     1
Name: type, Length: 396123, dtype: int64

In [24]:
# Trying Random Forest Classifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.feature_selection import SelectFromModel

model_tree = RandomForestClassifier(random_state=100, n_estimators=50)
model_tree.fit(X_train, y_train)
print(model_tree.feature_importances_)
sel_model_tree = SelectFromModel(estimator=model_tree, prefit=True, threshold='mean')  
      # since we already fit the data, we specify prefit option here
      # Features whose importance is greater or equal to the threshold are kept while the others are discarded.
X_train_sfm_tree = sel_model_tree.transform(X_train)
print(sel_model_tree.get_support())

feature_importances = pd.DataFrame(model_tree.feature_importances_,
                                   index = X_train.columns,
                                    columns=['importance']).sort_values('importance', 
                                                                        ascending=False)
feature_importances

[0.04274263 0.02563579 0.04251649 0.09687079 0.12135634 0.07872796
 0.07996513 0.01369492 0.01976304 0.03527722 0.05034467 0.00283175
 0.00331536 0.01004023 0.02406572 0.03589471 0.05895654 0.02478926
 0.00216147 0.0248709  0.05287936 0.04695409 0.05476205 0.05158358]
[ True False  True  True  True  True  True False False False  True False
 False False False False  True False False False  True  True  True  True]


importance
hundred_block      0.121356
Hour_Minute        0.096871
utm_y              0.079965
utm_x              0.078728
trees_100          0.058957
pressure           0.054762
temp_c             0.052879
hours_of_light     0.051584
light_pole_100     0.050345
humidity           0.046954
year               0.042743
day                0.042516
trees_25           0.035895
light_pole_50      0.035277
month              0.025636
total_precip_mm    0.024871
rain_mm            0.024789
signal_200         0.024066
light_pole_25      0.019763
light_pole_12_5    0.013695
signal_100         0.010040
signal_50          0.003315
signal_25          0.002832
snow_cm            0.002161

In [25]:
# Try using the MLP Classifier
mlp = MLPClassifier(hidden_layer_sizes=(24, 24, 24), activation='relu', solver='adam', max_iter=300)
mlp.fit(X_train, y_train)

predict_train = mlp.predict(X_train)
predict_test = mlp.predict(X_test)

In [26]:
print(confusion_matrix(y_train, predict_train))
print(classification_report(y_train, predict_train))

[[346923   3222]
 [ 40149   5829]]
              precision    recall  f1-score   support

           0       0.90      0.99      0.94    350145
           1       0.64      0.13      0.21     45978

    accuracy                           0.89    396123
   macro avg       0.77      0.56      0.58    396123
weighted avg       0.87      0.89      0.86    396123



In [27]:
print(confusion_matrix(y_test, predict_test))
print(classification_report(y_test, predict_test))

[[148511   1455]
 [ 17311   2491]]
              precision    recall  f1-score   support

           0       0.90      0.99      0.94    149966
           1       0.63      0.13      0.21     19802

    accuracy                           0.89    169768
   macro avg       0.76      0.56      0.58    169768
weighted avg       0.86      0.89      0.86    169768



In [28]:
# Try using the MLP Classifier
mlp = MLPClassifier(hidden_layer_sizes=(29, 29, 29, 29, 29, 29, 29), activation='relu', solver='adam', max_iter=300)
mlp.fit(X_train, y_train)

predict_train = mlp.predict(X_train)
predict_test = mlp.predict(X_test)

In [29]:
print(confusion_matrix(y_train, predict_train))
print(classification_report(y_train, predict_train))

[[347450   2695]
 [ 40089   5889]]
              precision    recall  f1-score   support

           0       0.90      0.99      0.94    350145
           1       0.69      0.13      0.22     45978

    accuracy                           0.89    396123
   macro avg       0.79      0.56      0.58    396123
weighted avg       0.87      0.89      0.86    396123



In [30]:
print(confusion_matrix(y_test, predict_test))
print(classification_report(y_test, predict_test))

[[148642   1324]
 [ 17424   2378]]
              precision    recall  f1-score   support

           0       0.90      0.99      0.94    149966
           1       0.64      0.12      0.20     19802

    accuracy                           0.89    169768
   macro avg       0.77      0.56      0.57    169768
weighted avg       0.87      0.89      0.85    169768



In [31]:
# Cut down features again

# split training data into training and testing
from sklearn.model_selection import train_test_split

# Select columns to that are data
cols = [col for col in crime if col not in ['type', 'minute', 'hour', 'latitude', 'longitude', 'datetime', 
                                            'snow_cm', 'rain_mm', 'signal_25', 'signal_50', 'signal_100', 
                                            'light_pole_12_5']]

X = crime[cols]

# Select target data
y = crime['type']

X_train, X_test, y_train, y_test = train_test_split(X, y, random_state=100, test_size=0.3)
print(X_train.shape)

(396123, 18)


In [32]:
# Trying Random Forest Classifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.feature_selection import SelectFromModel

model_tree = RandomForestClassifier(random_state=100, n_estimators=50)
model_tree.fit(X_train, y_train)
print(model_tree.feature_importances_)
sel_model_tree = SelectFromModel(estimator=model_tree, prefit=True, threshold='mean')  
      # since we already fit the data, we specify prefit option here
      # Features whose importance is greater or equal to the threshold are kept while the others are discarded.
X_train_sfm_tree = sel_model_tree.transform(X_train)
print(sel_model_tree.get_support())

feature_importances = pd.DataFrame(model_tree.feature_importances_,
                                   index = X_train.columns,
                                    columns=['importance']).sort_values('importance', 
                                                                        ascending=False)
feature_importances

[0.04307838 0.02579211 0.04437057 0.10938931 0.13001293 0.08474599
 0.08505731 0.02123953 0.03711656 0.05233352 0.02413564 0.03625676
 0.06145242 0.02988441 0.05503299 0.04851732 0.05760618 0.05397808]
[False False False  True  True  True  True False False False False False
  True False False False  True False]


importance
hundred_block      0.130013
Hour_Minute        0.109389
utm_y              0.085057
utm_x              0.084746
trees_100          0.061452
pressure           0.057606
temp_c             0.055033
hours_of_light     0.053978
light_pole_100     0.052334
humidity           0.048517
day                0.044371
year               0.043078
light_pole_50      0.037117
trees_25           0.036257
total_precip_mm    0.029884
month              0.025792
signal_200         0.024136
light_pole_25      0.021240

In [33]:
# Try using the MLP Classifier
mlp = MLPClassifier(hidden_layer_sizes=(18, 18, 18), activation='relu', solver='adam', max_iter=300)
mlp.fit(X_train, y_train)

predict_train = mlp.predict(X_train)
predict_test = mlp.predict(X_test)

In [34]:
print(confusion_matrix(y_train, predict_train))
print(classification_report(y_train, predict_train))

[[346722   3423]
 [ 40595   5383]]
              precision    recall  f1-score   support

           0       0.90      0.99      0.94    350145
           1       0.61      0.12      0.20     45978

    accuracy                           0.89    396123
   macro avg       0.75      0.55      0.57    396123
weighted avg       0.86      0.89      0.85    396123



In [35]:
print(confusion_matrix(y_test, predict_test))
print(classification_report(y_test, predict_test))

[[148467   1499]
 [ 17456   2346]]
              precision    recall  f1-score   support

           0       0.89      0.99      0.94    149966
           1       0.61      0.12      0.20     19802

    accuracy                           0.89    169768
   macro avg       0.75      0.55      0.57    169768
weighted avg       0.86      0.89      0.85    169768



In [36]:
# Try using the MLP Classifier
mlp = MLPClassifier(hidden_layer_sizes=(18, 18, 18, 18, 18, 18, 18), activation='relu', solver='adam', max_iter=300)
mlp.fit(X_train, y_train)

predict_train = mlp.predict(X_train)
predict_test = mlp.predict(X_test)

In [37]:
print(confusion_matrix(y_train, predict_train))
print(classification_report(y_train, predict_train))

[[347822   2323]
 [ 42195   3783]]
              precision    recall  f1-score   support

           0       0.89      0.99      0.94    350145
           1       0.62      0.08      0.15     45978

    accuracy                           0.89    396123
   macro avg       0.76      0.54      0.54    396123
weighted avg       0.86      0.89      0.85    396123



In [38]:
print(confusion_matrix(y_test, predict_test))
print(classification_report(y_test, predict_test))

[[148916   1050]
 [ 18112   1690]]
              precision    recall  f1-score   support

           0       0.89      0.99      0.94    149966
           1       0.62      0.09      0.15     19802

    accuracy                           0.89    169768
   macro avg       0.75      0.54      0.54    169768
weighted avg       0.86      0.89      0.85    169768

