In [1]:
# NOTE: This does NOT have points close to real ones removed!

import pandas as pd
import numpy as np
%matplotlib inline
import matplotlib.pyplot as plt
import sklearn

crime = pd.read_csv('E:/Vancouver Crime Final/Synthetic Data/both_bne_500k_notwithin_1week_25m.csv')

crime.head(20)

type             datetime  year  month  day  \
0   Break and Enter Residential/Other  2003-01-01 00:00:00  2003      1    1   
1          Break and Enter Commercial  2003-01-01 00:00:00  2003      1    1   
2   Break and Enter Residential/Other  2003-01-01 00:00:00  2003      1    1   
3   Break and Enter Residential/Other  2003-01-01 00:00:00  2003      1    1   
4   Break and Enter Residential/Other  2003-01-01 01:01:00  2003      1    1   
5   Break and Enter Residential/Other  2003-01-01 04:04:00  2003      1    1   
6   Break and Enter Residential/Other  2003-01-01 04:04:00  2003      1    1   
7          Break and Enter Commercial  2003-01-01 06:06:00  2003      1    1   
8          Break and Enter Commercial  2003-01-01 07:07:00  2003      1    1   
9          Break and Enter Commercial  2003-01-01 07:07:00  2003      1    1   
10  Break and Enter Residential/Other  2003-01-01 07:07:00  2003      1    1   
11  Break and Enter Residential/Other  2003-01-01 11:11:00  2003      1    1   
12         Break and Enter Commercial  2003-01-01 11:11:00  2003      1    1   
13  Break and Enter Residential/Other  2003-01-01 11:11:00  2003      1    1   
14         Break and Enter Commercial  2003-01-01 12:12:00  2003      1    1   
15         Break and Enter Commercial  2003-01-01 12:12:00  2003      1    1   
16  Break and Enter Residential/Other  2003-01-01 12:12:00  2003      1    1   
17         Break and Enter Commercial  2003-01-01 12:12:00  2003      1    1   
18  Break and Enter Residential/Other  2003-01-01 15:15:00  2003      1    1   
19  Break and Enter Residential/Other  2003-01-01 16:16:00  2003      1    1   

    hour  minute  Hour_Minute      hundred_block      utm_x  ...  signal_200  \
0      0       0     0.000000     9XX W 15TH AVE  490791.12  ...           2   
1      0       0     0.000000   64XX VICTORIA DR  495220.95  ...           2   
2      0       1     0.016667    34XX W 42ND AVE  486837.11  ...           3   
3      0      20     0.333333     19XX PARKER ST  495279.46  ...           1   
4      1      46     1.766667       45XX MAIN ST  492627.84  ...           2   
5      4       0     4.000000   25XX GRAVELEY ST  496100.23  ...           0   
6      4      30     4.500000  15XX SE MARINE DR  494572.37  ...           1   
7      6       0     6.000000   5XX W GEORGIA ST  491507.39  ...          10   
8      7      13     7.216667    18XX W 57TH AVE  489132.03  ...           0   
9      7      13     7.216667     45XX FRASER ST  493431.80  ...           2   
10     7      25     7.416667      7XX SEMLIN DR  495363.36  ...           1   
11    11       0    11.000000    22XX TRIUMPH ST  495716.74  ...           4   
12    11       0    11.000000     35XX FRASER ST  493447.88  ...           1   
13    11      45    11.750000    38XX HEATHER ST  491248.44  ...           1   
14    12       0    12.000000      5XX BEATTY ST  492024.04  ...          10   
15    12       0    12.000000   7XX PACIFIC BLVD  492005.87  ...           2   
16    12       0    12.000000       41XX VINE ST  488613.83  ...           0   
17    12      49    12.816667    28XX BENTALL ST  497676.19  ...           3   
18    15      30    15.500000  30XX E KENT N AVE  496782.22  ...           1   
19    16      30    16.500000    28XX E 22ND AVE  496722.62  ...           1   

    trees_25  trees_100  rain_mm  snow_cm  total_precip_mm  temp_c  humidity  \
0          0         32     21.6      0.0             21.6     5.8      81.0   
1          5         40     21.6      0.0             21.6     5.8      81.0   
2          6         38     21.6      0.0             21.6     5.8      81.0   
3          8         88     21.6      0.0             21.6     5.8      81.0   
4          8         83     21.6      0.0             21.6     6.2      78.0   
5          7         73     21.6      0.0             21.6     5.5      88.0   
6          0         41     21.6      0.0             21.6     5.5      88.0   
7          2         27     21.

In [2]:
# Set Break and ENters to 1 and everything else to 0

crime = crime.replace(['NONE'], 0)

crime = crime.replace(['Break and Enter Residential/Other', 'Break and Enter Commercial'], 1)
crime.head()

type             datetime  year  month  day  hour  minute  Hour_Minute  \
0     1  2003-01-01 00:00:00  2003      1    1     0       0     0.000000   
1     1  2003-01-01 00:00:00  2003      1    1     0       0     0.000000   
2     1  2003-01-01 00:00:00  2003      1    1     0       1     0.016667   
3     1  2003-01-01 00:00:00  2003      1    1     0      20     0.333333   
4     1  2003-01-01 01:01:00  2003      1    1     1      46     1.766667   

      hundred_block      utm_x  ...  signal_200  trees_25  trees_100  rain_mm  \
0    9XX W 15TH AVE  490791.12  ...           2         0         32     21.6   
1  64XX VICTORIA DR  495220.95  ...           2         5         40     21.6   
2   34XX W 42ND AVE  486837.11  ...           3         6         38     21.6   
3    19XX PARKER ST  495279.46  ...           1         8         88     21.6   
4      45XX MAIN ST  492627.84  ...           2         8         83     21.6   

   snow_cm  total_precip_mm  temp_c  humidity  pressure  hours_of_light  
0      0.0             21.6     5.8      81.0    101.70            9.53  
1      0.0             21.6     5.8      81.0    101.70            9.53  
2      0.0             21.6     5.8      81.0    101.70            9.53  
3      0.0             21.6     5.8      81.0    101.70            9.53  
4      0.0             21.6     6.2      78.0    101.73            9.53  

[5 rows x 30 columns]

In [3]:
crime

type             datetime  year  month  day  hour  minute  \
0          1  2003-01-01 00:00:00  2003      1    1     0       0   
1          1  2003-01-01 00:00:00  2003      1    1     0       0   
2          1  2003-01-01 00:00:00  2003      1    1     0       1   
3          1  2003-01-01 00:00:00  2003      1    1     0      20   
4          1  2003-01-01 01:01:00  2003      1    1     1      46   
...      ...                  ...   ...    ...  ...   ...     ...   
552758     0  2013-07-23 01:23:00  2013      7   23     1      23   
552759     0  2016-10-29 16:05:00  2016     10   29    16       5   
552760     0  2006-10-03 09:29:00  2006     10    3     9      29   
552761     0  2005-02-02 05:29:00  2005      2    2     5      29   
552762     0  2013-11-26 22:01:00  2013     11   26    22       1   

        Hour_Minute           hundred_block          utm_x  ...  signal_200  \
0          0.000000          9XX W 15TH AVE  490791.120000  ...           2   
1          0.000000        64XX VICTORIA DR  495220.950000  ...           2   
2          0.016667         34XX W 42ND AVE  486837.110000  ...           3   
3          0.333333          19XX PARKER ST  495279.460000  ...           1   
4          1.766667            45XX MAIN ST  492627.840000  ...           2   
...             ...                     ...            ...  ...         ...   
552758     1.383333          8XX W 37TH AVE  490975.209866  ...           0   
552759    16.083333        40XX BOUNDARY RD  498263.140760  ...           0   
552760     9.483333           42XX YUKON ST  491831.626717  ...           0   
552761     5.483333         19XX W 39TH AVE  489136.700000  ...           0   
552762    22.016667  E 35TH AVE / KNIGHT ST  494415.830000  ...           3   

        trees_25  trees_100  rain_mm  snow_cm  total_precip_mm  temp_c  \
0              0         32     21.6      0.0             21.6     5.8   
1              5         40     21.6      0.0             21.6     5.8   
2              6         38     21.6      0.0             21.6     5.8   
3              8         88     21.6      0.0             21.6     5.8   
4              8         83     21.6      0.0             21.6     6.2   
...          ...        ...      ...      ...              ...     ...   
552758         6         43      0.0      0.0              0.0    15.8   
552759         4         27      6.4      0.0              6.4    11.0   
552760         8         67      0.0      0.0              0.0    11.9   
552761         8         69      0.0      0.0              0.0     8.2   
552762         2         31      0.0      0.0              0.0     5.8   

        humidity  pressure  hours_of_light  
0           81.0    101.70            9.53  
1           81.0    101.70            9.53  
2           81.0    101.70            9.53  
3           81.0    101.70            9.53  
4           78.0    101.73            9.53  
...          ...       ...             ...  
552758      88.0    101.67           16.83  
552759      89.0    101.34           11.08  
552760      84.0    102.09           12.58  
552761      90.0    102.93           10.63  
552762      84.0    102.00            9.87  

[552763 rows x 30 columns]

In [4]:
### Begin Processing the Data


# Import Pre-processing module
from sklearn import preprocessing

# Create Label Encoder
le = preprocessing.LabelEncoder()

# Convert the string columns to numeric
# .astype(str) to ensude they are read as strings and not as mixed types
crime['datetime'] = le.fit_transform(crime['datetime'].astype(str))
crime['hundred_block'] = le.fit_transform(crime['hundred_block'].astype(str))


# Display the results
crime

type  datetime  year  month  day  hour  minute  Hour_Minute  \
0          1         0  2003      1    1     0       0     0.000000   
1          1         0  2003      1    1     0       0     0.000000   
2          1         0  2003      1    1     0       1     0.016667   
3          1         0  2003      1    1     0      20     0.333333   
4          1         5  2003      1    1     1      46     1.766667   
...      ...       ...   ...    ...  ...   ...     ...          ...   
552758     0    319294  2013      7   23     1      23     1.383333   
552759     0    418251  2016     10   29    16       5    16.083333   
552760     0    113443  2006     10    3     9      29     9.483333   
552761     0     63125  2005      2    2     5      29     5.483333   
552762     0    329745  2013     11   26    22       1    22.016667   

        hundred_block          utm_x  ...  signal_200  trees_25  trees_100  \
0               14804  490791.120000  ...           2         0         32   
1               11850  495220.950000  ...           2         5         40   
2                7276  486837.110000  ...           3         6         38   
3                2686  495279.460000  ...           1         8         88   
4                9186  492627.840000  ...           2         8         83   
...               ...            ...  ...         ...       ...        ...   
552758          14418  490975.209866  ...           0         6         43   
552759           8571  498263.140760  ...           0         4         27   
552760           8893  491831.626717  ...           0         8         67   
552761           2739  489136.700000  ...           0         8         69   
552762          17132  494415.830000  ...           3         2         31   

        rain_mm  snow_cm  total_precip_mm  temp_c  humidity  pressure  \
0          21.6      0.0             21.6     5.8      81.0    101.70   
1          21.6      0.0             21.6     5.8      81.0    101.70   
2          21.6      0.0             21.6     5.8      81.0    101.70   
3          21.6      0.0             21.6     5.8      81.0    101.70   
4          21.6      0.0             21.6     6.2      78.0    101.73   
...         ...      ...              ...     ...       ...       ...   
552758      0.0      0.0              0.0    15.8      88.0    101.67   
552759      6.4      0.0              6.4    11.0      89.0    101.34   
552760      0.0      0.0              0.0    11.9      84.0    102.09   
552761      0.0      0.0              0.0     8.2      90.0    102.93   
552762      0.0      0.0              0.0     5.8      84.0    102.00   

        hours_of_light  
0                 9.53  
1                 9.53  
2                 9.53  
3                 9.53  
4                 9.53  
...                ...  
552758           16.83  
552759           11.08  
552760           12.58  
552761           10.63  
552762            9.87  

[552763 rows x 30 columns]

In [5]:
# Scale the Data

columns = [col for col in crime if col not in ['type']]


# Properly scale the reduced set of features
features = crime[columns]

from sklearn.preprocessing import MinMaxScaler
scaler = preprocessing.MinMaxScaler()

print(scaler.fit(features))

MinMaxScaler(copy=True, feature_range=(0, 1))


In [6]:
# Properly scale the features

columns = [col for col in crime if col not in ['type']]

# Properly scale the reduced set of features
features = crime[columns]


scaler = MinMaxScaler().fit(features.values) # scaler = MinMaxScaler().fit(features.values)
features = scaler.transform(features.values) # features = scaler.transform(features.values)
crime[columns] = features
crime

type  datetime    year     month       day      hour    minute  \
0          1  0.000000  0.0000  0.000000  0.000000  0.000000  0.000000   
1          1  0.000000  0.0000  0.000000  0.000000  0.000000  0.000000   
2          1  0.000000  0.0000  0.000000  0.000000  0.000000  0.016949   
3          1  0.000000  0.0000  0.000000  0.000000  0.000000  0.338983   
4          1  0.000010  0.0000  0.000000  0.000000  0.043478  0.779661   
...      ...       ...     ...       ...       ...       ...       ...   
552758     0  0.633335  0.6250  0.545455  0.733333  0.043478  0.389831   
552759     0  0.829621  0.8125  0.818182  0.933333  0.695652  0.084746   
552760     0  0.225020  0.1875  0.818182  0.066667  0.391304  0.491525   
552761     0  0.125211  0.1250  0.090909  0.033333  0.217391  0.491525   
552762     0  0.654065  0.6250  0.909091  0.833333  0.956522  0.016949   

        Hour_Minute  hundred_block     utm_x  ...  signal_200  trees_25  \
0          0.000000       0.673368  0.485327  ...    0.133333  0.000000   
1          0.000000       0.539004  0.788720  ...    0.133333  0.151515   
2          0.000695       0.330953  0.214522  ...    0.200000  0.181818   
3          0.013899       0.122174  0.792727  ...    0.066667  0.242424   
4          0.073662       0.417830  0.611121  ...    0.133333  0.242424   
...             ...            ...       ...  ...         ...       ...   
552758     0.057679       0.655811  0.497935  ...    0.000000  0.181818   
552759     0.670605       0.389857  0.997076  ...    0.000000  0.121212   
552760     0.395413       0.404503  0.556590  ...    0.000000  0.242424   
552761     0.228631       0.124585  0.372018  ...    0.000000  0.242424   
552762     0.917999       0.779259  0.733578  ...    0.200000  0.060606   

        trees_100   rain_mm  snow_cm  total_precip_mm    temp_c  humidity  \
0        0.244275  0.235808      0.0         0.235808  0.408421  0.781609   
1        0.305344  0.235808      0.0         0.235808  0.408421  0.781609   
2        0.290076  0.235808      0.0         0.235808  0.408421  0.781609   
3        0.671756  0.235808      0.0         0.235808  0.408421  0.781609   
4        0.633588  0.235808      0.0         0.235808  0.416842  0.747126   
...           ...       ...      ...              ...       ...       ...   
552758   0.328244  0.000000      0.0         0.000000  0.618947  0.862069   
552759   0.206107  0.069869      0.0         0.069869  0.517895  0.873563   
552760   0.511450  0.000000      0.0         0.000000  0.536842  0.816092   
552761   0.526718  0.000000      0.0         0.000000  0.458947  0.885057   
552762   0.236641  0.000000      0.0         0.000000  0.408421  0.816092   

        pressure  hours_of_light  
0       0.612081        0.010909  
1       0.612081        0.010909  
2       0.612081        0.010909  
3       0.612081        0.010909  
4       0.616107        0.010909  
...          ...             ...  
552758  0.608054        0.895758  
552759  0.563758        0.198788  
552760  0.664430        0.380606  
552761  0.777181        0.144242  
552762  0.652349        0.052121  

[552763 rows x 30 columns]

In [7]:
# split training data into training and testing
from sklearn.model_selection import train_test_split

# Select columns to that are data
cols = [col for col in crime if col not in ['type']]

X = crime[cols]

# Select target data
y = crime['type']

X_train, X_test, y_train, y_test = train_test_split(X, y, random_state=100, test_size=0.3)
print(X_train.shape)

(386934, 29)


In [8]:
# Trying Random Forest Classifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.feature_selection import SelectFromModel

model_tree = RandomForestClassifier(random_state=100, n_estimators=50)
model_tree.fit(X_train, y_train)
print(model_tree.feature_importances_)
sel_model_tree = SelectFromModel(estimator=model_tree, prefit=True, threshold='mean')  
      # since we already fit the data, we specify prefit option here
      # Features whose importance is greater or equal to the threshold are kept while the others are discarded.
X_train_sfm_tree = sel_model_tree.transform(X_train)
print(sel_model_tree.get_support())

feature_importances = pd.DataFrame(model_tree.feature_importances_,
                                   index = X_train.columns,
                                    columns=['importance']).sort_values('importance', 
                                                                        ascending=False)
feature_importances

[0.03467108 0.01694779 0.01305226 0.02100286 0.01858355 0.30665725
 0.04089491 0.10233664 0.0373001  0.04078894 0.04359011 0.03834066
 0.01053071 0.01495017 0.01968477 0.03120609 0.00229717 0.00262002
 0.01106955 0.01802189 0.0216264  0.02962392 0.01218403 0.00137636
 0.01216313 0.0251277  0.02222148 0.02631551 0.02481491]
[ True False False False False  True  True  True  True  True  True  True
 False False False False False False False False False False False False
 False False False False False]


importance
minute             0.306657
hundred_block      0.102337
latitude           0.043590
Hour_Minute        0.040895
utm_y              0.040789
longitude          0.038341
utm_x              0.037300
datetime           0.034671
light_pole_100     0.031206
trees_100          0.029624
pressure           0.026316
temp_c             0.025128
hours_of_light     0.024815
humidity           0.022221
trees_25           0.021626
day                0.021003
light_pole_50      0.019685
hour               0.018584
signal_200         0.018022
year               0.016948
light_pole_25      0.014950
month              0.013052
rain_mm            0.012184
total_precip_mm    0.012163
signal_100         0.011070
light_pole_12_5    0.010531
signal_50          0.002620
signal_25          0.002297
snow_cm            0.001376

In [9]:
# Simple Neural Network

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import sklearn
from sklearn.neural_network import MLPClassifier
from sklearn.neural_network import MLPRegressor

# import needed modules
from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_squared_error
from math import sqrt
from sklearn.metrics import r2_score

In [10]:
# Try using the MLP Classifier
mlp = MLPClassifier(hidden_layer_sizes=(29, 29, 29), activation='relu', solver='adam', max_iter=300)
mlp.fit(X_train, y_train)

predict_train = mlp.predict(X_train)
predict_test = mlp.predict(X_test)

In [11]:
from sklearn.metrics import classification_report, confusion_matrix
print(confusion_matrix(y_train, predict_train))
print(classification_report(y_train, predict_train))

[[303715  10249]
 [ 26192  46778]]
              precision    recall  f1-score   support

           0       0.92      0.97      0.94    313964
           1       0.82      0.64      0.72     72970

    accuracy                           0.91    386934
   macro avg       0.87      0.80      0.83    386934
weighted avg       0.90      0.91      0.90    386934



In [12]:
print(confusion_matrix(y_test, predict_test))
print(classification_report(y_test, predict_test))

[[130116   4546]
 [ 11438  19729]]
              precision    recall  f1-score   support

           0       0.92      0.97      0.94    134662
           1       0.81      0.63      0.71     31167

    accuracy                           0.90    165829
   macro avg       0.87      0.80      0.83    165829
weighted avg       0.90      0.90      0.90    165829



In [13]:
# Try using the MLP Classifier
mlp = MLPClassifier(hidden_layer_sizes=(29, 29, 29), activation='relu', solver='adam', max_iter=200)
mlp.fit(X_train, y_train)

predict_train = mlp.predict(X_train)
predict_test = mlp.predict(X_test)

In [14]:
print(confusion_matrix(y_train, predict_train))
print(classification_report(y_train, predict_train))

[[305497   8467]
 [ 28807  44163]]
              precision    recall  f1-score   support

           0       0.91      0.97      0.94    313964
           1       0.84      0.61      0.70     72970

    accuracy                           0.90    386934
   macro avg       0.88      0.79      0.82    386934
weighted avg       0.90      0.90      0.90    386934



In [15]:
print(confusion_matrix(y_test, predict_test))
print(classification_report(y_test, predict_test))

[[130908   3754]
 [ 12488  18679]]
              precision    recall  f1-score   support

           0       0.91      0.97      0.94    134662
           1       0.83      0.60      0.70     31167

    accuracy                           0.90    165829
   macro avg       0.87      0.79      0.82    165829
weighted avg       0.90      0.90      0.90    165829



In [ ]:
############################# END HERE ###################################

In [16]:
# try a different split
# split training data into training and testing
from sklearn.model_selection import train_test_split

# Select columns to that are data
cols = [col for col in crime if col not in ['type']]

X = crime[cols]

# Select target data
y = crime['type']

X_train, X_test, y_train, y_test = train_test_split(X, y, random_state=100, test_size=0.3)
print(X_train.shape)

(386934, 29)


In [17]:
# Try using the MLP Classifier
mlp = MLPClassifier(hidden_layer_sizes=(29, 29, 29), activation='relu', solver='adam', max_iter=200)
mlp.fit(X_train, y_train)

predict_train = mlp.predict(X_train)
predict_test = mlp.predict(X_test)

In [18]:
print(confusion_matrix(y_train, predict_train))
print(classification_report(y_train, predict_train))

[[305084   8880]
 [ 28300  44670]]
              precision    recall  f1-score   support

           0       0.92      0.97      0.94    313964
           1       0.83      0.61      0.71     72970

    accuracy                           0.90    386934
   macro avg       0.87      0.79      0.82    386934
weighted avg       0.90      0.90      0.90    386934



In [19]:
print(confusion_matrix(y_test, predict_test))
print(classification_report(y_test, predict_test))

[[130738   3924]
 [ 12367  18800]]
              precision    recall  f1-score   support

           0       0.91      0.97      0.94    134662
           1       0.83      0.60      0.70     31167

    accuracy                           0.90    165829
   macro avg       0.87      0.79      0.82    165829
weighted avg       0.90      0.90      0.90    165829



In [20]:
# Trying Random Forest Classifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.feature_selection import SelectFromModel

model_tree = RandomForestClassifier(random_state=100, n_estimators=50)
model_tree.fit(X_train, y_train)
print(model_tree.feature_importances_)
sel_model_tree = SelectFromModel(estimator=model_tree, prefit=True, threshold='mean')  
      # since we already fit the data, we specify prefit option here
      # Features whose importance is greater or equal to the threshold are kept while the others are discarded.
X_train_sfm_tree = sel_model_tree.transform(X_train)
print(sel_model_tree.get_support())

feature_importances = pd.DataFrame(model_tree.feature_importances_,
                                   index = X_train.columns,
                                    columns=['importance']).sort_values('importance', 
                                                                        ascending=False)
feature_importances

[0.03467108 0.01694779 0.01305226 0.02100286 0.01858355 0.30665725
 0.04089491 0.10233664 0.0373001  0.04078894 0.04359011 0.03834066
 0.01053071 0.01495017 0.01968477 0.03120609 0.00229717 0.00262002
 0.01106955 0.01802189 0.0216264  0.02962392 0.01218403 0.00137636
 0.01216313 0.0251277  0.02222148 0.02631551 0.02481491]
[ True False False False False  True  True  True  True  True  True  True
 False False False False False False False False False False False False
 False False False False False]


importance
minute             0.306657
hundred_block      0.102337
latitude           0.043590
Hour_Minute        0.040895
utm_y              0.040789
longitude          0.038341
utm_x              0.037300
datetime           0.034671
light_pole_100     0.031206
trees_100          0.029624
pressure           0.026316
temp_c             0.025128
hours_of_light     0.024815
humidity           0.022221
trees_25           0.021626
day                0.021003
light_pole_50      0.019685
hour               0.018584
signal_200         0.018022
year               0.016948
light_pole_25      0.014950
month              0.013052
rain_mm            0.012184
total_precip_mm    0.012163
signal_100         0.011070
light_pole_12_5    0.010531
signal_50          0.002620
signal_25          0.002297
snow_cm            0.001376