In [1]:
# NOTE: This does NOT have points close to real ones removed!

import pandas as pd
import numpy as np
%matplotlib inline
import matplotlib.pyplot as plt
import sklearn

crime = pd.read_csv('E:/Vancouver Crime Final/Synthetic Data/both_bne_100k_combined.csv')

crime.head(20)

type             datetime  year  month  day  \
0   Break and Enter Residential/Other  2003-01-01 00:00:00  2003      1    1   
1          Break and Enter Commercial  2003-01-01 00:00:00  2003      1    1   
2   Break and Enter Residential/Other  2003-01-01 00:00:00  2003      1    1   
3   Break and Enter Residential/Other  2003-01-01 00:00:00  2003      1    1   
4   Break and Enter Residential/Other  2003-01-01 01:01:00  2003      1    1   
5   Break and Enter Residential/Other  2003-01-01 04:04:00  2003      1    1   
6   Break and Enter Residential/Other  2003-01-01 04:04:00  2003      1    1   
7          Break and Enter Commercial  2003-01-01 06:06:00  2003      1    1   
8          Break and Enter Commercial  2003-01-01 07:07:00  2003      1    1   
9          Break and Enter Commercial  2003-01-01 07:07:00  2003      1    1   
10  Break and Enter Residential/Other  2003-01-01 07:07:00  2003      1    1   
11  Break and Enter Residential/Other  2003-01-01 11:11:00  2003      1    1   
12         Break and Enter Commercial  2003-01-01 11:11:00  2003      1    1   
13  Break and Enter Residential/Other  2003-01-01 11:11:00  2003      1    1   
14         Break and Enter Commercial  2003-01-01 12:12:00  2003      1    1   
15         Break and Enter Commercial  2003-01-01 12:12:00  2003      1    1   
16  Break and Enter Residential/Other  2003-01-01 12:12:00  2003      1    1   
17         Break and Enter Commercial  2003-01-01 12:12:00  2003      1    1   
18  Break and Enter Residential/Other  2003-01-01 15:15:00  2003      1    1   
19  Break and Enter Residential/Other  2003-01-01 16:16:00  2003      1    1   

    hour  minute  Hour_Minute      hundred_block      utm_x  ...  signal_200  \
0      0       0     0.000000     9XX W 15TH AVE  490791.12  ...           2   
1      0       0     0.000000   64XX VICTORIA DR  495220.95  ...           2   
2      0       1     0.016667    34XX W 42ND AVE  486837.11  ...           3   
3      0      20     0.333333     19XX PARKER ST  495279.46  ...           1   
4      1      46     1.766667       45XX MAIN ST  492627.84  ...           2   
5      4       0     4.000000   25XX GRAVELEY ST  496100.23  ...           0   
6      4      30     4.500000  15XX SE MARINE DR  494572.37  ...           1   
7      6       0     6.000000   5XX W GEORGIA ST  491507.39  ...          10   
8      7      13     7.216667    18XX W 57TH AVE  489132.03  ...           0   
9      7      13     7.216667     45XX FRASER ST  493431.80  ...           2   
10     7      25     7.416667      7XX SEMLIN DR  495363.36  ...           1   
11    11       0    11.000000    22XX TRIUMPH ST  495716.74  ...           4   
12    11       0    11.000000     35XX FRASER ST  493447.88  ...           1   
13    11      45    11.750000    38XX HEATHER ST  491248.44  ...           1   
14    12       0    12.000000      5XX BEATTY ST  492024.04  ...          10   
15    12       0    12.000000   7XX PACIFIC BLVD  492005.87  ...           2   
16    12       0    12.000000       41XX VINE ST  488613.83  ...           0   
17    12      49    12.816667    28XX BENTALL ST  497676.19  ...           3   
18    15      30    15.500000  30XX E KENT N AVE  496782.22  ...           1   
19    16      30    16.500000    28XX E 22ND AVE  496722.62  ...           1   

    trees_25  trees_100  rain_mm  snow_cm  total_precip_mm  temp_c  humidity  \
0          0         32     21.6      0.0             21.6     5.8      81.0   
1          5         40     21.6      0.0             21.6     5.8      81.0   
2          6         38     21.6      0.0             21.6     5.8      81.0   
3          8         88     21.6      0.0             21.6     5.8      81.0   
4          8         83     21.6      0.0             21.6     6.2      78.0   
5          7         73     21.6      0.0             21.6     5.5      88.0   
6          0         41     21.6      0.0             21.6     5.5      88.0   
7          2         27     21.

In [2]:
# Set Break and ENters to 1 and everything else to 0

crime = crime.replace(['NONE'], 0)

crime = crime.replace(['Break and Enter Residential/Other', 'Break and Enter Commercial'], 1)
crime.head()

type             datetime  year  month  day  hour  minute  Hour_Minute  \
0     1  2003-01-01 00:00:00  2003      1    1     0       0     0.000000   
1     1  2003-01-01 00:00:00  2003      1    1     0       0     0.000000   
2     1  2003-01-01 00:00:00  2003      1    1     0       1     0.016667   
3     1  2003-01-01 00:00:00  2003      1    1     0      20     0.333333   
4     1  2003-01-01 01:01:00  2003      1    1     1      46     1.766667   

      hundred_block      utm_x  ...  signal_200  trees_25  trees_100  rain_mm  \
0    9XX W 15TH AVE  490791.12  ...           2         0         32     21.6   
1  64XX VICTORIA DR  495220.95  ...           2         5         40     21.6   
2   34XX W 42ND AVE  486837.11  ...           3         6         38     21.6   
3    19XX PARKER ST  495279.46  ...           1         8         88     21.6   
4      45XX MAIN ST  492627.84  ...           2         8         83     21.6   

   snow_cm  total_precip_mm  temp_c  humidity  pressure  hours_of_light  
0      0.0             21.6     5.8      81.0    101.70            9.53  
1      0.0             21.6     5.8      81.0    101.70            9.53  
2      0.0             21.6     5.8      81.0    101.70            9.53  
3      0.0             21.6     5.8      81.0    101.70            9.53  
4      0.0             21.6     6.2      78.0    101.73            9.53  

[5 rows x 30 columns]

In [3]:
crime

type             datetime  year  month  day  hour  minute  \
0          1  2003-01-01 00:00:00  2003      1    1     0       0   
1          1  2003-01-01 00:00:00  2003      1    1     0       0   
2          1  2003-01-01 00:00:00  2003      1    1     0       1   
3          1  2003-01-01 00:00:00  2003      1    1     0      20   
4          1  2003-01-01 01:01:00  2003      1    1     1      46   
...      ...                  ...   ...    ...  ...   ...     ...   
204154     0  2018-02-07 12:46:00  2018      2    7    12      46   
204155     0  2004-12-31 00:20:00  2004     12   31     0      20   
204156     0  2008-08-27 01:35:00  2008      8   27     1      35   
204157     0  2018-02-14 22:55:00  2018      2   14    22      55   
204158     0  2016-01-07 21:08:00  2016      1    7    21       8   

        Hour_Minute           hundred_block          utm_x  ...  signal_200  \
0          0.000000          9XX W 15TH AVE  490791.120000  ...           2   
1          0.000000        64XX VICTORIA DR  495220.950000  ...           2   
2          0.016667         34XX W 42ND AVE  486837.110000  ...           3   
3          0.333333          19XX PARKER ST  495279.460000  ...           1   
4          1.766667            45XX MAIN ST  492627.840000  ...           2   
...             ...                     ...            ...  ...         ...   
204154    12.766667          9XX E 27TH AVE  493764.962443  ...           0   
204155     0.333333   ODLUM DR / WILLIAM ST  494477.870000  ...           1   
204156     1.583333           9XX E 62ND AV  493674.480000  ...           0   
204157    22.916667  E 29TH AVE / QUEBEC ST  492535.810000  ...           3   
204158    21.133333      61XX SOUTHLANDS PL  487174.014115  ...           2   

        trees_25  trees_100  rain_mm  snow_cm  total_precip_mm  temp_c  \
0              0         32     21.6      0.0             21.6     5.8   
1              5         40     21.6      0.0             21.6     5.8   
2              6         38     21.6      0.0             21.6     5.8   
3              8         88     21.6      0.0             21.6     5.8   
4              8         83     21.6      0.0             21.6     6.2   
...          ...        ...      ...      ...              ...     ...   
204154        11         64      2.0      0.0              2.0     8.7   
204155         7         46      2.0      0.0              2.0     3.5   
204156         7         74      4.2      0.0              4.2    11.3   
204157        10         67      6.2      0.0              6.2     1.9   
204158         0          4      0.0      0.0              0.0     4.3   

        humidity  pressure  hours_of_light  
0           81.0    101.70            9.53  
1           81.0    101.70            9.53  
2           81.0    101.70            9.53  
3           81.0    101.70            9.53  
4           78.0    101.73            9.53  
...          ...       ...             ...  
204154      95.0    102.79           10.87  
204155      92.0    100.42            9.52  
204156      92.0    101.00           14.82  
204157      93.0    102.27           11.24  
204158      93.0    101.62            9.64  

[204159 rows x 30 columns]

In [4]:
### Begin Processing the Data


# Import Pre-processing module
from sklearn import preprocessing

# Create Label Encoder
le = preprocessing.LabelEncoder()

# Convert the string columns to numeric
# .astype(str) to ensude they are read as strings and not as mixed types
crime['datetime'] = le.fit_transform(crime['datetime'].astype(str))
crime['hundred_block'] = le.fit_transform(crime['hundred_block'].astype(str))


# Display the results
crime

type  datetime  year  month  day  hour  minute  Hour_Minute  \
0          1         0  2003      1    1     0       0     0.000000   
1          1         0  2003      1    1     0       0     0.000000   
2          1         0  2003      1    1     0       1     0.016667   
3          1         0  2003      1    1     0      20     0.333333   
4          1         2  2003      1    1     1      46     1.766667   
...      ...       ...   ...    ...  ...   ...     ...          ...   
204154     0    154654  2018      2    7    12      46    12.766667   
204155     0     23216  2004     12   31     0      20     0.333333   
204156     0     62956  2008      8   27     1      35     1.583333   
204157     0    154860  2018      2   14    22      55    22.916667   
204158     0    134531  2016      1    7    21       8    21.133333   

        hundred_block          utm_x  ...  signal_200  trees_25  trees_100  \
0               14750  490791.120000  ...           2         0         32   
1               11810  495220.950000  ...           2         5         40   
2                7246  486837.110000  ...           3         6         38   
3                2674  495279.460000  ...           1         8         88   
4                9153  492627.840000  ...           2         8         83   
...               ...            ...  ...         ...       ...        ...   
204154          14643  493764.962443  ...           0        11         64   
204155          19639  494477.870000  ...           1         7         46   
204156          14669  493674.480000  ...           0         7         74   
204157          16931  492535.810000  ...           3        10         67   
204158          11549  487174.014115  ...           2         0          4   

        rain_mm  snow_cm  total_precip_mm  temp_c  humidity  pressure  \
0          21.6      0.0             21.6     5.8      81.0    101.70   
1          21.6      0.0             21.6     5.8      81.0    101.70   
2          21.6      0.0             21.6     5.8      81.0    101.70   
3          21.6      0.0             21.6     5.8      81.0    101.70   
4          21.6      0.0             21.6     6.2      78.0    101.73   
...         ...      ...              ...     ...       ...       ...   
204154      2.0      0.0              2.0     8.7      95.0    102.79   
204155      2.0      0.0              2.0     3.5      92.0    100.42   
204156      4.2      0.0              4.2    11.3      92.0    101.00   
204157      6.2      0.0              6.2     1.9      93.0    102.27   
204158      0.0      0.0              0.0     4.3      93.0    101.62   

        hours_of_light  
0                 9.53  
1                 9.53  
2                 9.53  
3                 9.53  
4                 9.53  
...                ...  
204154           10.87  
204155            9.52  
204156           14.82  
204157           11.24  
204158            9.64  

[204159 rows x 30 columns]

In [5]:
# Scale the Data

columns = [col for col in crime if col not in ['type']]


# Properly scale the reduced set of features
features = crime[columns]

from sklearn.preprocessing import MinMaxScaler
scaler = preprocessing.MinMaxScaler()

print(scaler.fit(features))

MinMaxScaler(copy=True, feature_range=(0, 1))


In [6]:
# Properly scale the features

columns = [col for col in crime if col not in ['type']]

# Properly scale the reduced set of features
features = crime[columns]


scaler = MinMaxScaler().fit(features.values) # scaler = MinMaxScaler().fit(features.values)
features = scaler.transform(features.values) # features = scaler.transform(features.values)
crime[columns] = features
crime

type  datetime    year     month       day      hour    minute  \
0          1  0.000000  0.0000  0.000000  0.000000  0.000000  0.000000   
1          1  0.000000  0.0000  0.000000  0.000000  0.000000  0.000000   
2          1  0.000000  0.0000  0.000000  0.000000  0.000000  0.016949   
3          1  0.000000  0.0000  0.000000  0.000000  0.000000  0.338983   
4          1  0.000012  0.0000  0.000000  0.000000  0.043478  0.779661   
...      ...       ...     ...       ...       ...       ...       ...   
204154     0  0.914447  0.9375  0.090909  0.200000  0.521739  0.779661   
204155     0  0.137273  0.0625  1.000000  1.000000  0.000000  0.338983   
204156     0  0.372250  0.3125  0.636364  0.866667  0.043478  0.593220   
204157     0  0.915665  0.9375  0.090909  0.433333  0.956522  0.932203   
204158     0  0.795462  0.8125  0.000000  0.200000  0.913043  0.135593   

        Hour_Minute  hundred_block     utm_x  ...  signal_200  trees_25  \
0          0.000000       0.674934  0.485368  ...    0.142857   0.00000   
1          0.000000       0.540405  0.788787  ...    0.142857   0.15625   
2          0.000695       0.331564  0.214540  ...    0.214286   0.18750   
3          0.013899       0.122357  0.792795  ...    0.071429   0.25000   
4          0.073662       0.418825  0.611173  ...    0.142857   0.25000   
...             ...            ...       ...  ...         ...       ...   
204154     0.532314       0.670038  0.689060  ...    0.000000   0.34375   
204155     0.013899       0.898646  0.737890  ...    0.071429   0.21875   
204156     0.066018       0.671227  0.682862  ...    0.000000   0.21875   
204157     0.955525       0.774732  0.604870  ...    0.214286   0.31250   
204158     0.881167       0.528462  0.237616  ...    0.142857   0.00000   

        trees_100   rain_mm  snow_cm  total_precip_mm    temp_c  humidity  \
0        0.244275  0.235808      0.0         0.235808  0.408421  0.781609   
1        0.305344  0.235808      0.0         0.235808  0.408421  0.781609   
2        0.290076  0.235808      0.0         0.235808  0.408421  0.781609   
3        0.671756  0.235808      0.0         0.235808  0.408421  0.781609   
4        0.633588  0.235808      0.0         0.235808  0.416842  0.747126   
...           ...       ...      ...              ...       ...       ...   
204154   0.488550  0.021834      0.0         0.021834  0.469474  0.942529   
204155   0.351145  0.021834      0.0         0.021834  0.360000  0.908046   
204156   0.564885  0.045852      0.0         0.045852  0.524211  0.908046   
204157   0.511450  0.067686      0.0         0.067686  0.326316  0.919540   
204158   0.030534  0.000000      0.0         0.000000  0.376842  0.919540   

        pressure  hours_of_light  
0       0.609459        0.010909  
1       0.609459        0.010909  
2       0.609459        0.010909  
3       0.609459        0.010909  
4       0.613514        0.010909  
...          ...             ...  
204154  0.756757        0.173333  
204155  0.436486        0.009697  
204156  0.514865        0.652121  
204157  0.686486        0.218182  
204158  0.598649        0.024242  

[204159 rows x 30 columns]

In [7]:
# split training data into training and testing
from sklearn.model_selection import train_test_split

# Select columns to that are data
cols = [col for col in crime if col not in ['type']]

X = crime[cols]

# Select target data
y = crime['type']

X_train, X_test, y_train, y_test = train_test_split(X, y, random_state=100, test_size=0.3)
print(X_train.shape)

(142911, 29)


In [8]:
# Trying Random Forest Classifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.feature_selection import SelectFromModel

model_tree = RandomForestClassifier(random_state=100, n_estimators=50)
model_tree.fit(X_train, y_train)
print(model_tree.feature_importances_)
sel_model_tree = SelectFromModel(estimator=model_tree, prefit=True, threshold='mean')  
      # since we already fit the data, we specify prefit option here
      # Features whose importance is greater or equal to the threshold are kept while the others are discarded.
X_train_sfm_tree = sel_model_tree.transform(X_train)
print(sel_model_tree.get_support())

feature_importances = pd.DataFrame(model_tree.feature_importances_,
                                   index = X_train.columns,
                                    columns=['importance']).sort_values('importance', 
                                                                        ascending=False)
feature_importances

[0.0342665  0.01870516 0.0136869  0.02167436 0.02033142 0.24144447
 0.03825361 0.17503835 0.03579717 0.04294827 0.03852351 0.03635912
 0.01074901 0.01510868 0.01981361 0.0309436  0.00216248 0.00258578
 0.00927145 0.01761118 0.0197828  0.02925346 0.01225585 0.00107624
 0.01257095 0.02568216 0.02261085 0.02603548 0.02545756]
[False False False False False  True  True  True  True  True  True  True
 False False False False False False False False False False False False
 False False False False False]


importance
minute             0.241444
hundred_block      0.175038
utm_y              0.042948
latitude           0.038524
Hour_Minute        0.038254
longitude          0.036359
utm_x              0.035797
datetime           0.034267
light_pole_100     0.030944
trees_100          0.029253
pressure           0.026035
temp_c             0.025682
hours_of_light     0.025458
humidity           0.022611
day                0.021674
hour               0.020331
light_pole_50      0.019814
trees_25           0.019783
year               0.018705
signal_200         0.017611
light_pole_25      0.015109
month              0.013687
total_precip_mm    0.012571
rain_mm            0.012256
light_pole_12_5    0.010749
signal_100         0.009271
signal_50          0.002586
signal_25          0.002162
snow_cm            0.001076

In [9]:
# Simple Neural Network

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import sklearn
from sklearn.neural_network import MLPClassifier
from sklearn.neural_network import MLPRegressor

# import needed modules
from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_squared_error
from math import sqrt
from sklearn.metrics import r2_score

In [10]:
# Try using the MLP Classifier
mlp = MLPClassifier(hidden_layer_sizes=(29, 29, 29), activation='relu', solver='adam', max_iter=300)
mlp.fit(X_train, y_train)

predict_train = mlp.predict(X_train)
predict_test = mlp.predict(X_test)

In [11]:
from sklearn.metrics import classification_report, confusion_matrix
print(confusion_matrix(y_train, predict_train))
print(classification_report(y_train, predict_train))

[[59273 10859]
 [15728 57051]]
              precision    recall  f1-score   support

           0       0.79      0.85      0.82     70132
           1       0.84      0.78      0.81     72779

    accuracy                           0.81    142911
   macro avg       0.82      0.81      0.81    142911
weighted avg       0.82      0.81      0.81    142911



In [12]:
print(confusion_matrix(y_test, predict_test))
print(classification_report(y_test, predict_test))

[[25153  4737]
 [ 6975 24383]]
              precision    recall  f1-score   support

           0       0.78      0.84      0.81     29890
           1       0.84      0.78      0.81     31358

    accuracy                           0.81     61248
   macro avg       0.81      0.81      0.81     61248
weighted avg       0.81      0.81      0.81     61248



In [13]:
# Try using the MLP Classifier
mlp = MLPClassifier(hidden_layer_sizes=(29, 29, 29), activation='relu', solver='adam', max_iter=3000)
mlp.fit(X_train, y_train)

predict_train = mlp.predict(X_train)
predict_test = mlp.predict(X_test)

In [14]:
print(confusion_matrix(y_train, predict_train))
print(classification_report(y_train, predict_train))

[[62392  7740]
 [18345 54434]]
              precision    recall  f1-score   support

           0       0.77      0.89      0.83     70132
           1       0.88      0.75      0.81     72779

    accuracy                           0.82    142911
   macro avg       0.82      0.82      0.82    142911
weighted avg       0.83      0.82      0.82    142911



In [15]:
print(confusion_matrix(y_test, predict_test))
print(classification_report(y_test, predict_test))

[[26498  3392]
 [ 8080 23278]]
              precision    recall  f1-score   support

           0       0.77      0.89      0.82     29890
           1       0.87      0.74      0.80     31358

    accuracy                           0.81     61248
   macro avg       0.82      0.81      0.81     61248
weighted avg       0.82      0.81      0.81     61248



In [16]:
############################# END HERE ###################################

In [18]:
# Try using the MLP Classifier
mlp = MLPClassifier(hidden_layer_sizes=(29, 29, 29, 29, 29, 29, 29), activation='relu', solver='adam', max_iter=300)
mlp.fit(X_train, y_train)

predict_train = mlp.predict(X_train)
predict_test = mlp.predict(X_test)

In [19]:
print(confusion_matrix(y_train, predict_train))
print(classification_report(y_train, predict_train))

[[60555  9577]
 [16170 56609]]
              precision    recall  f1-score   support

           0       0.79      0.86      0.82     70132
           1       0.86      0.78      0.81     72779

    accuracy                           0.82    142911
   macro avg       0.82      0.82      0.82    142911
weighted avg       0.82      0.82      0.82    142911



In [20]:
print(confusion_matrix(y_test, predict_test))
print(classification_report(y_test, predict_test))

[[25685  4205]
 [ 7196 24162]]
              precision    recall  f1-score   support

           0       0.78      0.86      0.82     29890
           1       0.85      0.77      0.81     31358

    accuracy                           0.81     61248
   macro avg       0.82      0.81      0.81     61248
weighted avg       0.82      0.81      0.81     61248



In [17]:
feature_importances

importance
minute             0.241444
hundred_block      0.175038
utm_y              0.042948
latitude           0.038524
Hour_Minute        0.038254
longitude          0.036359
utm_x              0.035797
datetime           0.034267
light_pole_100     0.030944
trees_100          0.029253
pressure           0.026035
temp_c             0.025682
hours_of_light     0.025458
humidity           0.022611
day                0.021674
hour               0.020331
light_pole_50      0.019814
trees_25           0.019783
year               0.018705
signal_200         0.017611
light_pole_25      0.015109
month              0.013687
total_precip_mm    0.012571
rain_mm            0.012256
light_pole_12_5    0.010749
signal_100         0.009271
signal_50          0.002586
signal_25          0.002162
snow_cm            0.001076

In [21]:
# Cut down features

# split training data into training and testing
from sklearn.model_selection import train_test_split

# Select columns to that are data
cols = [col for col in crime if col not in ['type', 'minute', 'hour', 'latitude', 'longitude', 'datetime']]

X = crime[cols]

# Select target data
y = crime['type']

X_train, X_test, y_train, y_test = train_test_split(X, y, random_state=100, test_size=0.3)
print(X_train.shape)

(142911, 24)


In [22]:
X_train

year     month       day  Hour_Minute  hundred_block     utm_x  \
111865  0.5625  0.090909  0.200000     0.099375       0.738446  0.362105   
126893  0.6250  0.181818  0.366667     0.564281       0.521735  0.783722   
52976   0.3750  0.454545  0.033333     0.307853       0.482017  0.535677   
42606   0.2500  0.818182  0.500000     0.542043       0.572435  0.664330   
79077   0.6875  0.636364  0.633333     0.917304       0.060858  0.431690   
...        ...       ...       ...          ...            ...       ...   
194442  0.8125  0.909091  0.600000     0.474635       0.279262  0.586941   
65615   0.5000  1.000000  0.266667     0.458652       0.483939  0.521147   
77655   0.6875  0.363636  0.333333     0.834607       0.433651  0.467926   
56088   0.4375  0.000000  0.133333     0.625434       0.459595  0.711052   
38408   0.2500  0.181818  0.766667     0.604587       0.574357  0.520888   

           utm_y  light_pole_12_5  light_pole_25  light_pole_50  ...  \
111865  0.654789         0.000000       0.029851       0.038462  ...   
126893  0.249916         0.000000       0.014925       0.064103  ...   
52976   0.294698         0.035714       0.014925       0.128205  ...   
42606   0.688518         0.035714       0.014925       0.076923  ...   
79077   0.605003         0.071429       0.044776       0.410256  ...   
...          ...              ...            ...            ...  ...   
194442  0.749816         0.000000       0.000000       0.000000  ...   
65615   0.293253         0.035714       0.044776       0.102564  ...   
77655   0.368430         0.000000       0.029851       0.038462  ...   
56088   0.333695         0.000000       0.014925       0.076923  ...   
38408   0.589036         0.035714       0.044776       0.128205  ...   

        signal_200  trees_25  trees_100   rain_mm  snow_cm  total_precip_mm  \
111865    0.000000   0.00000   0.091603  0.000000      0.0         0.000000   
126893    0.142857   0.09375   0.358779  0.192140      0.0         0.192140   
52976     0.071429   0.25000   0.335878  0.000000      0.0         0.000000   
42606     0.214286   0.18750   0.641221  0.072052      0.0         0.072052   
79077     0.214286   0.00000   0.099237  0.000000      0.0         0.000000   
...            ...       ...        ...       ...      ...              ...   
194442    0.000000   0.00000   0.000000  0.021834      0.0         0.021834   
65615     0.071429   0.18750   0.190840  0.000000      0.0         0.000000   
77655     0.071429   0.31250   0.496183  0.000000      0.0         0.000000   
56088     0.000000   0.28125   0.374046  0.010917      0.0         0.010917   
38408     0.142857   0.37500   0.312977  0.172489      0.0         0.172489   

          temp_c  humidity  pressure  hours_of_light  
111865  0.277895  0.908046  0.562162        0.169697  
126893  0.511579  0.724138  0.593243        0.402424  
52976   0.673684  0.505747  0.586486        0.963636  
42606   0.505263  0.735632  0.363514        0.290909  
79077   0.658947  0.701149  0.572973        0.707879  
...          ...       ...       ...             ...  
194442  0.494737  0.724138  0.459459        0.081212  
65615   0.353684  0.816092  0.741892        0.013333  
77655   0.566316  0.724138  0.714865        0.844848  
56088   0.454737  0.873563  0.658108        0.019394  
38408   0.501053  0.931034  0.467568        0.488485  

[142911 rows x 24 columns]

In [23]:
y_train

111865    0
126893    0
52976     1
42606     1
79077     1
         ..
194442    0
65615     1
77655     1
56088     1
38408     1
Name: type, Length: 142911, dtype: int64

In [24]:
# Trying Random Forest Classifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.feature_selection import SelectFromModel

model_tree = RandomForestClassifier(random_state=100, n_estimators=50)
model_tree.fit(X_train, y_train)
print(model_tree.feature_importances_)
sel_model_tree = SelectFromModel(estimator=model_tree, prefit=True, threshold='mean')  
      # since we already fit the data, we specify prefit option here
      # Features whose importance is greater or equal to the threshold are kept while the others are discarded.
X_train_sfm_tree = sel_model_tree.transform(X_train)
print(sel_model_tree.get_support())

feature_importances = pd.DataFrame(model_tree.feature_importances_,
                                   index = X_train.columns,
                                    columns=['importance']).sort_values('importance', 
                                                                        ascending=False)
feature_importances

[0.04066394 0.02220201 0.03627619 0.07120974 0.22378582 0.07008909
 0.07584535 0.01626955 0.02368539 0.03278873 0.04821255 0.00323157
 0.00374665 0.01455227 0.02447086 0.03174823 0.0502351  0.02017242
 0.00161684 0.0205287  0.04322148 0.03878863 0.04407668 0.04258222]
[False False False  True  True  True  True False False False  True False
 False False False False  True False False False  True False  True  True]


importance
hundred_block      0.223786
utm_y              0.075845
Hour_Minute        0.071210
utm_x              0.070089
trees_100          0.050235
light_pole_100     0.048213
pressure           0.044077
temp_c             0.043221
hours_of_light     0.042582
year               0.040664
humidity           0.038789
day                0.036276
light_pole_50      0.032789
trees_25           0.031748
signal_200         0.024471
light_pole_25      0.023685
month              0.022202
total_precip_mm    0.020529
rain_mm            0.020172
light_pole_12_5    0.016270
signal_100         0.014552
signal_50          0.003747
signal_25          0.003232
snow_cm            0.001617

In [25]:
# Try using the MLP Classifier
mlp = MLPClassifier(hidden_layer_sizes=(24, 24, 24), activation='relu', solver='adam', max_iter=300)
mlp.fit(X_train, y_train)

predict_train = mlp.predict(X_train)
predict_test = mlp.predict(X_test)

In [26]:
print(confusion_matrix(y_train, predict_train))
print(classification_report(y_train, predict_train))

[[40318 29814]
 [ 9702 63077]]
              precision    recall  f1-score   support

           0       0.81      0.57      0.67     70132
           1       0.68      0.87      0.76     72779

    accuracy                           0.72    142911
   macro avg       0.74      0.72      0.72    142911
weighted avg       0.74      0.72      0.72    142911



In [27]:
print(confusion_matrix(y_test, predict_test))
print(classification_report(y_test, predict_test))

[[17094 12796]
 [ 4209 27149]]
              precision    recall  f1-score   support

           0       0.80      0.57      0.67     29890
           1       0.68      0.87      0.76     31358

    accuracy                           0.72     61248
   macro avg       0.74      0.72      0.71     61248
weighted avg       0.74      0.72      0.72     61248



In [28]:
# Try using the MLP Classifier
mlp = MLPClassifier(hidden_layer_sizes=(29, 29, 29, 29, 29, 29, 29), activation='relu', solver='adam', max_iter=300)
mlp.fit(X_train, y_train)

predict_train = mlp.predict(X_train)
predict_test = mlp.predict(X_test)

In [29]:
print(confusion_matrix(y_train, predict_train))
print(classification_report(y_train, predict_train))

[[47900 22232]
 [15252 57527]]
              precision    recall  f1-score   support

           0       0.76      0.68      0.72     70132
           1       0.72      0.79      0.75     72779

    accuracy                           0.74    142911
   macro avg       0.74      0.74      0.74    142911
weighted avg       0.74      0.74      0.74    142911



In [30]:
print(confusion_matrix(y_test, predict_test))
print(classification_report(y_test, predict_test))

[[20132  9758]
 [ 6810 24548]]
              precision    recall  f1-score   support

           0       0.75      0.67      0.71     29890
           1       0.72      0.78      0.75     31358

    accuracy                           0.73     61248
   macro avg       0.73      0.73      0.73     61248
weighted avg       0.73      0.73      0.73     61248



In [31]:
# Cut down features again

# split training data into training and testing
from sklearn.model_selection import train_test_split

# Select columns to that are data
cols = [col for col in crime if col not in ['type', 'minute', 'hour', 'latitude', 'longitude', 'datetime', 
                                            'snow_cm', 'rain_mm', 'signal_25', 'signal_50', 'signal_100', 
                                            'light_pole_12_5']]

X = crime[cols]

# Select target data
y = crime['type']

X_train, X_test, y_train, y_test = train_test_split(X, y, random_state=100, test_size=0.3)
print(X_train.shape)

(142911, 18)


In [32]:
# Trying Random Forest Classifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.feature_selection import SelectFromModel

model_tree = RandomForestClassifier(random_state=100, n_estimators=50)
model_tree.fit(X_train, y_train)
print(model_tree.feature_importances_)
sel_model_tree = SelectFromModel(estimator=model_tree, prefit=True, threshold='mean')  
      # since we already fit the data, we specify prefit option here
      # Features whose importance is greater or equal to the threshold are kept while the others are discarded.
X_train_sfm_tree = sel_model_tree.transform(X_train)
print(sel_model_tree.get_support())

feature_importances = pd.DataFrame(model_tree.feature_importances_,
                                   index = X_train.columns,
                                    columns=['importance']).sort_values('importance', 
                                                                        ascending=False)
feature_importances

[0.04082745 0.02191413 0.03758793 0.07746749 0.24402915 0.07509162
 0.08179472 0.02522647 0.03384836 0.05207897 0.02479278 0.03179603
 0.05214564 0.02459645 0.04582034 0.04001637 0.0465254  0.04444069]
[False False False  True  True  True  True False False False False False
 False False False False False False]


importance
hundred_block      0.244029
utm_y              0.081795
Hour_Minute        0.077467
utm_x              0.075092
trees_100          0.052146
light_pole_100     0.052079
pressure           0.046525
temp_c             0.045820
hours_of_light     0.044441
year               0.040827
humidity           0.040016
day                0.037588
light_pole_50      0.033848
trees_25           0.031796
light_pole_25      0.025226
signal_200         0.024793
total_precip_mm    0.024596
month              0.021914

In [33]:
# Try using the MLP Classifier
mlp = MLPClassifier(hidden_layer_sizes=(18, 18, 18), activation='relu', solver='adam', max_iter=300)
mlp.fit(X_train, y_train)

predict_train = mlp.predict(X_train)
predict_test = mlp.predict(X_test)

In [34]:
print(confusion_matrix(y_train, predict_train))
print(classification_report(y_train, predict_train))

[[40535 29597]
 [11064 61715]]
              precision    recall  f1-score   support

           0       0.79      0.58      0.67     70132
           1       0.68      0.85      0.75     72779

    accuracy                           0.72    142911
   macro avg       0.73      0.71      0.71    142911
weighted avg       0.73      0.72      0.71    142911



In [35]:
print(confusion_matrix(y_test, predict_test))
print(classification_report(y_test, predict_test))

[[17247 12643]
 [ 4719 26639]]
              precision    recall  f1-score   support

           0       0.79      0.58      0.67     29890
           1       0.68      0.85      0.75     31358

    accuracy                           0.72     61248
   macro avg       0.73      0.71      0.71     61248
weighted avg       0.73      0.72      0.71     61248



In [36]:
# Try using the MLP Classifier
mlp = MLPClassifier(hidden_layer_sizes=(18, 18, 18, 18, 18, 18, 18), activation='relu', solver='adam', max_iter=300)
mlp.fit(X_train, y_train)

predict_train = mlp.predict(X_train)
predict_test = mlp.predict(X_test)

In [37]:
print(confusion_matrix(y_train, predict_train))
print(classification_report(y_train, predict_train))

[[40381 29751]
 [11143 61636]]
              precision    recall  f1-score   support

           0       0.78      0.58      0.66     70132
           1       0.67      0.85      0.75     72779

    accuracy                           0.71    142911
   macro avg       0.73      0.71      0.71    142911
weighted avg       0.73      0.71      0.71    142911



In [38]:
print(confusion_matrix(y_test, predict_test))
print(classification_report(y_test, predict_test))

[[17090 12800]
 [ 4825 26533]]
              precision    recall  f1-score   support

           0       0.78      0.57      0.66     29890
           1       0.67      0.85      0.75     31358

    accuracy                           0.71     61248
   macro avg       0.73      0.71      0.71     61248
weighted avg       0.73      0.71      0.71     61248

