In [3]:
# NOTE: This does NOT have points close to real ones removed!

import pandas as pd
import numpy as np
%matplotlib inline
import matplotlib.pyplot as plt
import sklearn

crime = pd.read_csv('E:/Vancouver Crime Final/Synthetic Data/residential_bne_100k_combined.csv')

crime.head(20)

type             datetime  year  month  day  \
0   Break and Enter Residential/Other  2003-01-01 00:00:00  2003      1    1   
1   Break and Enter Residential/Other  2003-01-01 00:00:00  2003      1    1   
2   Break and Enter Residential/Other  2003-01-01 00:00:00  2003      1    1   
3   Break and Enter Residential/Other  2003-01-01 01:01:00  2003      1    1   
4   Break and Enter Residential/Other  2003-01-01 04:04:00  2003      1    1   
5   Break and Enter Residential/Other  2003-01-01 04:04:00  2003      1    1   
6   Break and Enter Residential/Other  2003-01-01 07:07:00  2003      1    1   
7   Break and Enter Residential/Other  2003-01-01 11:11:00  2003      1    1   
8   Break and Enter Residential/Other  2003-01-01 11:11:00  2003      1    1   
9   Break and Enter Residential/Other  2003-01-01 12:12:00  2003      1    1   
10  Break and Enter Residential/Other  2003-01-01 15:15:00  2003      1    1   
11  Break and Enter Residential/Other  2003-01-01 16:16:00  2003      1    1   
12  Break and Enter Residential/Other  2003-01-01 17:17:00  2003      1    1   
13  Break and Enter Residential/Other  2003-01-01 17:17:00  2003      1    1   
14  Break and Enter Residential/Other  2003-01-01 17:17:00  2003      1    1   
15  Break and Enter Residential/Other  2003-01-01 17:17:00  2003      1    1   
16  Break and Enter Residential/Other  2003-01-01 18:18:00  2003      1    1   
17  Break and Enter Residential/Other  2003-01-01 19:19:00  2003      1    1   
18  Break and Enter Residential/Other  2003-01-01 19:19:00  2003      1    1   
19  Break and Enter Residential/Other  2003-01-01 20:20:00  2003      1    1   

    hour  minute  Hour_Minute      hundred_block      utm_x  ...  signal_200  \
0      0       0     0.000000     9XX W 15TH AVE  490791.12  ...           2   
1      0       1     0.016667    34XX W 42ND AVE  486837.11  ...           3   
2      0      20     0.333333     19XX PARKER ST  495279.46  ...           1   
3      1      46     1.766667       45XX MAIN ST  492627.84  ...           2   
4      4       0     4.000000   25XX GRAVELEY ST  496100.23  ...           0   
5      4      30     4.500000  15XX SE MARINE DR  494572.37  ...           1   
6      7      25     7.416667      7XX SEMLIN DR  495363.36  ...           1   
7     11       0    11.000000    22XX TRIUMPH ST  495716.74  ...           4   
8     11      45    11.750000    38XX HEATHER ST  491248.44  ...           1   
9     12       0    12.000000       41XX VINE ST  488613.83  ...           0   
10    15      30    15.500000  30XX E KENT N AVE  496782.22  ...           1   
11    16      30    16.500000    28XX E 22ND AVE  496722.62  ...           1   
12    17       0    17.000000   16XX LAKEWOOD DR  495502.64  ...           2   
13    17       0    17.000000     39XX KNIGHT ST  494454.07  ...           3   
14    17       0    17.000000    14XX W 45TH AVE  489954.83  ...           1   
15    17       2    17.033333     5XX E 49TH AVE  493244.66  ...           2   
16    18      15    18.250000     9XX E 22ND AVE  493885.71  ...           0   
17    19       0    19.000000    17XX CYPRESS ST  489246.98  ...           1   
18    19       0    19.000000    17XX E 12TH AVE  495017.16  ...           4   
19    20       0    20.000000     15XX E 4TH AVE  494675.26  ...           0   

    trees_25  trees_100  rain_mm  snow_cm  total_precip_mm  temp_c  humidity  \
0          0         32     21.6      0.0             21.6     5.8      81.0   
1          6         38     21.6      0.0             21.6     5.8      81.0   
2          8         88     21.6      0.0             21.6     5.8      81.0   
3          8         83     21.6      0.0             21.6     6.2      78.0   
4          7         73     21.6      0.0             21.6     5.5      88.0   
5          0         41     21.6      0.0             21.6     5.5      88.0   
6          1         61     21.6      0.0             21.6     5.8      95.0   
7          6         67     21.

In [4]:
# Set Break and ENters to 1 and everything else to 0

crime = crime.replace(['NONE'], 0)

crime = crime.replace(['Break and Enter Residential/Other', 'Break and Enter Commercial'], 1)
crime.head()

type             datetime  year  month  day  hour  minute  Hour_Minute  \
0     1  2003-01-01 00:00:00  2003      1    1     0       0     0.000000   
1     1  2003-01-01 00:00:00  2003      1    1     0       1     0.016667   
2     1  2003-01-01 00:00:00  2003      1    1     0      20     0.333333   
3     1  2003-01-01 01:01:00  2003      1    1     1      46     1.766667   
4     1  2003-01-01 04:04:00  2003      1    1     4       0     4.000000   

      hundred_block      utm_x  ...  signal_200  trees_25  trees_100  rain_mm  \
0    9XX W 15TH AVE  490791.12  ...           2         0         32     21.6   
1   34XX W 42ND AVE  486837.11  ...           3         6         38     21.6   
2    19XX PARKER ST  495279.46  ...           1         8         88     21.6   
3      45XX MAIN ST  492627.84  ...           2         8         83     21.6   
4  25XX GRAVELEY ST  496100.23  ...           0         7         73     21.6   

   snow_cm  total_precip_mm  temp_c  humidity  pressure  hours_of_light  
0      0.0             21.6     5.8      81.0    101.70            9.53  
1      0.0             21.6     5.8      81.0    101.70            9.53  
2      0.0             21.6     5.8      81.0    101.70            9.53  
3      0.0             21.6     6.2      78.0    101.73            9.53  
4      0.0             21.6     5.5      88.0    101.70            9.53  

[5 rows x 30 columns]

In [5]:
crime

type             datetime  year  month  day  hour  minute  \
0          1  2003-01-01 00:00:00  2003      1    1     0       0   
1          1  2003-01-01 00:00:00  2003      1    1     0       1   
2          1  2003-01-01 00:00:00  2003      1    1     0      20   
3          1  2003-01-01 01:01:00  2003      1    1     1      46   
4          1  2003-01-01 04:04:00  2003      1    1     4       0   
...      ...                  ...   ...    ...  ...   ...     ...   
165797     0  2018-02-07 12:46:00  2018      2    7    12      46   
165798     0  2004-12-31 00:20:00  2004     12   31     0      20   
165799     0  2008-08-27 01:35:00  2008      8   27     1      35   
165800     0  2018-02-14 22:55:00  2018      2   14    22      55   
165801     0  2016-01-07 21:08:00  2016      1    7    21       8   

        Hour_Minute           hundred_block          utm_x  ...  signal_200  \
0          0.000000          9XX W 15TH AVE  490791.120000  ...           2   
1          0.016667         34XX W 42ND AVE  486837.110000  ...           3   
2          0.333333          19XX PARKER ST  495279.460000  ...           1   
3          1.766667            45XX MAIN ST  492627.840000  ...           2   
4          4.000000        25XX GRAVELEY ST  496100.230000  ...           0   
...             ...                     ...            ...  ...         ...   
165797    12.766667          9XX E 27TH AVE  493764.962443  ...           0   
165798     0.333333   ODLUM DR / WILLIAM ST  494477.870000  ...           1   
165799     1.583333           9XX E 62ND AV  493674.480000  ...           0   
165800    22.916667  E 29TH AVE / QUEBEC ST  492535.810000  ...           3   
165801    21.133333      61XX SOUTHLANDS PL  487174.014115  ...           2   

        trees_25  trees_100  rain_mm  snow_cm  total_precip_mm  temp_c  \
0              0         32     21.6      0.0             21.6     5.8   
1              6         38     21.6      0.0             21.6     5.8   
2              8         88     21.6      0.0             21.6     5.8   
3              8         83     21.6      0.0             21.6     6.2   
4              7         73     21.6      0.0             21.6     5.5   
...          ...        ...      ...      ...              ...     ...   
165797        11         64      2.0      0.0              2.0     8.7   
165798         7         46      2.0      0.0              2.0     3.5   
165799         7         74      4.2      0.0              4.2    11.3   
165800        10         67      6.2      0.0              6.2     1.9   
165801         0          4      0.0      0.0              0.0     4.3   

        humidity  pressure  hours_of_light  
0           81.0    101.70            9.53  
1           81.0    101.70            9.53  
2           81.0    101.70            9.53  
3           78.0    101.73            9.53  
4           88.0    101.70            9.53  
...          ...       ...             ...  
165797      95.0    102.79           10.87  
165798      92.0    100.42            9.52  
165799      92.0    101.00           14.82  
165800      93.0    102.27           11.24  
165801      93.0    101.62            9.64  

[165802 rows x 30 columns]

In [6]:
### Begin Processing the Data


# Import Pre-processing module
from sklearn import preprocessing

# Create Label Encoder
le = preprocessing.LabelEncoder()

# Convert the string columns to numeric
# .astype(str) to ensude they are read as strings and not as mixed types
crime['datetime'] = le.fit_transform(crime['datetime'].astype(str))
crime['hundred_block'] = le.fit_transform(crime['hundred_block'].astype(str))


# Display the results
crime

type  datetime  year  month  day  hour  minute  Hour_Minute  \
0          1         0  2003      1    1     0       0     0.000000   
1          1         0  2003      1    1     0       1     0.016667   
2          1         0  2003      1    1     0      20     0.333333   
3          1         2  2003      1    1     1      46     1.766667   
4          1         5  2003      1    1     4       0     4.000000   
...      ...       ...   ...    ...  ...   ...     ...          ...   
165797     0    135976  2018      2    7    12      46    12.766667   
165798     0     20668  2004     12   31     0      20     0.333333   
165799     0     55878  2008      8   27     1      35     1.583333   
165800     0    136145  2018      2   14    22      55    22.916667   
165801     0    118987  2016      1    7    21       8    21.133333   

        hundred_block          utm_x  ...  signal_200  trees_25  trees_100  \
0               14745  490791.120000  ...           2         0         32   
1                7242  486837.110000  ...           3         6         38   
2                2673  495279.460000  ...           1         8         88   
3                9149  492627.840000  ...           2         8         83   
4                4647  496100.230000  ...           0         7         73   
...               ...            ...  ...         ...       ...        ...   
165797          14638  493764.962443  ...           0        11         64   
165798          19632  494477.870000  ...           1         7         46   
165799          14664  493674.480000  ...           0         7         74   
165800          16925  492535.810000  ...           3        10         67   
165801          11545  487174.014115  ...           2         0          4   

        rain_mm  snow_cm  total_precip_mm  temp_c  humidity  pressure  \
0          21.6      0.0             21.6     5.8      81.0    101.70   
1          21.6      0.0             21.6     5.8      81.0    101.70   
2          21.6      0.0             21.6     5.8      81.0    101.70   
3          21.6      0.0             21.6     6.2      78.0    101.73   
4          21.6      0.0             21.6     5.5      88.0    101.70   
...         ...      ...              ...     ...       ...       ...   
165797      2.0      0.0              2.0     8.7      95.0    102.79   
165798      2.0      0.0              2.0     3.5      92.0    100.42   
165799      4.2      0.0              4.2    11.3      92.0    101.00   
165800      6.2      0.0              6.2     1.9      93.0    102.27   
165801      0.0      0.0              0.0     4.3      93.0    101.62   

        hours_of_light  
0                 9.53  
1                 9.53  
2                 9.53  
3                 9.53  
4                 9.53  
...                ...  
165797           10.87  
165798            9.52  
165799           14.82  
165800           11.24  
165801            9.64  

[165802 rows x 30 columns]

In [7]:
# Scale the Data

columns = [col for col in crime if col not in ['type']]


# Properly scale the reduced set of features
features = crime[columns]

from sklearn.preprocessing import MinMaxScaler
scaler = preprocessing.MinMaxScaler()

print(scaler.fit(features))

MinMaxScaler(copy=True, feature_range=(0, 1))


In [8]:
# Properly scale the features

columns = [col for col in crime if col not in ['type']]

# Properly scale the reduced set of features
features = crime[columns]


scaler = MinMaxScaler().fit(features.values) # scaler = MinMaxScaler().fit(features.values)
features = scaler.transform(features.values) # features = scaler.transform(features.values)
crime[columns] = features
crime

type  datetime    year     month       day      hour    minute  \
0          1  0.000000  0.0000  0.000000  0.000000  0.000000  0.000000   
1          1  0.000000  0.0000  0.000000  0.000000  0.000000  0.016949   
2          1  0.000000  0.0000  0.000000  0.000000  0.000000  0.338983   
3          1  0.000013  0.0000  0.000000  0.000000  0.043478  0.779661   
4          1  0.000034  0.0000  0.000000  0.000000  0.173913  0.000000   
...      ...       ...     ...       ...       ...       ...       ...   
165797     0  0.916997  0.9375  0.090909  0.200000  0.521739  0.779661   
165798     0  0.139381  0.0625  1.000000  1.000000  0.000000  0.338983   
165799     0  0.376831  0.3125  0.636364  0.866667  0.043478  0.593220   
165800     0  0.918137  0.9375  0.090909  0.433333  0.956522  0.932203   
165801     0  0.802426  0.8125  0.000000  0.200000  0.913043  0.135593   

        Hour_Minute  hundred_block     utm_x  ...  signal_200  trees_25  \
0          0.000000       0.674921  0.485368  ...    0.142857   0.00000   
1          0.000695       0.331487  0.214540  ...    0.214286   0.18750   
2          0.013899       0.122351  0.792795  ...    0.071429   0.25000   
3          0.073662       0.418776  0.611173  ...    0.142857   0.25000   
4          0.166782       0.212707  0.849013  ...    0.000000   0.21875   
...             ...            ...       ...  ...         ...       ...   
165797     0.532314       0.670023  0.689060  ...    0.000000   0.34375   
165798     0.013899       0.898613  0.737890  ...    0.071429   0.21875   
165799     0.066018       0.671213  0.682862  ...    0.000000   0.21875   
165800     0.955525       0.774706  0.604870  ...    0.214286   0.31250   
165801     0.881167       0.528448  0.237616  ...    0.142857   0.00000   

        trees_100   rain_mm  snow_cm  total_precip_mm    temp_c  humidity  \
0        0.244275  0.235808      0.0         0.235808  0.408421  0.781609   
1        0.290076  0.235808      0.0         0.235808  0.408421  0.781609   
2        0.671756  0.235808      0.0         0.235808  0.408421  0.781609   
3        0.633588  0.235808      0.0         0.235808  0.416842  0.747126   
4        0.557252  0.235808      0.0         0.235808  0.402105  0.862069   
...           ...       ...      ...              ...       ...       ...   
165797   0.488550  0.021834      0.0         0.021834  0.469474  0.942529   
165798   0.351145  0.021834      0.0         0.021834  0.360000  0.908046   
165799   0.564885  0.045852      0.0         0.045852  0.524211  0.908046   
165800   0.511450  0.067686      0.0         0.067686  0.326316  0.919540   
165801   0.030534  0.000000      0.0         0.000000  0.376842  0.919540   

        pressure  hours_of_light  
0       0.609459        0.010909  
1       0.609459        0.010909  
2       0.609459        0.010909  
3       0.613514        0.010909  
4       0.609459        0.010909  
...          ...             ...  
165797  0.756757        0.173333  
165798  0.436486        0.009697  
165799  0.514865        0.652121  
165800  0.686486        0.218182  
165801  0.598649        0.024242  

[165802 rows x 30 columns]

In [9]:
# split training data into training and testing
from sklearn.model_selection import train_test_split

# Select columns to that are data
cols = [col for col in crime if col not in ['type']]

X = crime[cols]

# Select target data
y = crime['type']

X_train, X_test, y_train, y_test = train_test_split(X, y, random_state=100, test_size=0.3)
print(X_train.shape)

(116061, 29)


In [10]:
# Trying Random Forest Classifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.feature_selection import SelectFromModel

model_tree = RandomForestClassifier(random_state=100, n_estimators=50)
model_tree.fit(X_train, y_train)
print(model_tree.feature_importances_)
sel_model_tree = SelectFromModel(estimator=model_tree, prefit=True, threshold='mean')  
      # since we already fit the data, we specify prefit option here
      # Features whose importance is greater or equal to the threshold are kept while the others are discarded.
X_train_sfm_tree = sel_model_tree.transform(X_train)
print(sel_model_tree.get_support())

feature_importances = pd.DataFrame(model_tree.feature_importances_,
                                   index = X_train.columns,
                                    columns=['importance']).sort_values('importance', 
                                                                        ascending=False)
feature_importances

[0.03981446 0.01976529 0.01323908 0.02134514 0.02286128 0.31009099
 0.04632278 0.1354348  0.03151758 0.03177608 0.03200584 0.03186441
 0.00940841 0.01444689 0.01856188 0.02444792 0.00328903 0.00206671
 0.00517576 0.0115454  0.02094099 0.02893148 0.01205475 0.00124038
 0.01236274 0.02529348 0.02269572 0.02617499 0.02532573]
[ True False False False False  True  True  True False False False False
 False False False False False False False False False False False False
 False False False False False]


importance
minute             0.310091
hundred_block      0.135435
Hour_Minute        0.046323
datetime           0.039814
latitude           0.032006
longitude          0.031864
utm_y              0.031776
utm_x              0.031518
trees_100          0.028931
pressure           0.026175
hours_of_light     0.025326
temp_c             0.025293
light_pole_100     0.024448
hour               0.022861
humidity           0.022696
day                0.021345
trees_25           0.020941
year               0.019765
light_pole_50      0.018562
light_pole_25      0.014447
month              0.013239
total_precip_mm    0.012363
rain_mm            0.012055
signal_200         0.011545
light_pole_12_5    0.009408
signal_100         0.005176
signal_25          0.003289
signal_50          0.002067
snow_cm            0.001240

In [11]:
# Simple Neural Network

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import sklearn
from sklearn.neural_network import MLPClassifier
from sklearn.neural_network import MLPRegressor

# import needed modules
from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_squared_error
from math import sqrt
from sklearn.metrics import r2_score

In [12]:
# Try using the MLP Classifier
mlp = MLPClassifier(hidden_layer_sizes=(29, 29, 29), activation='relu', solver='adam', max_iter=300)
mlp.fit(X_train, y_train)

predict_train = mlp.predict(X_train)
predict_test = mlp.predict(X_test)

In [13]:
from sklearn.metrics import classification_report, confusion_matrix
print(confusion_matrix(y_train, predict_train))
print(classification_report(y_train, predict_train))

[[67256  2826]
 [14897 31082]]
              precision    recall  f1-score   support

           0       0.82      0.96      0.88     70082
           1       0.92      0.68      0.78     45979

    accuracy                           0.85    116061
   macro avg       0.87      0.82      0.83    116061
weighted avg       0.86      0.85      0.84    116061



In [14]:
print(confusion_matrix(y_test, predict_test))
print(classification_report(y_test, predict_test))

[[28685  1255]
 [ 6516 13285]]
              precision    recall  f1-score   support

           0       0.81      0.96      0.88     29940
           1       0.91      0.67      0.77     19801

    accuracy                           0.84     49741
   macro avg       0.86      0.81      0.83     49741
weighted avg       0.85      0.84      0.84     49741



In [15]:
# Try using the MLP Classifier
mlp = MLPClassifier(hidden_layer_sizes=(29, 29, 29), activation='relu', solver='adam', max_iter=3000)
mlp.fit(X_train, y_train)

predict_train = mlp.predict(X_train)
predict_test = mlp.predict(X_test)

In [16]:
print(confusion_matrix(y_train, predict_train))
print(classification_report(y_train, predict_train))

[[64780  5302]
 [13328 32651]]
              precision    recall  f1-score   support

           0       0.83      0.92      0.87     70082
           1       0.86      0.71      0.78     45979

    accuracy                           0.84    116061
   macro avg       0.84      0.82      0.83    116061
weighted avg       0.84      0.84      0.84    116061



In [17]:
print(confusion_matrix(y_test, predict_test))
print(classification_report(y_test, predict_test))

[[27640  2300]
 [ 5985 13816]]
              precision    recall  f1-score   support

           0       0.82      0.92      0.87     29940
           1       0.86      0.70      0.77     19801

    accuracy                           0.83     49741
   macro avg       0.84      0.81      0.82     49741
weighted avg       0.84      0.83      0.83     49741



In [18]:
############################# END HERE ###################################

In [19]:
# Try using the MLP Classifier
mlp = MLPClassifier(hidden_layer_sizes=(29, 29, 29, 29, 29, 29, 29), activation='relu', solver='adam', max_iter=200)
mlp.fit(X_train, y_train)

predict_train = mlp.predict(X_train)
predict_test = mlp.predict(X_test)

In [20]:
print(confusion_matrix(y_train, predict_train))
print(classification_report(y_train, predict_train))

[[66887  3195]
 [14597 31382]]
              precision    recall  f1-score   support

           0       0.82      0.95      0.88     70082
           1       0.91      0.68      0.78     45979

    accuracy                           0.85    116061
   macro avg       0.86      0.82      0.83    116061
weighted avg       0.86      0.85      0.84    116061



In [21]:
print(confusion_matrix(y_test, predict_test))
print(classification_report(y_test, predict_test))

[[28538  1402]
 [ 6438 13363]]
              precision    recall  f1-score   support

           0       0.82      0.95      0.88     29940
           1       0.91      0.67      0.77     19801

    accuracy                           0.84     49741
   macro avg       0.86      0.81      0.83     49741
weighted avg       0.85      0.84      0.84     49741



In [22]:
feature_importances

importance
minute             0.310091
hundred_block      0.135435
Hour_Minute        0.046323
datetime           0.039814
latitude           0.032006
longitude          0.031864
utm_y              0.031776
utm_x              0.031518
trees_100          0.028931
pressure           0.026175
hours_of_light     0.025326
temp_c             0.025293
light_pole_100     0.024448
hour               0.022861
humidity           0.022696
day                0.021345
trees_25           0.020941
year               0.019765
light_pole_50      0.018562
light_pole_25      0.014447
month              0.013239
total_precip_mm    0.012363
rain_mm            0.012055
signal_200         0.011545
light_pole_12_5    0.009408
signal_100         0.005176
signal_25          0.003289
signal_50          0.002067
snow_cm            0.001240

In [23]:
# Cut down features

# split training data into training and testing
from sklearn.model_selection import train_test_split

# Select columns to that are data
cols = [col for col in crime if col not in ['type', 'minute', 'hour', 'latitude', 'longitude', 'datetime']]

X = crime[cols]

# Select target data
y = crime['type']

X_train, X_test, y_train, y_test = train_test_split(X, y, random_state=100, test_size=0.3)
print(X_train.shape)

(116061, 24)


In [24]:
X_train

year     month       day  Hour_Minute  hundred_block     utm_x  \
70316   0.5625  0.818182  0.033333     0.252953       0.425550  0.047699   
11727   0.0625  0.818182  0.066667     0.771369       0.025862  0.460223   
6169    0.0000  0.909091  0.766667     0.416956       0.014922  0.482503   
103336  0.3750  0.909091  0.066667     0.189715       0.916968  0.947287   
9092    0.0625  0.363636  0.000000     0.395413       0.256053  0.898446   
...        ...       ...       ...          ...            ...       ...   
82270   0.3125  0.000000  0.233333     0.127172       0.435712  0.135300   
65615   1.0000  0.636364  0.100000     0.833912       0.615416  0.675294   
77655   0.2500  0.545455  0.900000     0.329395       0.851833  0.717762   
56088   0.7500  0.909091  0.533333     0.000000       0.112418  0.382030   
38408   0.4375  0.272727  0.100000     0.959694       0.397354  0.814179   

           utm_y  light_pole_12_5  light_pole_25  light_pole_50  ...  \
70316   0.520506         0.000000       0.014925       0.025641  ...   
11727   0.228466         0.035714       0.014925       0.064103  ...   
6169    0.733887         0.035714       0.044776       0.153846  ...   
103336  0.456247         0.035714       0.029851       0.102564  ...   
9092    0.551214         0.035714       0.029851       0.089744  ...   
...          ...              ...            ...            ...  ...   
82270   0.368855         0.035714       0.014925       0.038462  ...   
65615   0.514778         0.035714       0.014925       0.102564  ...   
77655   0.265493         0.035714       0.014925       0.076923  ...   
56088   0.542361         0.035714       0.014925       0.025641  ...   
38408   0.418335         0.035714       0.014925       0.038462  ...   

        signal_200  trees_25  trees_100   rain_mm   snow_cm  total_precip_mm  \
70316     0.071429   0.28125   0.343511  0.000000  0.000000         0.000000   
11727     0.000000   0.15625   0.511450  0.000000  0.000000         0.000000   
6169      0.357143   0.18750   0.396947  0.048035  0.000000         0.048035   
103336    0.071429   0.25000   0.557252  0.000000  0.000000         0.000000   
9092      0.071429   0.12500   0.259542  0.000000  0.000000         0.000000   
...            ...       ...        ...       ...       ...              ...   
82270     0.000000   0.09375   0.183206  0.074236  0.156716         0.120087   
65615     0.142857   0.21875   0.442748  0.000000  0.000000         0.000000   
77655     0.000000   0.25000   0.488550  0.000000  0.000000         0.000000   
56088     0.214286   0.15625   0.366412  0.063319  0.000000         0.063319   
38408     0.000000   0.09375   0.229008  0.021834  0.000000         0.021834   

          temp_c  humidity  pressure  hours_of_light  
70316   0.501053  0.689655  0.654054        0.384242  
11727   0.606316  0.632184  0.636486        0.378182  
6169    0.393684  0.701149  0.575676        0.061818  
103336  0.393684  0.873563  0.770270        0.169697  
9092    0.694737  0.448276  0.640541        0.779394  
...          ...       ...       ...             ...  
82270   0.294737  0.919540  0.425676        0.026667  
65615   0.703158  0.758621  0.567568        0.823030  
77655   0.646316  0.724138  0.586486        0.869091  
56088   0.404211  0.931034  0.491892        0.094545  
38408   0.437895  0.827586  0.382432        0.573333  

[116061 rows x 24 columns]

In [25]:
y_train

70316     0
11727     1
6169      1
103336    0
9092      1
         ..
82270     0
65615     1
77655     0
56088     1
38408     1
Name: type, Length: 116061, dtype: int64

In [26]:
# Trying Random Forest Classifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.feature_selection import SelectFromModel

model_tree = RandomForestClassifier(random_state=100, n_estimators=50)
model_tree.fit(X_train, y_train)
print(model_tree.feature_importances_)
sel_model_tree = SelectFromModel(estimator=model_tree, prefit=True, threshold='mean')  
      # since we already fit the data, we specify prefit option here
      # Features whose importance is greater or equal to the threshold are kept while the others are discarded.
X_train_sfm_tree = sel_model_tree.transform(X_train)
print(sel_model_tree.get_support())

feature_importances = pd.DataFrame(model_tree.feature_importances_,
                                   index = X_train.columns,
                                    columns=['importance']).sort_values('importance', 
                                                                        ascending=False)
feature_importances

[0.05031145 0.02293808 0.03777122 0.09113505 0.19285371 0.06838166
 0.0684448  0.01483864 0.02252919 0.0334537  0.04457407 0.0071854
 0.00346727 0.00818612 0.02106705 0.03527901 0.05381897 0.02144666
 0.00185164 0.02157017 0.04629294 0.04054581 0.0472128  0.0448446 ]
[ True False False  True  True  True  True False False False  True False
 False False False False  True False False False  True False  True  True]


importance
hundred_block      0.192854
Hour_Minute        0.091135
utm_y              0.068445
utm_x              0.068382
trees_100          0.053819
year               0.050311
pressure           0.047213
temp_c             0.046293
hours_of_light     0.044845
light_pole_100     0.044574
humidity           0.040546
day                0.037771
trees_25           0.035279
light_pole_50      0.033454
month              0.022938
light_pole_25      0.022529
total_precip_mm    0.021570
rain_mm            0.021447
signal_200         0.021067
light_pole_12_5    0.014839
signal_100         0.008186
signal_25          0.007185
signal_50          0.003467
snow_cm            0.001852

In [27]:
# Try using the MLP Classifier
mlp = MLPClassifier(hidden_layer_sizes=(24, 24, 24), activation='relu', solver='adam', max_iter=300)
mlp.fit(X_train, y_train)

predict_train = mlp.predict(X_train)
predict_test = mlp.predict(X_test)

In [28]:
print(confusion_matrix(y_train, predict_train))
print(classification_report(y_train, predict_train))

[[56941 13141]
 [18442 27537]]
              precision    recall  f1-score   support

           0       0.76      0.81      0.78     70082
           1       0.68      0.60      0.64     45979

    accuracy                           0.73    116061
   macro avg       0.72      0.71      0.71    116061
weighted avg       0.72      0.73      0.72    116061



In [29]:
print(confusion_matrix(y_test, predict_test))
print(classification_report(y_test, predict_test))

[[24210  5730]
 [ 8212 11589]]
              precision    recall  f1-score   support

           0       0.75      0.81      0.78     29940
           1       0.67      0.59      0.62     19801

    accuracy                           0.72     49741
   macro avg       0.71      0.70      0.70     49741
weighted avg       0.72      0.72      0.72     49741



In [30]:
# Try using the MLP Classifier
mlp = MLPClassifier(hidden_layer_sizes=(29, 29, 29, 29, 29, 29, 29), activation='relu', solver='adam', max_iter=300)
mlp.fit(X_train, y_train)

predict_train = mlp.predict(X_train)
predict_test = mlp.predict(X_test)

d:\program files (x86)\microsoft visual studio\shared\python37_64\lib\site-packages\sklearn\neural_network\multilayer_perceptron.py:568: UserWarning: Training interrupted by user.
  warnings.warn("Training interrupted by user.")


In [31]:
print(confusion_matrix(y_train, predict_train))
print(classification_report(y_train, predict_train))

[[54924 15158]
 [16279 29700]]
              precision    recall  f1-score   support

           0       0.77      0.78      0.78     70082
           1       0.66      0.65      0.65     45979

    accuracy                           0.73    116061
   macro avg       0.72      0.71      0.72    116061
weighted avg       0.73      0.73      0.73    116061



In [32]:
print(confusion_matrix(y_test, predict_test))
print(classification_report(y_test, predict_test))

[[23334  6606]
 [ 7428 12373]]
              precision    recall  f1-score   support

           0       0.76      0.78      0.77     29940
           1       0.65      0.62      0.64     19801

    accuracy                           0.72     49741
   macro avg       0.71      0.70      0.70     49741
weighted avg       0.72      0.72      0.72     49741



In [33]:
# Cut down features again

# split training data into training and testing
from sklearn.model_selection import train_test_split

# Select columns to that are data
cols = [col for col in crime if col not in ['type', 'minute', 'hour', 'latitude', 'longitude', 'datetime', 
                                            'snow_cm', 'rain_mm', 'signal_25', 'signal_50', 'signal_100', 
                                            'light_pole_12_5']]

X = crime[cols]

# Select target data
y = crime['type']

X_train, X_test, y_train, y_test = train_test_split(X, y, random_state=100, test_size=0.3)
print(X_train.shape)

(116061, 18)


In [34]:
# Trying Random Forest Classifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.feature_selection import SelectFromModel

model_tree = RandomForestClassifier(random_state=100, n_estimators=50)
model_tree.fit(X_train, y_train)
print(model_tree.feature_importances_)
sel_model_tree = SelectFromModel(estimator=model_tree, prefit=True, threshold='mean')  
      # since we already fit the data, we specify prefit option here
      # Features whose importance is greater or equal to the threshold are kept while the others are discarded.
X_train_sfm_tree = sel_model_tree.transform(X_train)
print(sel_model_tree.get_support())

feature_importances = pd.DataFrame(model_tree.feature_importances_,
                                   index = X_train.columns,
                                    columns=['importance']).sort_values('importance', 
                                                                        ascending=False)
feature_importances

ERROR:root:Internal Python error in the inspect module.
Below is the traceback from this internal error.



Traceback (most recent call last):
  File "d:\program files (x86)\microsoft visual studio\shared\python37_64\lib\site-packages\IPython\core\interactiveshell.py", line 3326, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-34-6c822571a59f>", line 6, in <module>
    model_tree.fit(X_train, y_train)
  File "d:\program files (x86)\microsoft visual studio\shared\python37_64\lib\site-packages\sklearn\ensemble\forest.py", line 330, in fit
    for i, t in enumerate(trees))
  File "d:\program files (x86)\microsoft visual studio\shared\python37_64\lib\site-packages\joblib\parallel.py", line 1006, in __call__
    while self.dispatch_one_batch(iterator):
  File "d:\program files (x86)\microsoft visual studio\shared\python37_64\lib\site-packages\joblib\parallel.py", line 834, in dispatch_one_batch
    self._dispatch(tasks)
  File "d:\program files (x86)\microsoft visual studio\shared\python37_64\lib\site-packages\joblib\parallel.py", line 753, in _dispatch
  

KeyboardInterrupt: 

In [ ]:
# Try using the MLP Classifier
mlp = MLPClassifier(hidden_layer_sizes=(18, 18, 18), activation='relu', solver='adam', max_iter=300)
mlp.fit(X_train, y_train)

predict_train = mlp.predict(X_train)
predict_test = mlp.predict(X_test)

In [ ]:
print(confusion_matrix(y_train, predict_train))
print(classification_report(y_train, predict_train))

In [ ]:
print(confusion_matrix(y_test, predict_test))
print(classification_report(y_test, predict_test))

In [ ]:
# Try using the MLP Classifier
mlp = MLPClassifier(hidden_layer_sizes=(18, 18, 18, 18, 18, 18, 18), activation='relu', solver='adam', max_iter=300)
mlp.fit(X_train, y_train)

predict_train = mlp.predict(X_train)
predict_test = mlp.predict(X_test)

In [ ]:
print(confusion_matrix(y_train, predict_train))
print(classification_report(y_train, predict_train))

In [ ]:
print(confusion_matrix(y_test, predict_test))
print(classification_report(y_test, predict_test))