In [1]:
# NOTE: This does NOT have points close to real ones removed!

import pandas as pd
import numpy as np
%matplotlib inline
import matplotlib.pyplot as plt
import sklearn

crime = pd.read_csv('E:/Vancouver Crime Final/Synthetic Data/commercial_bne_100k_combined.csv')

crime.head(20)

type             datetime  year  month  day  hour  \
0   Break and Enter Commercial  2003-01-01 00:00:00  2003      1    1     0   
1   Break and Enter Commercial  2003-01-01 06:06:00  2003      1    1     6   
2   Break and Enter Commercial  2003-01-01 07:07:00  2003      1    1     7   
3   Break and Enter Commercial  2003-01-01 07:07:00  2003      1    1     7   
4   Break and Enter Commercial  2003-01-01 11:11:00  2003      1    1    11   
5   Break and Enter Commercial  2003-01-01 12:12:00  2003      1    1    12   
6   Break and Enter Commercial  2003-01-01 12:12:00  2003      1    1    12   
7   Break and Enter Commercial  2003-01-01 12:12:00  2003      1    1    12   
8   Break and Enter Commercial  2003-01-01 19:19:00  2003      1    1    19   
9   Break and Enter Commercial  2003-01-01 23:23:00  2003      1    1    23   
10  Break and Enter Commercial  2003-01-02 02:02:00  2003      1    2     2   
11  Break and Enter Commercial  2003-01-02 03:03:00  2003      1    2     3   
12  Break and Enter Commercial  2003-01-02 06:06:00  2003      1    2     6   
13  Break and Enter Commercial  2003-01-02 09:09:00  2003      1    2     9   
14  Break and Enter Commercial  2003-01-02 17:17:00  2003      1    2    17   
15  Break and Enter Commercial  2003-01-02 21:21:00  2003      1    2    21   
16  Break and Enter Commercial  2003-01-02 23:23:00  2003      1    2    23   
17  Break and Enter Commercial  2003-01-03 02:02:00  2003      1    3     2   
18  Break and Enter Commercial  2003-01-03 02:02:00  2003      1    3     2   
19  Break and Enter Commercial  2003-01-03 03:03:00  2003      1    3     3   

    minute  Hour_Minute          hundred_block      utm_x  ...  signal_200  \
0        0     0.000000       64XX VICTORIA DR  495220.95  ...           2   
1        0     6.000000       5XX W GEORGIA ST  491507.39  ...          10   
2       13     7.216667        18XX W 57TH AVE  489132.03  ...           0   
3       13     7.216667         45XX FRASER ST  493431.80  ...           2   
4        0    11.000000         35XX FRASER ST  493447.88  ...           1   
5        0    12.000000          5XX BEATTY ST  492024.04  ...          10   
6        0    12.000000       7XX PACIFIC BLVD  492005.87  ...           2   
7       49    12.816667        28XX BENTALL ST  497676.19  ...           3   
8       35    19.583333  9XX W KING EDWARD AVE  490906.22  ...           2   
9       19    23.316667      10XX E GEORGIA ST  494077.84  ...           1   
10       0     2.000000            3XX HOWE ST  491696.77  ...          10   
11       0     3.000000         28XX W 4TH AVE  487680.42  ...           4   
12      55     6.916667      10XX KINGSWAY AVE  494039.54  ...           2   
13       5     9.083333     36XX E HASTINGS ST  498193.37  ...           2   
14      30    17.500000         29XX W 4TH AVE  487535.71  ...           2   
15      41    21.683333       15XX KOOTENAY ST  498032.54  ...           2   
16      30    23.500000           21XX MAIN ST  492674.67  ...           2   
17       0     2.000000         27XX RUPERT ST  497553.23  ...           3   
18      28     2.466667         30XX SLOCAN ST  496391.40  ...           2   
19       0     3.000000     19XX COMMERCIAL DR  494925.66  ...           2   

    trees_25  trees_100  rain_mm  snow_cm  total_precip_mm  temp_c  humidity  \
0          5         40     21.6      0.0             21.6     5.8      81.0   
1          2         27     21.6      0.0             21.6     5.5      96.0   
2          8         73     21.6      0.0             21.6     5.8      95.0   
3          2         19     21.6      0.0             21.6     5.8      95.0   
4          3         51     21.6      0.0             21.6     6.0      95.0   
5          0         39     21.6      0.0             21.6     5.7      95.0   
6          0          0     21.6      0.0             21.6     5.7      95.0   
7          0         13     21.6      0.0             21.6     5.7      95.0   
8      

In [2]:
# Set Break and ENters to 1 and everything else to 0

crime = crime.replace(['NONE'], 0)

crime = crime.replace(['Break and Enter Residential/Other', 'Break and Enter Commercial'], 1)
crime.head()

type             datetime  year  month  day  hour  minute  Hour_Minute  \
0     1  2003-01-01 00:00:00  2003      1    1     0       0     0.000000   
1     1  2003-01-01 06:06:00  2003      1    1     6       0     6.000000   
2     1  2003-01-01 07:07:00  2003      1    1     7      13     7.216667   
3     1  2003-01-01 07:07:00  2003      1    1     7      13     7.216667   
4     1  2003-01-01 11:11:00  2003      1    1    11       0    11.000000   

      hundred_block      utm_x  ...  signal_200  trees_25  trees_100  rain_mm  \
0  64XX VICTORIA DR  495220.95  ...           2         5         40     21.6   
1  5XX W GEORGIA ST  491507.39  ...          10         2         27     21.6   
2   18XX W 57TH AVE  489132.03  ...           0         8         73     21.6   
3    45XX FRASER ST  493431.80  ...           2         2         19     21.6   
4    35XX FRASER ST  493447.88  ...           1         3         51     21.6   

   snow_cm  total_precip_mm  temp_c  humidity  pressure  hours_of_light  
0      0.0             21.6     5.8      81.0    101.70            9.53  
1      0.0             21.6     5.5      96.0    101.58            9.53  
2      0.0             21.6     5.8      95.0    101.50            9.53  
3      0.0             21.6     5.8      95.0    101.50            9.53  
4      0.0             21.6     6.0      95.0    101.33            9.53  

[5 rows x 30 columns]

In [3]:
crime

type             datetime  year  month  day  hour  minute  \
0          1  2003-01-01 00:00:00  2003      1    1     0       0   
1          1  2003-01-01 06:06:00  2003      1    1     6       0   
2          1  2003-01-01 07:07:00  2003      1    1     7      13   
3          1  2003-01-01 07:07:00  2003      1    1     7      13   
4          1  2003-01-01 11:11:00  2003      1    1    11       0   
...      ...                  ...   ...    ...  ...   ...     ...   
138374     0  2018-02-07 12:46:00  2018      2    7    12      46   
138375     0  2004-12-31 00:20:00  2004     12   31     0      20   
138376     0  2008-08-27 01:35:00  2008      8   27     1      35   
138377     0  2018-02-14 22:55:00  2018      2   14    22      55   
138378     0  2016-01-07 21:08:00  2016      1    7    21       8   

        Hour_Minute           hundred_block          utm_x  ...  signal_200  \
0          0.000000        64XX VICTORIA DR  495220.950000  ...           2   
1          6.000000        5XX W GEORGIA ST  491507.390000  ...          10   
2          7.216667         18XX W 57TH AVE  489132.030000  ...           0   
3          7.216667          45XX FRASER ST  493431.800000  ...           2   
4         11.000000          35XX FRASER ST  493447.880000  ...           1   
...             ...                     ...            ...  ...         ...   
138374    12.766667          9XX E 27TH AVE  493764.962443  ...           0   
138375     0.333333   ODLUM DR / WILLIAM ST  494477.870000  ...           1   
138376     1.583333           9XX E 62ND AV  493674.480000  ...           0   
138377    22.916667  E 29TH AVE / QUEBEC ST  492535.810000  ...           3   
138378    21.133333      61XX SOUTHLANDS PL  487174.014115  ...           2   

        trees_25  trees_100  rain_mm  snow_cm  total_precip_mm  temp_c  \
0              5         40     21.6      0.0             21.6     5.8   
1              2         27     21.6      0.0             21.6     5.5   
2              8         73     21.6      0.0             21.6     5.8   
3              2         19     21.6      0.0             21.6     5.8   
4              3         51     21.6      0.0             21.6     6.0   
...          ...        ...      ...      ...              ...     ...   
138374        11         64      2.0      0.0              2.0     8.7   
138375         7         46      2.0      0.0              2.0     3.5   
138376         7         74      4.2      0.0              4.2    11.3   
138377        10         67      6.2      0.0              6.2     1.9   
138378         0          4      0.0      0.0              0.0     4.3   

        humidity  pressure  hours_of_light  
0           81.0    101.70            9.53  
1           96.0    101.58            9.53  
2           95.0    101.50            9.53  
3           95.0    101.50            9.53  
4           95.0    101.33            9.53  
...          ...       ...             ...  
138374      95.0    102.79           10.87  
138375      92.0    100.42            9.52  
138376      92.0    101.00           14.82  
138377      93.0    102.27           11.24  
138378      93.0    101.62            9.64  

[138379 rows x 30 columns]

In [4]:
### Begin Processing the Data


# Import Pre-processing module
from sklearn import preprocessing

# Create Label Encoder
le = preprocessing.LabelEncoder()

# Convert the string columns to numeric
# .astype(str) to ensude they are read as strings and not as mixed types
crime['datetime'] = le.fit_transform(crime['datetime'].astype(str))
crime['hundred_block'] = le.fit_transform(crime['hundred_block'].astype(str))


# Display the results
crime

type  datetime  year  month  day  hour  minute  Hour_Minute  \
0          1         0  2003      1    1     0       0     0.000000   
1          1         5  2003      1    1     6       0     6.000000   
2          1         6  2003      1    1     7      13     7.216667   
3          1         6  2003      1    1     7      13     7.216667   
4          1         8  2003      1    1    11       0    11.000000   
...      ...       ...   ...    ...  ...   ...     ...          ...   
138374     0    118689  2018      2    7    12      46    12.766667   
138375     0     16783  2004     12   31     0      20     0.333333   
138376     0     46108  2008      8   27     1      35     1.583333   
138377     0    118863  2018      2   14    22      55    22.916667   
138378     0    102165  2016      1    7    21       8    21.133333   

        hundred_block          utm_x  ...  signal_200  trees_25  trees_100  \
0               11763  495220.950000  ...           2         5         40   
1               11326  491507.390000  ...          10         2         27   
2                2478  489132.030000  ...           0         8         73   
3                9101  493431.800000  ...           2         2         19   
4                7337  493447.880000  ...           1         3         51   
...               ...            ...  ...         ...       ...        ...   
138374          14589  493764.962443  ...           0        11         64   
138375          19583  494477.870000  ...           1         7         46   
138376          14615  493674.480000  ...           0         7         74   
138377          16875  492535.810000  ...           3        10         67   
138378          11502  487174.014115  ...           2         0          4   

        rain_mm  snow_cm  total_precip_mm  temp_c  humidity  pressure  \
0          21.6      0.0             21.6     5.8      81.0    101.70   
1          21.6      0.0             21.6     5.5      96.0    101.58   
2          21.6      0.0             21.6     5.8      95.0    101.50   
3          21.6      0.0             21.6     5.8      95.0    101.50   
4          21.6      0.0             21.6     6.0      95.0    101.33   
...         ...      ...              ...     ...       ...       ...   
138374      2.0      0.0              2.0     8.7      95.0    102.79   
138375      2.0      0.0              2.0     3.5      92.0    100.42   
138376      4.2      0.0              4.2    11.3      92.0    101.00   
138377      6.2      0.0              6.2     1.9      93.0    102.27   
138378      0.0      0.0              0.0     4.3      93.0    101.62   

        hours_of_light  
0                 9.53  
1                 9.53  
2                 9.53  
3                 9.53  
4                 9.53  
...                ...  
138374           10.87  
138375            9.52  
138376           14.82  
138377           11.24  
138378            9.64  

[138379 rows x 30 columns]

In [5]:
# Scale the Data

columns = [col for col in crime if col not in ['type']]


# Properly scale the reduced set of features
features = crime[columns]

from sklearn.preprocessing import MinMaxScaler
scaler = preprocessing.MinMaxScaler()

print(scaler.fit(features))

MinMaxScaler(copy=True, feature_range=(0, 1))


In [6]:
# Properly scale the features

columns = [col for col in crime if col not in ['type']]

# Properly scale the reduced set of features
features = crime[columns]


scaler = MinMaxScaler().fit(features.values) # scaler = MinMaxScaler().fit(features.values)
features = scaler.transform(features.values) # features = scaler.transform(features.values)
crime[columns] = features
crime

type  datetime    year     month       day      hour    minute  \
0          1  0.000000  0.0000  0.000000  0.000000  0.000000  0.000000   
1          1  0.000038  0.0000  0.000000  0.000000  0.260870  0.000000   
2          1  0.000046  0.0000  0.000000  0.000000  0.304348  0.220339   
3          1  0.000046  0.0000  0.000000  0.000000  0.304348  0.220339   
4          1  0.000061  0.0000  0.000000  0.000000  0.478261  0.000000   
...      ...       ...     ...       ...       ...       ...       ...   
138374     0  0.907589  0.9375  0.090909  0.200000  0.521739  0.779661   
138375     0  0.128336  0.0625  1.000000  1.000000  0.000000  0.338983   
138376     0  0.352578  0.3125  0.636364  0.866667  0.043478  0.593220   
138377     0  0.908919  0.9375  0.090909  0.433333  0.956522  0.932203   
138378     0  0.781233  0.8125  0.000000  0.200000  0.913043  0.135593   

        Hour_Minute  hundred_block     utm_x  ...  signal_200  trees_25  \
0          0.000000       0.539637  0.788730  ...    0.142857      0.20   
1          0.250174       0.519589  0.534303  ...    0.714286      0.08   
2          0.300903       0.113680  0.371560  ...    0.000000      0.32   
3          0.300903       0.417515  0.666150  ...    0.142857      0.08   
4          0.458652       0.336591  0.667252  ...    0.071429      0.12   
...             ...            ...       ...  ...         ...       ...   
138374     0.532314       0.669282  0.688976  ...    0.000000      0.44   
138375     0.013899       0.898385  0.737819  ...    0.071429      0.28   
138376     0.066018       0.670474  0.682777  ...    0.000000      0.28   
138377     0.955525       0.774154  0.604763  ...    0.214286      0.40   
138378     0.881167       0.527663  0.237410  ...    0.142857      0.00   

        trees_100   rain_mm  snow_cm  total_precip_mm    temp_c  humidity  \
0        0.305344  0.235808      0.0         0.235808  0.408421  0.776471   
1        0.206107  0.235808      0.0         0.235808  0.402105  0.952941   
2        0.557252  0.235808      0.0         0.235808  0.408421  0.941176   
3        0.145038  0.235808      0.0         0.235808  0.408421  0.941176   
4        0.389313  0.235808      0.0         0.235808  0.412632  0.941176   
...           ...       ...      ...              ...       ...       ...   
138374   0.488550  0.021834      0.0         0.021834  0.469474  0.941176   
138375   0.351145  0.021834      0.0         0.021834  0.360000  0.905882   
138376   0.564885  0.045852      0.0         0.045852  0.524211  0.905882   
138377   0.511450  0.067686      0.0         0.067686  0.326316  0.917647   
138378   0.030534  0.000000      0.0         0.000000  0.376842  0.917647   

        pressure  hours_of_light  
0       0.609459        0.010909  
1       0.593243        0.010909  
2       0.582432        0.010909  
3       0.582432        0.010909  
4       0.559459        0.010909  
...          ...             ...  
138374  0.756757        0.173333  
138375  0.436486        0.009697  
138376  0.514865        0.652121  
138377  0.686486        0.218182  
138378  0.598649        0.024242  

[138379 rows x 30 columns]

In [7]:
# split training data into training and testing
from sklearn.model_selection import train_test_split

# Select columns to that are data
cols = [col for col in crime if col not in ['type']]

X = crime[cols]

# Select target data
y = crime['type']

X_train, X_test, y_train, y_test = train_test_split(X, y, random_state=100, test_size=0.3)
print(X_train.shape)

(96865, 29)


In [8]:
# Trying Random Forest Classifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.feature_selection import SelectFromModel

model_tree = RandomForestClassifier(random_state=100, n_estimators=50)
model_tree.fit(X_train, y_train)
print(model_tree.feature_importances_)
sel_model_tree = SelectFromModel(estimator=model_tree, prefit=True, threshold='mean')  
      # since we already fit the data, we specify prefit option here
      # Features whose importance is greater or equal to the threshold are kept while the others are discarded.
X_train_sfm_tree = sel_model_tree.transform(X_train)
print(sel_model_tree.get_support())

feature_importances = pd.DataFrame(model_tree.feature_importances_,
                                   index = X_train.columns,
                                    columns=['importance']).sort_values('importance', 
                                                                        ascending=False)
feature_importances

[0.02553922 0.01441464 0.0109635  0.01682529 0.02436222 0.17053089
 0.03877002 0.1309976  0.04132972 0.05687688 0.05140221 0.03955736
 0.01619728 0.03005205 0.03199685 0.06369022 0.00255744 0.00787343
 0.03490984 0.0424777  0.01914201 0.03013887 0.00951517 0.00089337
 0.01004686 0.0201505  0.01836592 0.02049818 0.01992476]
[False False False False False  True  True  True  True  True  True  True
 False False False  True False False  True  True False False False False
 False False False False False]


importance
minute             0.170531
hundred_block      0.130998
light_pole_100     0.063690
utm_y              0.056877
latitude           0.051402
signal_200         0.042478
utm_x              0.041330
longitude          0.039557
Hour_Minute        0.038770
signal_100         0.034910
light_pole_50      0.031997
trees_100          0.030139
light_pole_25      0.030052
datetime           0.025539
hour               0.024362
pressure           0.020498
temp_c             0.020151
hours_of_light     0.019925
trees_25           0.019142
humidity           0.018366
day                0.016825
light_pole_12_5    0.016197
year               0.014415
month              0.010964
total_precip_mm    0.010047
rain_mm            0.009515
signal_50          0.007873
signal_25          0.002557
snow_cm            0.000893

In [9]:
# Simple Neural Network

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import sklearn
from sklearn.neural_network import MLPClassifier
from sklearn.neural_network import MLPRegressor

# import needed modules
from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_squared_error
from math import sqrt
from sklearn.metrics import r2_score

In [10]:
# Try using the MLP Classifier
mlp = MLPClassifier(hidden_layer_sizes=(29, 29, 29), activation='relu', solver='adam', max_iter=300)
mlp.fit(X_train, y_train)

predict_train = mlp.predict(X_train)
predict_test = mlp.predict(X_test)

In [11]:
from sklearn.metrics import classification_report, confusion_matrix
print(confusion_matrix(y_train, predict_train))
print(classification_report(y_train, predict_train))

[[63467  6437]
 [ 4841 22120]]
              precision    recall  f1-score   support

           0       0.93      0.91      0.92     69904
           1       0.77      0.82      0.80     26961

    accuracy                           0.88     96865
   macro avg       0.85      0.86      0.86     96865
weighted avg       0.89      0.88      0.88     96865



In [12]:
print(confusion_matrix(y_test, predict_test))
print(classification_report(y_test, predict_test))

[[27107  3011]
 [ 2213  9183]]
              precision    recall  f1-score   support

           0       0.92      0.90      0.91     30118
           1       0.75      0.81      0.78     11396

    accuracy                           0.87     41514
   macro avg       0.84      0.85      0.85     41514
weighted avg       0.88      0.87      0.88     41514



In [13]:
# Try using the MLP Classifier
mlp = MLPClassifier(hidden_layer_sizes=(29, 29, 29), activation='relu', solver='adam', max_iter=3000)
mlp.fit(X_train, y_train)

predict_train = mlp.predict(X_train)
predict_test = mlp.predict(X_test)

In [14]:
print(confusion_matrix(y_train, predict_train))
print(classification_report(y_train, predict_train))

[[65136  4768]
 [ 6471 20490]]
              precision    recall  f1-score   support

           0       0.91      0.93      0.92     69904
           1       0.81      0.76      0.78     26961

    accuracy                           0.88     96865
   macro avg       0.86      0.85      0.85     96865
weighted avg       0.88      0.88      0.88     96865



In [15]:
print(confusion_matrix(y_test, predict_test))
print(classification_report(y_test, predict_test))

[[27854  2264]
 [ 2797  8599]]
              precision    recall  f1-score   support

           0       0.91      0.92      0.92     30118
           1       0.79      0.75      0.77     11396

    accuracy                           0.88     41514
   macro avg       0.85      0.84      0.84     41514
weighted avg       0.88      0.88      0.88     41514



In [16]:
############################# END HERE ###################################

In [17]:
# Try using the MLP Classifier
mlp = MLPClassifier(hidden_layer_sizes=(29, 29, 29, 29, 29, 29, 29), activation='relu', solver='adam', max_iter=200)
mlp.fit(X_train, y_train)

predict_train = mlp.predict(X_train)
predict_test = mlp.predict(X_test)

In [18]:
print(confusion_matrix(y_train, predict_train))
print(classification_report(y_train, predict_train))

[[64724  5180]
 [ 6843 20118]]
              precision    recall  f1-score   support

           0       0.90      0.93      0.92     69904
           1       0.80      0.75      0.77     26961

    accuracy                           0.88     96865
   macro avg       0.85      0.84      0.84     96865
weighted avg       0.87      0.88      0.87     96865



In [19]:
print(confusion_matrix(y_test, predict_test))
print(classification_report(y_test, predict_test))

[[27710  2408]
 [ 3041  8355]]
              precision    recall  f1-score   support

           0       0.90      0.92      0.91     30118
           1       0.78      0.73      0.75     11396

    accuracy                           0.87     41514
   macro avg       0.84      0.83      0.83     41514
weighted avg       0.87      0.87      0.87     41514



In [20]:
feature_importances

importance
minute             0.170531
hundred_block      0.130998
light_pole_100     0.063690
utm_y              0.056877
latitude           0.051402
signal_200         0.042478
utm_x              0.041330
longitude          0.039557
Hour_Minute        0.038770
signal_100         0.034910
light_pole_50      0.031997
trees_100          0.030139
light_pole_25      0.030052
datetime           0.025539
hour               0.024362
pressure           0.020498
temp_c             0.020151
hours_of_light     0.019925
trees_25           0.019142
humidity           0.018366
day                0.016825
light_pole_12_5    0.016197
year               0.014415
month              0.010964
total_precip_mm    0.010047
rain_mm            0.009515
signal_50          0.007873
signal_25          0.002557
snow_cm            0.000893

In [21]:
# Cut down features

# split training data into training and testing
from sklearn.model_selection import train_test_split

# Select columns to that are data
cols = [col for col in crime if col not in ['type', 'minute', 'hour', 'latitude', 'longitude', 'datetime']]

X = crime[cols]

# Select target data
y = crime['type']

X_train, X_test, y_train, y_test = train_test_split(X, y, random_state=100, test_size=0.3)
print(X_train.shape)

(96865, 24)


In [22]:
X_train

year     month       day  Hour_Minute  hundred_block     utm_x  \
72095   0.3750  0.000000  0.866667     0.589993       0.444215  0.643550   
64323   0.1875  0.545455  0.366667     0.111883       0.159923  0.351495   
130897  0.1250  0.181818  0.866667     0.610841       0.068126  0.422120   
135079  0.3125  0.818182  0.666667     0.485754       0.563217  0.581250   
99821   0.1250  0.363636  0.066667     0.467686       0.557803  0.716358   
...        ...       ...       ...          ...            ...       ...   
82270   1.0000  0.545455  0.833333     0.851286       0.875172  0.606900   
65615   0.5000  0.272727  0.366667     0.683808       0.036563  0.724389   
77655   0.8125  0.000000  0.966667     0.687283       0.905634  0.442263   
56088   0.4375  1.000000  0.966667     0.637248       0.026791  0.518395   
38408   0.5000  0.454545  0.466667     0.368311       0.907102  0.402187   

           utm_y  light_pole_12_5  light_pole_25  light_pole_50  ...  \
72095   0.712832         0.000000       0.029851       0.192308  ...   
64323   0.597300         0.035714       0.059701       0.141026  ...   
130897  0.499471         0.000000       0.089552       0.205128  ...   
135079  0.300513         0.000000       0.014925       0.064103  ...   
99821   0.180692         0.000000       0.014925       0.064103  ...   
...          ...              ...            ...            ...  ...   
82270   0.119379         0.178571       0.134328       0.205128  ...   
65615   0.644755         0.035714       0.014925       0.051282  ...   
77655   0.742548         0.000000       0.044776       0.076923  ...   
56088   0.773960         0.107143       0.089552       0.192308  ...   
38408   0.596453         0.107143       0.089552       0.192308  ...   

        signal_200  trees_25  trees_100   rain_mm  snow_cm  total_precip_mm  \
72095     0.500000      0.16   0.465649  0.039301      0.0         0.039301   
64323     0.142857      0.40   0.526718  0.111354      0.0         0.111354   
130897    0.214286      0.20   0.458015  0.098253      0.0         0.098253   
135079    0.071429      0.28   0.435115  0.000000      0.0         0.000000   
99821     0.071429      0.36   0.625954  0.000000      0.0         0.000000   
...            ...       ...        ...       ...      ...              ...   
82270     0.071429      0.24   0.511450  0.000000      0.0         0.000000   
65615     0.071429      0.00   0.091603  0.000000      0.0         0.000000   
77655     0.071429      0.56   0.633588  0.019651      0.0         0.019651   
56088     0.500000      0.16   0.442748  0.000000      0.0         0.000000   
38408     0.285714      0.20   0.312977  0.024017      0.0         0.024017   

          temp_c  humidity  pressure  hours_of_light  
72095   0.305263  0.929412  0.647297        0.110303  
64323   0.608421  0.764706  0.533784        0.952727  
130897  0.494737  0.882353  0.362162        0.515152  
135079  0.511579  0.670588  0.859459        0.252121  
99821   0.587368  0.752941  0.624324        0.791515  
...          ...       ...       ...             ...  
82270   0.757895  0.529412  0.581081        0.880000  
65615   0.477895  0.588235  0.606757        0.632727  
77655   0.416842  0.811765  0.537838        0.122424  
56088   0.317895  0.400000  0.650000        0.007273  
38408   0.568421  0.705882  0.664865        0.996364  

[96865 rows x 24 columns]

In [23]:
y_train

72095     0
64323     0
130897    0
135079    0
99821     0
         ..
82270     0
65615     0
77655     0
56088     0
38408     0
Name: type, Length: 96865, dtype: int64

In [24]:
# Trying Random Forest Classifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.feature_selection import SelectFromModel

model_tree = RandomForestClassifier(random_state=100, n_estimators=50)
model_tree.fit(X_train, y_train)
print(model_tree.feature_importances_)
sel_model_tree = SelectFromModel(estimator=model_tree, prefit=True, threshold='mean')  
      # since we already fit the data, we specify prefit option here
      # Features whose importance is greater or equal to the threshold are kept while the others are discarded.
X_train_sfm_tree = sel_model_tree.transform(X_train)
print(sel_model_tree.get_support())

feature_importances = pd.DataFrame(model_tree.feature_importances_,
                                   index = X_train.columns,
                                    columns=['importance']).sort_values('importance', 
                                                                        ascending=False)
feature_importances

[0.02820917 0.01751653 0.02630101 0.06038927 0.16233077 0.07370706
 0.10075094 0.02049338 0.03478002 0.04848419 0.08001666 0.00492293
 0.00767515 0.03832619 0.06356925 0.02967979 0.04928472 0.0152447
 0.00141602 0.01521574 0.03129083 0.02873403 0.03140327 0.03025838]
[False False False  True  True  True  True False False  True  True False
 False False  True False  True False False False False False False False]


importance
hundred_block      0.162331
utm_y              0.100751
light_pole_100     0.080017
utm_x              0.073707
signal_200         0.063569
Hour_Minute        0.060389
trees_100          0.049285
light_pole_50      0.048484
signal_100         0.038326
light_pole_25      0.034780
pressure           0.031403
temp_c             0.031291
hours_of_light     0.030258
trees_25           0.029680
humidity           0.028734
year               0.028209
day                0.026301
light_pole_12_5    0.020493
month              0.017517
rain_mm            0.015245
total_precip_mm    0.015216
signal_50          0.007675
signal_25          0.004923
snow_cm            0.001416

In [25]:
# Try using the MLP Classifier
mlp = MLPClassifier(hidden_layer_sizes=(24, 24, 24), activation='relu', solver='adam', max_iter=300)
mlp.fit(X_train, y_train)

predict_train = mlp.predict(X_train)
predict_test = mlp.predict(X_test)

In [26]:
print(confusion_matrix(y_train, predict_train))
print(classification_report(y_train, predict_train))

[[61933  7971]
 [ 6768 20193]]
              precision    recall  f1-score   support

           0       0.90      0.89      0.89     69904
           1       0.72      0.75      0.73     26961

    accuracy                           0.85     96865
   macro avg       0.81      0.82      0.81     96865
weighted avg       0.85      0.85      0.85     96865



In [27]:
print(confusion_matrix(y_test, predict_test))
print(classification_report(y_test, predict_test))

[[26476  3642]
 [ 3034  8362]]
              precision    recall  f1-score   support

           0       0.90      0.88      0.89     30118
           1       0.70      0.73      0.71     11396

    accuracy                           0.84     41514
   macro avg       0.80      0.81      0.80     41514
weighted avg       0.84      0.84      0.84     41514



In [28]:
# Try using the MLP Classifier
mlp = MLPClassifier(hidden_layer_sizes=(29, 29, 29, 29, 29, 29, 29), activation='relu', solver='adam', max_iter=300)
mlp.fit(X_train, y_train)

predict_train = mlp.predict(X_train)
predict_test = mlp.predict(X_test)

d:\program files (x86)\microsoft visual studio\shared\python37_64\lib\site-packages\sklearn\neural_network\multilayer_perceptron.py:566: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (300) reached and the optimization hasn't converged yet.
  % self.max_iter, ConvergenceWarning)


In [29]:
print(confusion_matrix(y_train, predict_train))
print(classification_report(y_train, predict_train))

[[63866  6038]
 [ 6237 20724]]
              precision    recall  f1-score   support

           0       0.91      0.91      0.91     69904
           1       0.77      0.77      0.77     26961

    accuracy                           0.87     96865
   macro avg       0.84      0.84      0.84     96865
weighted avg       0.87      0.87      0.87     96865



In [30]:
print(confusion_matrix(y_test, predict_test))
print(classification_report(y_test, predict_test))

[[27038  3080]
 [ 3179  8217]]
              precision    recall  f1-score   support

           0       0.89      0.90      0.90     30118
           1       0.73      0.72      0.72     11396

    accuracy                           0.85     41514
   macro avg       0.81      0.81      0.81     41514
weighted avg       0.85      0.85      0.85     41514



In [31]:
# Cut down features again

# split training data into training and testing
from sklearn.model_selection import train_test_split

# Select columns to that are data
cols = [col for col in crime if col not in ['type', 'minute', 'hour', 'latitude', 'longitude', 'datetime', 
                                            'snow_cm', 'rain_mm', 'signal_25', 'signal_50', 'signal_100', 
                                            'light_pole_12_5']]

X = crime[cols]

# Select target data
y = crime['type']

X_train, X_test, y_train, y_test = train_test_split(X, y, random_state=100, test_size=0.3)
print(X_train.shape)

(96865, 18)


In [32]:
# Trying Random Forest Classifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.feature_selection import SelectFromModel

model_tree = RandomForestClassifier(random_state=100, n_estimators=50)
model_tree.fit(X_train, y_train)
print(model_tree.feature_importances_)
sel_model_tree = SelectFromModel(estimator=model_tree, prefit=True, threshold='mean')  
      # since we already fit the data, we specify prefit option here
      # Features whose importance is greater or equal to the threshold are kept while the others are discarded.
X_train_sfm_tree = sel_model_tree.transform(X_train)
print(sel_model_tree.get_support())

feature_importances = pd.DataFrame(model_tree.feature_importances_,
                                   index = X_train.columns,
                                    columns=['importance']).sort_values('importance', 
                                                                        ascending=False)
feature_importances

[0.02890289 0.01715424 0.02723613 0.06846547 0.17774334 0.08145314
 0.10923717 0.03931181 0.04612715 0.10985992 0.06857298 0.03009192
 0.05152786 0.01765977 0.03246152 0.02921679 0.03269181 0.0322861 ]
[False False False  True  True  True  True False False  True  True False
 False False False False False False]


importance
hundred_block      0.177743
light_pole_100     0.109860
utm_y              0.109237
utm_x              0.081453
signal_200         0.068573
Hour_Minute        0.068465
trees_100          0.051528
light_pole_50      0.046127
light_pole_25      0.039312
pressure           0.032692
temp_c             0.032462
hours_of_light     0.032286
trees_25           0.030092
humidity           0.029217
year               0.028903
day                0.027236
total_precip_mm    0.017660
month              0.017154

In [33]:
# Try using the MLP Classifier
mlp = MLPClassifier(hidden_layer_sizes=(18, 18, 18), activation='relu', solver='adam', max_iter=300)
mlp.fit(X_train, y_train)

predict_train = mlp.predict(X_train)
predict_test = mlp.predict(X_test)

In [34]:
print(confusion_matrix(y_train, predict_train))
print(classification_report(y_train, predict_train))

[[61939  7965]
 [ 8069 18892]]
              precision    recall  f1-score   support

           0       0.88      0.89      0.89     69904
           1       0.70      0.70      0.70     26961

    accuracy                           0.83     96865
   macro avg       0.79      0.79      0.79     96865
weighted avg       0.83      0.83      0.83     96865



In [35]:
print(confusion_matrix(y_test, predict_test))
print(classification_report(y_test, predict_test))

[[26573  3545]
 [ 3550  7846]]
              precision    recall  f1-score   support

           0       0.88      0.88      0.88     30118
           1       0.69      0.69      0.69     11396

    accuracy                           0.83     41514
   macro avg       0.79      0.79      0.79     41514
weighted avg       0.83      0.83      0.83     41514



In [36]:
# Try using the MLP Classifier
mlp = MLPClassifier(hidden_layer_sizes=(18, 18, 18, 18, 18, 18, 18), activation='relu', solver='adam', max_iter=300)
mlp.fit(X_train, y_train)

predict_train = mlp.predict(X_train)
predict_test = mlp.predict(X_test)

d:\program files (x86)\microsoft visual studio\shared\python37_64\lib\site-packages\sklearn\neural_network\multilayer_perceptron.py:566: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (300) reached and the optimization hasn't converged yet.
  % self.max_iter, ConvergenceWarning)


In [37]:
print(confusion_matrix(y_train, predict_train))
print(classification_report(y_train, predict_train))

[[62218  7686]
 [ 7217 19744]]
              precision    recall  f1-score   support

           0       0.90      0.89      0.89     69904
           1       0.72      0.73      0.73     26961

    accuracy                           0.85     96865
   macro avg       0.81      0.81      0.81     96865
weighted avg       0.85      0.85      0.85     96865



In [38]:
print(confusion_matrix(y_test, predict_test))
print(classification_report(y_test, predict_test))

[[26643  3475]
 [ 3225  8171]]
              precision    recall  f1-score   support

           0       0.89      0.88      0.89     30118
           1       0.70      0.72      0.71     11396

    accuracy                           0.84     41514
   macro avg       0.80      0.80      0.80     41514
weighted avg       0.84      0.84      0.84     41514

