In [87]:
import pandas as pd
import numpy as np
%matplotlib inline
import matplotlib.pyplot as plt
import sklearn

crime = pd.read_csv('E:/Vancouver Crime Final/vancouver_crime_final.csv')

crime

c_id                                               type  \
0            1                                 Theft from Vehicle   
1            2                                   Theft of Bicycle   
2            3                  Break and Enter Residential/Other   
3            4                                   Theft of Bicycle   
4            5                                 Theft from Vehicle   
...        ...                                                ...   
552557  552409                                 Theft from Vehicle   
552558  552410                                           Mischief   
552559  552411                                 Theft from Vehicle   
552560  552412  Vehicle Collision or Pedestrian Struck (with I...   
552561  552413  Vehicle Collision or Pedestrian Struck (with I...   

                   datetime  year  month  day  hour  minute  Hour_Minute  \
0       2003-01-01 00:00:00  2003      1    1     0       0     0.000000   
1       2003-01-01 00:00:00  2003      1    1     0       0     0.000000   
2       2003-01-01 00:00:00  2003      1    1     0       0     0.000000   
3       2003-01-01 00:00:00  2003      1    1     0       0     0.000000   
4       2003-01-01 00:00:00  2003      1    1     0       0     0.000000   
...                     ...   ...    ...  ...   ...     ...          ...   
552557  2019-08-29 22:22:00  2019      8   29    22      41    22.683333   
552558  2019-08-29 23:23:00  2019      8   29    23       7    23.116667   
552559  2019-08-29 23:23:00  2019      8   29    23      57    23.950000   
552560  2019-08-30 16:16:00  2019      8   30    16      48    16.800000   
552561  2019-08-30 21:21:00  2019      8   30    21      38    21.633333   

                   hundred_block  ... signal_50  signal_100  signal_200  \
0               57XX CULLODEN ST  ...         0           1           2   
1                   6X KEEFER PL  ...         0           1           6   
2                 9XX W 15TH AVE  ...         0           2           2   
3                 30XX W 4TH AVE  ...         0           1           2   
4                    X NK_LOC ST  ...         1           3          13   
...                          ...  ...       ...         ...         ...   
552557  SEYMOUR ST / W PENDER ST  ...         1           4          12   
552558           14XX WILLIAM ST  ...         0           0           1   
552559             48XX PATON ST  ...         0           0           0   
552560      MAPLE ST / W 4TH AVE  ...         1           1           3   
552561       NELSON ST / HOWE ST  ...         1           3          11   

        trees_25  trees_100  rain_mm  snow_cm  total_precip_mm  \
0              6         49     21.6      0.0             21.6   
1              8         49     21.6      0.0             21.6   
2              0         32     21.6      0.0             21.6   
3              6         21     21.6      0.0             21.6   
4              6         39     21.6      0.0             21.6   
...          ...        ...      ...      ...              ...   
552557         4         46      0.0      0.0              0.0   
552558         8         61      0.0      0.0              0.0   
552559         3         32      0.0      0.0              0.0   
552560         5         58      0.0      0.0              0.0   
552561         9         75      0.0      0.0              0.0   

        hours_of_light  Daytime  
0                 9.53        0  
1                 9.53        0  
2                 9.53        0  
3                 9.53        0  
4                 9.53        0  
...                ...      ...  
552557           14.74        0  
552558           14.74        0  
552559           14.74        0  
552560           14.68        1  
552561           14.68        0  

[552562 rows x 30 columns]

In [2]:
# Explore the data

In [3]:
crime.shape

(552562, 30)

In [4]:
crime.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 552562 entries, 0 to 552561
Data columns (total 30 columns):
c_id               552562 non-null int64
type               552562 non-null object
datetime           552562 non-null object
year               552562 non-null int64
month              552562 non-null int64
day                552562 non-null int64
hour               552562 non-null int64
minute             552562 non-null int64
Hour_Minute        552562 non-null float64
hundred_block      552549 non-null object
neighbourhood      550090 non-null object
utm_x              552562 non-null float64
utm_y              552562 non-null float64
latitude           552562 non-null float64
longitude          552562 non-null float64
light_pole_12_5    552562 non-null int64
light_pole_25      552562 non-null int64
light_pole_50      552562 non-null int64
light_pole_100     552562 non-null int64
signal_25          552562 non-null int64
signal_50          552562 non-null int64
signal_100    

In [5]:
crime.describe().transpose()

count          mean            std           min  \
c_id             552562.0  2.762270e+05  159451.178621  1.000000e+00   
year             552562.0  2.010395e+03       5.133866  2.003000e+03   
month            552562.0  6.477859e+00       3.390320  1.000000e+00   
day              552562.0  1.539022e+01       8.717921  1.000000e+00   
hour             552562.0  1.372101e+01       6.751736  0.000000e+00   
minute           552562.0  1.709855e+01      18.457957  0.000000e+00   
Hour_Minute      552562.0  1.400598e+01       6.743928  0.000000e+00   
utm_x            552562.0  4.922299e+05    2714.988848  3.883730e+05   
utm_y            552562.0  5.456714e+06    2483.975227  5.435925e+06   
latitude         552562.0  4.926313e+01       0.022340  4.907336e+01   
longitude        552562.0 -1.231068e+02       0.037319 -1.245498e+02   
light_pole_12_5  552562.0  1.261205e+00       1.238792  0.000000e+00   
light_pole_25    552562.0  4.024928e+00       3.389035  0.000000e+00   
light_pole_50    552562.0  1.090413e+01       7.719480  0.000000e+00   
light_pole_100   552562.0  3.632453e+01      21.420880  0.000000e+00   
signal_25        552562.0  2.595383e-01       0.439421  0.000000e+00   
signal_50        552562.0  4.150213e-01       0.538603  0.000000e+00   
signal_100       552562.0  1.075324e+00       1.127950  0.000000e+00   
signal_200       552562.0  3.899490e+00       3.620895  0.000000e+00   
trees_25         552562.0  5.023389e+00       3.332186  0.000000e+00   
trees_100        552562.0  4.716029e+01      20.682681  0.000000e+00   
rain_mm          552562.0  3.110145e+00       6.660803  0.000000e+00   
snow_cm          552562.0  6.590681e-02       0.749886  0.000000e+00   
total_precip_mm  552562.0  3.187166e+00       6.717170  0.000000e+00   
hours_of_light   552562.0  1.355470e+01       2.808994  9.440000e+00   
Daytime          552562.0  5.068083e-01       0.499954  0.000000e+00   

                          25%           50%           75%           max  
c_id             1.381412e+05  2.762815e+05  4.142728e+05  5.524130e+05  
year             2.006000e+03  2.010000e+03  2.015000e+03  2.019000e+03  
month            4.000000e+00  7.000000e+00  9.000000e+00  1.200000e+01  
day              8.000000e+00  1.500000e+01  2.300000e+01  3.100000e+01  
hour             9.000000e+00  1.500000e+01  1.900000e+01  2.300000e+01  
minute           0.000000e+00  1.100000e+01  3.000000e+01  5.900000e+01  
Hour_Minute      9.500000e+00  1.550000e+01  1.938333e+01  2.398333e+01  
utm_x            4.906364e+05  4.917791e+05  4.939781e+05  5.113030e+05  
utm_y            5.455278e+06  5.457329e+06  5.458724e+06  5.512579e+06  
latitude         4.925021e+01  4.926866e+01  4.928123e+01  4.975532e+01  
longitude       -1.231287e+02 -1.231130e+02 -1.230827e+02 -1.228446e+02  
light_pole_12_5  0.000000e+00  1.000000e+00  2.000000e+00  2.800000e+01  
light_pole_25    1.000000e+00  3.000000e+00  6.000000e+00  6.700000e+01  
light_pole_50    5.000000e+00  9.000000e+00  1.500000e+01  7.800000e+01  
light_pole_100   2.100000e+01  3.100000e+01  4.600000e+01  1.410000e+02  
signal_25        0.000000e+00  0.000000e+00  1.000000e+00  2.000000e+00  
signal_50        0.000000e+00  0.000000e+00  1.000000e+00  3.000000e+00  
signal_100       0.000000e+00  1.000000e+00  2.000000e+00  6.000000e+00  
signal_200       1.000000e+00  3.000000e+00  7.000000e+00  1.500000e+01  
trees_25         2.000000e+00  5.000000e+00  7.000000e+00  3.300000e+01  
trees_100        3.300000e+01  4.700000e+01  6.200000e+01  1.310000e+02  
rain_mm          0.000000e+00  0.000000e+00  3.200000e+00  9.160000e+01  
snow_cm          0.000000e+00  0.000000e+00  0.000000e+00  2.680000e+01  
total_precip_mm  0.000000e+00  0.000000e+00  3.400000e+00  9.160000e+01  
hours_of_light   1.084000e+01  1.355000e+01  1.625000e+01  1.769000e+01  
Daytime          0.000000e+00  1.000000e+00  1.000000e+00  1.000000e+00

In [6]:
crime.dtypes

c_id                 int64
type                object
datetime            object
year                 int64
month                int64
day                  int64
hour                 int64
minute               int64
Hour_Minute        float64
hundred_block       object
neighbourhood       object
utm_x              float64
utm_y              float64
latitude           float64
longitude          float64
light_pole_12_5      int64
light_pole_25        int64
light_pole_50        int64
light_pole_100       int64
signal_25            int64
signal_50            int64
signal_100           int64
signal_200           int64
trees_25             int64
trees_100            int64
rain_mm            float64
snow_cm            float64
total_precip_mm    float64
hours_of_light     float64
Daytime              int64
dtype: object

In [7]:
crime['c_id'].unique()

array([     1,      2,      3, ..., 552411, 552412, 552413], dtype=int64)

In [8]:
crime['type'].unique()

array(['Theft from Vehicle', 'Theft of Bicycle',
       'Break and Enter Residential/Other', 'Mischief',
       'Break and Enter Commercial',
       'Vehicle Collision or Pedestrian Struck (with Injury)',
       'Theft of Vehicle', 'Other Theft',
       'Vehicle Collision or Pedestrian Struck (with Fatality)'],
      dtype=object)

In [9]:
crime['datetime'].unique()

array(['2003-01-01 00:00:00', '2003-01-01 01:01:00',
       '2003-01-01 02:02:00', ..., '2019-08-29 23:23:00',
       '2019-08-30 16:16:00', '2019-08-30 21:21:00'], dtype=object)

In [10]:
crime['year'].unique()

array([2003, 2004, 2005, 2006, 2007, 2008, 2009, 2010, 2011, 2012, 2013,
       2014, 2015, 2016, 2017, 2018, 2019], dtype=int64)

In [11]:
crime['month'].unique()

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12], dtype=int64)

In [12]:
crime['day'].unique()

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31],
      dtype=int64)

In [13]:
crime['hour'].unique()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23], dtype=int64)

In [14]:
crime['minute'].unique()

array([ 0,  1,  5, 19, 20, 30, 15, 40, 45, 46, 10, 56, 34, 32, 13, 25,  8,
       14, 50, 57, 49, 54,  2, 31, 35, 12, 21,  4, 28, 53, 47, 55, 58, 51,
       39, 24, 23, 22, 41, 43, 59, 33, 38, 52, 18,  3, 48, 16, 42, 44, 36,
       37, 17,  7,  6, 27, 26,  9, 11, 29], dtype=int64)

In [15]:
crime['Hour_Minute'].unique()

array([0.        , 0.01666667, 0.08333333, ..., 9.21666667, 4.26666667,
       7.48333333])

In [16]:
crime['hundred_block'].unique()

array(['57XX CULLODEN ST', '6X KEEFER PL', '9XX W 15TH AVE', ...,
       'ADANAC ST / KOOTENAY ST', '7XX NEON ST', '4X E 47TH AVE'],
      dtype=object)

In [17]:
crime['neighbourhood'].unique()

array(['Sunset', 'Central Business District', 'Fairview', 'Kitsilano',
       nan, 'Grandview-Woodland', 'Shaughnessy', 'Victoria-Fraserview',
       'Killarney', 'Dunbar-Southlands', 'West End', 'Marpole',
       'Hastings-Sunrise', 'Riley Park', 'Kensington-Cedar Cottage',
       'Renfrew-Collingwood', 'Mount Pleasant', 'Strathcona',
       'Kerrisdale', 'South Cambie', 'Arbutus Ridge', 'Oakridge',
       'West Point Grey', 'Musqueam', 'Stanley Park'], dtype=object)

In [18]:
crime['utm_x'].unique()

array([494285.25, 492231.06, 490791.12, ..., 491751.27, 490657.07,
       488350.55])

In [19]:
crime['utm_y'].unique()

array([5453254.66, 5458545.72, 5456127.88, ..., 5454925.17, 5459239.04,
       5454565.25])

In [20]:
crime['latitude'].unique()

array([49.23204546, 49.27961699, 49.2578481 , ..., 49.28583738,
       49.28698366, 49.24375034])

In [21]:
crime['longitude'].unique()

array([-123.07849701, -123.10681569, -123.12655783, ..., -123.1230453 ,
       -123.12847572, -123.16005306])

In [22]:
crime['light_pole_12_5'].unique()

array([ 1,  2,  0,  4,  3, 15,  5,  6,  8,  7, 12, 11, 27, 28,  9, 13, 14,
       10, 20], dtype=int64)

In [23]:
crime['light_pole_25'].unique()

array([ 1,  3,  2,  4,  6, 11, 10,  8,  5,  7,  0,  9, 17, 12, 13, 15, 19,
       14, 20, 18, 16, 51, 67, 37, 40, 39, 52], dtype=int64)

In [24]:
crime['light_pole_50'].unique()

array([ 2,  8,  9, 13, 10, 16,  3, 15,  4, 19, 24, 17,  6, 14,  5, 20,  7,
       18, 11, 12, 23,  0, 21, 25, 22, 35,  1, 33, 29, 27, 26, 40, 28, 62,
       44, 32, 31, 38, 30, 34, 37, 48, 36, 39, 43, 46, 42, 41, 47, 78, 58,
       52, 77, 59, 45, 49, 50, 51, 60, 76], dtype=int64)

In [25]:
crime['light_pole_100'].unique()

array([ 30,  36,  34,  33,  50,  62,  20,  42,  11,  63,  18,  14,  15,
        57,  49,  22,  41,  65,  46,  54,  35,  48,  17,  25,  68,  16,
        19,  12,  72,  45,  27,  51,  53,  40,  29,   9,  31,  39,  37,
        23,  26,  66,  38,  28,   4,  69,   8,  32,  43,  24,  44,  95,
        21,  59,  77,  74,  97,  52,  47,  10,  67,   7,  79,  98,  60,
        56,  93,  90,   6,  75,  13,  58,  91,  71,  99,  55,  86,  96,
        78, 107,  73,  84,  70,  89,  76,  64,  82,  94, 100,   0, 103,
         3,  83,  61,  80, 106,   2,  87,   5,  85, 108, 104,  92, 102,
        88, 105,  81,   1, 101, 109, 113, 138, 111, 110, 135, 140, 139,
       128, 136, 134, 124, 112, 133, 137, 126, 125, 141, 132], dtype=int64)

In [26]:
crime['signal_25'].unique()

array([0, 1, 2], dtype=int64)

In [27]:
crime['signal_50'].unique()

array([0, 1, 2, 3], dtype=int64)

In [28]:
crime['signal_100'].unique()

array([1, 2, 3, 0, 4, 5, 6], dtype=int64)

In [29]:
crime['signal_200'].unique()

array([ 2,  6, 13,  3,  9,  1,  0,  7,  5,  4, 10,  8, 11, 12, 14, 15],
      dtype=int64)

In [30]:
crime['trees_25'].unique()

array([ 6,  8,  0,  7,  3,  5, 14, 13, 10,  1,  9,  4, 11,  2, 12, 15, 16,
       19, 17, 18, 20, 31, 25, 21, 33, 32, 23, 24], dtype=int64)

In [31]:
crime['trees_100'].unique()

array([ 49,  32,  21,  39,  58,  78,  31,  40,  62,  74,  38,  55,  46,
        88,  22,  59,  17,  70,  51,  52,  25,  83,  67,  65,  72,  37,
        48,  33,  73,  41,  36,  27,  50,  19,  61,  35,   0,   7,  14,
        71,  30,  79,  23,  93,  64,  24,  57,  86,   4,  42,  85,  13,
        82,  69,  75,  60,  68,  53,   2,  28,  29,  45,  90,  87,  16,
        20,  26,  43,  34,  92,   6,  66,  47,  89,  63,  54,  76, 101,
        56,  44,  81,  12,  94,  97,   5,  80,  10,  84,  77,   1,  18,
        15,   8,   9,  95,  11,   3,  91, 104,  96,  98,  99, 102, 100,
       108, 103, 107, 106, 111, 109, 110, 120, 116, 105, 112, 113, 114,
       121, 124, 117, 122, 115, 119, 131, 118], dtype=int64)

In [32]:
crime['rain_mm'].unique()

array([21.6, 23.4,  2.8, 13.9,  0. ,  5.8,  2.6,  3.4,  0.2,  1.8, 21.8,
        6.6,  3.2,  6.5,  6.9, 14.4, 12.8,  1.4,  0.6,  0.7,  5.6,  0.4,
        9. ,  1.2,  1.6, 12.4,  1. ,  4.1, 21.7, 10.9,  2. ,  0.9, 11.8,
       13. , 10.6,  3.8,  0.3,  8.2,  4.4,  8.4, 15.4,  7.9, 28.8,  7.2,
        1.5,  9.6,  2.4, 19.4, 24.4,  6.7,  4.2, 11. ,  3.6,  0.8,  6. ,
       12. ,  6.8,  8. , 18. ,  4. , 12.2,  7. , 85. , 55.8, 25.4, 10.4,
        8.8, 14.2, 19. , 37. , 62.6,  3. , 10.8,  5. ,  4.6,  7.6, 10. ,
       22.2,  6.4,  5.4, 16.6,  2.2, 17.2,  4.8,  5.2, 21.2, 11.4, 10.2,
        9.4, 13.8,  8.6, 15.2, 19.8, 13.2, 19.2,  6.2, 26.4, 91.6,  9.2,
       21. , 22.8, 14.6, 35. , 43.2, 11.6, 27.6, 35.4,  7.8, 26.2, 33.4,
       14.8, 56.6, 44.2, 28.4, 39.4, 16. , 13.4, 33. , 17.6,  9.8, 12.6,
       19.6, 39.2, 16.4, 20.2, 18.6,  7.4, 23.6, 17.8, 13.6, 22.4, 26.8,
       29.8, 15.6, 25. , 11.2, 25.8, 14. , 17.4, 31.6, 44.6, 35.8, 30. ,
       38.8, 15.8, 28.2, 18.2, 16.8, 23.2, 30.2, 20

In [33]:
crime['snow_cm'].unique()

array([ 0. ,  0.4,  2.1,  1.2,  0.2,  3. ,  3.4,  8.2,  1. ,  1.1,  6. ,
        4. ,  7.4,  4.8,  0.8,  1.4,  6.4, 18.4,  6.2,  8. ,  1.8,  2.4,
        9.2,  3.2,  3.1,  4.4,  8.4,  4.2,  6.8,  2. , 11.8, 22.4,  5.8,
       26.8, 15.6,  2.8,  5.2,  2.6,  5. ,  1.6,  7.2,  9.6, 14. ,  0.6,
       19.8, 10. , 14.4,  5.4,  7. , 12. , 10.6, 11. ,  5.6])

In [34]:
crime['total_precip_mm'].unique()

array([21.6, 23.4,  2.8, 13.9,  0. ,  5.8,  2.6,  3.4,  0.2,  1.8, 21.8,
        6.6,  3.2,  6.5,  6.9, 14.4, 12.8,  1.4,  0.6,  0.7,  5.6,  0.4,
        9. ,  1.2,  1.6,  2.1, 13.6,  1. ,  4.1, 21.7, 10.9,  2. ,  0.9,
       11.8, 13. , 10.6,  3.8,  0.3,  8.2,  4.4,  8.4, 15.4,  7.9, 28.8,
        7.2,  1.5,  9.6,  2.4, 19.4, 24.4,  6.7,  4.2, 11. ,  3.6,  0.8,
        6. , 12. ,  6.8,  8. , 18. ,  4. , 12.2,  7. , 85. , 55.8, 25.4,
       10.4,  8.8, 14.2, 19. , 37. , 62.6,  3. , 10.8,  5. ,  4.6,  7.6,
       13.4, 11.6, 22.2,  6.4,  5.4, 16.6,  2.2, 17.2,  4.8,  5.2, 21.2,
       11.4, 10.2,  9.4, 13.8,  8.6, 15.2, 19.8, 13.2, 19.2,  6.2, 26.4,
       91.6,  9.2, 21. , 10. , 22.8, 14.6, 35. , 43.2, 27.6, 35.4,  7.8,
       26.2, 33.4, 14.8, 56.6, 44.2, 28.4, 39.4, 16. , 33. , 17.6,  9.8,
       12.6, 19.6, 39.2, 16.4, 20.2, 18.6,  7.4, 23.6, 17.8, 22.4, 26.8,
       29.8, 15.6, 25. , 11.2, 25.8, 14. , 17.4, 31.6, 44.6, 35.8, 30. ,
       38.8, 15.8, 20.6, 28.2, 18.2, 20. , 23.2, 30

In [35]:
crime['hours_of_light'].unique()

array([ 9.53,  9.54,  9.56,  9.58,  9.6 ,  9.62,  9.64,  9.67,  9.69,
        9.72,  9.74,  9.77,  9.8 ,  9.83,  9.87,  9.9 ,  9.93,  9.97,
       10.  , 10.04, 10.08, 10.12, 10.16, 10.2 , 10.24, 10.28, 10.33,
       10.37, 10.42, 10.46, 10.51, 10.55, 10.6 , 10.65, 10.7 , 10.75,
       10.8 , 10.85, 10.9 , 10.95, 11.  , 11.06, 11.11, 11.16, 11.22,
       11.27, 11.33, 11.38, 11.44, 11.49, 11.55, 11.6 , 11.66, 11.72,
       11.78, 11.83, 11.89, 11.95, 12.01, 12.07, 12.13, 12.18, 12.24,
       12.3 , 12.36, 12.42, 12.48, 12.54, 12.6 , 12.66, 12.73, 12.79,
       12.85, 12.91, 12.97, 13.03, 13.09, 13.16, 13.22, 13.28, 13.34,
       13.4 , 13.47, 13.53, 13.59, 13.65, 13.72, 13.78, 13.84, 13.9 ,
       13.97, 14.03, 14.09, 14.15, 14.22, 14.28, 14.34, 14.41, 14.47,
       14.53, 14.59, 14.66, 14.72, 14.78, 14.85, 14.91, 14.97, 15.03,
       15.09, 15.16, 15.22, 15.28, 15.34, 15.4 , 15.46, 15.52, 15.59,
       15.65, 15.71, 15.76, 15.82, 15.88, 15.94, 16.  , 16.06, 16.12,
       16.17, 16.23,

In [36]:
crime['Daytime'].unique()

array([0, 1], dtype=int64)

In [88]:
### Begin Processing the Data


# Import Pre-processing module
from sklearn import preprocessing

# Create Label Encoder
le = preprocessing.LabelEncoder()

# Convert the string columns to numeric
# .astype(str) to ensude they are read as strings and not as mixed types
crime['type'] = le.fit_transform(crime['type'])
crime['datetime'] = le.fit_transform(crime['datetime'].astype(str))
crime['hundred_block'] = le.fit_transform(crime['hundred_block'].astype(str))
crime['neighbourhood'] = le.fit_transform(crime['neighbourhood'].astype(str))



# Display the results
crime

c_id  type  datetime  year  month  day  hour  minute  Hour_Minute  \
0            1     4         0  2003      1    1     0       0     0.000000   
1            2     5         0  2003      1    1     0       0     0.000000   
2            3     1         0  2003      1    1     0       0     0.000000   
3            4     5         0  2003      1    1     0       0     0.000000   
4            5     4         0  2003      1    1     0       0     0.000000   
...        ...   ...       ...   ...    ...  ...   ...     ...          ...   
552557  552409     4    133581  2019      8   29    22      41    22.683333   
552558  552410     2    133582  2019      8   29    23       7    23.116667   
552559  552411     4    133582  2019      8   29    23      57    23.950000   
552560  552412     8    133583  2019      8   30    16      48    16.800000   
552561  552413     8    133584  2019      8   30    21      38    21.633333   

        hundred_block  ...  signal_50  signal_100  signal_200  trees_25  \
0               10688  ...          0           1           2         6   
1               12335  ...          0           1           6         8   
2               14807  ...          0           2           2         0   
3                6346  ...          0           1           2         6   
4               21898  ...          1           3          13         6   
...               ...  ...        ...         ...         ...       ...   
552557          20304  ...          1           4          12         4   
552558           1430  ...          0           0           1         8   
552559           9514  ...          0           0           0         3   
552560          19358  ...          1           1           3         5   
552561          19636  ...          1           3          11         9   

        trees_100  rain_mm  snow_cm  total_precip_mm  hours_of_light  Daytime  
0              49     21.6      0.0             21.6            9.53        0  
1              49     21.6      0.0             21.6            9.53        0  
2              32     21.6      0.0             21.6            9.53        0  
3              21     21.6      0.0             21.6            9.53        0  
4              39     21.6      0.0             21.6            9.53        0  
...           ...      ...      ...              ...             ...      ...  
552557         46      0.0      0.0              0.0           14.74        0  
552558         61      0.0      0.0              0.0           14.74        0  
552559         32      0.0      0.0              0.0           14.74        0  
552560         58      0.0      0.0              0.0           14.68        1  
552561         75      0.0      0.0              0.0           14.68        0  

[552562 rows x 30 columns]

In [92]:
# Scale the Data

from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()

columns = [col for col in crime if col not in ['type', 'c_id']]


# Properly scale the reduced set of features
features = crime[columns]

#from sklearn.preprocessing import MinMaxScaler
#scaler = preprocessing.MinMaxScaler()

print(scaler.fit(features))

StandardScaler(copy=True, with_mean=True, with_std=True)


In [94]:
# Properly scale the features

columns = [col for col in crime if col not in ['type', 'c_id']]

# Properly scale the reduced set of features
features = crime[columns]


scaler = MinMaxScaler().fit(features.values) # scaler = MinMaxScaler().fit(features.values)
features = scaler.transform(features.values) # features = scaler.transform(features.values)
crime[columns] = features
crime


c_id  type  datetime  year     month       day      hour    minute  \
0            1     4  0.000000   0.0  0.000000  0.000000  0.000000  0.000000   
1            2     5  0.000000   0.0  0.000000  0.000000  0.000000  0.000000   
2            3     1  0.000000   0.0  0.000000  0.000000  0.000000  0.000000   
3            4     5  0.000000   0.0  0.000000  0.000000  0.000000  0.000000   
4            5     4  0.000000   0.0  0.000000  0.000000  0.000000  0.000000   
...        ...   ...       ...   ...       ...       ...       ...       ...   
552557  552409     4  0.999978   1.0  0.636364  0.933333  0.956522  0.694915   
552558  552410     2  0.999985   1.0  0.636364  0.933333  1.000000  0.118644   
552559  552411     4  0.999985   1.0  0.636364  0.933333  1.000000  0.966102   
552560  552412     8  0.999993   1.0  0.636364  0.966667  0.695652  0.813559   
552561  552413     8  1.000000   1.0  0.636364  0.966667  0.913043  0.644068   

        Hour_Minute  hundred_block  ...  signal_50  signal_100  signal_200  \
0          0.000000       0.485907  ...   0.000000    0.166667    0.133333   
1          0.000000       0.560784  ...   0.000000    0.166667    0.400000   
2          0.000000       0.673168  ...   0.000000    0.333333    0.133333   
3          0.000000       0.288507  ...   0.000000    0.166667    0.133333   
4          0.000000       0.995545  ...   0.333333    0.500000    0.866667   
...             ...            ...  ...        ...         ...         ...   
552557     0.945796       0.923077  ...   0.333333    0.666667    0.800000   
552558     0.963864       0.065012  ...   0.000000    0.000000    0.066667   
552559     0.998610       0.432533  ...   0.000000    0.000000    0.000000   
552560     0.700486       0.880069  ...   0.333333    0.166667    0.200000   
552561     0.902015       0.892708  ...   0.333333    0.500000    0.733333   

        trees_25  trees_100   rain_mm  snow_cm  total_precip_mm  \
0       0.181818   0.374046  0.235808      0.0         0.235808   
1       0.242424   0.374046  0.235808      0.0         0.235808   
2       0.000000   0.244275  0.235808      0.0         0.235808   
3       0.181818   0.160305  0.235808      0.0         0.235808   
4       0.181818   0.297710  0.235808      0.0         0.235808   
...          ...        ...       ...      ...              ...   
552557  0.121212   0.351145  0.000000      0.0         0.000000   
552558  0.242424   0.465649  0.000000      0.0         0.000000   
552559  0.090909   0.244275  0.000000      0.0         0.000000   
552560  0.151515   0.442748  0.000000      0.0         0.000000   
552561  0.272727   0.572519  0.000000      0.0         0.000000   

        hours_of_light  Daytime  
0             0.010909      0.0  
1             0.010909      0.0  
2             0.010909      0.0  
3             0.010909      0.0  
4             0.010909      0.0  
...                ...      ...  
552557        0.642424      0.0  
552558        0.642424      0.0  
552559        0.642424      0.0  
552560        0.635152      1.0  
552561        0.635152      0.0  

[552562 rows x 30 columns]

In [95]:
# split training data into training and testing
from sklearn.model_selection import train_test_split

# Select columns to that are data
cols = [col for col in crime if col not in ['type', 'c_id']]

X = crime[cols]

# Select target data
y = crime['type']

X_train, X_test, y_train, y_test = train_test_split(X, y, random_state=100, test_size=0.3)
print(X_train.shape)

(386793, 28)


In [96]:
X_train

datetime    year     month       day      hour    minute  Hour_Minute  \
187881  0.282017  0.2500  0.545455  0.166667  0.826087  0.084746     0.795691   
477897  0.871961  0.8750  0.545455  0.733333  0.695652  0.508475     0.687978   
166880  0.244228  0.1875  0.909091  0.700000  0.869565  0.508475     0.854760   
342292  0.607887  0.6250  0.090909  0.533333  0.391304  0.000000     0.375261   
438493  0.799864  0.8125  0.363636  0.433333  0.521739  0.508475     0.521195   
...          ...     ...       ...       ...       ...       ...          ...   
344414  0.613000  0.6250  0.181818  0.700000  0.739130  0.440678     0.726894   
212912  0.328887  0.3125  0.272727  0.433333  0.260870  0.101695     0.254343   
65615   0.090744  0.0625  0.454545  0.233333  0.521739  0.101695     0.504517   
210755  0.324635  0.3125  0.181818  0.600000  1.000000  0.000000     0.958999   
56088   0.077360  0.0625  0.181818  0.733333  0.173913  0.813559     0.200139   

        hundred_block  neighbourhood     utm_x  ...  signal_50  signal_100  \
187881       0.652073       0.041667  0.836889  ...   0.333333    0.333333   
477897       0.654164       0.041667  0.837030  ...   0.333333    0.500000   
166880       0.406210       0.250000  0.865344  ...   0.000000    0.000000   
342292       0.716539       0.291667  0.805522  ...   0.000000    0.000000   
438493       0.013866       0.041667  0.837560  ...   0.333333    0.666667   
...               ...            ...       ...  ...        ...         ...   
344414       0.060102       0.041667  0.833592  ...   0.333333    0.166667   
212912       0.085425       0.166667  0.865622  ...   0.000000    0.000000   
65615        0.096699       0.250000  0.867683  ...   0.000000    0.000000   
210755       0.451946       0.041667  0.838724  ...   0.666667    0.500000   
56088        0.552737       0.333333  0.886325  ...   0.000000    0.000000   

        signal_200  trees_25  trees_100   rain_mm  snow_cm  total_precip_mm  \
187881    0.666667  0.272727   0.465649  0.000000      0.0         0.000000   
477897    0.600000  0.060606   0.473282  0.000000      0.0         0.000000   
166880    0.000000  0.000000   0.404580  0.157205      0.0         0.157205   
342292    0.000000  0.212121   0.396947  0.000000      0.0         0.000000   
438493    0.600000  0.090909   0.259542  0.000000      0.0         0.000000   
...            ...       ...        ...       ...      ...              ...   
344414    0.266667  0.000000   0.137405  0.000000      0.0         0.000000   
212912    0.266667  0.272727   0.603053  0.000000      0.0         0.000000   
65615     0.400000  0.060606   0.251908  0.000000      0.0         0.000000   
210755    0.666667  0.212121   0.511450  0.054585      0.0         0.054585   
56088     0.066667  0.272727   0.488550  0.026201      0.0         0.026201   

        hours_of_light  Daytime  
187881        0.975758      1.0  
477897        0.894545      1.0  
166880        0.069091      0.0  
342292        0.238788      1.0  
438493        0.867879      1.0  
...                ...      ...  
344414        0.477576      1.0  
212912        0.653333      1.0  
65615         0.984242      1.0  
210755        0.455758      0.0  
56088         0.486061      0.0  

[386793 rows x 28 columns]

In [97]:
y_train

187881    3
477897    4
166880    1
342292    4
438493    5
         ..
344414    2
212912    6
65615     3
210755    4
56088     1
Name: type, Length: 386793, dtype: int32

In [98]:
X_test

datetime    year     month       day      hour    minute  Hour_Minute  \
248134  0.398753  0.3750  0.454545  0.566667  0.913043  0.220339     0.884642   
174853  0.257703  0.2500  0.090909  0.333333  0.173913  0.338983     0.180681   
317038  0.550455  0.5625  0.090909  0.466667  0.608696  0.508475     0.604587   
58375   0.080474  0.0625  0.272727  0.300000  0.304348  0.508475     0.312717   
507291  0.922304  0.9375  0.363636  0.666667  0.739130  0.000000     0.708826   
...          ...     ...       ...       ...       ...       ...          ...   
321804  0.561459  0.5625  0.272727  0.833333  0.608696  0.135593     0.589298   
98261   0.136094  0.1250  0.090909  0.833333  0.217391  0.728814     0.238360   
66723   0.092264  0.0625  0.454545  0.533333  0.260870  0.847458     0.284920   
400935  0.731263  0.7500  0.181818  0.900000  0.000000  0.016949     0.000695   
397267  0.723200  0.7500  0.090909  0.166667  0.043478  0.508475     0.062543   

        hundred_block  neighbourhood     utm_x  ...  signal_50  signal_100  \
248134       0.448491       0.833333  0.851949  ...   0.000000    0.000000   
174853       0.022186       0.250000  0.860143  ...   0.000000    0.166667   
317038       0.351064       0.083333  0.797609  ...   0.000000    0.166667   
58375        0.168167       0.291667  0.815450  ...   0.000000    0.000000   
507291       0.255819       0.208333  0.882093  ...   0.333333    0.166667   
...               ...            ...       ...  ...        ...         ...   
321804       0.193126       0.166667  0.864521  ...   0.000000    0.000000   
98261        0.148072       0.458333  0.840120  ...   0.333333    0.333333   
66723        0.407392       0.625000  0.845867  ...   0.000000    0.000000   
400935       0.618158       0.041667  0.843023  ...   0.000000    0.000000   
397267       0.270185       0.041667  0.846348  ...   0.000000    0.166667   

        signal_200  trees_25  trees_100   rain_mm  snow_cm  total_precip_mm  \
248134    0.000000  0.121212   0.419847  0.000000      0.0         0.000000   
174853    0.066667  0.212121   0.610687  0.045852      0.0         0.045852   
317038    0.133333  0.242424   0.343511  0.000000      0.0         0.000000   
58375     0.066667  0.151515   0.610687  0.000000      0.0         0.000000   
507291    0.066667  0.030303   0.137405  0.000000      0.0         0.000000   
...            ...       ...        ...       ...      ...              ...   
321804    0.133333  0.181818   0.259542  0.043668      0.0         0.043668   
98261     0.266667  0.000000   0.206107  0.000000      0.0         0.000000   
66723     0.000000  0.181818   0.572519  0.000000      0.0         0.000000   
400935    0.133333  0.000000   0.000000  0.032751      0.0         0.032751   
397267    0.400000  0.151515   0.519084  0.128821      0.0         0.128821   

        hours_of_light  Daytime  
248134        0.998788      0.0  
174853        0.196364      0.0  
317038        0.220606      1.0  
58375         0.623030      1.0  
507291        0.906667      1.0  
...                ...      ...  
321804        0.743030      1.0  
98261         0.300606      0.0  
66723         0.998788      1.0  
400935        0.518788      0.0  
397267        0.164848      0.0  

[165769 rows x 28 columns]

In [99]:
y_test

248134    2
174853    0
317038    4
58375     2
507291    4
         ..
321804    2
98261     8
66723     1
400935    4
397267    0
Name: type, Length: 165769, dtype: int32

In [100]:
# Simple Neural Network

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import sklearn
from sklearn.neural_network import MLPClassifier
from sklearn.neural_network import MLPRegressor

# import needed modules
from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_squared_error
from math import sqrt
from sklearn.metrics import r2_score

In [104]:
# Try using the MLP Classifier
mlp = MLPClassifier(hidden_layer_sizes=(28, 28, 28), activation='relu', solver='adam', max_iter=300)
mlp.fit(X_train, y_train)

predict_train = mlp.predict(X_train)
predict_test = mlp.predict(X_test)

d:\program files (x86)\microsoft visual studio\shared\python37_64\lib\site-packages\sklearn\neural_network\multilayer_perceptron.py:566: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (300) reached and the optimization hasn't converged yet.
  % self.max_iter, ConvergenceWarning)


In [105]:
from sklearn.metrics import classification_report, confusion_matrix
print(confusion_matrix(y_train, predict_train))
print(classification_report(y_train, predict_train))

[[  5858   1117   3309   1743  14702     29      5      0    144]
 [  1183  14790   1650   1064  27145     28     16      0    134]
 [  2885   4899   6452   3673  38262     80     29      0   1616]
 [   308    240   1008  36394   6252     37      0      0    231]
 [  2124   7857   4741   4686 121633    234     40      0   2385]
 [   293   1323    957   1200  16658    407      0      0    481]
 [   410   2808    888    849  23311     18     34      0    564]
 [    13     11     13      7     58      2      0      0     90]
 [   285    823    676    697   5211     26      0      0   9697]]


d:\program files (x86)\microsoft visual studio\shared\python37_64\lib\site-packages\sklearn\metrics\classification.py:1437: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)


              precision    recall  f1-score   support

           0       0.44      0.22      0.29     26907
           1       0.44      0.32      0.37     46010
           2       0.33      0.11      0.17     57896
           3       0.72      0.82      0.77     44470
           4       0.48      0.85      0.61    143700
           5       0.47      0.02      0.04     21319
           6       0.27      0.00      0.00     28882
           7       0.00      0.00      0.00       194
           8       0.63      0.56      0.59     17415

    accuracy                           0.50    386793
   macro avg       0.42      0.32      0.32    386793
weighted avg       0.47      0.50      0.43    386793



In [106]:
print(confusion_matrix(y_test, predict_test))
print(classification_report(y_test, predict_test))

[[ 2511   488  1328   818  6198    10     8     0    71]
 [  527  6347   740   450 11595    15     6     0    64]
 [ 1188  2112  2754  1553 16464    33     4     0   684]
 [  133    83   446 15445  2730    16     1     0   101]
 [  942  3375  2097  2066 52249    91    22     0  1003]
 [  145   580   397   528  7104   154     2     0   186]
 [  198  1226   369   362  9857    12    18     0   254]
 [    6     7     8     8    18     0     0     0    45]
 [  131   329   309   299  2301    10     1     0  4137]]
              precision    recall  f1-score   support

           0       0.43      0.22      0.29     11432
           1       0.44      0.32      0.37     19744
           2       0.33      0.11      0.17     24792
           3       0.72      0.81      0.76     18955
           4       0.48      0.84      0.61     61845
           5       0.45      0.02      0.03      9096
           6       0.29      0.00      0.00     12296
           7       0.00      0.00      0.00        92

In [109]:
# Try using the MLP Classifier
mlp = MLPClassifier(hidden_layer_sizes=(28, 28, 28), activation='relu', solver='adam', max_iter=3000)
mlp.fit(X_train, y_train)

predict_train = mlp.predict(X_train)
predict_test = mlp.predict(X_test)

In [110]:
print(confusion_matrix(y_train, predict_train))
print(classification_report(y_train, predict_train))

[[  5719   1351   3095   1731  14737     23      0      0    251]
 [   978  16431   2427    847  25082     26      0      0    219]
 [  2860   6464   7290   3828  35257     44      3      0   2150]
 [   430    387   1097  36471   5731     33      0      0    321]
 [  1730   8334   4219   3774 123297    111      3      0   2232]
 [   278   1380    704   1125  17146    189      0      0    497]
 [   322   3053   1011    596  23342     11      3      0    544]
 [    13     14     20      3     53      1      0      0     90]
 [   276   1040    989    783   4100     15      0      0  10212]]


d:\program files (x86)\microsoft visual studio\shared\python37_64\lib\site-packages\sklearn\metrics\classification.py:1437: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)


              precision    recall  f1-score   support

           0       0.45      0.21      0.29     26907
           1       0.43      0.36      0.39     46010
           2       0.35      0.13      0.19     57896
           3       0.74      0.82      0.78     44470
           4       0.50      0.86      0.63    143700
           5       0.42      0.01      0.02     21319
           6       0.33      0.00      0.00     28882
           7       0.00      0.00      0.00       194
           8       0.62      0.59      0.60     17415

    accuracy                           0.52    386793
   macro avg       0.43      0.33      0.32    386793
weighted avg       0.48      0.52      0.45    386793



In [111]:
print(confusion_matrix(y_test, predict_test))
print(classification_report(y_test, predict_test))

[[ 2404   595  1295   781  6249     6     0     0   102]
 [  440  6913   987   389 10905    19     2     0    89]
 [ 1222  2732  3140  1643 15154    10     1     0   890]
 [  165   161   475 15519  2486    10     0     0   139]
 [  806  3554  1885  1686 52906    48     0     0   960]
 [  120   613   311   517  7246    90     1     0   198]
 [  166  1314   415   276  9887     3     0     0   235]
 [    8     6     7     6    19     0     0     0    46]
 [  110   417   464   341  1753     5     0     0  4427]]
              precision    recall  f1-score   support

           0       0.44      0.21      0.28     11432
           1       0.42      0.35      0.38     19744
           2       0.35      0.13      0.19     24792
           3       0.73      0.82      0.77     18955
           4       0.50      0.86      0.63     61845
           5       0.47      0.01      0.02      9096
           6       0.00      0.00      0.00     12296
           7       0.00      0.00      0.00        92

In [107]:
# Try a Random Forest Classifier to show which features are actually predictive

In [108]:
# Trying Random Forest Classifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.feature_selection import SelectFromModel

model_tree = RandomForestClassifier(random_state=100, n_estimators=50)
model_tree.fit(X_train, y_train)
print(model_tree.feature_importances_)
sel_model_tree = SelectFromModel(estimator=model_tree, prefit=True, threshold='mean')  
      # since we already fit the data, we specify prefit option here
      # Features whose importance is greater or equal to the threshold are kept while the others are discarded.
X_train_sfm_tree = sel_model_tree.transform(X_train)
print(sel_model_tree.get_support())

[0.0611186  0.03369986 0.03326551 0.04663875 0.03712572 0.05812556
 0.05209014 0.0679325  0.01710737 0.05331899 0.05500222 0.05432819
 0.05306886 0.01673737 0.02903168 0.03889678 0.0503481  0.00435294
 0.0051959  0.01264704 0.0256319  0.03304495 0.04815646 0.02531545
 0.00170881 0.02552906 0.05326636 0.0073149 ]
[ True False False  True  True  True  True  True False  True  True  True
  True False False  True  True False False False False False  True False
 False False  True False]


In [112]:
feature_importances = pd.DataFrame(model_tree.feature_importances_,
                                   index = X_train.columns,
                                    columns=['importance']).sort_values('importance', 
                                                                        ascending=False)

feature_importances

importance
hundred_block      0.067933
datetime           0.061119
minute             0.058126
utm_y              0.055002
latitude           0.054328
utm_x              0.053319
hours_of_light     0.053266
longitude          0.053069
Hour_Minute        0.052090
light_pole_100     0.050348
trees_100          0.048156
day                0.046639
light_pole_50      0.038897
hour               0.037126
year               0.033700
month              0.033266
trees_25           0.033045
light_pole_25      0.029032
signal_200         0.025632
total_precip_mm    0.025529
rain_mm            0.025315
neighbourhood      0.017107
light_pole_12_5    0.016737
signal_100         0.012647
Daytime            0.007315
signal_50          0.005196
signal_25          0.004353
snow_cm            0.001709