In [1]:
import pandas as pd
import numpy as np
%matplotlib inline
import matplotlib.pyplot as plt
import sklearn

crime = pd.read_csv('E:/Vancouver Crime Final/vancouver_crime_all.csv')

crime.head()

c_id                               type             datetime  year  month  \
0    16                   Theft of Bicycle  2003-01-01 00:00:00  2003      1   
1    10                 Theft from Vehicle  2003-01-01 00:00:00  2003      1   
2    15                 Theft from Vehicle  2003-01-01 00:00:00  2003      1   
3    18  Break and Enter Residential/Other  2003-01-01 00:00:00  2003      1   
4     5                 Theft from Vehicle  2003-01-01 00:00:00  2003      1   

   day  hour  minute  Hour_Minute     hundred_block  ... signal_200  trees_25  \
0    1     0       5     0.083333    11XX HORNBY ST  ...          9         7   
1    1     0       0     0.000000  33XX ROSEMONT DR  ...          0        14   
2    1     0       1     0.016667   26XX E 48TH AVE  ...          2         8   
3    1     0      20     0.333333    19XX PARKER ST  ...          1         8   
4    1     0       0     0.000000       X NK_LOC ST  ...         13         6   

   trees_100  rain_mm  snow_cm  total_precip_mm  temp_c  humidity  pressure  \
0         55     21.6      0.0             21.6     5.8      81.0     101.7   
1         62     21.6      0.0             21.6     5.8      81.0     101.7   
2         38     21.6      0.0             21.6     5.8      81.0     101.7   
3         88     21.6      0.0             21.6     5.8      81.0     101.7   
4         39     21.6      0.0             21.6     5.8      81.0     101.7   

   hours_of_light  
0            9.53  
1            9.53  
2            9.53  
3            9.53  
4            9.53  

[5 rows x 32 columns]

In [2]:
# Set Break and ENters to 1 and everything else to 0

crime = crime.replace(['Break and Enter Residential/Other', 'Break and Enter Commercial', 
                       'Mischief',
       'Vehicle Collision or Pedestrian Struck (with Injury)',
       'Theft of Vehicle', 'Theft of Bicycle', 'Other Theft',
       'Vehicle Collision or Pedestrian Struck (with Fatality)'], 0)

crime = crime.replace(['Theft from Vehicle'], 1)
crime.head()

c_id  type             datetime  year  month  day  hour  minute  \
0    16     0  2003-01-01 00:00:00  2003      1    1     0       5   
1    10     1  2003-01-01 00:00:00  2003      1    1     0       0   
2    15     1  2003-01-01 00:00:00  2003      1    1     0       1   
3    18     0  2003-01-01 00:00:00  2003      1    1     0      20   
4     5     1  2003-01-01 00:00:00  2003      1    1     0       0   

   Hour_Minute     hundred_block  ... signal_200  trees_25  trees_100  \
0     0.083333    11XX HORNBY ST  ...          9         7         55   
1     0.000000  33XX ROSEMONT DR  ...          0        14         62   
2     0.016667   26XX E 48TH AVE  ...          2         8         38   
3     0.333333    19XX PARKER ST  ...          1         8         88   
4     0.000000       X NK_LOC ST  ...         13         6         39   

   rain_mm  snow_cm  total_precip_mm  temp_c  humidity  pressure  \
0     21.6      0.0             21.6     5.8      81.0     101.7   
1     21.6      0.0             21.6     5.8      81.0     101.7   
2     21.6      0.0             21.6     5.8      81.0     101.7   
3     21.6      0.0             21.6     5.8      81.0     101.7   
4     21.6      0.0             21.6     5.8      81.0     101.7   

   hours_of_light  
0            9.53  
1            9.53  
2            9.53  
3            9.53  
4            9.53  

[5 rows x 32 columns]

In [3]:
### Begin Processing the Data


# Import Pre-processing module
from sklearn import preprocessing

# Create Label Encoder
le = preprocessing.LabelEncoder()

# Convert the string columns to numeric
# .astype(str) to ensude they are read as strings and not as mixed types
crime['datetime'] = le.fit_transform(crime['datetime'].astype(str))
crime['hundred_block'] = le.fit_transform(crime['hundred_block'].astype(str))
crime['neighbourhood'] = le.fit_transform(crime['neighbourhood'].astype(str))



# Display the results
crime.head(20)

c_id  type  datetime  year  month  day  hour  minute  Hour_Minute  \
0     16     0         0  2003      1    1     0       5     0.083333   
1     10     1         0  2003      1    1     0       0     0.000000   
2     15     1         0  2003      1    1     0       1     0.016667   
3     18     0         0  2003      1    1     0      20     0.333333   
4      5     1         0  2003      1    1     0       0     0.000000   
5      6     0         0  2003      1    1     0       0     0.000000   
6     17     0         0  2003      1    1     0      19     0.316667   
7     21     1         0  2003      1    1     0      30     0.500000   
8      3     0         0  2003      1    1     0       0     0.000000   
9      1     1         0  2003      1    1     0       0     0.000000   
10     9     0         0  2003      1    1     0       0     0.000000   
11     7     1         0  2003      1    1     0       0     0.000000   
12    14     0         0  2003      1    1     0       1     0.016667   
13    13     1         0  2003      1    1     0       1     0.016667   
14    11     1         0  2003      1    1     0       0     0.000000   
15    20     0         0  2003      1    1     0      30     0.500000   
16     8     1         0  2003      1    1     0       0     0.000000   
17     2     0         0  2003      1    1     0       0     0.000000   
18    19     0         0  2003      1    1     0      30     0.500000   
19    12     1         0  2003      1    1     0       0     0.000000   

    hundred_block  ...  signal_200  trees_25  trees_100  rain_mm  snow_cm  \
0             480  ...           9         7         55     21.6      0.0   
1            6995  ...           0        14         62     21.6      0.0   
2            4876  ...           2         8         38     21.6      0.0   
3            2687  ...           1         8         88     21.6      0.0   
4           21898  ...          13         6         39     21.6      0.0   
5            2172  ...           3         7         58     21.6      0.0   
6           19644  ...           5         5         46     21.6      0.0   
7            9726  ...           7         5         55     21.6      0.0   
8           14807  ...           2         0         32     21.6      0.0   
9           10688  ...           2         6         49     21.6      0.0   
10          11852  ...           2         5         40     21.6      0.0   
11            481  ...           9         3         78     21.6      0.0   
12           7278  ...           3         6         38     21.6      0.0   
13          21898  ...          13         6         39     21.6      0.0   
14           5950  ...           7        13         62     21.6      0.0   
15           1697  ...           4         7         59     21.6      0.0   
16            264  ...           1         5         31     21.6      0.0   
17          12335  ...           6         8         49     21.6      0.0   
18          14669  ...           6         0         22     21.6      0.0   
19           4482  ...           1        10         74     21.6      0.0   

    total_precip_mm  temp_c  humidity  pressure  hours_of_light  
0              21.6     5.8      81.0     101.7            9.53  
1              21.6     5.8      81.0     101.7            9.53  
2              21.6     5.8      81.0     101.7            9.53  
3              21.6     5.8      81.0     101.7            9.53  
4              21.6     5.8      81.0     101.7            9.53  
5              21.6     5.8      81.0     101.7            9.53  
6              21.6     5.8      81.0     101.7            9.53  
7              21.6     5.8      81.0     101.7            9.53  
8              21.6     5.8      81.0     101.7            9.53  
9              21.6     5.8      81.0     101.7            9.53  
10             21.6     5.8      81.0     101.7            9.53  
11             21.6     5.8      81.0     101.7            9

In [4]:
# Scale the Data

#from sklearn.preprocessing import StandardScaler
#scaler = StandardScaler()

columns = [col for col in crime if col not in ['c_id']] # 'type', 


# Properly scale the reduced set of features
features = crime[columns]

from sklearn.preprocessing import MinMaxScaler
scaler = preprocessing.MinMaxScaler()

print(scaler.fit(features))

MinMaxScaler(copy=True, feature_range=(0, 1))


In [5]:
scaler = MinMaxScaler().fit(features.values) # scaler = MinMaxScaler().fit(features.values)
features = scaler.transform(features.values) # features = scaler.transform(features.values)
crime[columns] = features
crime

c_id  type  datetime  year     month       day      hour    minute  \
0           16   0.0  0.000000   0.0  0.000000  0.000000  0.000000  0.084746   
1           10   1.0  0.000000   0.0  0.000000  0.000000  0.000000  0.000000   
2           15   1.0  0.000000   0.0  0.000000  0.000000  0.000000  0.016949   
3           18   0.0  0.000000   0.0  0.000000  0.000000  0.000000  0.338983   
4            5   1.0  0.000000   0.0  0.000000  0.000000  0.000000  0.000000   
...        ...   ...       ...   ...       ...       ...       ...       ...   
552855  552408   1.0  0.999978   1.0  0.636364  0.933333  0.956522  0.322034   
552856  552411   1.0  0.999985   1.0  0.636364  0.933333  1.000000  0.966102   
552857  552410   0.0  0.999985   1.0  0.636364  0.933333  1.000000  0.118644   
552858  552412   0.0  0.999993   1.0  0.636364  0.966667  0.695652  0.813559   
552859  552413   0.0  1.000000   1.0  0.636364  0.966667  0.913043  0.644068   

        Hour_Minute  hundred_block  ...  signal_200  trees_25  trees_100  \
0          0.003475       0.021822  ...    0.600000  0.212121   0.419847   
1          0.000000       0.318012  ...    0.000000  0.424242   0.473282   
2          0.000695       0.221677  ...    0.133333  0.242424   0.290076   
3          0.013899       0.122159  ...    0.066667  0.242424   0.671756   
4          0.000000       0.995545  ...    0.866667  0.181818   0.297710   
...             ...            ...  ...         ...       ...        ...   
552855     0.930507       0.144572  ...    0.266667  0.272727   0.374046   
552856     0.998610       0.432533  ...    0.000000  0.090909   0.244275   
552857     0.963864       0.065012  ...    0.066667  0.242424   0.465649   
552858     0.700486       0.880069  ...    0.200000  0.151515   0.442748   
552859     0.902015       0.892708  ...    0.733333  0.272727   0.572519   

         rain_mm  snow_cm  total_precip_mm    temp_c  humidity  pressure  \
0       0.235808      0.0         0.235808  0.408421  0.781609  0.612081   
1       0.235808      0.0         0.235808  0.408421  0.781609  0.612081   
2       0.235808      0.0         0.235808  0.408421  0.781609  0.612081   
3       0.235808      0.0         0.235808  0.408421  0.781609  0.612081   
4       0.235808      0.0         0.235808  0.408421  0.781609  0.612081   
...          ...      ...              ...       ...       ...       ...   
552855  0.000000      0.0         0.000000  0.711579  0.632184  0.577181   
552856  0.000000      0.0         0.000000  0.692632  0.678161  0.578523   
552857  0.000000      0.0         0.000000  0.692632  0.678161  0.578523   
552858  0.000000      0.0         0.000000  0.751579  0.597701  0.605369   
552859  0.000000      0.0         0.000000  0.682105  0.758621  0.597315   

        hours_of_light  
0             0.010909  
1             0.010909  
2             0.010909  
3             0.010909  
4             0.010909  
...                ...  
552855        0.642424  
552856        0.642424  
552857        0.642424  
552858        0.635152  
552859        0.635152  

[552860 rows x 32 columns]

In [6]:
# split training data into training and testing
from sklearn.model_selection import train_test_split

# Select columns to that are data
cols = [col for col in crime if col not in ['type', 'c_id']]

X = crime[cols]

# Select target data
y = crime['type']

X_train, X_test, y_train, y_test = train_test_split(X, y, random_state=100, test_size=0.3)
print(X_train.shape)

(387002, 30)


In [7]:
# Trying Random Forest Classifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.feature_selection import SelectFromModel

model_tree = RandomForestClassifier(random_state=100, n_estimators=50)
model_tree.fit(X_train, y_train)
print(model_tree.feature_importances_)
sel_model_tree = SelectFromModel(estimator=model_tree, prefit=True, threshold='mean')  
      # since we already fit the data, we specify prefit option here
      # Features whose importance is greater or equal to the threshold are kept while the others are discarded.
X_train_sfm_tree = sel_model_tree.transform(X_train)
print(sel_model_tree.get_support())

feature_importances = pd.DataFrame(model_tree.feature_importances_,
                                   index = X_train.columns,
                                    columns=['importance']).sort_values('importance', 
                                                                        ascending=False)

[0.05629015 0.02811781 0.02459127 0.03962273 0.03065254 0.07825603
 0.0445621  0.04953752 0.01368969 0.04788622 0.05003085 0.04918925
 0.04721886 0.01319247 0.02178479 0.03012013 0.04126129 0.00316957
 0.00407105 0.0092045  0.02110467 0.02631878 0.04149166 0.02175737
 0.00158975 0.02196671 0.0470081  0.04204934 0.04791572 0.04634907]
[ True False False  True False  True  True  True False  True  True  True
  True False False False  True False False False False False  True False
 False False  True  True  True  True]


In [8]:
feature_importances

importance
minute             0.078256
datetime           0.056290
utm_y              0.050031
hundred_block      0.049538
latitude           0.049189
pressure           0.047916
utm_x              0.047886
longitude          0.047219
temp_c             0.047008
hours_of_light     0.046349
Hour_Minute        0.044562
humidity           0.042049
trees_100          0.041492
light_pole_100     0.041261
day                0.039623
hour               0.030653
light_pole_50      0.030120
year               0.028118
trees_25           0.026319
month              0.024591
total_precip_mm    0.021967
light_pole_25      0.021785
rain_mm            0.021757
signal_200         0.021105
neighbourhood      0.013690
light_pole_12_5    0.013192
signal_100         0.009205
signal_50          0.004071
signal_25          0.003170
snow_cm            0.001590

In [9]:
# Simple Neural Network

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import sklearn
from sklearn.neural_network import MLPClassifier
from sklearn.neural_network import MLPRegressor

# import needed modules
from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_squared_error
from math import sqrt
from sklearn.metrics import r2_score

In [10]:
# Try using the MLP Classifier
mlp = MLPClassifier(hidden_layer_sizes=(30, 30, 30), activation='relu', solver='adam', max_iter=300)
mlp.fit(X_train, y_train)

predict_train = mlp.predict(X_train)
predict_test = mlp.predict(X_test)

In [11]:
from sklearn.metrics import classification_report, confusion_matrix
print(confusion_matrix(y_train, predict_train))
print(classification_report(y_train, predict_train))

[[217701  25365]
 [ 97326  46610]]
              precision    recall  f1-score   support

         0.0       0.69      0.90      0.78    243066
         1.0       0.65      0.32      0.43    143936

    accuracy                           0.68    387002
   macro avg       0.67      0.61      0.61    387002
weighted avg       0.67      0.68      0.65    387002



In [12]:
print(confusion_matrix(y_test, predict_test))
print(classification_report(y_test, predict_test))

[[93315 10848]
 [41855 19840]]
              precision    recall  f1-score   support

         0.0       0.69      0.90      0.78    104163
         1.0       0.65      0.32      0.43     61695

    accuracy                           0.68    165858
   macro avg       0.67      0.61      0.60    165858
weighted avg       0.67      0.68      0.65    165858



In [13]:
# Try using the MLP Classifier
mlp = MLPClassifier(hidden_layer_sizes=(30, 30, 30), activation='relu', solver='adam', max_iter=3000)
mlp.fit(X_train, y_train)

predict_train = mlp.predict(X_train)
predict_test = mlp.predict(X_test)

In [14]:
print(confusion_matrix(y_train, predict_train))
print(classification_report(y_train, predict_train))

[[202531  40535]
 [ 74705  69231]]
              precision    recall  f1-score   support

         0.0       0.73      0.83      0.78    243066
         1.0       0.63      0.48      0.55    143936

    accuracy                           0.70    387002
   macro avg       0.68      0.66      0.66    387002
weighted avg       0.69      0.70      0.69    387002



In [15]:
print(confusion_matrix(y_test, predict_test))
print(classification_report(y_test, predict_test))

[[86669 17494]
 [32326 29369]]
              precision    recall  f1-score   support

         0.0       0.73      0.83      0.78    104163
         1.0       0.63      0.48      0.54     61695

    accuracy                           0.70    165858
   macro avg       0.68      0.65      0.66    165858
weighted avg       0.69      0.70      0.69    165858



In [16]:
feature_importances

importance
minute             0.078256
datetime           0.056290
utm_y              0.050031
hundred_block      0.049538
latitude           0.049189
pressure           0.047916
utm_x              0.047886
longitude          0.047219
temp_c             0.047008
hours_of_light     0.046349
Hour_Minute        0.044562
humidity           0.042049
trees_100          0.041492
light_pole_100     0.041261
day                0.039623
hour               0.030653
light_pole_50      0.030120
year               0.028118
trees_25           0.026319
month              0.024591
total_precip_mm    0.021967
light_pole_25      0.021785
rain_mm            0.021757
signal_200         0.021105
neighbourhood      0.013690
light_pole_12_5    0.013192
signal_100         0.009205
signal_50          0.004071
signal_25          0.003170
snow_cm            0.001590

In [17]:
# Cut down features

# split training data into training and testing
from sklearn.model_selection import train_test_split

# Select columns to that are data
cols = [col for col in crime if col in ['Hour_Minute', 'hundred_block', 'pressure', 'temp_c', 
                                       'hours_of_light', 'humidity', 'light_pole_100', 'trees_100', 
                                       'rain_mm', 'signal_200']]

X = crime[cols]

# Select target data
y = crime['type']

X_train, X_test, y_train, y_test = train_test_split(X, y, random_state=100, test_size=0.3)
print(X_train.shape)

(387002, 10)


In [18]:
X

Hour_Minute  hundred_block  light_pole_100  signal_200  trees_100  \
0          0.003475       0.021822        0.404255    0.600000   0.419847   
1          0.000000       0.318012        0.078014    0.000000   0.473282   
2          0.000695       0.221677        0.106383    0.133333   0.290076   
3          0.013899       0.122159        0.156028    0.066667   0.671756   
4          0.000000       0.995545        0.354610    0.866667   0.297710   
...             ...            ...             ...         ...        ...   
552855     0.930507       0.144572        0.418440    0.266667   0.374046   
552856     0.998610       0.432533        0.127660    0.000000   0.244275   
552857     0.963864       0.065012        0.106383    0.066667   0.465649   
552858     0.700486       0.880069        0.212766    0.200000   0.442748   
552859     0.902015       0.892708        0.432624    0.733333   0.572519   

         rain_mm    temp_c  humidity  pressure  hours_of_light  
0       0.235808  0.408421  0.781609  0.612081        0.010909  
1       0.235808  0.408421  0.781609  0.612081        0.010909  
2       0.235808  0.408421  0.781609  0.612081        0.010909  
3       0.235808  0.408421  0.781609  0.612081        0.010909  
4       0.235808  0.408421  0.781609  0.612081        0.010909  
...          ...       ...       ...       ...             ...  
552855  0.000000  0.711579  0.632184  0.577181        0.642424  
552856  0.000000  0.692632  0.678161  0.578523        0.642424  
552857  0.000000  0.692632  0.678161  0.578523        0.642424  
552858  0.000000  0.751579  0.597701  0.605369        0.635152  
552859  0.000000  0.682105  0.758621  0.597315        0.635152  

[552860 rows x 10 columns]

In [19]:
# Trying Random Forest Classifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.feature_selection import SelectFromModel

model_tree = RandomForestClassifier(random_state=100, n_estimators=50)
model_tree.fit(X_train, y_train)
print(model_tree.feature_importances_)
sel_model_tree = SelectFromModel(estimator=model_tree, prefit=True, threshold='mean')  
      # since we already fit the data, we specify prefit option here
      # Features whose importance is greater or equal to the threshold are kept while the others are discarded.
X_train_sfm_tree = sel_model_tree.transform(X_train)
print(sel_model_tree.get_support())

feature_importances = pd.DataFrame(model_tree.feature_importances_,
                                   index = X_train.columns,
                                    columns=['importance']).sort_values('importance', 
                                                                        ascending=False)

feature_importances

[0.1216866  0.13803712 0.10345865 0.05111614 0.10702137 0.05494604
 0.10932521 0.09113655 0.11214096 0.11113136]
[ True  True  True False  True False  True False  True  True]


importance
hundred_block     0.138037
Hour_Minute       0.121687
pressure          0.112141
hours_of_light    0.111131
temp_c            0.109325
trees_100         0.107021
light_pole_100    0.103459
humidity          0.091137
rain_mm           0.054946
signal_200        0.051116

In [20]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import sklearn
from sklearn.neural_network import MLPClassifier
from sklearn.neural_network import MLPRegressor

# import needed modules
from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_squared_error
from math import sqrt
from sklearn.metrics import r2_score

# Try using the MLP Classifier
mlp = MLPClassifier(hidden_layer_sizes=(10, 10, 10), activation='relu', solver='adam', max_iter=5000)
mlp.fit(X_train, y_train)

predict_train = mlp.predict(X_train)
predict_test = mlp.predict(X_test)

In [21]:
from sklearn.metrics import classification_report, confusion_matrix
print(confusion_matrix(y_train, predict_train))
print(classification_report(y_train, predict_train))

[[225155  17911]
 [116259  27677]]
              precision    recall  f1-score   support

         0.0       0.66      0.93      0.77    243066
         1.0       0.61      0.19      0.29    143936

    accuracy                           0.65    387002
   macro avg       0.63      0.56      0.53    387002
weighted avg       0.64      0.65      0.59    387002



In [22]:
print(confusion_matrix(y_test, predict_test))
print(classification_report(y_test, predict_test))

[[96516  7647]
 [49917 11778]]
              precision    recall  f1-score   support

         0.0       0.66      0.93      0.77    104163
         1.0       0.61      0.19      0.29     61695

    accuracy                           0.65    165858
   macro avg       0.63      0.56      0.53    165858
weighted avg       0.64      0.65      0.59    165858



In [23]:
# Cut down features further

# split training data into training and testing
from sklearn.model_selection import train_test_split

# Select columns to that are data
cols = [col for col in crime if col in ['Hour_Minute', 'hundred_block', 'pressure', 'temp_c', 
                                       'hours_of_light']]

X = crime[cols]

# Select target data
y = crime['type']

X_train, X_test, y_train, y_test = train_test_split(X, y, random_state=100, test_size=0.3)
print(X_train.shape)

(387002, 5)


In [24]:
# Trying Random Forest Classifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.feature_selection import SelectFromModel

model_tree = RandomForestClassifier(random_state=100, n_estimators=50)
model_tree.fit(X_train, y_train)
print(model_tree.feature_importances_)
sel_model_tree = SelectFromModel(estimator=model_tree, prefit=True, threshold='mean')  
      # since we already fit the data, we specify prefit option here
      # Features whose importance is greater or equal to the threshold are kept while the others are discarded.
X_train_sfm_tree = sel_model_tree.transform(X_train)
print(sel_model_tree.get_support())

feature_importances = pd.DataFrame(model_tree.feature_importances_,
                                   index = X_train.columns,
                                    columns=['importance']).sort_values('importance', 
                                                                        ascending=False)

feature_importances

[0.17394878 0.27642666 0.17621392 0.18823238 0.18517827]
[False  True False False False]


importance
hundred_block     0.276427
pressure          0.188232
hours_of_light    0.185178
temp_c            0.176214
Hour_Minute       0.173949

In [25]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import sklearn
from sklearn.neural_network import MLPClassifier
from sklearn.neural_network import MLPRegressor

# import needed modules
from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_squared_error
from math import sqrt
from sklearn.metrics import r2_score

# Try using the MLP Classifier
mlp = MLPClassifier(hidden_layer_sizes=(5, 5, 5), activation='relu', solver='adam', max_iter=5000)
mlp.fit(X_train, y_train)

predict_train = mlp.predict(X_train)
predict_test = mlp.predict(X_test)

In [26]:
from sklearn.metrics import classification_report, confusion_matrix
print(confusion_matrix(y_train, predict_train))
print(classification_report(y_train, predict_train))

[[243066      0]
 [143936      0]]


d:\program files (x86)\microsoft visual studio\shared\python37_64\lib\site-packages\sklearn\metrics\classification.py:1437: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)


              precision    recall  f1-score   support

         0.0       0.63      1.00      0.77    243066
         1.0       0.00      0.00      0.00    143936

    accuracy                           0.63    387002
   macro avg       0.31      0.50      0.39    387002
weighted avg       0.39      0.63      0.48    387002



In [27]:
print(confusion_matrix(y_test, predict_test))
print(classification_report(y_test, predict_test))

[[104163      0]
 [ 61695      0]]
              precision    recall  f1-score   support

         0.0       0.63      1.00      0.77    104163
         1.0       0.00      0.00      0.00     61695

    accuracy                           0.63    165858
   macro avg       0.31      0.50      0.39    165858
weighted avg       0.39      0.63      0.48    165858

