In [1]:
import pandas as pd
import numpy as np
%matplotlib inline
import matplotlib.pyplot as plt
import sklearn

crime = pd.read_csv('E:/Vancouver Crime Final/crimes_2015_2019.csv')

crime.head()

c_id                               type             datetime  year  \
0  394341  Break and Enter Residential/Other  2015-01-01 00:00:00  2015   
1  394345                 Theft from Vehicle  2015-01-01 00:00:00  2015   
2  394337                 Theft from Vehicle  2015-01-01 00:00:00  2015   
3  394344         Break and Enter Commercial  2015-01-01 00:00:00  2015   
4  394343                           Mischief  2015-01-01 00:00:00  2015   

   month  day  hour  minute  Hour_Minute               hundred_block  ...  \
0      1    1     0       0          0.0             19XX W 19TH AVE  ...   
1      1    1     0       0          0.0      HEMLOCK ST / W 4TH AVE  ...   
2      1    1     0       0          0.0              40XX WELWYN ST  ...   
3      1    1     0       0          0.0            51XX VICTORIA DR  ...   
4      1    1     0       0          0.0  DUNLEVY AVE / E CORDOVA ST  ...   

  signal_200  trees_25  trees_100  rain_mm  snow_cm  total_precip_mm  temp_c  \
0          0         6         81      0.0      0.0              0.0    -2.4   
1          7        11         56      0.0      0.0              0.0    -2.4   
2          1         6         51      0.0      0.0              0.0    -2.4   
3          2         0         29      0.0      0.0              0.0    -2.4   
4          9         3         37      0.0      0.0              0.0    -2.4   

   humidity  pressure  hours_of_light  
0      83.0    103.07            9.53  
1      83.0    103.07            9.53  
2      83.0    103.07            9.53  
3      83.0    103.07            9.53  
4      83.0    103.07            9.53  

[5 rows x 32 columns]

In [2]:
# Set Break and ENters to 1 and everything else to 0

crime = crime.replace(['Mischief', 'Theft from Vehicle',
       'Vehicle Collision or Pedestrian Struck (with Injury)',
       'Theft of Vehicle', 'Theft of Bicycle', 'Other Theft',
       'Vehicle Collision or Pedestrian Struck (with Fatality)'], 0)

crime = crime.replace(['Break and Enter Residential/Other', 'Break and Enter Commercial'], 1)
crime.head()

c_id  type             datetime  year  month  day  hour  minute  \
0  394341     1  2015-01-01 00:00:00  2015      1    1     0       0   
1  394345     0  2015-01-01 00:00:00  2015      1    1     0       0   
2  394337     0  2015-01-01 00:00:00  2015      1    1     0       0   
3  394344     1  2015-01-01 00:00:00  2015      1    1     0       0   
4  394343     0  2015-01-01 00:00:00  2015      1    1     0       0   

   Hour_Minute               hundred_block  ... signal_200  trees_25  \
0          0.0             19XX W 19TH AVE  ...          0         6   
1          0.0      HEMLOCK ST / W 4TH AVE  ...          7        11   
2          0.0              40XX WELWYN ST  ...          1         6   
3          0.0            51XX VICTORIA DR  ...          2         0   
4          0.0  DUNLEVY AVE / E CORDOVA ST  ...          9         3   

   trees_100  rain_mm  snow_cm  total_precip_mm  temp_c  humidity  pressure  \
0         81      0.0      0.0              0.0    -2.4      83.0    103.07   
1         56      0.0      0.0              0.0    -2.4      83.0    103.07   
2         51      0.0      0.0              0.0    -2.4      83.0    103.07   
3         29      0.0      0.0              0.0    -2.4      83.0    103.07   
4         37      0.0      0.0              0.0    -2.4      83.0    103.07   

   hours_of_light  
0            9.53  
1            9.53  
2            9.53  
3            9.53  
4            9.53  

[5 rows x 32 columns]

In [3]:
### Begin Processing the Data


# Import Pre-processing module
from sklearn import preprocessing

# Create Label Encoder
le = preprocessing.LabelEncoder()

# Convert the string columns to numeric
# .astype(str) to ensude they are read as strings and not as mixed types
crime['datetime'] = le.fit_transform(crime['datetime'].astype(str))
crime['hundred_block'] = le.fit_transform(crime['hundred_block'].astype(str))
crime['neighbourhood'] = le.fit_transform(crime['neighbourhood'].astype(str))



# Display the results
crime.head(20)

c_id  type  datetime  year  month  day  hour  minute  Hour_Minute  \
0   394341     1         0  2015      1    1     0       0     0.000000   
1   394345     0         0  2015      1    1     0       0     0.000000   
2   394337     0         0  2015      1    1     0       0     0.000000   
3   394344     1         0  2015      1    1     0       0     0.000000   
4   394343     0         0  2015      1    1     0       0     0.000000   
5   394348     0         0  2015      1    1     0      40     0.666667   
6   394338     0         0  2015      1    1     0       0     0.000000   
7   394336     0         0  2015      1    1     0       0     0.000000   
8   394347     0         0  2015      1    1     0      35     0.583333   
9   394340     0         0  2015      1    1     0       0     0.000000   
10  394339     0         0  2015      1    1     0       0     0.000000   
11  394346     0         0  2015      1    1     0       1     0.016667   
12  394342     1         0  2015      1    1     0       0     0.000000   
13  394351     1         1  2015      1    1     2       0     2.000000   
14  394352     0         1  2015      1    1     2      36     2.600000   
15  394349     0         1  2015      1    1     2       0     2.000000   
16  394350     0         1  2015      1    1     2       0     2.000000   
17  394355     0         2  2015      1    1     3      22     3.366667   
18  394354     1         2  2015      1    1     3      22     3.366667   
19  394353     0         2  2015      1    1     3       1     3.016667   

    hundred_block  ...  signal_200  trees_25  trees_100  rain_mm  snow_cm  \
0            2100  ...           0         6         81      0.0      0.0   
1           13683  ...           7        11         56      0.0      0.0   
2            6679  ...           1         6         51      0.0      0.0   
3            7789  ...           2         0         29      0.0      0.0   
4           12316  ...           9         3         37      0.0      0.0   
5           10138  ...           0         6         70      0.0      0.0   
6             883  ...           2         7         53      0.0      0.0   
7            6948  ...           0         9         83      0.0      0.0   
8            2338  ...           1         3         29      0.0      0.0   
9            5905  ...           3         6         68      0.0      0.0   
10           8635  ...           2         4         45      0.0      0.0   
11           8289  ...           1         6         52      0.0      0.0   
12           1520  ...           0         5         63      0.0      0.0   
13            619  ...           2         0         13      0.0      0.0   
14           1008  ...           3         3         23      0.0      0.0   
15           8360  ...           1         6         54      0.0      0.0   
16           4165  ...           1         6         51      0.0      0.0   
17           7546  ...           0         0         71      0.0      0.0   
18           7546  ...           0         0         71      0.0      0.0   
19           6570  ...          11         0         41      0.0      0.0   

    total_precip_mm  temp_c  humidity  pressure  hours_of_light  
0               0.0    -2.4      83.0    103.07            9.53  
1               0.0    -2.4      83.0    103.07            9.53  
2               0.0    -2.4      83.0    103.07            9.53  
3               0.0    -2.4      83.0    103.07            9.53  
4               0.0    -2.4      83.0    103.07            9.53  
5               0.0    -2.4      83.0    103.07            9.53  
6               0.0    -2.4      83.0    103.07            9.53  
7               0.0    -2.4      83.0    103.07            9.53  
8               0.0    -2.4      83.0    103.07            9.53  
9               0.0    -2.4      83.0    103.07            9.53  
10              0.0    -2.4      83.0    103.07            9.53  
11              0.0 

In [4]:
# Scale the Data

#from sklearn.preprocessing import StandardScaler
#scaler = StandardScaler()

columns = [col for col in crime if col not in ['c_id']] # 'type', 


# Properly scale the reduced set of features
features = crime[columns]

from sklearn.preprocessing import MinMaxScaler
scaler = preprocessing.MinMaxScaler()

print(scaler.fit(features))

MinMaxScaler(copy=True, feature_range=(0, 1))


In [5]:
scaler = MinMaxScaler().fit(features.values) # scaler = MinMaxScaler().fit(features.values)
features = scaler.transform(features.values) # features = scaler.transform(features.values)
crime[columns] = features
crime

c_id  type  datetime  year     month       day      hour    minute  \
0       394341   1.0  0.000000   0.0  0.000000  0.000000  0.000000  0.000000   
1       394345   0.0  0.000000   0.0  0.000000  0.000000  0.000000  0.000000   
2       394337   0.0  0.000000   0.0  0.000000  0.000000  0.000000  0.000000   
3       394344   1.0  0.000000   0.0  0.000000  0.000000  0.000000  0.000000   
4       394343   0.0  0.000000   0.0  0.000000  0.000000  0.000000  0.000000   
...        ...   ...       ...   ...       ...       ...       ...       ...   
158073  552408   0.0  0.999921   1.0  0.636364  0.933333  0.956522  0.322034   
158074  552411   0.0  0.999947   1.0  0.636364  0.933333  1.000000  0.966102   
158075  552410   0.0  0.999947   1.0  0.636364  0.933333  1.000000  0.118644   
158076  552412   0.0  0.999974   1.0  0.636364  0.966667  0.695652  0.813559   
158077  552413   0.0  1.000000   1.0  0.636364  0.966667  0.913043  0.644068   

        Hour_Minute  hundred_block  ...  signal_200  trees_25  trees_100  \
0          0.000000       0.133554  ...    0.000000  0.193548   0.669421   
1          0.000000       0.870198  ...    0.466667  0.354839   0.462810   
2          0.000000       0.424765  ...    0.066667  0.193548   0.421488   
3          0.000000       0.495357  ...    0.133333  0.000000   0.239669   
4          0.000000       0.783261  ...    0.600000  0.096774   0.305785   
...             ...            ...  ...         ...       ...        ...   
158073     0.930507       0.154223  ...    0.266667  0.290323   0.404959   
158074     0.998610       0.464513  ...    0.000000  0.096774   0.264463   
158075     0.963864       0.071165  ...    0.066667  0.258065   0.504132   
158076     0.700486       0.902697  ...    0.200000  0.161290   0.479339   
158077     0.902015       0.912427  ...    0.733333  0.290323   0.619835   

        rain_mm  snow_cm  total_precip_mm    temp_c  humidity  pressure  \
0           0.0      0.0              0.0  0.159574  0.792683  0.851211   
1           0.0      0.0              0.0  0.159574  0.792683  0.851211   
2           0.0      0.0              0.0  0.159574  0.792683  0.851211   
3           0.0      0.0              0.0  0.159574  0.792683  0.851211   
4           0.0      0.0              0.0  0.159574  0.792683  0.851211   
...         ...      ...              ...       ...       ...       ...   
158073      0.0      0.0              0.0  0.760638  0.609756  0.569204   
158074      0.0      0.0              0.0  0.736702  0.658537  0.570934   
158075      0.0      0.0              0.0  0.736702  0.658537  0.570934   
158076      0.0      0.0              0.0  0.811170  0.573171  0.605536   
158077      0.0      0.0              0.0  0.723404  0.743902  0.595156   

        hours_of_light  
0             0.010909  
1             0.010909  
2             0.010909  
3             0.010909  
4             0.010909  
...                ...  
158073        0.642424  
158074        0.642424  
158075        0.642424  
158076        0.635152  
158077        0.635152  

[158078 rows x 32 columns]

In [6]:
# split training data into training and testing
from sklearn.model_selection import train_test_split

# Select columns to that are data
cols = [col for col in crime if col not in ['type', 'c_id']]

X = crime[cols]

# Select target data
y = crime['type']

X_train, X_test, y_train, y_test = train_test_split(X, y, random_state=100, test_size=0.3)
print(X_train.shape)

(110654, 30)


In [7]:
# Trying Random Forest Classifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.feature_selection import SelectFromModel

model_tree = RandomForestClassifier(random_state=100, n_estimators=50)
model_tree.fit(X_train, y_train)
print(model_tree.feature_importances_)
sel_model_tree = SelectFromModel(estimator=model_tree, prefit=True, threshold='mean')  
      # since we already fit the data, we specify prefit option here
      # Features whose importance is greater or equal to the threshold are kept while the others are discarded.
X_train_sfm_tree = sel_model_tree.transform(X_train)
print(sel_model_tree.get_support())

feature_importances = pd.DataFrame(model_tree.feature_importances_,
                                   index = X_train.columns,
                                    columns=['importance']).sort_values('importance', 
                                                                        ascending=False)

[0.0520271  0.01434375 0.02200417 0.03691875 0.04219567 0.03526715
 0.06580267 0.06437005 0.01707216 0.05039097 0.05132075 0.05106481
 0.049587   0.01289607 0.02746363 0.03375938 0.04177531 0.00702132
 0.00486515 0.01146989 0.02194238 0.02884852 0.04453889 0.02029329
 0.00166825 0.02051621 0.04383431 0.03823651 0.04511963 0.04338623]
[ True False False  True  True  True  True  True False  True  True  True
  True False False  True  True False False False False False  True False
 False False  True  True  True  True]


In [8]:
feature_importances

importance
Hour_Minute        0.065803
hundred_block      0.064370
datetime           0.052027
utm_y              0.051321
latitude           0.051065
utm_x              0.050391
longitude          0.049587
pressure           0.045120
trees_100          0.044539
temp_c             0.043834
hours_of_light     0.043386
hour               0.042196
light_pole_100     0.041775
humidity           0.038237
day                0.036919
minute             0.035267
light_pole_50      0.033759
trees_25           0.028849
light_pole_25      0.027464
month              0.022004
signal_200         0.021942
total_precip_mm    0.020516
rain_mm            0.020293
neighbourhood      0.017072
year               0.014344
light_pole_12_5    0.012896
signal_100         0.011470
signal_25          0.007021
signal_50          0.004865
snow_cm            0.001668

In [9]:
# Simple Neural Network

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import sklearn
from sklearn.neural_network import MLPClassifier
from sklearn.neural_network import MLPRegressor

# import needed modules
from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_squared_error
from math import sqrt
from sklearn.metrics import r2_score

In [10]:
# Try using the MLP Classifier
mlp = MLPClassifier(hidden_layer_sizes=(30, 30, 30), activation='relu', solver='adam', max_iter=300)
mlp.fit(X_train, y_train)

predict_train = mlp.predict(X_train)
predict_test = mlp.predict(X_test)

In [11]:
from sklearn.metrics import classification_report, confusion_matrix
print(confusion_matrix(y_train, predict_train))
print(classification_report(y_train, predict_train))

[[92825  1699]
 [13554  2576]]
              precision    recall  f1-score   support

         0.0       0.87      0.98      0.92     94524
         1.0       0.60      0.16      0.25     16130

    accuracy                           0.86    110654
   macro avg       0.74      0.57      0.59    110654
weighted avg       0.83      0.86      0.83    110654



In [12]:
print(confusion_matrix(y_test, predict_test))
print(classification_report(y_test, predict_test))

[[39619   905]
 [ 6005   895]]
              precision    recall  f1-score   support

         0.0       0.87      0.98      0.92     40524
         1.0       0.50      0.13      0.21      6900

    accuracy                           0.85     47424
   macro avg       0.68      0.55      0.56     47424
weighted avg       0.81      0.85      0.82     47424



In [13]:
# Try using the MLP Classifier
mlp = MLPClassifier(hidden_layer_sizes=(30, 30, 30), activation='relu', solver='adam', max_iter=3000)
mlp.fit(X_train, y_train)

predict_train = mlp.predict(X_train)
predict_test = mlp.predict(X_test)

In [14]:
print(confusion_matrix(y_train, predict_train))
print(classification_report(y_train, predict_train))

[[92914  1610]
 [13540  2590]]
              precision    recall  f1-score   support

         0.0       0.87      0.98      0.92     94524
         1.0       0.62      0.16      0.25     16130

    accuracy                           0.86    110654
   macro avg       0.74      0.57      0.59    110654
weighted avg       0.84      0.86      0.83    110654



In [15]:
print(confusion_matrix(y_test, predict_test))
print(classification_report(y_test, predict_test))

[[39583   941]
 [ 6032   868]]
              precision    recall  f1-score   support

         0.0       0.87      0.98      0.92     40524
         1.0       0.48      0.13      0.20      6900

    accuracy                           0.85     47424
   macro avg       0.67      0.55      0.56     47424
weighted avg       0.81      0.85      0.81     47424



In [16]:
feature_importances

importance
Hour_Minute        0.065803
hundred_block      0.064370
datetime           0.052027
utm_y              0.051321
latitude           0.051065
utm_x              0.050391
longitude          0.049587
pressure           0.045120
trees_100          0.044539
temp_c             0.043834
hours_of_light     0.043386
hour               0.042196
light_pole_100     0.041775
humidity           0.038237
day                0.036919
minute             0.035267
light_pole_50      0.033759
trees_25           0.028849
light_pole_25      0.027464
month              0.022004
signal_200         0.021942
total_precip_mm    0.020516
rain_mm            0.020293
neighbourhood      0.017072
year               0.014344
light_pole_12_5    0.012896
signal_100         0.011470
signal_25          0.007021
signal_50          0.004865
snow_cm            0.001668

In [17]:
# Cut down features

# split training data into training and testing
from sklearn.model_selection import train_test_split

# Select columns to that are data
cols = [col for col in crime if col in ['Hour_Minute', 'hundred_block', 'pressure', 'temp_c', 
                                       'hours_of_light', 'humidity', 'light_pole_100', 'trees_100', 
                                       'rain_mm', 'signal_200']]

X = crime[cols]

# Select target data
y = crime['type']

X_train, X_test, y_train, y_test = train_test_split(X, y, random_state=100, test_size=0.3)
print(X_train.shape)

(110654, 10)


In [18]:
X

Hour_Minute  hundred_block  light_pole_100  signal_200  trees_100  \
0          0.000000       0.133554        0.113475    0.000000   0.669421   
1          0.000000       0.870198        0.517730    0.466667   0.462810   
2          0.000000       0.424765        0.085106    0.066667   0.421488   
3          0.000000       0.495357        0.241135    0.133333   0.239669   
4          0.000000       0.783261        0.340426    0.600000   0.305785   
...             ...            ...             ...         ...        ...   
158073     0.930507       0.154223        0.418440    0.266667   0.404959   
158074     0.998610       0.464513        0.127660    0.000000   0.264463   
158075     0.963864       0.071165        0.106383    0.066667   0.504132   
158076     0.700486       0.902697        0.212766    0.200000   0.479339   
158077     0.902015       0.912427        0.432624    0.733333   0.619835   

        rain_mm    temp_c  humidity  pressure  hours_of_light  
0           0.0  0.159574  0.792683  0.851211        0.010909  
1           0.0  0.159574  0.792683  0.851211        0.010909  
2           0.0  0.159574  0.792683  0.851211        0.010909  
3           0.0  0.159574  0.792683  0.851211        0.010909  
4           0.0  0.159574  0.792683  0.851211        0.010909  
...         ...       ...       ...       ...             ...  
158073      0.0  0.760638  0.609756  0.569204        0.642424  
158074      0.0  0.736702  0.658537  0.570934        0.642424  
158075      0.0  0.736702  0.658537  0.570934        0.642424  
158076      0.0  0.811170  0.573171  0.605536        0.635152  
158077      0.0  0.723404  0.743902  0.595156        0.635152  

[158078 rows x 10 columns]

In [19]:
## Import the random forest model.
from sklearn.ensemble import RandomForestClassifier 
## This line instantiates the model. 
rf = RandomForestClassifier() 
## Fit the model on your training data.
rf.fit(X_train, y_train) 
## And score it on your testing data.
rf.score(X_test, y_test)

feature_importances = pd.DataFrame(rf.feature_importances_,
                                   index = X_train.columns,
                                    columns=['importance']).sort_values('importance', 
                                                                        ascending=False)

feature_importances

d:\program files (x86)\microsoft visual studio\shared\python37_64\lib\site-packages\sklearn\ensemble\forest.py:245: FutureWarning: The default value of n_estimators will change from 10 in version 0.20 to 100 in 0.22.
  "10 in version 0.20 to 100 in 0.22.", FutureWarning)


importance
hundred_block     0.150290
Hour_Minute       0.145301
pressure          0.105100
temp_c            0.103669
light_pole_100    0.103302
hours_of_light    0.103286
trees_100         0.102519
humidity          0.084039
signal_200        0.054163
rain_mm           0.048332

In [20]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import sklearn
from sklearn.neural_network import MLPClassifier
from sklearn.neural_network import MLPRegressor

# import needed modules
from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_squared_error
from math import sqrt
from sklearn.metrics import r2_score

# Try using the MLP Classifier
mlp = MLPClassifier(hidden_layer_sizes=(10, 10, 10), activation='relu', solver='adam', max_iter=5000)
mlp.fit(X_train, y_train)

predict_train = mlp.predict(X_train)
predict_test = mlp.predict(X_test)

In [21]:
from sklearn.metrics import classification_report, confusion_matrix
print(confusion_matrix(y_train, predict_train))
print(classification_report(y_train, predict_train))

[[94434    90]
 [16031    99]]
              precision    recall  f1-score   support

         0.0       0.85      1.00      0.92     94524
         1.0       0.52      0.01      0.01     16130

    accuracy                           0.85    110654
   macro avg       0.69      0.50      0.47    110654
weighted avg       0.81      0.85      0.79    110654



In [22]:
print(confusion_matrix(y_test, predict_test))
print(classification_report(y_test, predict_test))

[[40494    30]
 [ 6857    43]]
              precision    recall  f1-score   support

         0.0       0.86      1.00      0.92     40524
         1.0       0.59      0.01      0.01      6900

    accuracy                           0.85     47424
   macro avg       0.72      0.50      0.47     47424
weighted avg       0.82      0.85      0.79     47424

