In [2]:
import pandas as pd
import numpy as np
%matplotlib inline
import matplotlib.pyplot as plt
import sklearn

crime = pd.read_csv('E:/Vancouver Crime Final/Central_Business_District_crimes.csv')

crime.head()

c_id                type             datetime  year  month  day  hour  \
0    16    Theft of Bicycle  2003-01-01 00:00:00  2003      1    1     0   
1    21  Theft from Vehicle  2003-01-01 00:00:00  2003      1    1     0   
2     7  Theft from Vehicle  2003-01-01 00:00:00  2003      1    1     0   
3    11  Theft from Vehicle  2003-01-01 00:00:00  2003      1    1     0   
4     2    Theft of Bicycle  2003-01-01 00:00:00  2003      1    1     0   

   minute  Hour_Minute   hundred_block  ... signal_200  trees_25  trees_100  \
0       5     0.083333  11XX HORNBY ST  ...          9         7         55   
1      30     0.500000   4XX ABBOTT ST  ...          7         5         55   
2       0     0.000000    11XX HOWE ST  ...          9         3         78   
3       0     0.000000    2XX DRAKE ST  ...          7        13         62   
4       0     0.000000    6X KEEFER PL  ...          6         8         49   

   rain_mm  snow_cm  total_precip_mm  temp_c  humidity  pressure  \
0     21.6      0.0             21.6     5.8      81.0     101.7   
1     21.6      0.0             21.6     5.8      81.0     101.7   
2     21.6      0.0             21.6     5.8      81.0     101.7   
3     21.6      0.0             21.6     5.8      81.0     101.7   
4     21.6      0.0             21.6     5.8      81.0     101.7   

   hours_of_light  
0            9.53  
1            9.53  
2            9.53  
3            9.53  
4            9.53  

[5 rows x 32 columns]

In [3]:
# Set Break and ENters to 1 and everything else to 0

crime = crime.replace(['Mischief', 'Theft from Vehicle',
       'Vehicle Collision or Pedestrian Struck (with Injury)',
       'Theft of Vehicle', 'Theft of Bicycle', 'Other Theft',
       'Vehicle Collision or Pedestrian Struck (with Fatality)'], 0)

crime = crime.replace(['Break and Enter Residential/Other', 'Break and Enter Commercial'], 1)
crime.head()

c_id  type             datetime  year  month  day  hour  minute  \
0    16     0  2003-01-01 00:00:00  2003      1    1     0       5   
1    21     0  2003-01-01 00:00:00  2003      1    1     0      30   
2     7     0  2003-01-01 00:00:00  2003      1    1     0       0   
3    11     0  2003-01-01 00:00:00  2003      1    1     0       0   
4     2     0  2003-01-01 00:00:00  2003      1    1     0       0   

   Hour_Minute   hundred_block  ... signal_200  trees_25  trees_100  rain_mm  \
0     0.083333  11XX HORNBY ST  ...          9         7         55     21.6   
1     0.500000   4XX ABBOTT ST  ...          7         5         55     21.6   
2     0.000000    11XX HOWE ST  ...          9         3         78     21.6   
3     0.000000    2XX DRAKE ST  ...          7        13         62     21.6   
4     0.000000    6X KEEFER PL  ...          6         8         49     21.6   

   snow_cm  total_precip_mm  temp_c  humidity  pressure  hours_of_light  
0      0.0             21.6     5.8      81.0     101.7            9.53  
1      0.0             21.6     5.8      81.0     101.7            9.53  
2      0.0             21.6     5.8      81.0     101.7            9.53  
3      0.0             21.6     5.8      81.0     101.7            9.53  
4      0.0             21.6     5.8      81.0     101.7            9.53  

[5 rows x 32 columns]

In [4]:
### Begin Processing the Data


# Import Pre-processing module
from sklearn import preprocessing

# Create Label Encoder
le = preprocessing.LabelEncoder()

# Convert the string columns to numeric
# .astype(str) to ensude they are read as strings and not as mixed types
crime['datetime'] = le.fit_transform(crime['datetime'].astype(str))
crime['hundred_block'] = le.fit_transform(crime['hundred_block'].astype(str))
crime['neighbourhood'] = le.fit_transform(crime['neighbourhood'].astype(str))



# Display the results
crime.head(20)

c_id  type  datetime  year  month  day  hour  minute  Hour_Minute  \
0     16     0         0  2003      1    1     0       5     0.083333   
1     21     0         0  2003      1    1     0      30     0.500000   
2      7     0         0  2003      1    1     0       0     0.000000   
3     11     0         0  2003      1    1     0       0     0.000000   
4      2     0         0  2003      1    1     0       0     0.000000   
5     19     0         0  2003      1    1     0      30     0.500000   
6     23     0         1  2003      1    1     1       0     1.000000   
7     32     0         2  2003      1    1     2       0     2.000000   
8     36     0         3  2003      1    1     3       0     3.000000   
9     44     0         4  2003      1    1     4      15     4.250000   
10    46     0         5  2003      1    1     5      30     5.500000   
11    48     1         6  2003      1    1     6       0     6.000000   
12    51     0         7  2003      1    1     7       0     7.000000   
13    60     0         8  2003      1    1     8      30     8.500000   
14    71     0         9  2003      1    1    11      45    11.750000   
15    74     0        10  2003      1    1    12       0    12.000000   
16    84     0        10  2003      1    1    12       0    12.000000   
17    83     0        10  2003      1    1    12       0    12.000000   
18    79     1        10  2003      1    1    12       0    12.000000   
19    77     1        10  2003      1    1    12       0    12.000000   

    hundred_block  ...  signal_200  trees_25  trees_100  rain_mm  snow_cm  \
0              76  ...           9         7         55     21.6      0.0   
1             416  ...           7         5         55     21.6      0.0   
2              77  ...           9         3         78     21.6      0.0   
3             319  ...           7        13         62     21.6      0.0   
4             577  ...           6         8         49     21.6      0.0   
5             859  ...           6         0         22     21.6      0.0   
6             450  ...          10         9         70     21.6      0.0   
7             796  ...          10         7         59     21.6      0.0   
8             788  ...           9        11         72     21.6      0.0   
9              77  ...           9         3         78     21.6      0.0   
10             43  ...           9         2         48     21.6      0.0   
11            560  ...          10         2         27     21.6      0.0   
12            502  ...           6         9         48     21.6      0.0   
13            323  ...           8         0          7     21.6      0.0   
14            971  ...          11         4         23     21.6      0.0   
15            394  ...           5         5         24     21.6      0.0   
16            274  ...           4         8         42     21.6      0.0   
17            260  ...           7         5         58     21.6      0.0   
18            720  ...           2         0          0     21.6      0.0   
19            504  ...          10         0         39     21.6      0.0   

    total_precip_mm  temp_c  humidity  pressure  hours_of_light  
0              21.6     5.8      81.0    101.70            9.53  
1              21.6     5.8      81.0    101.70            9.53  
2              21.6     5.8      81.0    101.70            9.53  
3              21.6     5.8      81.0    101.70            9.53  
4              21.6     5.8      81.0    101.70            9.53  
5              21.6     5.8      81.0    101.70            9.53  
6              21.6     6.2      78.0    101.73            9.53  
7              21.6     6.6      76.0    101.71            9.53  
8              21.6     5.5      88.0    101.73            9.53  
9              21.6     5.5      88.0    101.70            9.53  
10             21.6     6.1      89.0    101.61            9.53  
11             21.6     5.5      96.0    101.58            9

In [5]:
# Scale the Data

#from sklearn.preprocessing import StandardScaler
#scaler = StandardScaler()

columns = [col for col in crime if col not in ['c_id']] # 'type', 


# Properly scale the reduced set of features
features = crime[columns]

from sklearn.preprocessing import MinMaxScaler
scaler = preprocessing.MinMaxScaler()

print(scaler.fit(features))

MinMaxScaler(copy=True, feature_range=(0, 1))


In [6]:
scaler = MinMaxScaler().fit(features.values) # scaler = MinMaxScaler().fit(features.values)
features = scaler.transform(features.values) # features = scaler.transform(features.values)
crime[columns] = features
crime

c_id  type  datetime  year     month       day      hour    minute  \
0           16   0.0  0.000000   0.0  0.000000  0.000000  0.000000  0.084746   
1           21   0.0  0.000000   0.0  0.000000  0.000000  0.000000  0.508475   
2            7   0.0  0.000000   0.0  0.000000  0.000000  0.000000  0.000000   
3           11   0.0  0.000000   0.0  0.000000  0.000000  0.000000  0.000000   
4            2   0.0  0.000000   0.0  0.000000  0.000000  0.000000  0.000000   
...        ...   ...       ...   ...       ...       ...       ...       ...   
134727  552403   0.0  0.999963   1.0  0.636364  0.933333  0.782609  0.559322   
134728  552406   0.0  0.999975   1.0  0.636364  0.933333  0.826087  0.881356   
134729  552409   0.0  0.999988   1.0  0.636364  0.933333  0.956522  0.694915   
134730  552408   0.0  0.999988   1.0  0.636364  0.933333  0.956522  0.322034   
134731  552413   0.0  1.000000   1.0  0.636364  0.966667  0.913043  0.644068   

        Hour_Minute  hundred_block  ...  signal_200  trees_25  trees_100  \
0          0.003475       0.052741  ...    0.600000      0.35   0.523810   
1          0.020848       0.288688  ...    0.466667      0.25   0.523810   
2          0.000000       0.053435  ...    0.600000      0.15   0.742857   
3          0.000000       0.221374  ...    0.466667      0.65   0.590476   
4          0.000000       0.400416  ...    0.400000      0.40   0.466667   
...             ...            ...  ...         ...       ...        ...   
134727     0.773454       0.492019  ...    0.733333      0.15   0.457143   
134728     0.828353       0.453158  ...    0.600000      0.00   0.390476   
134729     0.945796       0.909785  ...    0.800000      0.20   0.438095   
134730     0.930507       0.190146  ...    0.266667      0.45   0.466667   
134731     0.902015       0.850104  ...    0.733333      0.45   0.714286   

         rain_mm  snow_cm  total_precip_mm    temp_c  humidity  pressure  \
0       0.235808      0.0         0.235808  0.410148  0.781609  0.612081   
1       0.235808      0.0         0.235808  0.410148  0.781609  0.612081   
2       0.235808      0.0         0.235808  0.410148  0.781609  0.612081   
3       0.235808      0.0         0.235808  0.410148  0.781609  0.612081   
4       0.235808      0.0         0.235808  0.410148  0.781609  0.612081   
...          ...      ...              ...       ...       ...       ...   
134727  0.000000      0.0         0.000000  0.731501  0.586207  0.558389   
134728  0.000000      0.0         0.000000  0.720930  0.609195  0.562416   
134729  0.000000      0.0         0.000000  0.714588  0.632184  0.577181   
134730  0.000000      0.0         0.000000  0.714588  0.632184  0.577181   
134731  0.000000      0.0         0.000000  0.684989  0.758621  0.597315   

        hours_of_light  
0             0.010909  
1             0.010909  
2             0.010909  
3             0.010909  
4             0.010909  
...                ...  
134727        0.642424  
134728        0.642424  
134729        0.642424  
134730        0.642424  
134731        0.635152  

[134732 rows x 32 columns]

In [7]:
# split training data into training and testing
from sklearn.model_selection import train_test_split

# Select columns to that are data
cols = [col for col in crime if col not in ['type', 'c_id']]

X = crime[cols]

# Select target data
y = crime['type']

X_train, X_test, y_train, y_test = train_test_split(X, y, random_state=100, test_size=0.3)
print(X_train.shape)

(94312, 30)


In [8]:
# Trying Random Forest Classifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.feature_selection import SelectFromModel

model_tree = RandomForestClassifier(random_state=100, n_estimators=50)
model_tree.fit(X_train, y_train)
print(model_tree.feature_importances_)
sel_model_tree = SelectFromModel(estimator=model_tree, prefit=True, threshold='mean')  
      # since we already fit the data, we specify prefit option here
      # Features whose importance is greater or equal to the threshold are kept while the others are discarded.
X_train_sfm_tree = sel_model_tree.transform(X_train)
print(sel_model_tree.get_support())

feature_importances = pd.DataFrame(model_tree.feature_importances_,
                                   index = X_train.columns,
                                    columns=['importance']).sort_values('importance', 
                                                                        ascending=False)

[0.05534295 0.03151843 0.02668176 0.03985797 0.05651209 0.03481184
 0.0805264  0.04928864 0.         0.04146357 0.04155306 0.04130594
 0.04250027 0.01568595 0.0302971  0.03195862 0.03678022 0.00834626
 0.00681001 0.0126053  0.02069124 0.02486606 0.03628267 0.02377248
 0.00243176 0.02307954 0.04723047 0.04218019 0.04888958 0.04672963]
[ True False False  True  True  True  True  True False  True  True  True
  True False False False  True False False False False False  True False
 False False  True  True  True  True]


In [9]:
feature_importances

importance
Hour_Minute        0.080526
hour               0.056512
datetime           0.055343
hundred_block      0.049289
pressure           0.048890
temp_c             0.047230
hours_of_light     0.046730
longitude          0.042500
humidity           0.042180
utm_y              0.041553
utm_x              0.041464
latitude           0.041306
day                0.039858
light_pole_100     0.036780
trees_100          0.036283
minute             0.034812
light_pole_50      0.031959
year               0.031518
light_pole_25      0.030297
month              0.026682
trees_25           0.024866
rain_mm            0.023772
total_precip_mm    0.023080
signal_200         0.020691
light_pole_12_5    0.015686
signal_100         0.012605
signal_25          0.008346
signal_50          0.006810
snow_cm            0.002432
neighbourhood      0.000000

In [14]:
# Simple Neural Network

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import sklearn
from sklearn.neural_network import MLPClassifier
from sklearn.neural_network import MLPRegressor

# import needed modules
from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_squared_error
from math import sqrt
from sklearn.metrics import r2_score

In [15]:
# Try using the MLP Classifier
mlp = MLPClassifier(hidden_layer_sizes=(30, 30, 30), activation='relu', solver='adam', max_iter=300)
mlp.fit(X_train, y_train)

predict_train = mlp.predict(X_train)
predict_test = mlp.predict(X_test)

In [16]:
from sklearn.metrics import classification_report, confusion_matrix
print(confusion_matrix(y_train, predict_train))
print(classification_report(y_train, predict_train))

[[82860  1241]
 [ 7944  2267]]
              precision    recall  f1-score   support

         0.0       0.91      0.99      0.95     84101
         1.0       0.65      0.22      0.33     10211

    accuracy                           0.90     94312
   macro avg       0.78      0.60      0.64     94312
weighted avg       0.88      0.90      0.88     94312



In [17]:
print(confusion_matrix(y_test, predict_test))
print(classification_report(y_test, predict_test))

[[35403   773]
 [ 3517   727]]
              precision    recall  f1-score   support

         0.0       0.91      0.98      0.94     36176
         1.0       0.48      0.17      0.25      4244

    accuracy                           0.89     40420
   macro avg       0.70      0.57      0.60     40420
weighted avg       0.87      0.89      0.87     40420



In [18]:
# Try using the MLP Classifier
mlp = MLPClassifier(hidden_layer_sizes=(30, 30, 30), activation='relu', solver='adam', max_iter=3000)
mlp.fit(X_train, y_train)

predict_train = mlp.predict(X_train)
predict_test = mlp.predict(X_test)

In [19]:
print(confusion_matrix(y_train, predict_train))
print(classification_report(y_train, predict_train))

[[83214   887]
 [ 8170  2041]]
              precision    recall  f1-score   support

         0.0       0.91      0.99      0.95     84101
         1.0       0.70      0.20      0.31     10211

    accuracy                           0.90     94312
   macro avg       0.80      0.59      0.63     94312
weighted avg       0.89      0.90      0.88     94312



In [20]:
print(confusion_matrix(y_test, predict_test))
print(classification_report(y_test, predict_test))

[[35571   605]
 [ 3625   619]]
              precision    recall  f1-score   support

         0.0       0.91      0.98      0.94     36176
         1.0       0.51      0.15      0.23      4244

    accuracy                           0.90     40420
   macro avg       0.71      0.56      0.59     40420
weighted avg       0.87      0.90      0.87     40420



In [21]:
feature_importances

importance
Hour_Minute        0.080526
hour               0.056512
datetime           0.055343
hundred_block      0.049289
pressure           0.048890
temp_c             0.047230
hours_of_light     0.046730
longitude          0.042500
humidity           0.042180
utm_y              0.041553
utm_x              0.041464
latitude           0.041306
day                0.039858
light_pole_100     0.036780
trees_100          0.036283
minute             0.034812
light_pole_50      0.031959
year               0.031518
light_pole_25      0.030297
month              0.026682
trees_25           0.024866
rain_mm            0.023772
total_precip_mm    0.023080
signal_200         0.020691
light_pole_12_5    0.015686
signal_100         0.012605
signal_25          0.008346
signal_50          0.006810
snow_cm            0.002432
neighbourhood      0.000000

In [22]:
# Cut down features

# split training data into training and testing
from sklearn.model_selection import train_test_split

# Select columns to that are data
cols = [col for col in crime if col in ['Hour_Minute', 'hundred_block', 'pressure', 'temp_c', 
                                       'hours_of_light', 'humidity', 'light_pole_100', 'trees_100', 
                                       'rain_mm', 'signal_200']]

X = crime[cols]

# Select target data
y = crime['type']

X_train, X_test, y_train, y_test = train_test_split(X, y, random_state=100, test_size=0.3)
print(X_train.shape)

(94312, 10)


In [23]:
X

Hour_Minute  hundred_block  light_pole_100  signal_200  trees_100  \
0          0.003475       0.052741        0.504425    0.600000   0.523810   
1          0.020848       0.288688        0.575221    0.466667   0.523810   
2          0.000000       0.053435        0.548673    0.600000   0.742857   
3          0.000000       0.221374        0.557522    0.466667   0.590476   
4          0.000000       0.400416        0.318584    0.400000   0.466667   
...             ...            ...             ...         ...        ...   
134727     0.773454       0.492019        0.814159    0.733333   0.457143   
134728     0.828353       0.453158        0.504425    0.600000   0.390476   
134729     0.945796       0.909785        0.734513    0.800000   0.438095   
134730     0.930507       0.190146        0.522124    0.266667   0.466667   
134731     0.902015       0.850104        0.539823    0.733333   0.714286   

         rain_mm    temp_c  humidity  pressure  hours_of_light  
0       0.235808  0.410148  0.781609  0.612081        0.010909  
1       0.235808  0.410148  0.781609  0.612081        0.010909  
2       0.235808  0.410148  0.781609  0.612081        0.010909  
3       0.235808  0.410148  0.781609  0.612081        0.010909  
4       0.235808  0.410148  0.781609  0.612081        0.010909  
...          ...       ...       ...       ...             ...  
134727  0.000000  0.731501  0.586207  0.558389        0.642424  
134728  0.000000  0.720930  0.609195  0.562416        0.642424  
134729  0.000000  0.714588  0.632184  0.577181        0.642424  
134730  0.000000  0.714588  0.632184  0.577181        0.642424  
134731  0.000000  0.684989  0.758621  0.597315        0.635152  

[134732 rows x 10 columns]

In [28]:
# Trying Random Forest Classifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.feature_selection import SelectFromModel

model_tree = RandomForestClassifier(random_state=100, n_estimators=50)
model_tree.fit(X_train, y_train)
print(model_tree.feature_importances_)
sel_model_tree = SelectFromModel(estimator=model_tree, prefit=True, threshold='mean')  
      # since we already fit the data, we specify prefit option here
      # Features whose importance is greater or equal to the threshold are kept while the others are discarded.
X_train_sfm_tree = sel_model_tree.transform(X_train)
print(sel_model_tree.get_support())

feature_importances = pd.DataFrame(model_tree.feature_importances_,
                                   index = X_train.columns,
                                    columns=['importance']).sort_values('importance', 
                                                                        ascending=False)

feature_importances

[0.17055524 0.11940996 0.09616009 0.05097552 0.09728977 0.05520321
 0.10545767 0.08837415 0.1082667  0.1083077 ]
[ True  True False False False False  True False  True  True]


importance
Hour_Minute       0.170555
hundred_block     0.119410
hours_of_light    0.108308
pressure          0.108267
temp_c            0.105458
trees_100         0.097290
light_pole_100    0.096160
humidity          0.088374
rain_mm           0.055203
signal_200        0.050976

In [25]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import sklearn
from sklearn.neural_network import MLPClassifier
from sklearn.neural_network import MLPRegressor

# import needed modules
from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_squared_error
from math import sqrt
from sklearn.metrics import r2_score

# Try using the MLP Classifier
mlp = MLPClassifier(hidden_layer_sizes=(10, 10, 10), activation='relu', solver='adam', max_iter=5000)
mlp.fit(X_train, y_train)

predict_train = mlp.predict(X_train)
predict_test = mlp.predict(X_test)

In [26]:
from sklearn.metrics import classification_report, confusion_matrix
print(confusion_matrix(y_train, predict_train))
print(classification_report(y_train, predict_train))

[[83837   264]
 [ 9935   276]]
              precision    recall  f1-score   support

         0.0       0.89      1.00      0.94     84101
         1.0       0.51      0.03      0.05     10211

    accuracy                           0.89     94312
   macro avg       0.70      0.51      0.50     94312
weighted avg       0.85      0.89      0.85     94312



In [27]:
print(confusion_matrix(y_test, predict_test))
print(classification_report(y_test, predict_test))

[[36050   126]
 [ 4139   105]]
              precision    recall  f1-score   support

         0.0       0.90      1.00      0.94     36176
         1.0       0.45      0.02      0.05      4244

    accuracy                           0.89     40420
   macro avg       0.68      0.51      0.50     40420
weighted avg       0.85      0.89      0.85     40420



In [29]:
# Cut down features further

# split training data into training and testing
from sklearn.model_selection import train_test_split

# Select columns to that are data
cols = [col for col in crime if col in ['Hour_Minute', 'hundred_block', 'pressure', 'temp_c', 
                                       'hours_of_light']]

X = crime[cols]

# Select target data
y = crime['type']

X_train, X_test, y_train, y_test = train_test_split(X, y, random_state=100, test_size=0.3)
print(X_train.shape)

(94312, 5)


In [30]:
# Trying Random Forest Classifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.feature_selection import SelectFromModel

model_tree = RandomForestClassifier(random_state=100, n_estimators=50)
model_tree.fit(X_train, y_train)
print(model_tree.feature_importances_)
sel_model_tree = SelectFromModel(estimator=model_tree, prefit=True, threshold='mean')  
      # since we already fit the data, we specify prefit option here
      # Features whose importance is greater or equal to the threshold are kept while the others are discarded.
X_train_sfm_tree = sel_model_tree.transform(X_train)
print(sel_model_tree.get_support())

feature_importances = pd.DataFrame(model_tree.feature_importances_,
                                   index = X_train.columns,
                                    columns=['importance']).sort_values('importance', 
                                                                        ascending=False)

feature_importances

[0.2289075  0.22410992 0.17387269 0.18553633 0.18757356]
[ True  True False False False]


importance
Hour_Minute       0.228907
hundred_block     0.224110
hours_of_light    0.187574
pressure          0.185536
temp_c            0.173873

In [37]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import sklearn
from sklearn.neural_network import MLPClassifier
from sklearn.neural_network import MLPRegressor

# import needed modules
from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_squared_error
from math import sqrt
from sklearn.metrics import r2_score

# Try using the MLP Classifier
mlp = MLPClassifier(hidden_layer_sizes=(5, 5, 5), activation='relu', solver='adam', max_iter=5000)
mlp.fit(X_train, y_train)

predict_train = mlp.predict(X_train)
predict_test = mlp.predict(X_test)

In [38]:
from sklearn.metrics import classification_report, confusion_matrix
print(confusion_matrix(y_train, predict_train))
print(classification_report(y_train, predict_train))

[[84101     0]
 [10211     0]]
              precision    recall  f1-score   support

         0.0       0.89      1.00      0.94     84101
         1.0       0.00      0.00      0.00     10211

    accuracy                           0.89     94312
   macro avg       0.45      0.50      0.47     94312
weighted avg       0.80      0.89      0.84     94312



d:\program files (x86)\microsoft visual studio\shared\python37_64\lib\site-packages\sklearn\metrics\classification.py:1437: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)


In [39]:
print(confusion_matrix(y_test, predict_test))
print(classification_report(y_test, predict_test))

[[36176     0]
 [ 4244     0]]
              precision    recall  f1-score   support

         0.0       0.90      1.00      0.94     36176
         1.0       0.00      0.00      0.00      4244

    accuracy                           0.90     40420
   macro avg       0.45      0.50      0.47     40420
weighted avg       0.80      0.90      0.85     40420

