In [4]:
import pandas as pd
import numpy as np
%matplotlib inline
import matplotlib.pyplot as plt
import sklearn

crime = pd.read_csv('E:/Vancouver Crime Final/vancouver_crime_complete.csv')

crime.head()

c_id                               type             datetime  year  month  \
0     1                 Theft from Vehicle  2003-01-01 00:00:00  2003      1   
1     2                   Theft of Bicycle  2003-01-01 00:00:00  2003      1   
2     3  Break and Enter Residential/Other  2003-01-01 00:00:00  2003      1   
3     4                   Theft of Bicycle  2003-01-01 00:00:00  2003      1   
4     6                           Mischief  2003-01-01 00:00:00  2003      1   

   day  hour  minute  Hour_Minute     hundred_block  ... signal_200  trees_25  \
0    1     0       0          0.0  57XX CULLODEN ST  ...          2         6   
1    1     0       0          0.0      6X KEEFER PL  ...          6         8   
2    1     0       0          0.0    9XX W 15TH AVE  ...          2         0   
3    1     0       0          0.0    30XX W 4TH AVE  ...          2         6   
4    1     0       0          0.0    17XX PARKER ST  ...          3         7   

   trees_100  rain_mm  snow_cm  total_precip_mm  temp_c  humidity  pressure  \
0         49     21.6      0.0             21.6     5.8      81.0     101.7   
1         49     21.6      0.0             21.6     5.8      81.0     101.7   
2         32     21.6      0.0             21.6     5.8      81.0     101.7   
3         21     21.6      0.0             21.6     5.8      81.0     101.7   
4         58     21.6      0.0             21.6     5.8      81.0     101.7   

   hours_of_light  
0            9.53  
1            9.53  
2            9.53  
3            9.53  
4            9.53  

[5 rows x 32 columns]

In [5]:
# Set Break and ENters to 1 and everything else to 0

crime = crime.replace(['Vehicle Collision or Pedestrian Struck (with Injury)',
                       'Vehicle Collision or Pedestrian Struck (with Fatality)'], 0)

crime = crime.replace(['Mischief', 'Theft from Vehicle', 'Other Theft',
                       'Theft of Vehicle', 'Theft of Bicycle'], 1)

crime = crime.replace(['Break and Enter Residential/Other', 'Break and Enter Commercial'], 2)

crime.head()

c_id  type             datetime  year  month  day  hour  minute  \
0     1     1  2003-01-01 00:00:00  2003      1    1     0       0   
1     2     1  2003-01-01 00:00:00  2003      1    1     0       0   
2     3     2  2003-01-01 00:00:00  2003      1    1     0       0   
3     4     1  2003-01-01 00:00:00  2003      1    1     0       0   
4     6     1  2003-01-01 00:00:00  2003      1    1     0       0   

   Hour_Minute     hundred_block  ... signal_200  trees_25  trees_100  \
0          0.0  57XX CULLODEN ST  ...          2         6         49   
1          0.0      6X KEEFER PL  ...          6         8         49   
2          0.0    9XX W 15TH AVE  ...          2         0         32   
3          0.0    30XX W 4TH AVE  ...          2         6         21   
4          0.0    17XX PARKER ST  ...          3         7         58   

   rain_mm  snow_cm  total_precip_mm  temp_c  humidity  pressure  \
0     21.6      0.0             21.6     5.8      81.0     101.7   
1     21.6      0.0             21.6     5.8      81.0     101.7   
2     21.6      0.0             21.6     5.8      81.0     101.7   
3     21.6      0.0             21.6     5.8      81.0     101.7   
4     21.6      0.0             21.6     5.8      81.0     101.7   

   hours_of_light  
0            9.53  
1            9.53  
2            9.53  
3            9.53  
4            9.53  

[5 rows x 32 columns]

In [6]:
### Begin Processing the Data


# Import Pre-processing module
from sklearn import preprocessing

# Create Label Encoder
le = preprocessing.LabelEncoder()

# Convert the string columns to numeric
# .astype(str) to ensude they are read as strings and not as mixed types
crime['datetime'] = le.fit_transform(crime['datetime'].astype(str))
crime['hundred_block'] = le.fit_transform(crime['hundred_block'].astype(str))
crime['neighbourhood'] = le.fit_transform(crime['neighbourhood'].astype(str))



# Display the results
crime.head(20)

c_id  type  datetime  year  month  day  hour  minute  Hour_Minute  \
0      1     1         0  2003      1    1     0       0     0.000000   
1      2     1         0  2003      1    1     0       0     0.000000   
2      3     2         0  2003      1    1     0       0     0.000000   
3      4     1         0  2003      1    1     0       0     0.000000   
4      6     1         0  2003      1    1     0       0     0.000000   
5      7     1         0  2003      1    1     0       0     0.000000   
6      8     1         0  2003      1    1     0       0     0.000000   
7      9     2         0  2003      1    1     0       0     0.000000   
8     10     1         0  2003      1    1     0       0     0.000000   
9     11     1         0  2003      1    1     0       0     0.000000   
10    12     1         0  2003      1    1     0       0     0.000000   
11    14     2         0  2003      1    1     0       1     0.016667   
12    15     1         0  2003      1    1     0       1     0.016667   
13    16     1         0  2003      1    1     0       5     0.083333   
14    17     0         0  2003      1    1     0      19     0.316667   
15    18     2         0  2003      1    1     0      20     0.333333   
16    19     1         0  2003      1    1     0      30     0.500000   
17    20     1         0  2003      1    1     0      30     0.500000   
18    21     1         0  2003      1    1     0      30     0.500000   
19    22     1         1  2003      1    1     1       0     1.000000   

    hundred_block  ...  signal_200  trees_25  trees_100  rain_mm  snow_cm  \
0           10688  ...           2         6         49     21.6      0.0   
1           12335  ...           6         8         49     21.6      0.0   
2           14807  ...           2         0         32     21.6      0.0   
3            6346  ...           2         6         21     21.6      0.0   
4            2172  ...           3         7         58     21.6      0.0   
5             481  ...           9         3         78     21.6      0.0   
6             264  ...           1         5         31     21.6      0.0   
7           11852  ...           2         5         40     21.6      0.0   
8            6995  ...           0        14         62     21.6      0.0   
9            5950  ...           7        13         62     21.6      0.0   
10           4482  ...           1        10         74     21.6      0.0   
11           7278  ...           3         6         38     21.6      0.0   
12           4876  ...           2         8         38     21.6      0.0   
13            480  ...           9         7         55     21.6      0.0   
14          19644  ...           5         5         46     21.6      0.0   
15           2687  ...           1         8         88     21.6      0.0   
16          14669  ...           6         0         22     21.6      0.0   
17           1697  ...           4         7         59     21.6      0.0   
18           9726  ...           7         5         55     21.6      0.0   
19           1102  ...           1         1         17     21.6      0.0   

    total_precip_mm  temp_c  humidity  pressure  hours_of_light  
0              21.6     5.8      81.0    101.70            9.53  
1              21.6     5.8      81.0    101.70            9.53  
2              21.6     5.8      81.0    101.70            9.53  
3              21.6     5.8      81.0    101.70            9.53  
4              21.6     5.8      81.0    101.70            9.53  
5              21.6     5.8      81.0    101.70            9.53  
6              21.6     5.8      81.0    101.70            9.53  
7              21.6     5.8      81.0    101.70            9.53  
8              21.6     5.8      81.0    101.70            9.53  
9              21.6     5.8      81.0    101.70            9.53  
10             21.6     5.8      81.0    101.70            9.53  
11             21.6     5.8      81.0    101.70            9

In [7]:
# Scale the Data

#from sklearn.preprocessing import StandardScaler
#scaler = StandardScaler()

columns = [col for col in crime if col not in ['c_id', 'type']] # 'type', 


# Properly scale the reduced set of features
features = crime[columns]

from sklearn.preprocessing import MinMaxScaler
scaler = preprocessing.MinMaxScaler()

print(scaler.fit(features))

MinMaxScaler(copy=True, feature_range=(0, 1))


In [8]:
scaler = MinMaxScaler().fit(features.values) # scaler = MinMaxScaler().fit(features.values)
features = scaler.transform(features.values) # features = scaler.transform(features.values)
crime[columns] = features
crime

c_id  type  datetime  year     month       day      hour    minute  \
0            1     1  0.000000   0.0  0.000000  0.000000  0.000000  0.000000   
1            2     1  0.000000   0.0  0.000000  0.000000  0.000000  0.000000   
2            3     2  0.000000   0.0  0.000000  0.000000  0.000000  0.000000   
3            4     1  0.000000   0.0  0.000000  0.000000  0.000000  0.000000   
4            6     1  0.000000   0.0  0.000000  0.000000  0.000000  0.000000   
...        ...   ...       ...   ...       ...       ...       ...       ...   
550400  552409     1  0.999978   1.0  0.636364  0.933333  0.956522  0.694915   
550401  552410     1  0.999985   1.0  0.636364  0.933333  1.000000  0.118644   
550402  552411     1  0.999985   1.0  0.636364  0.933333  1.000000  0.966102   
550403  552412     0  0.999993   1.0  0.636364  0.966667  0.695652  0.813559   
550404  552413     0  1.000000   1.0  0.636364  0.966667  0.913043  0.644068   

        Hour_Minute  hundred_block  ...  signal_200  trees_25  trees_100  \
0          0.000000       0.485973  ...    0.133333  0.181818   0.374046   
1          0.000000       0.560860  ...    0.400000  0.242424   0.374046   
2          0.000000       0.673260  ...    0.133333  0.000000   0.244275   
3          0.000000       0.288546  ...    0.133333  0.181818   0.160305   
4          0.000000       0.098759  ...    0.200000  0.212121   0.442748   
...             ...            ...  ...         ...       ...        ...   
550400     0.945796       0.923203  ...    0.800000  0.121212   0.351145   
550401     0.963864       0.065021  ...    0.066667  0.242424   0.465649   
550402     0.998610       0.432592  ...    0.000000  0.090909   0.244275   
550403     0.700486       0.880189  ...    0.200000  0.151515   0.442748   
550404     0.902015       0.892830  ...    0.733333  0.272727   0.572519   

         rain_mm  snow_cm  total_precip_mm    temp_c  humidity  pressure  \
0       0.235808      0.0         0.235808  0.408421  0.781609  0.612081   
1       0.235808      0.0         0.235808  0.408421  0.781609  0.612081   
2       0.235808      0.0         0.235808  0.408421  0.781609  0.612081   
3       0.235808      0.0         0.235808  0.408421  0.781609  0.612081   
4       0.235808      0.0         0.235808  0.408421  0.781609  0.612081   
...          ...      ...              ...       ...       ...       ...   
550400  0.000000      0.0         0.000000  0.711579  0.632184  0.577181   
550401  0.000000      0.0         0.000000  0.692632  0.678161  0.578523   
550402  0.000000      0.0         0.000000  0.692632  0.678161  0.578523   
550403  0.000000      0.0         0.000000  0.751579  0.597701  0.605369   
550404  0.000000      0.0         0.000000  0.682105  0.758621  0.597315   

        hours_of_light  
0             0.010909  
1             0.010909  
2             0.010909  
3             0.010909  
4             0.010909  
...                ...  
550400        0.642424  
550401        0.642424  
550402        0.642424  
550403        0.635152  
550404        0.635152  

[550405 rows x 32 columns]

In [9]:
# split training data into training and testing
from sklearn.model_selection import train_test_split

# Select columns to that are data
cols = [col for col in crime if col not in ['type', 'c_id']]

X = crime[cols]

# Select target data
y = crime['type']#.astype('int32')

X_train, X_test, y_train, y_test = train_test_split(X, y, random_state=100, test_size=0.3)
print(X_train.shape)

(385283, 30)


In [10]:
# Trying Random Forest Classifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.feature_selection import SelectFromModel

model_tree = RandomForestClassifier(random_state=100, n_estimators=50)
model_tree.fit(X_train, y_train)
print(model_tree.feature_importances_)
sel_model_tree = SelectFromModel(estimator=model_tree, prefit=True, threshold='mean')  
      # since we already fit the data, we specify prefit option here
      # Features whose importance is greater or equal to the threshold are kept while the others are discarded.
X_train_sfm_tree = sel_model_tree.transform(X_train)
print(sel_model_tree.get_support())

feature_importances = pd.DataFrame(model_tree.feature_importances_,
                                   index = X_train.columns,
                                    columns=['importance']).sort_values('importance', 
                                                                        ascending=False)

[0.04758859 0.02525161 0.02186864 0.03417254 0.03588501 0.0458769
 0.05610507 0.0885422  0.01677232 0.0487179  0.05253428 0.0505062
 0.04886044 0.01390613 0.02623493 0.03017259 0.04068948 0.00626509
 0.00475871 0.01042383 0.02259488 0.02724047 0.04288457 0.02002141
 0.00175239 0.01999158 0.04083857 0.03660101 0.0422639  0.04067874]
[ True False False  True  True  True  True  True False  True  True  True
  True False False False  True False False False False False  True False
 False False  True  True  True  True]


In [11]:
feature_importances

importance
hundred_block      0.088542
Hour_Minute        0.056105
utm_y              0.052534
latitude           0.050506
longitude          0.048860
utm_x              0.048718
datetime           0.047589
minute             0.045877
trees_100          0.042885
pressure           0.042264
temp_c             0.040839
light_pole_100     0.040689
hours_of_light     0.040679
humidity           0.036601
hour               0.035885
day                0.034173
light_pole_50      0.030173
trees_25           0.027240
light_pole_25      0.026235
year               0.025252
signal_200         0.022595
month              0.021869
rain_mm            0.020021
total_precip_mm    0.019992
neighbourhood      0.016772
light_pole_12_5    0.013906
signal_100         0.010424
signal_25          0.006265
signal_50          0.004759
snow_cm            0.001752

In [12]:
# Simple Neural Network

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import sklearn
from sklearn.neural_network import MLPClassifier
from sklearn.neural_network import MLPRegressor

# import needed modules
from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_squared_error
from math import sqrt
from sklearn.metrics import r2_score

In [13]:
# Try using the MLP Classifier
mlp = MLPClassifier(hidden_layer_sizes=(30, 30, 30), activation='relu', solver='adam', max_iter=200)
mlp.fit(X_train, y_train)

predict_train = mlp.predict(X_train)
predict_test = mlp.predict(X_test)

In [14]:
from sklearn.metrics import classification_report, confusion_matrix
print(confusion_matrix(y_train, predict_train))
print(classification_report(y_train, predict_train))

[[  8883   8156    617]
 [  3053 280421  11336]
 [   238  58221  14358]]
              precision    recall  f1-score   support

           0       0.73      0.50      0.60     17656
           1       0.81      0.95      0.87    294810
           2       0.55      0.20      0.29     72817

    accuracy                           0.79    385283
   macro avg       0.69      0.55      0.59    385283
weighted avg       0.76      0.79      0.75    385283



In [15]:
print(confusion_matrix(y_test, predict_test))
print(classification_report(y_test, predict_test))

[[  3793   3565    226]
 [  1395 119760   5057]
 [   115  25164   6047]]
              precision    recall  f1-score   support

           0       0.72      0.50      0.59      7584
           1       0.81      0.95      0.87    126212
           2       0.53      0.19      0.28     31326

    accuracy                           0.78    165122
   macro avg       0.69      0.55      0.58    165122
weighted avg       0.75      0.78      0.75    165122



In [16]:
# Try using the MLP Classifier
mlp = MLPClassifier(hidden_layer_sizes=(30, 30, 30), activation='relu', solver='adam', max_iter=200)
mlp.fit(X_train, y_train)

predict_train = mlp.predict(X_train)
predict_test = mlp.predict(X_test)

In [17]:
print(confusion_matrix(y_train, predict_train))
print(classification_report(y_train, predict_train))

[[  9986   7164    506]
 [  4049 281012   9749]
 [   364  59106  13347]]
              precision    recall  f1-score   support

           0       0.69      0.57      0.62     17656
           1       0.81      0.95      0.88    294810
           2       0.57      0.18      0.28     72817

    accuracy                           0.79    385283
   macro avg       0.69      0.57      0.59    385283
weighted avg       0.76      0.79      0.75    385283



In [18]:
print(confusion_matrix(y_test, predict_test))
print(classification_report(y_test, predict_test))

[[  4301   3079    204]
 [  1769 120062   4381]
 [   172  25540   5614]]
              precision    recall  f1-score   support

           0       0.69      0.57      0.62      7584
           1       0.81      0.95      0.87    126212
           2       0.55      0.18      0.27     31326

    accuracy                           0.79    165122
   macro avg       0.68      0.57      0.59    165122
weighted avg       0.75      0.79      0.75    165122



In [19]:
feature_importances

importance
hundred_block      0.088542
Hour_Minute        0.056105
utm_y              0.052534
latitude           0.050506
longitude          0.048860
utm_x              0.048718
datetime           0.047589
minute             0.045877
trees_100          0.042885
pressure           0.042264
temp_c             0.040839
light_pole_100     0.040689
hours_of_light     0.040679
humidity           0.036601
hour               0.035885
day                0.034173
light_pole_50      0.030173
trees_25           0.027240
light_pole_25      0.026235
year               0.025252
signal_200         0.022595
month              0.021869
rain_mm            0.020021
total_precip_mm    0.019992
neighbourhood      0.016772
light_pole_12_5    0.013906
signal_100         0.010424
signal_25          0.006265
signal_50          0.004759
snow_cm            0.001752

In [20]:
###################################

# Cut down features

# split training data into training and testing
from sklearn.model_selection import train_test_split

# Select columns to that are data
cols = [col for col in crime if col not in ['latitude', 'longitude', 'minute', 'hour', 'year']]

X = crime[cols]

# Select target data
y = crime['type']

X_train, X_test, y_train, y_test = train_test_split(X, y, random_state=100, test_size=0.3)
print(X_train.shape)

(385283, 27)


In [21]:
X

c_id  type  datetime     month       day  Hour_Minute  \
0            1     1  0.000000  0.000000  0.000000     0.000000   
1            2     1  0.000000  0.000000  0.000000     0.000000   
2            3     2  0.000000  0.000000  0.000000     0.000000   
3            4     1  0.000000  0.000000  0.000000     0.000000   
4            6     1  0.000000  0.000000  0.000000     0.000000   
...        ...   ...       ...       ...       ...          ...   
550400  552409     1  0.999978  0.636364  0.933333     0.945796   
550401  552410     1  0.999985  0.636364  0.933333     0.963864   
550402  552411     1  0.999985  0.636364  0.933333     0.998610   
550403  552412     0  0.999993  0.636364  0.966667     0.700486   
550404  552413     0  1.000000  0.636364  0.966667     0.902015   

        hundred_block  neighbourhood     utm_x     utm_y  ...  signal_200  \
0            0.485973       0.833333  0.861566  0.226076  ...    0.133333   
1            0.560860       0.041667  0.844855  0.295102  ...    0.400000   
2            0.673260       0.125000  0.833142  0.263559  ...    0.133333   
3            0.288546       0.375000  0.805729  0.278948  ...    0.133333   
4            0.098759       0.166667  0.867226  0.289523  ...    0.200000   
...               ...            ...       ...       ...  ...         ...   
550400       0.923203       0.041667  0.840711  0.301497  ...    0.800000   
550401       0.065021       0.166667  0.863783  0.286863  ...    0.066667   
550402       0.432592       0.000000  0.813288  0.243174  ...    0.000000   
550403       0.880189       0.375000  0.819051  0.278433  ...    0.200000   
550404       0.892830       0.041667  0.834662  0.295549  ...    0.733333   

        trees_25  trees_100   rain_mm  snow_cm  total_precip_mm    temp_c  \
0       0.181818   0.374046  0.235808      0.0         0.235808  0.408421   
1       0.242424   0.374046  0.235808      0.0         0.235808  0.408421   
2       0.000000   0.244275  0.235808      0.0         0.235808  0.408421   
3       0.181818   0.160305  0.235808      0.0         0.235808  0.408421   
4       0.212121   0.442748  0.235808      0.0         0.235808  0.408421   
...          ...        ...       ...      ...              ...       ...   
550400  0.121212   0.351145  0.000000      0.0         0.000000  0.711579   
550401  0.242424   0.465649  0.000000      0.0         0.000000  0.692632   
550402  0.090909   0.244275  0.000000      0.0         0.000000  0.692632   
550403  0.151515   0.442748  0.000000      0.0         0.000000  0.751579   
550404  0.272727   0.572519  0.000000      0.0         0.000000  0.682105   

        humidity  pressure  hours_of_light  
0       0.781609  0.612081        0.010909  
1       0.781609  0.612081        0.010909  
2       0.781609  0.612081        0.010909  
3       0.781609  0.612081        0.010909  
4       0.781609  0.612081        0.010909  
...          ...       ...             ...  
550400  0.632184  0.577181        0.642424  
550401  0.678161  0.578523        0.642424  
550402  0.678161  0.578523        0.642424  
550403  0.597701  0.605369        0.635152  
550404  0.758621  0.597315        0.635152  

[550405 rows x 27 columns]

In [22]:
# Trying Random Forest Classifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.feature_selection import SelectFromModel

model_tree = RandomForestClassifier(random_state=100, n_estimators=50)
model_tree.fit(X_train, y_train)
print(model_tree.feature_importances_)
sel_model_tree = SelectFromModel(estimator=model_tree, prefit=True, threshold='mean')  
      # since we already fit the data, we specify prefit option here
      # Features whose importance is greater or equal to the threshold are kept while the others are discarded.
X_train_sfm_tree = sel_model_tree.transform(X_train)
print(sel_model_tree.get_support())

feature_importances = pd.DataFrame(model_tree.feature_importances_,
                                   index = X_train.columns,
                                    columns=['importance']).sort_values('importance', 
                                                                        ascending=False)

feature_importances

[2.53431863e-03 9.00087360e-01 2.10789665e-03 6.81324434e-04
 1.06941526e-03 1.19718133e-02 2.75536799e-02 1.94116391e-03
 4.86815865e-03 7.24566760e-03 2.49328589e-03 6.35952804e-03
 3.75148611e-03 4.20967230e-03 3.42318260e-03 8.03633868e-04
 1.16078481e-03 5.96099626e-03 2.03994996e-03 2.53984309e-03
 7.04621859e-04 9.23594404e-05 7.21236036e-04 1.48947302e-03
 1.34211430e-03 1.44341232e-03 1.40362197e-03]
[False  True False False False False False False False False False False
 False False False False False False False False False False False False
 False False False]


importance
type               0.900087
hundred_block      0.027554
Hour_Minute        0.011972
utm_y              0.007246
light_pole_25      0.006360
signal_200         0.005961
utm_x              0.004868
light_pole_100     0.004210
light_pole_50      0.003751
signal_25          0.003423
trees_100          0.002540
c_id               0.002534
light_pole_12_5    0.002493
datetime           0.002108
trees_25           0.002040
neighbourhood      0.001941
temp_c             0.001489
pressure           0.001443
hours_of_light     0.001404
humidity           0.001342
signal_100         0.001161
day                0.001069
signal_50          0.000804
total_precip_mm    0.000721
rain_mm            0.000705
month              0.000681
snow_cm            0.000092

In [23]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import sklearn
from sklearn.neural_network import MLPClassifier
from sklearn.neural_network import MLPRegressor

# import needed modules
from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_squared_error
from math import sqrt
from sklearn.metrics import r2_score

# Try using the MLP Classifier
mlp = MLPClassifier(hidden_layer_sizes=(27, 27, 27), activation='relu', solver='adam', max_iter=200)
mlp.fit(X_train, y_train)

predict_train = mlp.predict(X_train)
predict_test = mlp.predict(X_test)

In [24]:
from sklearn.metrics import classification_report, confusion_matrix
print(confusion_matrix(y_train, predict_train))
print(classification_report(y_train, predict_train))

[[     0  17656      0]
 [     0 294810      0]
 [     0  72805     12]]


d:\program files (x86)\microsoft visual studio\shared\python37_64\lib\site-packages\sklearn\metrics\classification.py:1437: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)


              precision    recall  f1-score   support

           0       0.00      0.00      0.00     17656
           1       0.77      1.00      0.87    294810
           2       1.00      0.00      0.00     72817

    accuracy                           0.77    385283
   macro avg       0.59      0.33      0.29    385283
weighted avg       0.77      0.77      0.66    385283



In [25]:
print(confusion_matrix(y_test, predict_test))
print(classification_report(y_test, predict_test))

[[     0   7584      0]
 [     0 126212      0]
 [     0  31323      3]]
              precision    recall  f1-score   support

           0       0.00      0.00      0.00      7584
           1       0.76      1.00      0.87    126212
           2       1.00      0.00      0.00     31326

    accuracy                           0.76    165122
   macro avg       0.59      0.33      0.29    165122
weighted avg       0.77      0.76      0.66    165122



In [23]:
# Cut down features further

# split training data into training and testing
from sklearn.model_selection import train_test_split

# Select columns to that are data
cols = [col for col in crime if col in ['Hour_Minute', 'hundred_block', 'pressure', 'temp_c', 
                                       'hours_of_light']]

X = crime[cols]

# Select target data
y = crime['type']

X_train, X_test, y_train, y_test = train_test_split(X, y, random_state=100, test_size=0.3)
print(X_train.shape)

(387002, 5)


In [24]:
# Trying Random Forest Classifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.feature_selection import SelectFromModel

model_tree = RandomForestClassifier(random_state=100, n_estimators=50)
model_tree.fit(X_train, y_train)
print(model_tree.feature_importances_)
sel_model_tree = SelectFromModel(estimator=model_tree, prefit=True, threshold='mean')  
      # since we already fit the data, we specify prefit option here
      # Features whose importance is greater or equal to the threshold are kept while the others are discarded.
X_train_sfm_tree = sel_model_tree.transform(X_train)
print(sel_model_tree.get_support())

feature_importances = pd.DataFrame(model_tree.feature_importances_,
                                   index = X_train.columns,
                                    columns=['importance']).sort_values('importance', 
                                                                        ascending=False)

feature_importances

[0.18346454 0.31421564 0.15920755 0.17405714 0.16905513]
[False  True False False False]


importance
hundred_block     0.314216
Hour_Minute       0.183465
pressure          0.174057
hours_of_light    0.169055
temp_c            0.159208

In [25]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import sklearn
from sklearn.neural_network import MLPClassifier
from sklearn.neural_network import MLPRegressor

# import needed modules
from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_squared_error
from math import sqrt
from sklearn.metrics import r2_score

# Try using the MLP Classifier
mlp = MLPClassifier(hidden_layer_sizes=(5, 5, 5), activation='relu', solver='adam', max_iter=200)
mlp.fit(X_train, y_train)

predict_train = mlp.predict(X_train)
predict_test = mlp.predict(X_test)

In [26]:
from sklearn.metrics import classification_report, confusion_matrix
print(confusion_matrix(y_train, predict_train))
print(classification_report(y_train, predict_train))

[[     0  17572      0]
 [     0 296491      0]
 [     0  72939      0]]


d:\program files (x86)\microsoft visual studio\shared\python37_64\lib\site-packages\sklearn\metrics\classification.py:1437: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)


              precision    recall  f1-score   support

           0       0.00      0.00      0.00     17572
           1       0.77      1.00      0.87    296491
           2       0.00      0.00      0.00     72939

    accuracy                           0.77    387002
   macro avg       0.26      0.33      0.29    387002
weighted avg       0.59      0.77      0.66    387002



In [27]:
print(confusion_matrix(y_test, predict_test))
print(classification_report(y_test, predict_test))

[[     0   7668      0]
 [     0 126980      0]
 [     0  31210      0]]
              precision    recall  f1-score   support

           0       0.00      0.00      0.00      7668
           1       0.77      1.00      0.87    126980
           2       0.00      0.00      0.00     31210

    accuracy                           0.77    165858
   macro avg       0.26      0.33      0.29    165858
weighted avg       0.59      0.77      0.66    165858

